### ISSUE TITLE
mvn clean install -Psql -Pdeploy fails because deploy-apps.sh can't be found

### ISSUE THREAD

**Issue by kartben** [eclipse/kapua#1]
When trying to deploy Kapua in the Vagrant box using ```/deploy-apps.sh```, I get an error when the assembly is trying to execute the ```vagrant_console_deploy```:

```
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.1:exec (vagrant_console_deploy) on project org.eclipse.kapua.assembly: Result of /bin/sh -c cd /Users/kartben/Repositories/kapua/org.eclipse.kapua.assembly/../org.eclipse.kapua.dev-tools/src/main/vagrant/demo && ./deployScript/deploy-apps.sh execution is: '127'. -> [Help 1]
```

Looks like `org.eclipse.kapua.dev-tools` is now `dev-tools`?

**Comment by hekonsek** [comment]
Yes, Benjamin. We should refactor `deploy-apps.sh` script. Can I push to the new Kapua repository? /CC @Coduz

**Comment by kartben** [comment]
It seems to be more than just updating this script, in the end, as several
bundles seem to not be living in the org.eclipse.kapua.* namespace anymore
- at least the jars aren't? I started to update the scripts but stopped
there since I guess first step is to make sure all Kapua bundles are
org.eclipse.kapua.xxx.jar as per Eclipse Development Process.

Le sam. 15 oct. 2016 02:13, Henryk Konsek <notifications@github.com> a
écrit :

**Comment by hekonsek** [comment]
Hi Benjamin,

We will not be using `org.eclipse.kapua...` jar naming convention as Kapua doesn't provide OSGi bundles, just plain good old jars. `org.eclipse.kapua...` makes sense for bundles, but not for ragular jars. I believe that Leshan and Californium follows the same principle as we do i.e. don't prefix artifacts with groupId.

Thanks!

**Comment by Coduz** [comment]
Hi @kartben ,

Has this been fixed? 

Thanks, 

_Alberto_

**Comment by kartben** [comment]
I think so :) Thanks!

**Comment by Coduz** [comment]
So i'll close this ;)
