### ISSUE TITLE
Groups should not be assignable for non groupable permissions

### ISSUE THREAD

**Issue by stefanomorson** [eclipse/kapua#1007]
When granting permissions to a user or a role, it is always allowed to assign a group while, for some domain it doesn't make sense. For example the domain "broker" is not groupable hence the group field should not be assignable. Here is a first list of (currently) non groupable domains:
* Domain
* Account
* User
* Group
* Tag
* Role
* Access Info
* Access Token
* Credential
* Broker
* Device connection
* Device events
* Device lifecycle
* Device managements
* Job

**Comment by Coduz** [comment]
Also scheduler domain which is missing #1008
