### ISSUE TITLE
Job executions tab not refreshed

### ISSUE THREAD

**Issue by stefanomorson** [eclipse/kapua#1017]
Testflow:

* login into kapua-sys as kapua-sys
* manually create a device client-001
* create a new job job-001
* add client-001 as a target
* add a step step-001, start bunde, bundle id heater
* select job-001
* press start
* select tab executions

The tab does not show any execution. 
To get the execution visualized, click on another view (e.g. the users), then go back to the executions tab and the entry appears.

Expected:
* the entry for the job execution should be visible right after the execution is submitted by pressing the start button

**Comment by stefanomorson** [comment]
According to @Coduz : the user should press the refresh button in the tab toolbar. This behaviour is consistent with other tabs (e.g.  device management) in the console: the content of a currently selected tab is not automatically updated when the status changes in the back-end.
This feature (having the tab content automatically updated upon relevant global status changes) coul be a possible future improvement for the UI.

Changed from bug to enhancement.

**Comment by muros-ct** [comment]
@Coduz and @lorthirk what is status of this issue.
One solution would be to add Timer on Executions tab that would refresh it every couple of seconds.
Or we can say as @stefanomorson suggested, that selecting refresh is normal behaviour and close this issue with that.

What do you think?

**Comment by Coduz** [comment]
Hi @muros-ct ,

sorry for the delay.

I think that is not an issue. 
Once a tab is loaded it will never be refreshed unless a `selectionChanged` event or a `refresh button` press.

I would also close this, since any improvement on this is something very big that we don't want to go with for now.

Regards, 

_Alberto_

**Comment by muros-ct** [comment]
Thank you Alberto for the answer.
I agree with your and I think we close this issue.
