### ISSUE TITLE
Kapua not allow to give permissions to users

### ISSUE THREAD

**Issue by dineshkumar4728** [eclipse/kapua#1018]
HI,
   
     In kapua ui when i give permissions to user ,it shows like a infinite loop.
i am following the documentations

for docker:https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#install-using-the-repository

for kapua to kura connection:https://github.com/eclipse/kapua/blob/develop/docs/kuraKapuaDocs.md

  i am attaching the both error and docker log file
![screenshot from 2017-11-21 17-51-36](https://user-images.githubusercontent.com/32698518/33113514-c59856b4-cf7e-11e7-9918-7db4d237dac5.png)
![screenshot from 2017-11-22 12-16-36](https://user-images.githubusercontent.com/32698518/33113630-48405a12-cf7f-11e7-9175-3a0f8604d5d3.png)
![screenshot from 2017-11-22 12-17-13](https://user-images.githubusercontent.com/32698518/33113631-48840b7c-cf7f-11e7-8173-3ea5c12ba06f.png)

Thank you
-dinesh

**Comment by LeoNerdoG** [comment]
Hi @dineshkumar4728 ,
I think this has been resolved with one of the previous commits (at least I do not ahve this problem any more). Can you please pull changes from develop, rebuild Kapua and try again?

**Comment by lorthirk** [comment]
Unfortunately the interesting lines are cutted out from the screen :\ Could you please attach the log file to a .txt file?

**Comment by dineshkumar4728** [comment]
HI @lorthirk 
      The below attachment is the docker logs(kapua console)
 Thank you
-Dinesh
[docker logs(kapua console).txt](https://github.com/eclipse/kapua/files/1495294/docker.logs.kapua.console.txt)

**Comment by lorthirk** [comment]
I see no errors nor exceptions in this log...

**Comment by cervesus** [comment]
I have the same problem, altough I work with a build based on a fresh (30 minutes) clone from git.

![bildschirmfoto vom 2017-11-22 22-00-18](https://user-images.githubusercontent.com/28099066/33149593-95113f86-cfd0-11e7-88c3-8c4c076f307f.png)

[docker-console_log.txt](https://github.com/eclipse/kapua/files/1497451/docker-console_log.txt)

**Comment by dineshkumar4728** [comment]
HI @lorthirk @LeoNerdoG ,
   
     I am try with many times,still face the same error. can u provide the some solution about this.when i am run the docker commands and others i did not find any errors.
 
 Thank you
-Dinesh kumar

**Comment by dineshkumar4728** [comment]
HI @cervesus ,
   
       you got any solution for this issue?
 
Thank you

**Comment by cervesus** [comment]
@dineshkumar4728 , unfortunately not, but the connection works anyway.

**Comment by LeoNerdoG** [comment]
Hi @dineshkumar4728 @cervesus ,
I cannot replicate your problem in any way. 

Can you please try this: 
1. Create new folder and clone kapua into it (`git clone https://github.com/eclipse/kapua`)
2. Go to Kapua folder and run `mvn clean install -DskipTests -Pconsole,docker`
3. After that run `mvn clean install -f external/pom.xml`
4. Run all the docker commands listed on kapua github page (kapua-api, broker, console, sql, elasticsearch).
5. Go to `https://localhost:8080 `and login as kapua-sys. 
6. Go to Users, create new user and give it _**ALL**_ permissions. 
7. Create new child account and add a user with _**ALL**_ permissions. 

There should be no problems doing so. 
Please report if you will have any more problems.

**Comment by dineshkumar4728** [comment]
Hi @LeoNerdoG , 
    
            I am following your solution
[log files.txt](https://github.com/eclipse/kapua/files/1508589/log.files.txt)
 as like above but still i am facing the same problem.when i am run this command  "mvn clean install -DskipTests -Pconsole,docker" i got some errors like below attachment . can you please look once

Thank you

**Comment by LeoNerdoG** [comment]
Hi @dineshkumar4728 ,
try to run `mvn clean install -f external/pom.xml` before `mvn clean install -DskipTests -Pconsole,docker`.
Can you please provide information about your OS and maven version?

**Comment by dineshkumar4728** [comment]
Hi @LeoNerdoG ,
 Just now i am try and same issue arise.
 maven version- 3.3.9
 OS -ubuntu(16.04 LTS) 
 I have run ubuntu on VirtualBox

Thank you

**Comment by LeoNerdoG** [comment]
Hi @dineshkumar4728 ,
Please try with CentOS. Ubuntu needs some tweaking for Kapua to work.

**Comment by dineshkumar4728** [comment]
Hi @LeoNerdoG ,
   One of my colleague follow the same documentation , for him kapua works properly and when i am follow the same  i got same issue.
 Thank you
