### ISSUE TITLE
Kapua Returns An Error Although User Successfully Created Or Deleted

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1022]
Although certain user has all the _**user**_ permissions and everything works fine, Kapua returns an error when user tries to create or delete a user. 

Testflow: 
1. Login as kapua-sys
2. Go to Users, create a user (e.g. kapua-user1)
3. Select kapua-user1, add User permissions
4. Login as kapua-user1 and try to add/delete a user. 
_**Kapua will return an error (as shown bellow) but operation will be completed successfully.**_

<img width="1439" alt="screen shot 2017-11-22 at 09 59 05" src="https://user-images.githubusercontent.com/15121999/33118589-92ce6668-cf6c-11e7-8a32-81e147ec5863.png">

Browsers used:
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by lorthirk** [comment]
This should have been fixed, since now credentials are only created only if the user has proper authorizations. Can we check again please?

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
