### ISSUE TITLE
The broker URL in the settings view should be set to the broker external endpoint

### ISSUE THREAD

**Issue by stefanomorson** [eclipse/kapua#1030]
In some deployments broker URL may be different for external (field facing) and internal (backend facing) clients. For example the external URL may be resolved by a DNS and routed to the actual internal URL.  
During deployments the internal broker URL is set through system configurations. Current implementation shows this value in the account settings view under the group "Deployment Plan".

The proposal is to change the value of the field from internal URL to external URL, in this way the user can easily identify which address has to be configured in the device in order to reach the service.

The value has to be seeded as a scoped configuration since it is a deployment specific information that has to be provided by the operations.

For demo deployments it could be useful to make the behaviour a little smarter: if there's no scoped configuration then show the internal URL otherwise show the configured value.

**Comment by lorthirk** [comment]
Should be fixed by 05a4447

**Comment by stefanomorson** [comment]
@lorthirk : tested the solution and it works. 
However, while testing I realised that now, when a child account is created, the value of this configuration is copied into the child account scoped configurations. Still fine with this but if the external end point has to be changed later for some reason then all the child accounts configurations need also to be updated (manually). 
Since in the current deployment model there's only one Mqtt service instance assigned to the root account, the child account could simply look at the root configuration to discover what is the URL assigned for the Mqtt service. This configuration should be editable only at the root account level while the value should be viewable at any level.

**Comment by lorthirk** [comment]
Additional fixes in 77e034ea0

**Comment by stefanomorson** [comment]
@lorthirk : after last change it just partially work.
Testflow:

* Connect to kapua-sys as kapua-sys
* Goto settings/settings, set a value for brokerUri in account service settings
* Save
* Create a child account test and an admin user in it test
* Logout and login in test as test
* Open settings view

An error appears both in the description view and in settings view
