### ISSUE TITLE
Roles Toolbar Not Frozen Although User Has Partial Permission

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1034]
Problem emerges when creating a user (e.g. kapua-user1) and granting Role permissions. Although we grant partial permissions (only **read**/**write**/**delete** or any combination of **read** and others), device toolbar of kapua-user1 is not frozen (in every case add, edit and delete options are clickable).

Testflow:
1. Login as kapua-sys
2. Go to Users, create a user (e.g. kapua-user1)
3. Select kapua-user1, add read or read and write/delete/ Role permissions
4. Login as kapua-user1 and try to read/edit/delete roles.
**Screnshot bellow shows that toolbar is not frozen (but it should be.**

![screen shot 2017-11-22 at 12 46 58](https://user-images.githubusercontent.com/15121999/33126016-2f31d29a-cf83-11e7-9d33-6c63a0a56d59.png)

Browsers used:
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by lorthirk** [comment]
#1432 covers the generic case for the Add button

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved by PR #1525.
