### ISSUE TITLE
Toolbar Of Selected Device Not Frozen As It Should Be

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1035]
Problem emerges when creating a user (e.g. kapua-user1) and granting Device permissions. Although we grant _**ALL**_ device permissions and none of device connection, event, lifecycle or management permissions, toolbar of selected device (bottom toolbar) of kapua-user1 is not frozen (screenshot No. 1) until user clicks on one of the devices (screenshot No. 2) and Kapua returns a lot of errors. 
At this point it is OK for toolbar to be frozen, but nevertheless there should be no errors from Kapua. 

Testflow:
1. Login as kapua-sys
2. Go to Users, create a user (e.g. kapua-user1)
3. Select kapua-user1, add _**ALL**_ device permissions
4. Login as kapua-user1 and go to Devices.
**Screnshot No. 1 bellow shows that toolbar is not frozen (but it should be - as shown in screenshot No. 2).**

Screenshot No. 1: 
![screen shot 2017-11-22 at 13 16 49](https://user-images.githubusercontent.com/15121999/33127079-4505ecce-cf87-11e7-905d-7a6de01db2ec.png)

Screenshot No. 2: 
<img width="1439" alt="screen shot 2017-11-22 at 13 05 42" src="https://user-images.githubusercontent.com/15121999/33127056-2e5722f4-cf87-11e7-9ebf-6698d7eecac6.png">

Browsers used:
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by lorthirk** [comment]
We should check the various `*TabDescriptor` `isEnabled()` method

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
