### ISSUE TITLE
In job schedule edit form put date and time pickers in the same row

### ISSUE THREAD

**Issue by stefanomorson** [eclipse/kapua#1036]
Using one row would reduce the vertical space used and reduce the horizontal span of each single field

**Comment by ct-ajovanovic** [comment]
Hi @stefanomorson 
I created a PR solving this issue. It contains the new dialog layout. Can you please check this?

**Comment by LeoNerdoG** [comment]
@stefanomorson I have verified that this issue has been resolved (I tested in develop branch) so it can be closed.

**Comment by muros-ct** [comment]
I am closing this issue as everything is ok.
@stefanomorson do you agree?
