### ISSUE TITLE
No Delete Button In Connections 

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1044]
When adding device connection permissions there is also **delete** permission (screenshot No. 1) although there is no delete button in Connections (screenshot No. 2). 

Testflow:
1. Login as kapua-sys
2. Add live device to Kapua (create a connection)
3. Go to Users, create a user (e.g. kapua-user1)
4. Select kapua-user1, add _**read**_ and _**delete**_** device_connection permission
5. Login as kapua-user1 and go to Connections
**Screnshot bellow shows that there is no delete button although there is permission for it.**

Screenshot No. 1
<img width="721" alt="screen shot 2017-11-22 at 14 58 37" src="https://user-images.githubusercontent.com/15121999/33131165-fb3de254-cf95-11e7-97c1-6680e5bddf3b.png">

Screenshot No. 2
![screen shot 2017-11-22 at 15 04 20](https://user-images.githubusercontent.com/15121999/33131257-492793de-cf96-11e7-932c-3424e579d57e.png)

Browsers used:
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by lorthirk** [comment]
Not an issue. Only the broker is entitled to create and destroy connections.

**Comment by gnunzi** [comment]
Hi, sorry for follow-up: how would the broker destroy a connection then? Is there a particular message to be sent or ?
Thanks,
