### ISSUE TITLE
Add AccessGroupService

### ISSUE THREAD

**Issue by stefanomorson** [eclipse/kapua#105]
AccessGroup model object inherits from KapuaNamedEntity, no specific fields
Add Groupable marker interface
Make the Device model object inherit from Groupable and add groupId Attrbiute

**Comment by Coduz** [comment]
Hi all,

the GroupService is a service for creating Groups.
This service is the starting point of the feature of group access, which is the epic for this issue (#103).

- [x]  Implement API on me.
- [x]  Reference implementation on me.
- [ ]  REST API integration on @lorthirk
- [ ]  Final review.

Regards,

Alberto
