### ISSUE TITLE
Packages Tab Not Automatically Refreshed

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1050]
If user installs/uninstalls a package, Package tab does not refresh automatically. Instead, user has to click something else and then return back to Packages tab, which is now refreshed. 

Testflow: 
1. Login as kapua-sys
2. Go to Users, create a user (e.g. kapua-user1)
3. Go to Devices and add a live device
4. Select kapua-user1, add **_read_** permissions to devices, and _**ALL**_ permissions for device_management domain
5. Login as kapua-user1, go to Devices, select sample-device1 and go to Packages tab
6. Try to install package from Eclipse Marketplace (e.g. example publisher) or uninstall one from the Packages list. 
**Packages are successfully installed/uninstalled but Packages tab is not refreshed.**

Browsers used:
1. Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
2. Safari (Version 11.0.1 (13604.3.5))
3. Mozilla Firefox (57.0 (64-bit))
4. Opera (Version 49.0.2725.39)

**Comment by Coduz** [comment]
Hi @LeoNerdoG ,

is this still an issue? 

Regards, 

_Alberto_

**Comment by LeoNerdoG** [comment]
@Coduz 
Yes, this problem still persists. As said in the original post, user has to click something else in order to get the updated view of the Packages tab.

**Comment by Coduz** [comment]
Hi @LeoNerdoG ,

as https://github.com/eclipse/kapua/issues/1017,

I think that is not an issue.
Once a tab is loaded it will never be refreshed unless a selectionChanged event or a refresh button press.

On each tab there is a `Refresh` button which can be used. 

I think also that we can close this.

Regards, 

_Alberto_

**Comment by LeoNerdoG** [comment]
Hi @Coduz,
no problem on my side. Can you please close with label "wont-fix"? 

Regards,
Leo
