### ISSUE TITLE
User Cannot Edit Its Settings

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1054]
Although user has **_ALL_** Account permissions, Settings cannot be update. Instead, Kapua returns an error saying that user does not have _**account:write**_ permissions. 

Testflow:
1. Login as kapua-sys
2. Go to Users and add user (e.g. kapua-user1) with ALL Account permissions
3. Login as kapua-user1 and go to Settings tab
4. Try to edit some of the fileds.
**Kapua returns an error that user does not have needed permissions for the operation, although user has ALL permissions.**

<img width="1439" alt="screen shot 2017-11-23 at 13 02 02" src="https://user-images.githubusercontent.com/15121999/33172023-c81e8644-d04e-11e7-9e14-2a46a17020bf.png">

Browsers used:
1. Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
2. Safari (Version 11.0.1 (13604.3.5))
3. Mozilla Firefox (57.0 (64-bit))
4. Opera (Version 49.0.2725.39)

**Comment by LeoNerdoG** [comment]
I have verified that this issue is resolved.

**Comment by lorthirk** [comment]
After editing the Account details the grid underneath doesn't refresh automatically
