### ISSUE TITLE
User Cannot Change Settings Of Certain Child Account

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1055]
Although user has **_ALL_** Account permissions, user cannot see child account settings (look at the screenshot).  When User clickSettings tab, Kapua immediately returns an error saying that user does not have **_account:read_** permissions. 

Testflow:
1. Login as kapua-sys
2. Go to Users and add user (e.g. kapua-user1) with ALL Account permissions
3. Login as kapua-user1, go to Child Accounts tab and create a child account. 
4. Try to view child accounts Settings. 
**Kapua returns an error that user does not have needed permissions for the operation, although user has ALL permissions.**

<img width="1437" alt="screen shot 2017-11-23 at 13 08 19" src="https://user-images.githubusercontent.com/15121999/33172272-bf9cfa36-d04f-11e7-806e-efdb4f9ea140.png">

Browsers used:
1. Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
2. Safari (Version 11.0.1 (13604.3.5))
3. Mozilla Firefox (57.0 (64-bit))
4. Opera (Version 49.0.2725.39)

**Comment by lorthirk** [comment]
For which scopeId is the permission granted?

**Comment by lorthirk** [comment]
This is not a bug. If the permission is not forwardable the user can view all his resources (including his child accounts), but nothing of his child account's resources (including configuration and informations). We could manage more gracefully the error though.

**Comment by stefanomorson** [comment]
Agree with @lorthirk.

@LeoNerdoG : can you close this issue and open another one (this time a bug) to gracefully manage the permission error ?

**Comment by LeoNerdoG** [comment]
I am closing this issue as I have opened issue #1059 .
