### ISSUE TITLE
User Cannot View Users Of Certain Child Account

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1056]
Although user has proper Account permissions ( _**user:read**_ and _**user:write**_) , user cannot see child account users (look at the screenshot). When User clickSettings tab, Kapua immediately returns an error saying that user does not have **user:read** permissions.

Testflow:
1. Login as kapua-sys
2. Go to Users and add user (e.g. kapua-user1) with _**ALL**_ Account permissions and _**user:read**_ permissions
3. Login as kapua-user1, go to Child Accounts tab and create a child account.
4. Try to view child accounts **User** tab.
**Kapua returns an error that user does not have needed permissions for the operation, although user has required permissions.**

<img width="1437" alt="screen shot 2017-11-23 at 13 56 38" src="https://user-images.githubusercontent.com/15121999/33173839-f5f92ed2-d055-11e7-997d-8e326f003b6c.png">

Browsers used:
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by lorthirk** [comment]
For which scopeId is the permission granted?

**Comment by lorthirk** [comment]
Related to #1055. Users of a child account belongs to this last one, and the permission must be forwardable to be effective.

**Comment by LeoNerdoG** [comment]
I am closing this issue as I have opened issue #1059 .
