### ISSUE TITLE
Migration of build from Hudson to Jenkins instance

### ISSUE THREAD

**Issue by stefanomorson** [eclipse/kapua#1058]

**Comment by muros-ct** [comment]
We have issue open on Eclipse bugzila: [Bug 527669](https://bugs.eclipse.org/bugs/show_bug.cgi?id=527669) 

We decided to wait after release and then continue with activities.

One activity that is mandatory is to move from job templates to ordinary Hudson jobs, because Jenkins doesn't support templates.

**Comment by muros-ct** [comment]
All jobs that were based on templates template-dev-build and template-release-build were copied to new jobs that have same name just with new-* prefix.

new-develop was allready executed and it looks ok.

This would need a second review by some one familiar with current CI environment.

After review, next step would be to remove old jobs and templates then rename new-* jobs to regular - existing names.

Followed by conntacting eclipse webmaster to run migration scripts. Then we will see.

**Comment by muros-ct** [comment]
@Coduz can you please take a quick look at this new-* jobs.

**Comment by Coduz** [comment]
Hi @muros-ct ,

checked configurations and they are ok! 
After they get migrated to Jenkins I'll check that everything is ok and I'll try to document about new configurations/features available on Jenkins to optimize CI.

Thanks,

_Alberto_

**Comment by muros-ct** [comment]
I removed old jobs (with some problems deleting from chrome).
I also tried to rename new-develop to develop, but it coused Hudson to become unresponsive.
I requested restart of Kapua instance of Hudson.

**Comment by muros-ct** [comment]
Rename of all new-* jobs was successful.
Hudson was restarted in the meantime.
I also posted another comment on eclipse issue to proceed with migration to Jenkins.

**Comment by muros-ct** [comment]
Migration to Jenkins succeded fine.
Minor changes were needed for checkstyle exclusions.
.repository folder was added to exclusions.
Build looks ok, develop builds the same as on Hudson.
Release builds are still struggling but this is not Jenkins issue.

Thereby I am closing this issue.
