### ISSUE TITLE
"Add User" Button Not Frozen Although User Has No Write Permissions

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1068]
_**Add User**_ button is not frozen (as it should be), although user has no write permissions. 

Testflow: 
1. Login as kapua-sys
2. Go to Users, create new user (e.g. kapua-user1) 
3. Add _**Users:read**_ permission. 
4. Login as kapua-user1 and go to Users tab. 
**_Add_ button is not frozen as it should be. Nevertheless Kapua does not allow adding new user.**

![screen shot 2017-11-27 at 09 38 49](https://user-images.githubusercontent.com/15121999/33257492-a0dd88fe-d356-11e7-9096-c67f6658cf3e.png)
 
Browsers used:
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by lorthirk** [comment]
#1432 covers the generic case of all "Add" button in Entity Grids

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
