### ISSUE TITLE
Problem With "Action" Dropdown Menu in Permissions

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1082]
This issue presents itself in two places: in Roles and in Users. 
When creating new role and adding permissions to it, _**Domain**_ and _**Access Group**_ dropdown menus can be opened by clicking anywhere on the dropdown box (green colour on the screenshots). But the _**Action**_ menu can be opened just by clicking on arrow symbol at the end of the box (orange colour on the screenshots).
Same goes for users, when granting permissions.

Testflow: 
1. Login as kapua-sys
2. Go to Roles, create new role (e.g. role1) and go to Permissions tab
3. Domain and Access Group dropdown menus can be opene by clicking anywhere. 
4. Action dropdown menu can be opened only by clicking on arrow symbol. 

![screen shot 2017-11-29 at 09 56 59](https://user-images.githubusercontent.com/15121999/33368701-ab0f1c14-d4f2-11e7-8928-7073cae2bb8a.png)

![screen shot 2017-11-29 at 09 58 01](https://user-images.githubusercontent.com/15121999/33368702-ab29769a-d4f2-11e7-89b1-da04258426e3.png)

Browsers used:
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by ct-goranpalibrk** [comment]
This issue is fixed in PR #879

**Comment by LeoNerdoG** [comment]
As PR #879 has been closed, this still needs fixing.

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
