### ISSUE TITLE
Add UI for authorization use case

### ISSUE THREAD

**Issue by stefanomorson** [eclipse/kapua#109]
- Ass Authorization menu item in the task bar
- Add Roles tab
- Add Groups tab

**Comment by stefanomorson** [comment]
@lorthirk : can you update the status of this issue ?

**Comment by lorthirk** [comment]
This is still to be implemented, as now the efforts on the Patternfly console are mainly on the Devices part

**Comment by Coduz** [comment]
Hi all, 

This issue can be closed since Console V2 is no longer a thing, right? 

Regards, 

_Alberto_

**Comment by Coduz** [comment]
Closing this issue due to change of plans for the Web Administration Console
