### ISSUE TITLE
jar update script in vagrant deployment should not consider project qa-steps

### ISSUE THREAD

**Issue by stefanomorson** [eclipse/kapua#1092]
Testflow:

* Clone Kapua to a local dir
* Build kapua develop
* Build kapua 0.3.x
* Start vagrant env
* Login into Vagrant
* Start the Broker
* Open borker logs

The broker is running but there are errors due to the Kapua locator not being able to load a class contained in project qa-steps of Kapua.

The issue is due to a bug in update-kapua-jars-cfg.sh that should discard links to qa-steps.

Technically this issue does not affect 0.3.1 because when starting from a clean build it doesn't happen. However, to simplify the work for developers using Vagrant it would be better to fix this in 0.3.x as well so that it can be included in the next service release.

**Comment by muros-ct** [comment]
I think this is issue which Henryk brought in in one implementation of standalone service which is run inside main().
Shall I take a look and remove it.

**Comment by stefanomorson** [comment]
Sure, the quick way is to change line 19 in update-kapua-jars-cfg.sh adding the skip for qa-test.
