### ISSUE TITLE
Console Accounts Usability Improvements

### ISSUE THREAD

**Issue by mcarrer** [eclipse/kapua#1095]
The following usability improvements can be applied to the Accounts section in the Kapua Console.
* Accounts table
    * [x] Add a “Loading…” mask while the table data is loading
    * [x] Modified On value should conform to date time representation in Kapua
* Accounts > Filter tab
    * [x] Title should be Account Filter
    * [x] Change info text to: All non-empty fields will be compiled and applied into the query taken into consideration in the filter.
* Accounts > New Account dialog
    * [x] Change info text to "Create a new Account with its Organization and Contact Person.”
    * [x] The background color of the info text should be the same light grey of the background of the dialog 
    * [x] Parent Account value is empty even for non root account. It should be populated with a text field.
    * [x] Change "More Information” label to "Primary Contact"
    * [x] Change "Reference Person" to "Contact Name"
    * [x] The width of the fields Account Name, Organization Name and Email should match the width of the Primary Contact fields
    * [x] The height of the dialog seems to be too big
* Accounts > Edit Account dialog
    * [x] Title should be corrected to: “Edit Account: <account name>"
    * [x] Change info text to “Edit Account Organization and Contact Person.”
    * [x] The width of the fields Organization Name and Email should match the width of the Primary Contact fields
    * [x] The background color of the info text should be the same light grey of the background of the dialog
    * [x] The height of the dialog seems to be too big
* Accounts > Delete Account dialog
    * [x] Title should be consistent with all the Delete dialogs: Delete Account: <account name>
    * [x] Info text should be: Are you sure you want to delete the selected Account?
* Accounts > Description tab
    * [ ] We should remove the Deployment Info section as that is not editable from the account properties
    * [x] Change "Reference Person" to "Contact Name”
    * [x] Created On value  should conform to date time representation in Kapua
    * [x] Modified On value should conform to date time representation in Kapua

**Comment by lorthirk** [comment]
The Deployment Info section could still be useful to show endpoints once #1358 is merged

**Comment by lorthirk** [comment]
Branch `fix-accounts_view_usability_improvements` is ready with the requested changes

**Comment by LeoNerdoG** [comment]
@lorthirk I have reviewed the changes and I found only one thing: When deleting account the text on top of dialogue box is _**Delete account:**_ instead of _**Delete Account:**_ (capital "A"). 
Everything else is successfully fixed.

**Comment by lorthirk** [comment]
Branch updated with the fixed message. Please check it so I can merge it in develop.

**Comment by LeoNerdoG** [comment]
@lorthirk Message is successfully fixed. You can merge.

**Comment by lorthirk** [comment]
Merged in develop with a75cd9738
