### ISSUE TITLE
Console “Users” and "Accounts > Users" Usability Improvements

### ISSUE THREAD

**Issue by mcarrer** [eclipse/kapua#1096]
The following usability improvements can be applied to the Users and the Accounts > Users section in the Kapua Console.

* Users table
   * [x] Add a “Loading…” mask while the table data is loading. We only have it in the case of the table under the Accounts > Users tab.
    * [x] Add tooltip on the Status Icon. It is not clear that that icons mean an enabled user
    * [x] Replace the Created On value with the Modified On like in Account
    * [x] Modified On value should conform to date time representation in Kapua
    * [x] Expiration Date value should conform to date time representation in Kapua
* Accounts > Filter tab
    * [x] Title should be User Filter
    * [x] Change info text to: All non-empty fields will be compiled and applied into the query taken into consideration in the filter.
* Users > Description
    * [x] Created On value should conform to date time representation in Kapua
    * [x] Modified Date value should conform to date time representation in Kapua
    * [x] Add Expiration Date row
* Users > New User dialog
    * [x] Change info text to "Create a new User with its Credentials.”
    * [x] The background color of the info text should be the same light grey of the background of the dialog 
    * [x] The height of the dialog seems to be too big
* Users > Edit User dialog
    * [x] Change info text to “Edit user information.”
* Users > Delete User dialog
    * [x] Title should be consistent with all the Delete dialogs: Delete User: <user name>
    * [x] Info text should be: Are you sure you want to delete the selected User?
* Users > Credentials > table
    * [x] Add tooltip over the key and lock icons
    * [x] Change the column order to Created on, Created By, and Expiration Date to be consistent with the table above
* Users > Credentials > New Credentials dialog
    * [x] User field is not very visibile. It should be set to a text only field.
* Users > Credentials > Edit Credentials dialog
    * [x] Title of the dialog should be: "Edit Credentials” there is a column null now
    * [x] User field is not very visibile. It should be set to a text only field.
* Users > Credentials > Delete Credentials dialog
    * [x] Title of the dialog should be: “Delete Credentials” 
    * [x] Info text should be: Are you sure you want to delete the selected Credentials?

**Comment by lorthirk** [comment]
The code is in [fix-users_view_usability_improvements](https://github.com/eclipse/kapua/tree/fix-users_view_usability_improvements)

**Comment by LeoNerdoG** [comment]
Hi @lorthirk I have tested the code and everything is ok except value of user that created certain users (in my example kapua-user2 was created by kapua-sys but in Users -> Description -> Created By and Modified By kapua-user2 is listed).
Secind thing: The delete dialogue box info text on top is "Delete credential:....", but should be "Delete Credentials:...." (capital C)
Third thing: The Edit dialogue box info text on top is "Edit Credentials:...." but should be "Edit Credentials:...." (capital C)

Screenshot No. 1 (First issue):
![screen shot 2018-01-29 at 14 40 12](https://user-images.githubusercontent.com/15121999/35513768-6279cd68-0504-11e8-92a4-be1f65262787.png)

Screenshot No. 2 (Second issue):
![screen shot 2018-01-29 at 14 48 16](https://user-images.githubusercontent.com/15121999/35513773-67a04326-0504-11e8-95b6-c6fbbe7b9ceb.png)

Screenshot No. 3 (Third issue):
![screen shot 2018-01-29 at 14 53 30](https://user-images.githubusercontent.com/15121999/35513778-6b9653da-0504-11e8-9462-f12e3f8eda89.png)

**Comment by lorthirk** [comment]
All the comments should have been addressed now

**Comment by LeoNerdoG** [comment]
@lorthirk 
I have just four trivial problems to report here: 
1. _**New User**_ dialogue box is maybe a little too big (space on the bottom)
2. _**Edit User**_ dialogue box is a little too big (space on the bottom)
3. In _**Edit Credential**_ there is a missing "s" on the end (it should be _**Edit Credentials**_)
4. In _**Delete Credential**_ there is also missing "s" on the end (it should be _**Delete Credentials**_)

Screenshot No. 1 ():
![screen shot 2018-01-30 at 13 22 39](https://user-images.githubusercontent.com/15121999/35566248-fa24dc22-05c0-11e8-9e87-293dfab21c45.png)

Screenshot No. 2 ():
![screen shot 2018-01-30 at 13 23 07](https://user-images.githubusercontent.com/15121999/35566254-fccdf300-05c0-11e8-9937-d47ccc05813b.png)

Screenshot No. 3 ():
![screen shot 2018-01-30 at 13 28 01](https://user-images.githubusercontent.com/15121999/35566262-01060214-05c1-11e8-89ce-0781c0e821cc.png)

Screenshot No. 4 ():
![screen shot 2018-01-30 at 13 28 08](https://user-images.githubusercontent.com/15121999/35566264-026e3df6-05c1-11e8-8741-f869694bbe7b.png)

**Comment by lorthirk** [comment]
Branch updated addressing latest comments

**Comment by LeoNerdoG** [comment]
@lorthirk I have retested with these new improvements and everything looks OK.

**Comment by lorthirk** [comment]
Pushed to develop with 9612844fc
