### ISSUE TITLE
Console “Roles” and “Users > Roles" Usability Improvements

### ISSUE THREAD

**Issue by mcarrer** [eclipse/kapua#1097]
The following usability improvements can be applied to the Roles and theUsers > Roles sections in the Kapua Console.

* Roles table
    * [x] Add a “Loading…” mask while the table data is loading. We only have it in the case of the table under the Accounts > Users tab.
    * [x] Replace the Created On / Created By value with the Modified On / Modified By like in Account
    * [x] Change the order of the column to be Modified On | Modified By
* Roles > Filter tab
    * [x] Title should be Role Filter
    * [x] Change info text to: All non-empty fields will be compiled and applied into the query taken into consideration in the filter.
* Roles > Description
    * [x] Created On value should conform to date time representation in Kapua
    * [x] Modified Date value should conform to date time representation in Kapua
* Roles > Delete Role dialog
    * [x] Title should be consistent with all the Delete dialogs: Delete Role: <user name>
    * [x] Info text should be: Are you sure you want to delete the selected User?
* Roles > Permissions table
    * [x] Swap Added On and Added By columns
    * [x] Added On columns should be conform to date time representation in Kapua
* Roles > New Permissions dialog
    * [x] Title should be “New Permission”
* Roles > Delete Permissions dialog
    * [x] Title should be “Delete Permission” <permission connect>”
    * [x] Info text should be: Are you sure you want to delete the selected Permission?
* Roles > Granted User tab
    * [x] Add a “Loading…” mask while the table data is loading.
    * [x] Remove the Type column

**Comment by lorthirk** [comment]
The code is in [fix-roles_view_usability_improvements](https://github.com/eclipse/kapua/tree/fix-roles_view_usability_improvements)

**Comment by LeoNerdoG** [comment]
Hi @lorthirk I have tested the code and everything is ok except column order in Users -> Roles and Users -> Permissions (look at the screenshots bellow).

Screenshot No. 1 (Users -> Roles the Created By and Created On are switched):
![screen shot 2018-01-29 at 14 30 15](https://user-images.githubusercontent.com/15121999/35512693-f6fb0550-0500-11e8-8e97-4c1e91a13024.png)

Screenshot No. 2 (Users -> Permissions the Granted By and Granted On are switched):
![screen shot 2018-01-29 at 14 30 21](https://user-images.githubusercontent.com/15121999/35512700-fa1fa97a-0500-11e8-8dbe-133d2dc95931.png)

**Comment by lorthirk** [comment]
All the comments should have been addressed now

**Comment by LeoNerdoG** [comment]
@lorthirk I found just some trivial issues (regarding dialogue box size). Maybe this is not directly connected to this issue, but as we are dealing with roles and roles in users, I will "report" it here (all screenshots are bellow).
1. _**New User**_ dialogue box is maybe a little too big (space on the bottom)
2. _**Edit User**_ dialogue box is a little too big (space on the bottom)
3. _**New Credential**_ dialogue box is a little too big (space on the bottom)
4. _**Edit Credentials**_ dialogue box is a little too big (space on the bottom)
5. _**Add Role**_ in _**Users**_ dialogue box is a little too big (space on the bottom)
6. _**Grant Permissions**_ dialogue box is a little too big (space on the bottom)

![screen shot 2018-01-30 at 13 41 30](https://user-images.githubusercontent.com/15121999/35567249-a57be2a2-05c4-11e8-8edf-02a79d64b4ed.png)

![screen shot 2018-01-30 at 13 41 23](https://user-images.githubusercontent.com/15121999/35567256-a7534872-05c4-11e8-8783-2168b8f0bebf.png)

![screen shot 2018-01-30 at 13 46 36](https://user-images.githubusercontent.com/15121999/35567258-aa8dc17a-05c4-11e8-932d-0cac320406ad.png)

![screen shot 2018-01-30 at 13 46 43](https://user-images.githubusercontent.com/15121999/35567260-ac096c34-05c4-11e8-8219-68f98c0bfee9.png)

![screen shot 2018-01-30 at 13 46 53](https://user-images.githubusercontent.com/15121999/35567261-ad87f27e-05c4-11e8-813e-bcb4e1fdcfb6.png)

![screen shot 2018-01-30 at 13 47 02](https://user-images.githubusercontent.com/15121999/35567263-aefbcf7c-05c4-11e8-906b-e83d5f5b43e6.png)

**Comment by lorthirk** [comment]
The point is, it will be hard to have a perfect sizing of the dialogues since usually we specify a fixed height for them; they don't just adapt to the content.

I'll try to improve them anyway; anyway, please keep in mind that:

- The New Credential has that spacing because selecting "Password" as Credential Type adds two more fields
- The Assign Role dialog is already fixed in branch `fix-roles_view_usability_improvements`

**Comment by lorthirk** [comment]
Ok, the situation should be a bit improved now.

**Comment by LeoNerdoG** [comment]
@lorthirk I have reviewed the changes and I think it is much better now. From my point of view this can be merged.

**Comment by lorthirk** [comment]
Merged in develop with 22ba49881
