### ISSUE TITLE
Console “Devices" Usability Improvements

### ISSUE THREAD

**Issue by mcarrer** [eclipse/kapua#1098]
The following usability improvements can be applied to the Devices section in the Kapua Console.
* Devices table
    * [x] Can we have the “Loading…” mask while the table data is loading? The mask is there during the re-loading.
    * [x] Last Event On date formatting should be consistent
* Device > Filter
    * [x] Title should be singular as "Device Filter”
    * [x] Change info text to "All non-empty fields will be compiled and applied into the query taken into consideration in the filter."
    * [x] "KURA/ESF Version” should be “IoT Framework Version”
* Devices > New Device dialog
    * [x] If I put a duplicate Client ID, the operations fails with an error but the dialog is dismissed.
* Devices > Delete Device dialog
    * [x] Title should be consistent with all the Delete dialogs: Delete Device: <client id>
    * [x] Info text should be: Are you sure you want to delete the selected Device and its events?
* Device > Description
    * [x] Last Connected User, Reserved User not populated
    * [x] Value for "Last Event On” should be a formatted date
* Device > Events
    * [x] Event Received On > Date formatting should be consistent (Today or what format?)
* Device > Configuration
    * [x] When applying a Configuration update, the panel is refreshed twice
    * [x] MqttDataTransport, RebootService, RestService services has a dirty configuration always 
    * [ ] Sometimes after a configuration update I get an out of date warning and the configuration is not applied
* Device > Asset 
    * [x] Title should be Assets
* Device > Filter
    * [x] Title for the filter should be Device Filter (singular)
* Where do we show the applied Tags?
    * In the dedicated "Tags" tab
* What’s the value for Remote IP and Client IP?
    * Server IP: the address of the broker to which the device is connected to
    * Client IP: the address of the client as reported by the broker

**Comment by lorthirk** [comment]
All the comments should be addressed in branch `fix-devices_view_usability_improvements`

**Comment by LeoNerdoG** [comment]
@lorthirk I have reviewed the branch and I can confirm, that contains all the requested changes.

**Comment by lorthirk** [comment]
Merged in develop with 77d58da3d
