### ISSUE TITLE
Console “Connection" Usability Improvements

### ISSUE THREAD

**Issue by mcarrer** [eclipse/kapua#1099]
The following usability improvements can be applied to the Connections section in the Kapua Console.
* Connections table
    * [x] Can we have the “Loading…” mask while the table data is loading?
    * [x] Column: Connection-user bound -> User Coupling Mode
    * [x] Column: Reserved User Name -> Reserved User
    * [x] Why is the Modified On column not populated but it has a value in the Description tab?
    * [x] Value for “Modified On” should be a formatted date
* Connection > Description
    * [x] Is the Client IP correct?
    * [x] Why is the Server IP N/A?
    * [x] "Connection-User bout Infromations” -> User Coupling Mode Information
    * [x] Connection-user bound -> User Coupling Mode
    * [x] Reserved User Name -> Reserved User
    * [x] Allow user change -> Allow User Change
    * [x] Value for “Modified On” should be a formatted date
    * [x] Value for “First Established On” should be a formatted date
* Connection > Edit
    * [x] Dialog tile: Edit Connection
    * [x] Dialog Info: Edit Connection security options.
    * [x] Filed group title should be: Security Options
    * [x] Last User filed should be text o a disabled Text Field
    * [x] Last user -> Last User
    * [x] User coupling mode -> User Coupling Mode
    * [x] Reserved user id -> Reserved User
    * [x] Allow user change -> Allow User Change
* What does Client IP represent?
    * The IP of the Device as seen by the broker

**Comment by LeoNerdoG** [comment]
@lorthirk I have reviewed the changes in branch [fix-connections_view_usability_improvements](https://github.com/eclipse/kapua/tree/fix-connections_view_usability_improvements) . Everything is OK, except _**User-connection coupling**_ and _**Reserved user name**_ column names in Connection table; shouldn't there fields be named _**User Couplnig Mode**_ and _**Reserved User**_ (please look at the screenshots bellow)?

Screenshot No. 1 ():
![screen shot 2018-01-30 at 12 44 04](https://user-images.githubusercontent.com/15121999/35565036-53e289b2-05bc-11e8-9aaa-54d45d0465a1.png)

Screenshot No 2 ():
![screen shot 2018-01-30 at 12 50 51](https://user-images.githubusercontent.com/15121999/35565039-555d6a32-05bc-11e8-8530-802acfa2bcc2.png)

**Comment by lorthirk** [comment]
Column headers fixed

**Comment by LeoNerdoG** [comment]
@lorthirk I have verified that all issues described above have been fixed. From my point of view this can be merged.

**Comment by lorthirk** [comment]
Merged in develop with 160f77619
