### ISSUE TITLE
Add UI for managing device access groups

### ISSUE THREAD

**Issue by stefanomorson** [eclipse/kapua#110]
- Add AccessGroups tab in device detail view

**Comment by stefanomorson** [comment]
@lorthirk : can you update the status of this issue ?

**Comment by lorthirk** [comment]
This is still to be implemented, as now the efforts on the Patternfly console are mainly on the Devices part

**Comment by Coduz** [comment]
Hi all, 

do we want to implement this in Console V1? 
Just asking to know how to manage labels.

Regards, 

_Alberto_

**Comment by Coduz** [comment]
Closing this issue due to change of plans for the Web Administration Console
