### ISSUE TITLE
Console “Data" Usability Improvements

### ISSUE THREAD

**Issue by mcarrer** [eclipse/kapua#1100]
The following usability improvements can be applied to the Data section in the Kapua Console.
* Data
    * By Topic
        * [x] Can we move the Refresh button on the right side of Available Topics top bar or in a toolbar inside the first grid?
        * [x] Result table, can we balance the width of the columns? Timestamp is expanding too much
    * By Device
        * [x] Is there a "Loading..." mask used on available Devices?
        * [x] Can we show the Display Name in the available Devices table and the client ID between parenthesis like we do in EC4?
        * [x] Can we move the Refresh button on the right side of Available Topics top bar or in a toolbar inside the first grid?
        * [x] Result table, can we balance the width of the columns? Timestamp is expanding too much
    * By Asset
        * [x] Is there a "Loading..." mask used on available Devices?
        * [x] Can we show the Display Name in the available Devices table and the client ID between parenthesis like we do in EC4?
        * [x] Can we move the Refresh button on the right side of Available Topics top bar or in a toolbar inside the first grid?
        * [x] Result table, can we balance the width of the columns? Timestamp is expanding too much

**Comment by lorthirk** [comment]
All the comments should have been addressed in branch `fix-data_view_usability_improvements`

**Comment by LeoNerdoG** [comment]
@lorthirk I have verified that all the changes are successfully implemented in the branch above. From my point of view it can be merged.

**Comment by lorthirk** [comment]
Merged in develop with 488866206
