### ISSUE TITLE
New and Edit dialog behavior for unique constraint violations

### ISSUE THREAD

**Issue by mcarrer** [eclipse/kapua#1111]
In the dialogs like New/Edit Account, User, Role, Device... where a unique constraint on a filed may prevent the operation from succeeding, the behaviors should be the following:

1. The dialog should stay open 
2. The offering field should be highlighted in red with an error icon on the right side of the field

This applies to at least the following use cases:

1. [x] New Account, duplicate name
2. [x] New User, duplicate name
3. [x] New Device, duplicate Client ID
4. [x] New Tag
5. [x] Edit Tag
6. [x] New Role
7. [x] Edit Role
8. [x] New Access Group
9. [x] Edit Access Group

**Comment by lorthirk** [comment]
Also implemented in

[x] New Job
[x] Edit Job
[x] New Job Step
[x] Edit Job Step
[x] New Job Schedule

**Comment by lorthirk** [comment]
Branch `fix-new_edit_dialog_collision_close` is ready with the requested changes

**Comment by LeoNerdoG** [comment]
@lorthirk I have verified the changes and every scenario except Access Groups scenario works. So if you want to add a group with non-unique name the dialogue box closes (both: add and edit).

**Comment by lorthirk** [comment]
My mistake. The branch is updated, can you check again?

**Comment by LeoNerdoG** [comment]
I have checked again and now everything is OK. You can merge.

**Comment by lorthirk** [comment]
Merged in develop with 8df63c737
