### ISSUE TITLE
Setup Kapua build in Eclipse Hudson instance for test coverage

### ISSUE THREAD

**Issue by stefanomorson** [eclipse/kapua#112]
We would like to start setting up the build in Hudson.
At this stage it is required to just build and run unit tests. 
No upload of the build artifacts into eclipse repos has to be done.

**Comment by hekonsek** [comment]
I have just added job configuration named `develop` [1]. It is intended to run basic Kapua build from develop branch. Including all unit tests of course.

[1] https://hudson.eclipse.org/kapua/

**Comment by hekonsek** [comment]
BTW Eclipse Hudson is waaaay slower than Travis CI [1] :)

[1] https://travis-ci.org/eclipse/kapua/builds

**Comment by hekonsek** [comment]
Done.
