### ISSUE TITLE
Kapua Changes Tabs When Installing Package

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1124]
When user goes **_Devices_** -> **_Packages_** -> **_In Progress_** and clicks _**Install **_, enters a URL of a package (e.g. from Eclipse MarketPlace), package name and version and hits _**Submit**_, Kapua automatically swtiches to _**installed**_ tab, rather than staying on _**In Progress**_ tab. 

Testflow: 
1. Login as kapua-sys
2. Connect live Kura device to Kapua
2. Go to Devices (select the connected Kura device) -> Packages -> In Progress -> Install
4. Install a deployment package (e.g. from Eclipse MarketPlace)
**Observe how Kapua switches to _Installed_ tab.**

Screenshot No. 1 (When user hits uninstall, _**In Progress**_ tab is chosen):
![screen shot 2017-12-05 at 09 21 13](https://user-images.githubusercontent.com/15121999/33596945-0cc413ec-d99e-11e7-8843-baa616597610.png)

Screenshot No. 2 (Kapua switcehs form _**In Progress**_ to _**Installed**_ automatically):
![screen shot 2017-12-05 at 09 26 54](https://user-images.githubusercontent.com/15121999/33597089-8ddc9c9c-d99e-11e7-92c8-322c7845fffb.png)

Browsers used:
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by lorthirk** [comment]
The **In Progress** tab is hidden at this moment.

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
