### ISSUE TITLE
Device Packages Columns Arrangement Not Working

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1128]
Tipically, when user is widening or narrowing the columns in certain tab, all the other columns get narrowed and/or widened, so all the columns take up the entire length of a window (screenshot No. 1).
But in this case, if user narrows columns in Device -> Packages, others do not adopt to new situation, so now we can get window with empty right side (screenshot No. 2).

Testflow: 
1. Login as kapua-sys
2. Connect a live Kura device to Kapua 
3. Go to Devices -> Packages (select live device)
4. Try to narrow columns, as showed on screenshot No. 2.
**This should not be possible, but nevertheless, Kapua allows user to narrow columns in this unussual way.**

Screenshot No. 1 (regardless of how wide certain column is, they should always cover entire window):
<img width="1435" alt="screen shot 2017-12-05 at 11 43 00" src="https://user-images.githubusercontent.com/15121999/33602952-37d2b378-d9b1-11e7-8713-2fd625c2b183.png">

Screenshot No. 2: 
![screen shot 2017-12-05 at 10 56 17](https://user-images.githubusercontent.com/15121999/33602950-33c71efe-d9b1-11e7-9eea-507ec4f35217.png)

Browsers used:
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by lorthirk** [comment]
This should also be fixed by 2476a78

**Comment by LeoNerdoG** [comment]
hi @lorthirk ,
I have verified that this issue is resolved.
