### ISSUE TITLE
Device's Configuration Tab Not Refreshed Automatically 

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1133]
When user changes configuration of a device, _**refresh**_ button has to be pressed in order to get the latest configuration. 

Testflow: 
1. Login as kapua-sys 
2. Connect live Kura device to Kapua (e.g. Raspberry pi)
3. Go to Devices, select live device, go to Configuration.
4. Change some Configuration parameters (ClockService...) and click _**Save**_
**Kapua does save the changes that have been made, but user has to press _refresh_ button in order to get this updated configuration.**

Screenshot No. 1 (setting ClockService from False to True): 
<img width="1436" alt="screen shot 2017-12-06 at 10 26 42" src="https://user-images.githubusercontent.com/15121999/33655241-d3ce2bce-da72-11e7-9ea3-8e1f93ef3340.png">

Screenshot No. 2 (Applying the changes):
<img width="1437" alt="screen shot 2017-12-06 at 10 26 53" src="https://user-images.githubusercontent.com/15121999/33655280-ed1ffe86-da72-11e7-98ad-c3bc0dec9c2b.png">

Screenshot No. 3 (ClockService settings are still set to False. Settings chage, If user refreshes the configuration.): 
![screen shot 2017-12-06 at 10 27 31](https://user-images.githubusercontent.com/15121999/33655446-5f292d5e-da73-11e7-97ce-7310b74b8649.png)

Browsers used:
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by lorthirk** [comment]
This is probably because we don't have any feedback from the device when it applies the changes. Since it may take a few seconds before the device acknowledge the change the automatic refresh is triggered before this acknowledgment. Can you confirm @Coduz?

**Comment by LeoNerdoG** [comment]
Hej @Coduz @lorthirk I agree to close this with label _**wontfix**_ if there is (currently) no way to norify the web UI. 

Regards, 
Leo

**Comment by LeoNerdoG** [comment]
I am closing this due to upper comments. 
@lorthirk can you please add "WONTFIX" label to it? 
Thank you,
Leo
