### ISSUE TITLE
No Error Message For Non-Saved Changes When Leaving Devices Tab

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1137]
When user adds or connects a device and then changes its configuration - if changes are not saved when selecting some other parameter, Kapua returns an error aksing user if save or discard changes (look at the screenshot).
However, if user selects any other _main_ tab (Tags, Roles, Child Accounts...) Kapua does not ask user for saving/discarding changes. 

Testflow: 
1. Login as kapua-sys 
2. Connect live Kura device to Kapua (e.g. Raspberry pi)
3. Go to Devices, select live device, go to Configuration.
4. Change some Configuration parameters (ClockService...) but do not save them
5. Go to Roles/Groups/Tags/...
**Kapua does not warn user that there are unsaved changes, but instead it discards them automatically.**

Screenshot (This kind of error should be reported, if user changed configuration and left Devices tab without saving them):
<img width="1434" alt="screen shot 2017-12-06 at 12 24 16" src="https://user-images.githubusercontent.com/15121999/33659742-94e40546-da81-11e7-959a-1a1426c02844.png">

Browsers used:
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by lorthirk** [comment]
The best option would be to add the same listener we now have on service change to tab change as well

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
