### ISSUE TITLE
Tags Automatically Added To All Devices

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1140]
If user creates a certain amount of tags, they will automatically be added to Device's tags (look at the screenshot bellow).

Testflow: 
1. Login as kapua-sys
2. Go to Tags, create 10+ unique tags
3. Go to Devices, created or add several devices
4. Select any device, go to its Tags tab and click _**refresh**_ button on the bottom. 
**The tag list gets populated with all tafs, which are added in _Tags_ tab.**

Screenshot (e.g. if user creates 6 tags, all of them will be added to all devices):
<img width="1437" alt="screen shot 2017-12-06 at 15 41 47" src="https://user-images.githubusercontent.com/15121999/33666905-abfd70f4-da9b-11e7-97fc-43320fb8f20c.png">

Browsers used:
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by lorthirk** [comment]
I can't seem to reproduce the issue. Could you please test it again?

**Comment by LeoNerdoG** [comment]
Hi @lorthirk ,
I was still able to reproduce the issue following the instructions.

**Comment by lorthirk** [comment]
A fix is available in `fix-tag_grid_pagination_toolbar` branch

**Comment by LeoNerdoG** [comment]
@lorthirk I have verified that branch `fix-tag_grid_pagination_toolbar` successfully fixes this issue. It can be merged when ready.

**Comment by lorthirk** [comment]
Merged in develop with 5f32e5a529e58193d5dec7ac6830aceb27e69ff7

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
