### ISSUE TITLE
Device Configuration Windows Cannot Be Resized Unless One Of The Services Is Clicked

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1141]
When user connects live device to Kapua, selects it and looks at its configuration, the two windows cannot be resized (look at screenshot No. 1) and the input fields are very short, unless user clicks on one of the Services (screenshot No. 2). After that, everything works normally. 

Testflow:
1. Login as kapua-sys
2. Connect live Kura device to Kapua (e.g. Raspberry Pi)
3. In Kapua go to Devices - > slecet live device -> Configuration
**At this point user cannot resize bottom windows and the input fields are very short (screenshot 1). But if user clicks on one of the service, the _three dot button_ for resizing appears and input fields have normal length (screenshot No. 2).**

Screenshot No. 1 (Situation, before user clicks on one of the services):
![screen shot 2017-12-07 at 09 26 07](https://user-images.githubusercontent.com/15121999/33705690-904dfa54-db31-11e7-8d38-5426a8122dee.png)

Screenshot No. 2 (When user clicks on one of the services, everything is back to normal):
![screen shot 2017-12-07 at 09 33 37](https://user-images.githubusercontent.com/15121999/33705695-935d37aa-db31-11e7-9ac3-41d08446b3d5.png)

Browsers used:
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by lorthirk** [comment]
Auto select the first configuration item at device selection so the panel load is forced?

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
