### ISSUE TITLE
In Available Topics In Data, Slider Appears Although Only One Topic Is Available

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1144]
If user expands bottom window, the _**Available Topics**_ windows gets a slider, although there is only one topic available. 

Testflow: 
1. Login as kapua-sys
2. Connect live Kura device with installed Example Publisher (e.g. Raspberry Pi)
3. Go to Data -> By Topic
4. Expand bottom (results) window.
**At this point, the _Available topics_ window gets a slider, although there is only Example publisher listed.**

![screen shot 2017-12-07 at 13 17 57](https://user-images.githubusercontent.com/15121999/33715877-65c48316-db54-11e7-9b74-89a1a71c432b.png)

Browsers used:
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by muros-ct** [comment]
This is issue that occurs inside GWT component that displays this scroll bar.
It can not be fixed without doing changes to GWT, but we are limited with certain version and this is no-go.
