### ISSUE TITLE
In Available Devices In Data, Slides Appear Although Only One Device Is Available

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1145]
If user expands bottom (results) window, the _**Available Devices**_ window gets sliders, although there is only one device available. 

Testflow: 
1. Login as kapua-sys
2. Connect live Kura device with installed Example Publisher (e.g. Raspberry Pi)
3. Go to Data -> By Device/By Asset
4. Expand bottom (results) window.
**At this point, the _Available devices_ window gets a slider, although there is only one device listed.**

![screen shot 2017-12-07 at 13 18 50](https://user-images.githubusercontent.com/15121999/33716243-b20eb970-db55-11e7-958d-b3b45239ede4.png)

![screen shot 2017-12-19 at 09 39 11](https://user-images.githubusercontent.com/15121999/34148150-86aebe16-e4a0-11e7-81a4-ff031ca37970.png)

Browsers used:
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by muros-ct** [comment]
This is issue that occurs inside GWT component that displays this scroll bar.
It can not be fixed without doing changes to GWT, but we are limited with certain version and this is no-go.
