### ISSUE TITLE
In Available Assets In Data, Slider Appears Although No Assets Available

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1146]
If user expands bottom (results) window, the _**Available Devices**_ window gets a slider, although there are no assets available. 

Testflow: 
1. Login as kapua-sys
2. Go to Data -> By Asset
3. Expand bottom (results) window.
**At this point, the _Available Assets_ window gets a slider, although no assets are available.**

![screen shot 2017-12-07 at 13 19 46](https://user-images.githubusercontent.com/15121999/33716403-52e21c02-db56-11e7-8c4e-faa338fe5528.png)

Browsers used:
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by muros-ct** [comment]
This is issue that occurs inside GWT component that displays this scroll bar.
It can not be fixed without doing changes to GWT, but we are limited with certain version and this is no-go.
