### ISSUE TITLE
Column Arrangement In Available Topics And Available Metrics For Topic in Data Not Working

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1147]
Tipically, when user is widening or narrowing the columns in certain tab, all the other columns get narrowed and/or widened, so all the columns take up the entire length of a window.
But in this case, if user narrows columns in Data -> Available Topics/Available Metrics For Topic, others do not adopt to new situation, so now we can get window with empty right side (look at the screenshot).

Testflow: 
1. Login as kapua-sys
2. Go to Data -> By Topic -> Available Topics/Available Metrics For Topic
3. Try to narrow columns, as showed in screenshot.
**This should not be possible, but nevertheless, Kapua allows user to narrow columns in this unusual way.**

![screen shot 2017-12-07 at 14 03 22](https://user-images.githubusercontent.com/15121999/33717126-0f0ebde8-db59-11e7-8514-12be4fb53dbe.png)

Browsers used:
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by LeoNerdoG** [comment]
Hi @lorthirk ,
issue still persists in Available Metrics for Topic, if only **Metric** or only **Metric Type** column selected. If both metrics are selected, the issue is somehow resolved. 
In **Available Topics** part everything is OK: 

Screenshot No. 1 (If only **Metric** column selected):
<img width="1439" alt="screen shot 2018-01-15 at 10 33 04" src="https://user-images.githubusercontent.com/15121999/34936032-2df53e26-f9e0-11e7-94f6-03dcba2efb2e.png">

Screenshot No. 2 (if only **Metrc Type** column selected):
<img width="1438" alt="screen shot 2018-01-15 at 10 32 54" src="https://user-images.githubusercontent.com/15121999/34936025-2a057222-f9e0-11e7-8a6a-51cb53a422a8.png">

**Comment by lorthirk** [comment]
I suspect that this could be related to the grid having also a checkbox selection model. If this is true it could be a bug in GXT. I'm putting this on hold, and close the other instances of this issue as duplicates so that we can track the progress in one single place.

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
