### ISSUE TITLE
Column Arrangement in Available Devices And Available Metrics For Device in Data Not Working

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1148]
Tipically, when user is widening or narrowing the columns in certain tab, all the other columns get narrowed and/or widened, so all the columns take up the entire length of a window.
But in this case, if user narrows columns in Data -> Available Devices/Available Metrics For Topic, others do not adopt to new situation, so now we can get window with empty right side (look at the screenshot).

Testflow: 
1. Login as kapua-sys
2. Go to Data -> By Device -> Available Devices/Available Metrics For Device
3. Try to narrow columns, as showed in screenshot.
**This should not be possible, but nevertheless, Kapua allows user to narrow columns in this unusual way.**

![screen shot 2017-12-07 at 14 20 25](https://user-images.githubusercontent.com/15121999/33717253-86694930-db59-11e7-9f33-694348cb6568.png)

Browsers used:
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by LeoNerdoG** [comment]
Hi @lorthirk ,
issue still persists in Available Metrics for Device, if only **Metric** or only **Metric Type** column selected. If both metrics are selected, the issue is somehow resolved. 
In **Available Devices** part everything is OK: 

Screenshot No. 1 (If only **Metric** column selected):
<img width="1438" alt="screen shot 2018-01-15 at 10 42 24" src="https://user-images.githubusercontent.com/15121999/34936194-bfba0f26-f9e0-11e7-9544-ebf9a961d8c8.png">

Screenshot No. 2 (if only **Metrc Type** column selected):
<img width="1440" alt="screen shot 2018-01-15 at 10 42 14" src="https://user-images.githubusercontent.com/15121999/34936198-c39e0e44-f9e0-11e7-9c6b-5d71383ad3c8.png">

**Comment by lorthirk** [comment]
Duplicates #1147
