### ISSUE TITLE
Kapua UI Freezes If Job Step Name Too Long 

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1153]
If user adds job step with name longer than 256 characters, Kapua UI freezes and has to be refreshed. 

Testflow: 
1. Login as kapua-sys
2. Go to Jobs, creat a job and add a step to it with name longer than 256 characters
**Kapua should report an error or warning regarding the job step name, but UI freezes instead.**

<img width="1438" alt="screen shot 2017-12-08 at 13 00 33" src="https://user-images.githubusercontent.com/15121999/33765157-e7483db0-dc17-11e7-9c95-ffbfb65b1314.png">

Browsers used:
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0.1 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by lorthirk** [comment]
Fixed by 7995a6b2c

**Comment by LeoNerdoG** [comment]
Hi @lorthirk ,
I have tested this and now I get _**Error while adding step: null**_ error if I try to add a step with name shorter than 256 characters (look at the screenshot No. 1 bellow). 
If I enter step name with name longer than 255 characters I get an _**Error while adding step: An illegal value was provided for the argument jobStepCreator.name: Value over than allowed max value. Max value is 255.**_ error, which is ok, because name is too long (nevertheless I think the error should be shorter, because user can barely read all the text -  info box dissapears too fast).  

Screenshot No. 1 (If job step name is shorter than 256 characters): 
<img width="1335" alt="screen shot 2018-01-17 at 10 30 19" src="https://user-images.githubusercontent.com/15121999/35036094-80515be8-fb73-11e7-9d2c-bffd38db068d.png">

Screenshot No. 2 (If job step name is longer than 256 characters - OK response): 
<img width="1436" alt="screen shot 2018-01-17 at 10 43 14" src="https://user-images.githubusercontent.com/15121999/35036097-82ca5640-fb73-11e7-8d81-23a2dc7d48bc.png">

Browsers used:
- Google Chrome (Version 63.0.3239.132 (Official Build) (64-bit)))
- Safari (Version 11.0.2 (13604.3.5))
- Mozilla Firefox (57.0.4 (64-bit))
- Opera (Version 50.0.2762.45)

**Comment by lorthirk** [comment]
The previous fix didn't consider an empty description. With e5cfcceda there should be no more issues

**Comment by LeoNerdoG** [comment]
Hi @lorthirk ,
I have verified that this issue is resolved.
