### ISSUE TITLE
No Upper Limit For Job Step Description Field

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1154]
User can enter any number of characters in job step description box - if string entered is too long (30M+ characters), Kapua becomes extremely unresponsive. 

Testflow: 
1. Login as kapua-sys 
2. Go to Jobs, create a job and add a step to it
3. Enter very long string of characters into _**job step description**_
**Because Kapua does not have upper limit for this field, it can become unresponsive or even crash.**

Screenshot No. 1 (Loading screen is present for 30 sec+ if job step description extremely long): 
<img width="1436" alt="screen shot 2017-12-08 at 12 56 42" src="https://user-images.githubusercontent.com/15121999/33765497-581b045e-dc19-11e7-8dd6-d8bcec700122.png">

Screenshot No. 2 (When editing job with very long step name, it takes a lot of time to refresh):
<img width="1436" alt="screen shot 2017-12-08 at 12 57 04" src="https://user-images.githubusercontent.com/15121999/33765506-6427e80c-dc19-11e7-9e58-baf948d702b2.png">

Browsers used:
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0.1 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by LeoNerdoG** [comment]
Hi @lorthirk ,
the issue still persists. I have tested this and user can still enter "unlimited" number of characters.

**Comment by lorthirk** [comment]
@LeoNerdoG you're right of course, I only limited it backend side to prevent a value larger than 8k, but I forgot to add the check in the UI. I've added it now in 45ab6e59b. Sorry about that!

**Comment by LeoNerdoG** [comment]
@lorthirk no problem :)
I have verified that commit `45ab6e5` successfully resolves this issue. Closing.
