### ISSUE TITLE
Any Symbol Can Be Entered in BundleID Field in Kapua Jobs

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1156]
Although bundleID is a number, user can enter any symbol to the _**bundleID**_ field (screenshot No. 1).
This job can also be successfully started (screenshot No. 2). 

Testflow: 
1. Login as kapua-sys
2. Go to Jobs, create new job and add a step to it
3. As _**Step Definition**_ set _**Device Bundle Management Start/Stop**_
**At this point, user can enter any symbol into _BundleID_, although this parameter is a number.**

Screenshot No. 1: 
<img width="1435" alt="screen shot 2017-12-08 at 13 30 59" src="https://user-images.githubusercontent.com/15121999/33766840-9d9079b4-dc1f-11e7-903b-704bd5c89e51.png">

Screenshot No. 2:  
<img width="1433" alt="screen shot 2017-12-08 at 13 32 43" src="https://user-images.githubusercontent.com/15121999/33767200-f9972658-dc20-11e7-8a9d-8c7e5d7ce8ed.png">

Browsers used:
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0.1 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by lorthirk** [comment]
After a brief talk with @Coduz, we thought that the Bundle ID field should be left as a String to allow more flexibility in supporting frameworks different from OSGi that may have a non-numeric ID.
