### ISSUE TITLE
No Upper Limit For bundleID Field in Jobs

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1157]
User can enter any number of characters in job bundleID field - if string entered is too long (30M+ characters), Kapua becomes extremely unresponsive. 

Testflow: 
1. Login as kapua-sys 
2. Go to Jobs, create a job and add a step to it
3. Select _**Device Bundle Management Start/Stop**_ in Step definition
3. Enter very long string of characters into _**bundleID**_
**Because Kapua does not have upper limit for this field, it can become unresponsive or even crash.**

<img width="1438" alt="screen shot 2017-12-08 at 14 18 33" src="https://user-images.githubusercontent.com/15121999/33767558-5bc63c78-dc22-11e7-8a92-423cbabc8f27.png">

Browsers used:
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0.1 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by lorthirk** [comment]
@Coduz could we think about a limit to the field characters to set here?

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
