### ISSUE TITLE
No Upper Limit For CommandInput Field in Jobs

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1160]
User can enter any number of characters in job CommandInput field - if string entered is too long (30M+ characters), Kapua becomes extremely unresponsive. 

Testflow: 
1. Login as kapua-sys 
2. Go to Jobs, create a job and add a step to it
3. Select _**Device Command Management Execution**_ in Step definition
3. Enter very long string of characters into _**commandInput**_
**Because Kapua does not have upper limit for this field, it can become unresponsive or even crash.**

Screenshot No. 1 (Adding long string of characters): 
<img width="1438" alt="screen shot 2017-12-08 at 15 11 25" src="https://user-images.githubusercontent.com/15121999/33769517-c8f29c62-dc2a-11e7-8fcc-a0f9f98c23c9.png">

Screenshot No. 2 (Kapua freezes for a while, when trying to edit the job step):
<img width="1439" alt="screen shot 2017-12-08 at 15 12 21" src="https://user-images.githubusercontent.com/15121999/33769522-cfa96a5e-dc2a-11e7-912a-d5809d721714.png">

Browsers used:
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0.1 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by muros-ct** [comment]
Closing with the same comment as #1158.
