### ISSUE TITLE
No Upper Limit For Configuration Field in Jobs

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1161]
User can enter any number of characters in job Configuration field - if string entered is too long (30M+ characters), Kapua becomes extremely unresponsive. 

Testflow: 
1. Login as kapua-sys 
2. Go to Jobs, create a job and add a step to it
3. Select _**Device Configuration Management Configuration**_ in Step definition
3. Enter very long string of characters into _**Configuration**_
**Because Kapua does not have upper limit for this field, it can become unresponsive or even crash.**

Screenshot No. 1 (Adding long string of characters): 
<img width="1435" alt="screen shot 2017-12-08 at 15 28 58" src="https://user-images.githubusercontent.com/15121999/33769927-30becbb2-dc2c-11e7-8ca2-8985a2451b4d.png">

Screenshot No. 2 (Kapua freezes for a while, when trying to edit the job step):
<img width="1438" alt="screen shot 2017-12-08 at 15 28 41" src="https://user-images.githubusercontent.com/15121999/33769916-27133c74-dc2c-11e7-8221-fb32e3dee880.png">

Browsers used:
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0.1 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by muros-ct** [comment]
Closing with the same comment as #1158.
