### ISSUE TITLE
No Upper Limit For PackageDownloadRequest Field in Jobs

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1162]
User can enter any number of characters in job PackageDownloadRequest field - if string entered is too long (30M+ characters), Kapua becomes extremely unresponsive. 

Testflow: 
1. Login as kapua-sys 
2. Go to Jobs, create a job and add a step to it
3. Select _**Device Packages Management Download Execution**_ in Step definition
3. Enter very long string of characters into _**PackageDownloadRequest**_
**Because Kapua does not have upper limit for this field, it can become unresponsive or even crash.**

Screenshot No. 1 (Adding long string of characters): 
<img width="1438" alt="screen shot 2017-12-08 at 15 30 11" src="https://user-images.githubusercontent.com/15121999/33770211-15e1c280-dc2d-11e7-8adb-75b62d0e25e9.png">

Screenshot No. 2 (Kapua freezes for a while, when trying to edit the job step):
<img width="1435" alt="screen shot 2017-12-08 at 15 35 48" src="https://user-images.githubusercontent.com/15121999/33770232-2620cab0-dc2d-11e7-9761-8bb18b6b5139.png">

Browsers used:
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0.1 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by muros-ct** [comment]
Closing with the same comment as #1158.
