### ISSUE TITLE
No Upper Limit For PackageUninstallRequest Field in Jobs

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1164]
User can enter any number of characters in job PackageUninstallRequest field - if string entered is too long (30M+ characters), Kapua becomes extremely unresponsive. 

Testflow: 
1. Login as kapua-sys 
2. Go to Jobs, create a job and add a step to it
3. Select _**Device Packages Management Uninstall Execution**_ in Step definition
3. Enter very long string of characters into _**PackageUninstallRequest**_
**Because Kapua does not have upper limit for this field, it can become unresponsive or even crash.**

Screenshot No. 1 (Adding long string of characters): 
<img width="1438" alt="screen shot 2017-12-11 at 08 17 27" src="https://user-images.githubusercontent.com/15121999/33819588-8a1d5946-de4b-11e7-8a0e-88130ef418a1.png">

Screenshot No. 2 (Kapua freezes for a while, when trying to edit the job step):
<img width="1440" alt="screen shot 2017-12-11 at 08 16 12" src="https://user-images.githubusercontent.com/15121999/33819589-8bfd2002-de4b-11e7-84a1-37880f799050.png">

Browsers used
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0.1 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by muros-ct** [comment]
Closing with the same comment as #1158.
