### ISSUE TITLE
Wrong Maximum Value For Retry Interval in Jobs

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1165]
When user is creating a schedule for certain job, the maximum possible number, Kapua should accept, cannot be entered (look at the screenshot bellow). 

Testflow: 
1. Login as kapua-sys
2. Go to Jobs, create a job (e.g. job1) 
3. Create a schedule for job1 (add _name_, _starts on_ and _Time_). 
4. When entering _Retry interval_, user cannot enter the maximum possible number (1.7976931348623157e+308) as stated by Kapua. 
**When trying to enter the number mentioned, Kapua returns a warning.**

Screenshot (Kapua returns a warning, when trying to enter maximum possible number): 
<img width="1432" alt="screen shot 2017-12-11 at 08 45 34" src="https://user-images.githubusercontent.com/15121999/33820872-c60606f0-de51-11e7-873a-2cb518f71515.png">

Browsers used
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0.1 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by LeoNerdoG** [comment]
Hi @stefanomorson ,
this issue is kind of _**obsolete**_, Kapua today behaves differently.
The absolute maximum value I was able to enter into _**retry interval**_ field is actually **999999999** (tested today).
There must have been some changes since I last tested this, because in example above number entered is much longer than I could enter today.
User also does not get this error ( _**The maximum value for this...**_) but Kapua closes the window (when "submit" is clicked) instead and shows generic _**Persistance**_ error.

**Comment by lorthirk** [comment]
So, @LeoNerdoG, the only issue is now that the dialogue closes with a PersistenceException if you try to enter **999999999** as a retry interval?

**Comment by LeoNerdoG** [comment]
@lorthirk today I have again noticed different behaviour from kapua regarding this matter. The maximum number I can enter is 999999999, but if I enter 9999999999 (one "9" more) Kapua does not highlight the _**Retry interval**_ field with error but just reports _**Persistance Exception**_ (look at the screenshot). 
<img width="1370" alt="screen shot 2018-02-09 at 09 28 24" src="https://user-images.githubusercontent.com/15121999/36018421-f83e7234-0d7b-11e8-96b0-f6d7d240823d.png">

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
