### ISSUE TITLE
"Add" Button in Schedules Not Frozen Although No Job Selected

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1167]
When User clicks on _**Job**_ tab on the left side of Kapua GUI, no job is selected. But if user goes to _**Schedule**_, the _**Add**_ button is not frozen, although it should be, because no job is selected (look at the screenshots bellow). User can click on this button and enter all the parameters, but when _**Submit**_ is clicked, Kapua freezes. 

Testflow: 
1. Login as kapua-sys
2. Go to Jobs -> Schedules
**_Add_ button should be frozen, if no job is selected, but it is not.**

Screenshot No. 1: 
![screen shot 2017-12-11 at 09 27 08](https://user-images.githubusercontent.com/15121999/33822028-61ee4b1e-de56-11e7-94bc-54c130ed1e7c.png)

Screenshot No. 2:
<img width="1437" alt="screen shot 2017-12-11 at 09 27 26" src="https://user-images.githubusercontent.com/15121999/33822013-4de42c60-de56-11e7-968f-fe124c4e3144.png">

Browsers used
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0.1 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by stefanomorson** [comment]
@LeoNerdoG: I would use the term disabled in place of frozen.

**Comment by stefanomorson** [comment]
#### Expected results
* If no job is selected the "Add" button in the job schedules tab should be disabled
* IF no job is selected the "Refresh" button in the job schedules should be disabled

**Comment by LeoNerdoG** [comment]
I have verified that this issue is resolved with PR #1354 .
