### ISSUE TITLE
Kapua GUI Freezes If Schedule's Time Parameter Not In Proper Format

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1169]
When user creates a schedule, any number (or symbol) in the **_Time_** field can be added, as this is free-input field. 
So if user enters time paramter as expected (e.g. 01:15, 12:30,...) everything is OK, otherwise Kapua freezes. 

Testflow: 
1. Login as kapua-sys
2. Go to Jobs, add a job (e.g. job1) 
3. Create a schedule for job1 (in Time field enter any symbol or time in incorrect format)
**At this point Kapua freezes and browser tab has to be refreshed.**

Screenshot No. 1 (Entering number in wrong format - correct would be _01:00_ ):
<img width="1440" alt="screen shot 2017-12-11 at 10 38 06" src="https://user-images.githubusercontent.com/15121999/33825590-6a7267dc-de62-11e7-8cc1-06b0c4ab003b.png">

Screenshot No. 2 (Entering number in wrong format and also too long): 
<img width="1437" alt="screen shot 2017-12-11 at 10 44 53" src="https://user-images.githubusercontent.com/15121999/33825595-6cb61f34-de62-11e7-87bb-8e12fc30e3c7.png">

Screenshot No. 3 (Any symbols can be added and Kapuadoes not warn user about this):
<img width="1438" alt="screen shot 2017-12-11 at 10 48 56" src="https://user-images.githubusercontent.com/15121999/33825598-6f4a45f4-de62-11e7-80b1-6c8ad2ff4086.png">

Browsers used
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0.1 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by stefanomorson** [comment]
#### Expected results
If the value typed by the user is not in the correct format, the UI has to show an error. The way the error has to be managed is the same as for date fields (client side validation).

**Comment by LeoNerdoG** [comment]
I have verified that this issue is resolved.
