### ISSUE TITLE
Buttons in Jobs Not Frozen Although Lists Are Empty

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1171]
When there are no jobs in Job tab, the bottom toolbar is not frozen, although the **_Targets_**, **_Steps_**, **_Schedules_** and **_Executions_** lists are empty (look at the screenshots). The toolbar freezes whe user click the bottom _**refresh button.**_

Testfow: 
1. Login as kapua-sys
2. Go to Jobs, checkout the _**Targets**_, _**Steps**_, _**Schedules**_ and _**Executions**_
2.1 The bottom toolbar is not frozen (although all the lists are empty), until the bottom refresh button is pressd. 

Screenshot No. 1 (Bottom toolbar is not frozen, altohugh all the lists are empty):
![screen shot 2017-12-11 at 12 49 26](https://user-images.githubusercontent.com/15121999/33830350-21bf4610-de74-11e7-9a5d-7ccbeda3126e.png)

Screenshot No. 2 (When bottom refresh button is pressed, toolbar gets frozen):
![screen shot 2017-12-11 at 12 50 02](https://user-images.githubusercontent.com/15121999/33830356-27e98d48-de74-11e7-91d6-92c09bc3f13c.png)

Browsers used
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0.1 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by stefanomorson** [comment]
#### Expected results:
The pagination buttons should be in disabled state.

**Comment by lorthirk** [comment]
Probably we only need to refresh the grid once it's rendered.

**Comment by lorthirk** [comment]
A fix is proposed in branch `fix-other_grids_pagination_toolbar`

**Comment by LeoNerdoG** [comment]
@lorthirk I have verified that branch `fix-other_grids_pagination_toolbar` successfully fixes this issue. It can be merged when ready.

**Comment by lorthirk** [comment]
Merged in develop with 236feba0b9cdbfdd1c75e5859c42212acd65313b

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
