### ISSUE TITLE
Buttons in Data Results Not Frozen Although List Is Empty

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1173]
When there are no data (results) in Data tab, the bottom toolbar is not frozen, although the result list is empty (look at the screenshots). The toolbar freezes whe user click the bottom _**refresh button.**_

Testfow: 
1. Login as kapua-sys
2. Go to Data, checkout the _**Results**_ 
2.1 The bottom toolbar is not frozen (although all the list is empty), until the bottom refresh button is pressd. 

Screenshot No. 1 (Bottom toolbar is not frozen, altohugh all the list is empty):
![screen shot 2017-12-11 at 12 49 00](https://user-images.githubusercontent.com/15121999/33831846-f475c0e8-de79-11e7-8cfb-51ce62a99a12.png)

Screenshot No. 2 (When bottom refresh button is pressed, toolbar gets frozen):
![screen shot 2017-12-11 at 12 50 09](https://user-images.githubusercontent.com/15121999/33831849-f73fa8b6-de79-11e7-9bd5-b2650884f7ea.png)

Browsers used
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0.1 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by stefanomorson** [comment]
#### Expected results:
The pagination buttons should be in disabled state.

**Comment by lorthirk** [comment]
This should be similar to #1171. Try to refresh the grid as soon as it's rendered.

**Comment by lorthirk** [comment]
A fix is proposed in branch `fix-other_grids_pagination_toolbar`

**Comment by LeoNerdoG** [comment]
@lorthirk I have verified that branch `fix-other_grids_pagination_toolbar` successfully fixes this issue. It can be merged when ready.

**Comment by lorthirk** [comment]
Merged in develop with 236feba0b9cdbfdd1c75e5859c42212acd65313b

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved with PR #2479.
