### ISSUE TITLE
No Upper Limit For Access Groups Filter Box

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1174]
User can enter any number of characters in Access Groups search/filter box. This can lead to Kapua crash ( _**Java Heap Space**_ errors and similar).

Testflow: 
1. Login as kapua-sys 
2. Go to Access Groups
4. In filter box  try to enter long search strings (60 Milion+)
**Because Kapua does not have upper limit for this fields, it can crash (freezing, etc.).**

<img width="1425" alt="screen shot 2017-12-11 at 14 21 51" src="https://user-images.githubusercontent.com/15121999/33832968-4602ebd0-de7e-11e7-818e-5038844f629c.png">

Browsers used:
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by stefanomorson** [comment]
#### Expected results
The user should not be allowed to add more characters than those allowed for the size of the field in the database.  The limit has to be enforced client side.

**Comment by stefanomorson** [comment]
Limit can be enforced by using the KapuaTextField object introduced as part of #1154

**Comment by LeoNerdoG** [comment]
I have verified that this issue is resolved with PR #1347 .
