### ISSUE TITLE
No Upper Limit For Tags Filter Box

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1176]
User can enter any number of characters in Tag search/filter box. This can lead to Kapua crash ( _**Java Heap Space**_ errors and similar).

Testflow: 
1. Login as kapua-sys 
2. Go to Tags
4. In filter box  try to enter long search strings (60 Milion+)
**Because Kapua does not have upper limit for this fields, it can crash (freezing, etc.).**

<img width="1432" alt="screen shot 2017-12-11 at 15 11 16" src="https://user-images.githubusercontent.com/15121999/33835232-194077b8-de86-11e7-882f-ac436b9ff412.png">

Browsers used:
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by stefanomorson** [comment]
#### Expected results:
Same as #1174

**Comment by LeoNerdoG** [comment]
I have verified that this issue is resolved with PR #1347 .
