### ISSUE TITLE
No Upper Limit For User's Filter Box

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1179]
User can enter any number of characters in User search/filter box. This can lead to Kapua crash ( _**Java Heap Space**_ errors and similar).

Testflow: 
1. Login as kapua-sys 
2. Go to Users
4. In filter box  try to enter long search strings (60 Milion+)
**Because Kapua does not have upper limit for this fields, it can crash (freezing, etc.).**

<img width="1434" alt="screen shot 2017-12-12 at 08 31 13" src="https://user-images.githubusercontent.com/15121999/33872388-fd3ffe76-df16-11e7-9a1e-4aefe99e7402.png">

Browsers used:
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by stefanomorson** [comment]
#### Expected results:
Same as #1174

**Comment by LeoNerdoG** [comment]
I have verified that this issue is resolved with PR #1347 .
