### ISSUE TITLE
Buttons in Device Tags Not Frozen Although List Is Empty

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1183]
When there are no devices connected to Kapua, the _**Tags**_  list is empty, therefore its toolbar should be frozen (look at the screenshots). The toolbar freezes, when user click the bottom _**refresh button.**_

Testfow: 
1. Login as kapua-sys
2. Go to Devices -> Tags
2.1 The bottom toolbar is not frozen (although all the list is empty), until the bottom refresh button is pressd. 

Screenshot No. 1 (Bottom toolbar is not frozen, altohugh all the list is empty):
![screen shot 2017-12-12 at 12 21 54](https://user-images.githubusercontent.com/15121999/33882235-be5f457e-df37-11e7-82bc-2e8e51a80277.png)

Screenshot No. 2 (When bottom refresh button is pressed, toolbar gets frozen):
![screen shot 2017-12-12 at 12 26 13](https://user-images.githubusercontent.com/15121999/33882240-c038c58c-df37-11e7-8e19-3ad9c8f606e1.png)

Browsers used
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0.1 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by stefanomorson** [comment]
#### Expected results
The pagination buttons should be in disabled state.

**Comment by lorthirk** [comment]
This should be similar to #1171. Try to refresh the grid as soon as it's rendered.

**Comment by lorthirk** [comment]
A fix is available in `fix-tag_grid_pagination_toolbar` branch

**Comment by LeoNerdoG** [comment]
@lorthirk I have verified that branch `fix-tag_grid_pagination_toolbar successfully fixes this issue. It can be merged when ready.

**Comment by lorthirk** [comment]
Merged in develop with 5f32e5a529e58193d5dec7ac6830aceb27e69ff7

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
