### ISSUE TITLE
Refresh Button in Device Configuration Not Frozen Although List Is Empty

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1185]
When there are no devices connected to Kapua, the _**Configuration**_  list is empty, therefore its toolbar should be frozen as whole and not just _**save**_ and _**discard**_ (but also _**refresh**_ button - look at the screenshot). 

Testfow: 
1. Login as kapua-sys
2. Go to Devices -> Configuration
3. The refresh button is not frozen (although all the list is empty and no devices are connected), but in _**Tags**_, _**Events**_, _**Bundles**_ and _**Packages**_ refresh button is frozen. 

![screen shot 2017-12-12 at 12 30 49](https://user-images.githubusercontent.com/15121999/33882782-9f1e7304-df39-11e7-95c6-bcb21c47269f.png)

Browsers used
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0.1 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by stefanomorson** [comment]
#### Expected results:
The refresh button should be in disabled state.

**Comment by LeoNerdoG** [comment]
I have verified that this issue is resolved.
