### ISSUE TITLE
Buttons in Users Not Frozen Although No User Selected

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1186]
When no users are selected in User tab, the bottom toolbar is not frozen, although the **_Roles_**, **_Permissions_**, and **_Credentials_** lists are empty (look at the screenshots). The toolbar freezes whe user click the bottom _**refresh button.**_

Testfow: 
1. Login as kapua-sys
2. Go to Users, do not select any user, just checkout the **_Roles_**, **_Permissions_**, and **_Credentials_**
3. The bottom toolbar is not frozen (although all the lists are empty), until the bottom refresh button is pressd. 

Screenshot No. 1 (Bottom toolbar is not frozen, altohugh all the lists are empty):
![screen shot 2017-12-12 at 13 06 34](https://user-images.githubusercontent.com/15121999/33883815-9ac80f1e-df3d-11e7-9741-fa7f8c421d59.png)

Screenshot No. 2 (When bottom refresh button is pressed, toolbar gets frozen):
![screen shot 2017-12-12 at 13 08 03](https://user-images.githubusercontent.com/15121999/33883818-9caadd34-df3d-11e7-87c7-f6597678960c.png)

Browsers used
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0.1 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by stefanomorson** [comment]
#### Expected results:
The pagination buttons should be in disabled state.

**Comment by lorthirk** [comment]
This should be similar to #1171. Try to refresh the grid as soon as it's rendered.

**Comment by lorthirk** [comment]
A fix is proposed in branch `fix-other_grids_pagination_toolbar`

**Comment by LeoNerdoG** [comment]
@lorthirk I have verified that branch `fix-other_grids_pagination_toolbar` successfully fixes this issue. It can be merged when ready.

**Comment by lorthirk** [comment]
Merged in develop with 236feba0b9cdbfdd1c75e5859c42212acd65313b

**Comment by LeoNerdoG** [comment]
I have verified that this issue is resolved.
