### ISSUE TITLE
Background Color In Delete Dialogue Box Is Split In Two Parts

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1188]
When user tries to delete device/job/group... the delete dialogue box is split in two parts: The top slight darker one and the bottom lighter one (see the screenshots). 

Testflow: 
1. Login as kapua-sys
2. Go to Device/Job/Access Groups/Tags/Users/Roles/Child Accounts and add a device/job/group/tag/user/role/child account respectively (e.g. device1, job1, group1,...) 
3. Select the created object and try to delete it.
**When delet info box pops-up, try to spot that the upper part of the dialogue box is darker than bottom part (look at the screenshots bellow).**

Screenshot No. 1 (Device delete dialogue box):
![screen shot 2017-12-12 at 15 32 45](https://user-images.githubusercontent.com/15121999/33890623-1938f460-df54-11e7-8c9d-642ce7182083.png)

Screenshot No. 2 (Jobs delete dialogue box):
![screen shot 2017-12-12 at 15 32 53](https://user-images.githubusercontent.com/15121999/33890631-1cba730c-df54-11e7-81d2-1d41cf3a8c20.png)

Screenshot No. 3 (Users delete dialogue box):
![screen shot 2017-12-12 at 15 33 04](https://user-images.githubusercontent.com/15121999/33890641-23528812-df54-11e7-8dfe-ceb2ee4e77bb.png)

Browsers used
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0.1 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by lorthirk** [comment]
@LeoNerdoG Is this still an issue?

**Comment by LeoNerdoG** [comment]
@lorthirk I have verified that this issue has been fixed.
