### ISSUE TITLE
Use "Authorization Bearer" HTTP header instead of X-Access-Token

### ISSUE THREAD

**Issue by lorthirk** [eclipse/kapua#119]

**Comment by lorthirk** [comment]
Implemented in commit 1ac92da

**Comment by Coduz** [comment]
Hi @lorthirk ,

This issue has been closed with merge of PR #172, right? 
The commit [`f35907f`](https://github.com/eclipse/kapua/commit/f35907f6ab6a6a21bf2e7698f4f65d3fa874386d) has been cherry-picked into that branch, right? 

Regards, 

_Alberto_

**Comment by lorthirk** [comment]
Yes, that's correct. Sorry I forgot to mention it in the PR request expicitly.
