### ISSUE TITLE
No Upper Limit For Child Account Filter Boxes

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1196]
User can enter any number of characters in Child Account search/filter boxes ( _**Account Name**_, _**Organization Name**_ and _**Organization Email**_). This can lead to Kapua crash ( _**Java Heap Space**_ errors and similar).

Testflow: 
1. Login as kapua-sys 
2. Go to Child Accounts
4. In filter boxes try to enter long search strings (60 Milion+)
**Because Kapua does not have upper limit for this fields, it can crash (freezing, etc.).**

<img width="1432" alt="screen shot 2017-12-13 at 13 02 08" src="https://user-images.githubusercontent.com/15121999/33937967-d831c188-e005-11e7-9788-31255fc152df.png">

Browsers used:
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0.1 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by stefanomorson** [comment]
#### Expected results:
Same as #1174

**Comment by LeoNerdoG** [comment]
I have verified that this issue is resolved with PR #1347 .
