### ISSUE TITLE
Unnecessary Sliders in Child Accounts When Resizing Windows

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1202]
When user resizes bottom window in Child Accounts, unnecessary horizontal and a additional vertical slider appear (look at the screenshot). 

Testflow: 
1. Login as kapua-sys 
2. Go to Child Accounts, create a child account (e.g. kapua-child1) 
3. Select kapua-child1, go to its Settings and resize the window as shown in screenshot. 
**Although window does not need additional sliders, Kapua adds Horizontal and vertical one.**

![screen shot 2017-12-15 at 10 25 27](https://user-images.githubusercontent.com/15121999/34035918-dd713834-e183-11e7-9360-74e3a3a720b0.png)

Browsers used:
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0.1 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by stefanomorson** [comment]
@LeoNerdoG I was not able to reproduce this. Can you confirm it is still an issue?

**Comment by LeoNerdoG** [comment]
@stefanomorson I was able to reproduce it following the steps described above. 
Try this: 
0. Browser should be full-sized before test. 
1. Go to child accounts, select one of them and go to _**Settings**_ tab
2. Select _**Role Service**_ and verticlly resize bottom window (the _**Settings**_ window) and shrink (horizontally resize) the whole browser window.
_**Now all the unnecessary sliders should appear.**_

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
