### ISSUE TITLE
Unnecessary Slider in Devices When Resizing Windows

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1203]
When user resizes bottom window in Devices, unnecessary horizontal and a additional vertical slider appear (look at the screenshot). 

Testflow: 
1. Login as kapua-sys 
2. Go to Devices and connect live Kura device to Kapua (e.g. device1) 
3. Select device1 and go to its Configuration settings and resize this window.
**Although window does not need additional sliders, Kapua adds Horizontal and vertical one.**

![screen shot 2017-12-15 at 10 36 46](https://user-images.githubusercontent.com/15121999/34036127-8b6f2d74-e184-11e7-9d41-d760de8b8ecc.png)

Browsers used:
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0.1 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by stefanomorson** [comment]
@LeoNerdoG I was not able to reproduce. Do you confirm this is still an issue ?

**Comment by LeoNerdoG** [comment]
@stefanomorson I was able to reproduce it following the steps described above. 
Try this: 
1. Browser should be full-sized before test. 
2. Connect a live kura device to kapua 
3. Go to Devices, select live connected device and go to its _**Configuration**_
4. Select _**Position service**_ and verticlly resize bottom window (the _**Configuration**_ window) and shrink (horizontally resize) the whole browser window.
_**Now all the unnecessary sliders should appear.**_

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
