### ISSUE TITLE
Background Color In Kapua Devices Split in Two Parts

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1205]
When user resizes bottom window in Devices (Configuration), unnecessary horizontal and a additional vertical slider appear. If user scrolls the second vertical slider all the way down, a white strip appears, that should not be there (look at the screenshot).

Testflow: 
1. Login as kapua-sys 
2. Go to Devices, add a live Kura deveice to Kapua (e.g. device1) 
3. Select device1 and go to its Configuration settings. 
4. Scroll the second (inner) vertical slider all the way down. 
**At the bottom a white strip appears, that should ot be there.**

![screen shot 2017-12-15 at 10 26 24](https://user-images.githubusercontent.com/15121999/34036387-55613384-e185-11e7-9220-f19232626b96.png)

Browsers used:
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0.1 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by stefanomorson** [comment]
@LeoNerdoG I was not able to reproduce, can you confirm that this is still an issue ?

**Comment by LeoNerdoG** [comment]
@stefanomorson I was able to reproduce it following the steps described above.

**Comment by lorthirk** [comment]
Could be related to #1203

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
