### ISSUE TITLE
Wrong Message When Adding Empty Target List in Jobs 

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1206]
When user wants to add a target for a certain job, but selects none of them, Kapua returns _**Targets successfully added**_, although non have been added, because user has not selected any. 

Testflow: 
1. Login as kapua-sys
2. Go to Jobs, add a job. 
3. Try to add _none_ of the devices to the target list
**Although user has not added any devices as targets, Kapua returns info as described above and seen in bellow screenshots.**

Screenshot No. 1 (User selects none of the devices and clicks _Submit_):
<img width="1436" alt="screen shot 2017-12-15 at 10 28 45" src="https://user-images.githubusercontent.com/15121999/34036442-7e53a844-e185-11e7-8474-9b76834af81d.png">

Screenshot No. 2 (Kapua says that devices have been added successfully, although none have  been selected): 
<img width="1437" alt="screen shot 2017-12-15 at 10 28 51" src="https://user-images.githubusercontent.com/15121999/34036447-80b0278e-e185-11e7-86de-08f50e60669d.png">

Browsers used:
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0.1 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by stefanomorson** [comment]
SImilar to #1172

**Comment by LeoNerdoG** [comment]
I have verified that thiss issue has been resolved with PR #1355 .
