### ISSUE TITLE
Broken OpenShift template and docker images for 'restricted' user

### ISSUE THREAD

**Issue by alezzandro** [eclipse/kapua#1207]
Hi there,

I want to report that the current script, template, deploymentconfig for Openshift are broken for a normal user that wants to run Kapua using the knowledge base available in this repo.
I setup a standard Openshift installation cluster with an user using a restricted profile, the standard one shipping with Openshift installation.
Without doing any modification if I run the following script:
`dev-tools/src/main/openshift/openshift-deploy.sh`

I experienced the following errors in the running containers:

**kapua-console:**

**####### LOGS #######**

```
Generating a 4096 bit RSA private key
...................................................++
...++
unable to write 'random state'
writing new private key to '/home/kapua/key.pem'
/home/kapua/key.pem: Permission denied
140597807876000:error:0200100D:system library:fopen:Permission denied:bss_file.c:402:fopen('/home/kapua/key.pem','w')
140597807876000:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:404:
Can't open input file /home/kapua/key.pem
rm: cannot remove '/home/kapua/key.pem': No such file or directory
START_ARGS = -Djetty.home=/home/kapua/jetty -Djetty.base=/var/lib/jetty
JAVA_OPTS = -Xmx1G -Dcommons.db.connection.host=172.30.39.28 -Dcommons.db.connection.port=3306 -Dcommons.db.schema.update=true -Dbroker.host=172.30.102.25 -Ddatastore.elasticsearch.nodes=172.30.155.208 -javaagent:/jolokia-jvm-agent.jar=port=8778,protocol=https,caCert=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt,clientPrincipal=cn=system:master-proxy,useSslClientAuthentication=true,extraClientCheck=true,host=0.0.0.0,discoveryEnabled=false,user=jolokia,password=iEldHiE6WDPxHsm
I> No access restrictor found, access to any MBean is allowed
...
```

**####### DEBUG on container #######**

```
sh-4.2$ id                                                                                                                                                                      
uid=1000050000 gid=0(root) groups=0(root),1000050000       
sh-4.2$ ls -l /home/                                                                                                                                                            
total 0                                                                                                                                                                         
drwxr-xr-x. 3 kapua kapua 111 Dec  1 08:41 kapua                                                                                                                                
sh-4.2$ 
```

**kapua-broker:**

**####### LOGS #######**

```
Generating a 4096 bit RSA private key
.................................................................++
.....................................................................++
unable to write 'random state'
writing new private key to '/home/kapua/key.pem'
/home/kapua/key.pem: Permission denied
139859632584608:error:0200100D:system library:fopen:Permission denied:bss_file.c:402:fopen('/home/kapua/key.pem','w')
139859632584608:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:404:
Can't open input file /home/kapua/key.pem
rm: cannot remove '/home/kapua/key.pem': Permission denied
INFO: Loading '/maven//bin/env'
INFO: Using java '/usr/lib/jvm/jre-openjdk/bin/java'
INFO: Starting in foreground, this is just for debugging purposes (stop process by pressing CTRL+C)
INFO: Creating pidfile /maven//data/activemq.pid
I> No access restrictor found, access to any MBean is allowed
...
```

**####### DEBUG on container #######**

```
sh-4.2$ id                                                                                                                                                                      
uid=1000050000 gid=0(root) groups=0(root),1000050000                                                                                                                            
sh-4.2$ ls -l /home                                                                                                                                                             
total 0                                                                                                                                                                         
drwx------. 2 kapua kapua 62 Nov 29 11:28 kapua   
```

The containers continue starting successfully and all seem ok. Anyway trying to login on kapua-console (kapua-sys user) output this error:
`Unable to provision, see the following errors: 1) Error injecting constructor, org.eclipse.kapua.service.certificate.exception.KapuaCertificateException: Error: at org.eclipse.kapua.service.certificate.internal.CertificateServiceImpl.<init>(CertificateServiceImpl.java:53) while locating org.eclipse.kapua.service.certificate.internal.CertificateServiceImpl at org.eclipse.kapua.locator.guice.KapuaModule.configure(KapuaModule.java:108) while locating: org.eclipse.kapua.service.certificate.CertificateService 1 error`

As you can see by the remote shell debugging, Openshift will assign a random user-id to the container, for that reason the script/process that at startup generate new certificate will fail creating them.
As simple and easy workaround we can change permission on /home/kapua folder letting other user accessing it.

I've tried solving these issues: 
I've made the fix on both containers available on my dockerhub account https://hub.docker.com/r/alezzandro changing permissions.

Basically making a `chmod og+rwx /home/kapua` will solve the permission issues:

**kapua-console:**

**####### LOGS #######**
```
Generating a 4096 bit RSA private key
......................................++
...........................++
unable to write 'random state'
writing new private key to '/home/kapua/key.pem'
-----
START_ARGS = -Djetty.home=/home/kapua/jetty -Djetty.base=/var/lib/jetty
...
```

**kapua-broker:**

**####### LOGS #######**

```
Generating a 4096 bit RSA private key
...............................++
..........................................................................................................................++
unable to write 'random state'
writing new private key to '/home/kapua/key.pem'
-----
INFO: Loading '/maven//bin/env'
INFO: Using java '/usr/lib/jvm/jre-openjdk/bin/java'
INFO: Starting in foreground, this is just for debugging purposes (stop process by pressing CTRL+C)
INFO: Creating pidfile /maven//data/activemq.pid
I> No access restrictor found, access to any MBean is allowed
...
```

Anyway this is not enough, I kept receiving the following errors while trying login on the kapua-console through kapua-sys user:
`Unable to provision, see the following errors: 1) Error injecting constructor, org.eclipse.kapua.service.certificate.exception.KapuaCertificateException: Error: at org.eclipse.kapua.service.certificate.internal.CertificateServiceImpl.<init>(CertificateServiceImpl.java:53) while locating org.eclipse.kapua.service.certificate.internal.CertificateServiceImpl at org.eclipse.kapua.locator.guice.KapuaModule.configure(KapuaModule.java:108) while locating org.eclipse.kapua.service.certificate.CertificateService 1 error
`

It seems that the Openshift's template/deploymentconfig is out-dated looking at the default options we set during the assembly of the containers (kapua-console and kapua-broker) used for startup.

These are the current `JAVA_OPTS` and `ACTIVEMQ_OPTS` used in the respective assembly pom.xml for kapua-console and kapua-broker:

**develop/assembly/console/pom.xml:**
```
...
<JAVA_OPTS>
    -Dcommons.db.connection.host=\${SQL_DB_ADDR} \
    -Dcommons.db.connection.port=\${SQL_DB_PORT} \
    -Dbroker.host=\${BROKER_PORT_1883_TCP_ADDR} \
    -Ddatastore.elasticsearch.nodes=\${DATASTORE_ADDR} \
    -Ddatastore.elasticsearch.port=\${DATASTORE_PORT} \
    -Ddatastore.client.class=\${DATASTORE_CLIENT} \
    -Dcertificate.jwt.private.key=file:///home/kapua/key.pk8 \
    -Dcertificate.jwt.certificate=file:///home/kapua/cert.pem
</JAVA_OPTS>
...
```

and

**develop/assembly/broker/pom.xml:**
```
...
<ACTIVEMQ_OPTS>
    -Dcommons.db.connection.host=\${SQL_DB_ADDR} \
    -Dcommons.db.connection.port=\${SQL_DB_PORT} \
    -Ddatastore.elasticsearch.nodes=\${DATASTORE_ADDR} \
    -Ddatastore.elasticsearch.port=\${DATASTORE_PORT} \
    -Ddatastore.client.class=\${DATASTORE_CLIENT} \
    -Dcertificate.jwt.private.key=file:///home/kapua/key.pk8 \
    -Dcertificate.jwt.certificate=file:///home/kapua/cert.pem
</ACTIVEMQ_OPTS>
...
```

These two options are missing from Openshift template:
`-Dcertificate.jwt.private.key=file:///home/kapua/key.pk8  -Dcertificate.jwt.certificate=file:///home/kapua/cert.pem`

As you can see on `dev-tools/src/main/openshift/kapua-template.yml`.

I've fixed all these issues on my forked repo, I'll make the pull request right now.

**Comment by lorthirk** [comment]
Fixed by #1208
