### ISSUE TITLE
Error Message Regarding Unsaved Changes When Leaving Account Service 

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1210]
When user clicks on or leaves **AccountService** setting in _**Settings**_ tab, Kapua reports unsaved changes, although there aren't any (_**brokerURI**_ field can be modified)

Testflow: 
1. Login as kapua-sys
2. Go to _**Settings**_ tab and click through its services (Account Service, Groups Service, Job Service...)
**When user clicks on or leaves _**AccountService**_, Kapua reports unsaved changes, although there aren't any.** 

Screenshot No. 1 (brokerURI field can be modified): 
![screen shot 2017-12-18 at 12 27 29](https://user-images.githubusercontent.com/15121999/34103989-ef736f08-e3ee-11e7-8564-5a1470abc2af.png)

Screenshot No. 2 (Kapua asking if user wants to discard changes, although there aren't any): 
<img width="1372" alt="screen shot 2017-12-15 at 14 42 22" src="https://user-images.githubusercontent.com/15121999/34045592-dc74c6d2-e1a9-11e7-8380-66dbe213af67.png">

Browsers used:
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0.1 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by lorthirk** [comment]
Has this been fixed in #1098 already? The configuration component should be the same one of the Devices view

**Comment by LeoNerdoG** [comment]
@lorthirk Yes, I have verified that this is resolved.
