### ISSUE TITLE
Any Symbol Can Be Inserted Into "Phone Number" Field in Settings 

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1211]
End user can enter any symbol in _**Phone Number**_ field in Settings -> Description -> Edit -> Phone Number. 

Testflow: 
1. Login as kapua-sys
2. Go to Settings -> Descritption and edit _**Phone Number**_ setting. 
**Kapua permits any symbol in this field,a althoguh there should be only numbers and _+_ sign in the beginning.**

![screen shot 2017-12-15 at 15 31 12](https://user-images.githubusercontent.com/15121999/34046341-02fcd1de-e1ad-11e7-8ce9-44af9b16a64f.png)

Browsers used:
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0.1 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by stefanomorson** [comment]
Should be applied the same fix implemented in #938

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
