### ISSUE TITLE
Kapua Settings Not Refreshed Automatically 

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1214]
When user changes its settings in Settings -> Description -> Edit, settings do not refresh, until someting else is pressed (this is conencted with issue #1209). 

Testflow: 
1. Login as kapua-sys
2. Go to Settings and try to edit some paratmers (Address 1, Address 2, ZIP code, Country...)
**When user clicks _Submit_, changes do not refresh automatically, although Kapua reports changes as saved and updated.**

<img width="1433" alt="screen shot 2017-12-15 at 14 40 10" src="https://user-images.githubusercontent.com/15121999/34104164-acc3f37a-e3ef-11e7-8de9-d0db54c51f63.png">

Browsers used:
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0.1 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by lorthirk** [comment]
This should be fixed in #1095. @LeoNerdoG can you confirm?

**Comment by LeoNerdoG** [comment]
@lorthirk I have verified that this has been resolved via #1095 .
