### ISSUE TITLE
No "No Group" Option in Device Filter

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1218]
When user adds or creates a device, it ahs to be aassigned to one of the groups or to _**No group**_. But if user wants to search devices that _belong_ to _No group_ group, there is no such option (although, there is at device creation - look at the screeshots). 

Testflow: 
1. Login as kapua-sys
2. Go to Devices, add a device (e.g. device1 and select _**No group**_ Access Groups option)
3. After the device is created, go to _**Device Filter**_ -> _**Group**_
**Kapua does not have _No Group_ option, but there should be, as user can add a device to this _group_.**

Screenshot No. 1 (): 
![screen shot 2017-12-19 at 10 08 26](https://user-images.githubusercontent.com/15121999/34149546-bd5473ac-e4a5-11e7-877c-064bd5d7948c.png)

Screenshot No. 2 (): 
![screen shot 2017-12-19 at 10 08 41](https://user-images.githubusercontent.com/15121999/34149549-c03ff80c-e4a5-11e7-9c06-39c84b29e48c.png)

Browsers used:
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0.1 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by lorthirk** [comment]
A new, "static" item called "No Group" should be added to the filter dropdown. If selected, the filter operation will only return devices with no assigned group.

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
