### ISSUE TITLE
Multiple Spaces in Name Reduced To Single Space 

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1221]
When creating groups, jobs, roles or tags user can add multiple spaces in name (e.g. _**t    a    g   
 1**_) but when this name is on the list, it seems like it has only one space. If user wants to edit this name, it is properly shown (with multiple spaces). So the problem is only with the list (look at the screenshots bellow). 

Testflow: 
1. Login as kapua-sys
2. Go to jobs/groups/roles/tags and create an entry, which contains multiple white spaces (see the example above).
**After user clicks _Submit_, the entry is shown on the list, but with only one space instead of multiple.**

Screenshot No. 1 (Problem described in Jobs): 
<img width="1439" alt="screen shot 2017-12-20 at 13 04 27" src="https://user-images.githubusercontent.com/15121999/34211449-656ef686-e599-11e7-848e-a1e25c557470.png">

Screenshot No. 2 (Problem described in Tags): 
<img width="1440" alt="screen shot 2017-12-20 at 13 05 04" src="https://user-images.githubusercontent.com/15121999/34211451-6797b240-e599-11e7-9f7f-ff2124d09992.png">

Screenshot No. 3 (Problem described in Groups): 
<img width="1437" alt="screen shot 2017-12-20 at 13 04 07" src="https://user-images.githubusercontent.com/15121999/34211445-62aa8fa0-e599-11e7-908a-87a9c4acd2fa.png">

Screenshot No. 4 (Problem described in Roles):
<img width="1439" alt="screen shot 2017-12-20 at 13 05 27" src="https://user-images.githubusercontent.com/15121999/34211477-7f2e23d0-e599-11e7-945a-94185bfa9c44.png">

Browsers used:
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0.1 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by stefanomorson** [comment]
#### Expected result:
Spaces should not be allowed for name fields of the following entities: groups, jobs, roles or tags

**Comment by LeoNerdoG** [comment]
I have verified that this issue is resolved.
