### ISSUE TITLE
Commands Can Be Executed Although No Device Selected

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1222]
When user uses only keyboard for navigating through kapua, it can _execute_ commands, althoguh no device is selected (look at the screenshots).

Testflow: 
1. Login as kapua-sys
2. With keyboard keys (_**TAB**_ and _**arrow**_ keys) navigate to _**Command**_ tab of device tab (no device should be selected)
3. With _**TAB**_ key navigate to **Execute** tab and enter a command (e.g. _**ls -l**_ or **sudo shutdown**). 
**At this point Kapua chages info window from _No Device selected_ to _Executing command_.**

Screenshot No. 1 (Entering the command):
![screen shot 2017-12-20 at 13 59 50](https://user-images.githubusercontent.com/15121999/34212896-0466e4de-e59e-11e7-8f15-4df71a4981a7.png)

Screenshot No. 2 (Executing the command): 
![screen shot 2017-12-20 at 14 00 02](https://user-images.githubusercontent.com/15121999/34212918-1415bae0-e59e-11e7-9c8f-5acb8c719c10.png)

Screenshot No. 3 (Kapua reports that it is _executing the command_ ):
![screen shot 2017-12-20 at 14 00 12](https://user-images.githubusercontent.com/15121999/34212939-20bba8b8-e59e-11e7-9226-54c2e8f930e9.png)

Browsers used:
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0.1 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by lorthirk** [comment]
We should prevent keyboard based navigation in disabled components. Perhaps disable the whole panel instead of only masking it?

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
