### ISSUE TITLE
Any Symbol Can Be Entered in Page Number Fields

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1225]
In page number fields, which serve user to switch between pages, any symbol and also any number of symbols can be enteres, which can lead to Kapua crash. 

Testflow: 
1. Login as kapua-sys
2. Select any number enetring field and try to enter any number of all kinds of symbols
**If number exceeds several milion, Kapua freezes.**

Screenshot No. 1 (Error, when too big number entered in Child Accounts page field):
![screen shot 2017-12-21 at 09 15 45](https://user-images.githubusercontent.com/15121999/34248818-acd1836a-e637-11e7-87d4-f68fae638dcb.png)

Screenshot No. 2 (Error, when too big number entered in Roles page field):
![screen shot 2017-12-21 at 09 25 00](https://user-images.githubusercontent.com/15121999/34248822-b0ab1168-e637-11e7-94d4-fe19defea975.png)

Screenshot No. 3 (Kapua's GUI can also crash):
<img width="1439" alt="screen shot 2017-12-21 at 09 27 55" src="https://user-images.githubusercontent.com/15121999/34247361-7bcd83e0-e632-11e7-96d6-8a56f53578da.png">

Browsers used:
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0.1 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by lorthirk** [comment]
The TextBox that holds the current page is currently built-in in GXT PagingToolBar. We would need to find a safe way to replace it with a custom TextBox that can only holds a specified amount of characters.

**Comment by muros-ct** [comment]
@lorthirk I tried to play arround with this paging toolbar and noticed that we already have similar KapuaPagingToolbar.
Can you take a look at this branch if this could be solution.

https://github.com/eclipse/kapua/tree/fix-pagingToolbarText

**Comment by LeoNerdoG** [comment]
I have verified that this issue hasn been resolved. The field number still allows entering any symbol, but as this field is limited to five characters and enetering non-number returns a page number, this is resolved.
