### ISSUE TITLE
jobs - xml registry factory methods should align with object names 

### ISSUE THREAD

**Issue by stefanomorson** [eclipse/kapua#1236]
JobStepXmlRegistry should expose different methods names:
* newJob --> newStep
* newJobCreator --> newStepCreator
* newJobListResult --> newStepListResult

**Comment by lorthirk** [comment]
I choosed to adhere to the classnames for better coherence with the code. So the names went to:

- newJob --> newJobStep
- newJobCreator --> newJobStepCreator
- newJobListResult --> newJobStepListResult

The same goes for JobStepDefinition, JobExecution and JobTarget (the last two covered in 8f5ea663b)
