### ISSUE TITLE
Add more tests to user service

### ISSUE THREAD

**Issue by stefanomorson** [eclipse/kapua#124]
Could be useful to add some more unit tests to the user service:

- changeUserName() 
  - check the update on every field (except the fields of the abstract entity classes)
- add test for find()
- add test for findByName()
- add test for query
  - check the query retrieves exactly the expected users
- add test for parameters (validator)
  - spell check username

**Comment by stefanomorson** [comment]
Parameter testing (validators) will be done in a separated issue

**Comment by lorthirk** [comment]
@muros-ct can you confirm that all these tests have been implemented?

**Comment by muros-ct** [comment]
Yes. This was implemented long time ago.
Leonardo also worked on other issue with validators, so that this is more than closed.

**Comment by Coduz** [comment]
Closing this
