### ISSUE TITLE
msg broker - modularize security broker filter

### ISSUE THREAD

**Issue by stefanomorson** [eclipse/kapua#1241]

**Comment by riccardomodanese** [comment]
The security broker plugin should be modular to allow customization on authentication/authorization logic.
The steps to move toward this pluggability are:

- create an interface, agnostic from any specific broker implementation class (so no ActiveMQ class), to provide a decoupled connection between the broker specific pluggability class and the authentication/authorization logic
- move the authentication/authorization logic outside the current security broker filter implementation
- refactorize the current authentication/authorization logic to allow easy override of one or more steps for each operation

**Comment by riccardomodanese** [comment]
fixed by #1325
