### ISSUE TITLE
telemetry - implement dynamic camel routes

### ISSUE THREAD

**Issue by stefanomorson** [eclipse/kapua#1242]

**Comment by riccardomodanese** [comment]
Telemetry messages should be forwarded to different endpoints on account base.
Changing the forwarding rules should be allowed without rebuilding the application.
With the current code base it's possible through camel.xml customization but the xml could became very huge and complex to manage.

The incoming broker filter refactoring will introduce the camel dynamic router feature allowing more complex routing customization and moving the routing rules in a different configuration file (with the default routing implementation).

**Comment by riccardomodanese** [comment]
#1589 introduces a kind of a Camel configuration wrapper that translates few tags into Camel routes. In that way it's possible to write several telemetry routes indipendently (based on Camel multicast feature) and without any Camel knowledge.
