### ISSUE TITLE
Kapua Does Not Report Error If Years in Users Entered in Wrong Format

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1248]
When entering expiration date for Credentials and Permissions in Users, years should be added as four digit number (YYYY) but Kapua accepts all dates from 0 - 199999.

Testflow: 
1. Login as kapua-sys
2. Go to Users, add or edit existing user (e.g. kapua-user1)
3. Select kapua-user1, go to Credentials and/or Permissions and set Expiration date with the year parameter > 9999. 
**If Expiration date is in range 0 - 199999, Kapua accepts it, although format is _YYYY_.**

Screenshot (Entering Expriation date in wrong format): 
<img width="1372" alt="screen shot 2018-01-04 at 13 39 45" src="https://user-images.githubusercontent.com/15121999/34564085-ab9526c2-f155-11e7-87cf-4ba9eeb0d621.png">

Browsers used:
- Google Chrome (Version 63.0.3202.84 (Official Build) (64-bit))
- Safari (Version 11.0.2 (13604.3.5))
- Mozilla Firefox (57.0.1 (64-bit))
- Opera (Version 49.0.2725.64)

**Comment by lorthirk** [comment]
YYYY doesn't mean "Four digit year", but rather "Full year", as per JDK 8 documentation ([JavaDoc](https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html) and [Oracle Tutorial](https://docs.oracle.com/javase/tutorial/i18n/format/simpleDateFormat.html)). Although it's a border line case (of course no one would want to input a date with a year > 9999, but that could be true for years > 2100, actually), it's technically conforming to the format. So I'd say it's not an issue.

**Comment by LeoNerdoG** [comment]
Ok, because technically this is conforming to the format I am closing.
