### ISSUE TITLE
Kapua Does Not Report Error If Years in Jobs Entered in Wrong Format

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1249]
When entering **Starts On** and **Ends On** paramteres in Job Schedules, year should be added as four digit number (YYYY) but Kapua accepts all dates from 0 - 199999.

Testflow: 
1. Login as kapua-sys
2. Go to Jobs, create new job (e.g. job1)
3. Add schedule to job1 and as year parameters try to enter anything from 0001 to 199999
**If Expirationdate is in range 0 - 199999, Kapua accepts it, although format is _YYYY_.**

Screenshot No. 1 (Entering Expiration date in wrong format): 
<img width="1372" alt="screen shot 2018-01-04 at 13 37 59" src="https://user-images.githubusercontent.com/15121999/34564222-1c371cdc-f156-11e7-9ca3-9c80f0672a64.png">

Browsers used:
- Google Chrome (Version 63.0.3202.84 (Official Build) (64-bit))
- Safari (Version 11.0.2 (13604.3.5))
- Mozilla Firefox (57.0.1 (64-bit))
- Opera (Version 49.0.2725.64)

**Comment by lorthirk** [comment]
This should be the same as #1248

**Comment by LeoNerdoG** [comment]
Ok, because technically this is conforming to the format I am closing.
