### ISSUE TITLE
docker-compose.yml missing environment variables

### ISSUE THREAD

**Issue by nehmetohme** [eclipse/kapua#1252]
kapua/dev-tools/src/main/docker/docker-compose.yml is missing the environment variables. 

Kapua Console was complaining that DB_PORT_3306_TCP_PORT was missing. After adding the below variables I was able to rectify the issue on the console. But this seems to be also missing from the other containers.

  kapua-console:
    image: kapua/kapua-console:${IMAGE_VERSION}
    ports:
    - 8080:8080
    environment:
    **- DB_PORT_3306_TCP_PORT=3306
    - DB_PORT_3306_TCP_ADDR=10.0.0.21**

Cheers,
Nehmé

**Comment by stefanomorson** [comment]
@nehmetohme I cannot reproduce the issue you are describing. I'm using the current develop branch, can you confirm this is still an issue? If so, it would be useful if you could provide some more details to ease the test on our side such as the release version of Kapua, how the issue shows, the logs you are getting, the steps that you execute before getting the issue, etc.

Thanks

**Comment by leinad87** [comment]
The issue is shown when you log the containers with docker-compose logs -f. It is also needed to add 
'--env commons.db.schema.update=true'
to the kapua-broker, kapua-console and kapua-api docker.
