### ISSUE TITLE
Implement user permission update tests

### ISSUE THREAD

**Issue by stefanomorson** [eclipse/kapua#126]
To be detailed:

More tests need to be implemented
  - (user) invalid permission update tests
  - (user) invalid permission update for root test
  - (user) invalid role create for root test
  - (user) invalid role update for root test
  - (user) Cascade to update the underlying role
  - (user) self manage

Tests above are integration tests
- Add scenarios for tests
- Add implementation (requires integration tests framework)

**Comment by lorthirk** [comment]
@muros-ct can you please check whether these tests have been implemented?

**Comment by Coduz** [comment]
@muros-ct  Ping on this

**Comment by muros-ct** [comment]
Wau, this is old. I will check.

**Comment by muros-ct** [comment]
I discussed this with @andrejn-ct and we didn't find any tests regarding permissions.
@Coduz we should discuss scenarios in a little more detail. What exactly is meant under invalid permission or role.
Tests that come to my mind are:
- User that is not admin can not assign itself permission or role.
- Admin can assign permissions and roles to himself and other users in his account.
- I am not sure about permissions regarding sub accounts.

Who could provide some spec around what is allowed and what not?

**Comment by Coduz** [comment]
Hi @LeoNerdoG ,

has this been solved? 

Regards,

_Alberto_

**Comment by LeoNerdoG** [comment]
Hey @Coduz,
this has no been resolved yet. There are no tests Stefano descbire above regarding this.

**Comment by Coduz** [comment]
Hi @LeoNerdoG ,

Yes this is something that we wanted to be carried on. 
Makes more sense waiting the QA refactoring to me merged before start work on this? 

I'll check with @stefanomorson what is the status on this issue BTW

Regards, 

_Alberto_

**Comment by LeoNerdoG** [comment]
Hej @Coduz,
yes, it would be logical to wait for QA refactoring to be merged, otherwise there would come conflicts for sure and we would lose time with debuging and fixing this. But we can add tests for this also, no problem 😄 

Regards,
Leonardo

**Comment by code-incubus** [comment]
Hey @Coduz, @LeoNerdoG   I've checked this issue and all the above-mentioned scenarios are covered under these two feature files:
- qa/integration/src/test/resources/features/user/UserPermissionI9n.feature 
- qa/integration/src/test/resources/features/user/UserRoleServiceI9n.feature

Therefore I think this issue can be closed.

**Comment by Coduz** [comment]
This issue has been closed a while ago by many PRs.
Moving this to 1.2.0 project and marking as Done
