### ISSUE TITLE
Dialogue Box Closes if User With Non-Unique Name Entered

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1264]
If user enters non-unique name in Users, Kapua does not close the dialogue box, but only shows an error that user has not used a non-unique name. 
But if user enters for example a tag with non-unique name, after clicking **Submit** the dialogue box closes and an error is shown (which is ok).
Problem here is non consistency and for end user is much better, if dialogue box does not close. 

Testflow: 
1. Login as kapua-sys
2. Go to Users, add a job (e.g. user1) 
3. Try to add another user, also with name user1
**At this point Kapua will close the dialogue box and show error, instead just showing the error and keeping the dialogue box open.**

Screenshot No. 1 (No dialogue box when job with non-unique name entered):
<img width="1438" alt="screen shot 2018-01-09 at 11 21 36" src="https://user-images.githubusercontent.com/15121999/34721418-f31acc54-f542-11e7-8162-412e50590353.png">

Screenshot No. 2 (Dialogue box does not close when tag with non-unique name entered): 
<img width="721" alt="screen shot 2018-01-09 at 11 21 45" src="https://user-images.githubusercontent.com/15121999/34720944-081d6abe-f541-11e7-9090-6e233838b999.png">

Browsers used:
- Google Chrome (Version 63.0.3239.132 (Official Build) (64-bit)))
- Safari (Version 11.0.2 (13604.3.5))
- Mozilla Firefox (57.0.4 (64-bit))
- Opera (Version 50.0.2762.45)

**Comment by stefanomorson** [comment]
The dialog should stay open when a validation error occurs.

**Comment by lorthirk** [comment]
@stefanomorson I'm afraid we have to deal with this in a per-dialog basis, since the `hide()` is usually called in the callback of the service call that every dialog performs on its own to retrieve the data it needs.

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been successfully resolved with PR #1350 .
