### ISSUE TITLE
Dialogue Box Closes if User Enters Device With Non-Unique Name

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1265]
If user enters non-unique name in Devices, Kapua does not close the dialogue box, but only shows an error that user has not used a non-unique name. 
But if user enters for example a tag with non-unique name, after clicking **Submit** the dialogue box closes and an error is shown (which is ok).
Problem here is non consistency and for end user is much better, if dialogue box does not close. 

Testflow: 
1. Login as kapua-sys
2. Go to Devices, add a device (e.g. device1) 
3. Try to add another device, also with name device1
**At this point Kapua will close the dialogue box and show error, instead just showing the error and keeping the dialogue box open.**

Screenshot No. 1 (No dialogue box when device with non-unique name entered):
<img width="1434" alt="screen shot 2018-01-09 at 11 21 15" src="https://user-images.githubusercontent.com/15121999/34720940-04f69e32-f541-11e7-8a5b-242cae4000df.png">

Screenshot No. 2 (Dialogue box does not close when tag with non-unique name entered): 
<img width="721" alt="screen shot 2018-01-09 at 11 21 45" src="https://user-images.githubusercontent.com/15121999/34720944-081d6abe-f541-11e7-9090-6e233838b999.png">

Browsers used:
- Google Chrome (Version 63.0.3239.132 (Official Build) (64-bit)))
- Safari (Version 11.0.2 (13604.3.5))
- Mozilla Firefox (57.0.4 (64-bit))
- Opera (Version 50.0.2762.45)

**Comment by stefanomorson** [comment]
@LeoNerdoG : maybe there's an inconsistency in the description, did you mean that the device dialog closes while the tag dialog keeps open ?
In any case the issue looks similar to #1264

**Comment by LeoNerdoG** [comment]
Hi @stefanomorson ,
yes, exactly. The tag dialogue box is kept open, if user enters non-unique name and error pops-out. This way user does not have to click "add" again and enter all the info, but only changes the tag name and that's it. 
But the Device dialogue box closes, which is very inconvenient (as it has a lot more fields to fill).

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been successfully resolved with PR #1350 .
