### ISSUE TITLE
Dialogue Box Closes if User Enters Job With Non-Unique Name

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1266]
If user enters non-unique name in Jobs, Kapua does not close the dialogue box, but only shows an error that user has not used a non-unique name. 
But if user enters for example a tag with non-unique name, after clicking **Submit** the dialogue box closes and an error is shown (which is ok).
Problem here is non consistency and for end user is much better, if dialogue box does not close. 

Testflow: 
1. Login as kapua-sys
2. Go to Jobs, add a job (e.g. job1) 
3. Try to add another job, also with name job1
**At this point Kapua will close the dialogue box and show error, instead just showing the error and keeping the dialogue box open.**

Screenshot No. 1 (No dialogue box when job with non-unique name entered):
<img width="1435" alt="screen shot 2018-01-09 at 11 21 27" src="https://user-images.githubusercontent.com/15121999/34721132-dc63de84-f541-11e7-8a9a-fc418cf4559c.png">

Screenshot No. 2 (Dialogue box does not close when tag with non-unique name entered): 
<img width="721" alt="screen shot 2018-01-09 at 11 21 45" src="https://user-images.githubusercontent.com/15121999/34720944-081d6abe-f541-11e7-9090-6e233838b999.png">

Browsers used:
- Google Chrome (Version 63.0.3239.132 (Official Build) (64-bit)))
- Safari (Version 11.0.2 (13604.3.5))
- Mozilla Firefox (57.0.4 (64-bit))
- Opera (Version 50.0.2762.45)

**Comment by stefanomorson** [comment]
#### Expected results:
Same as #1264

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been successfully resolved with PR #1350 .
