### ISSUE TITLE
Kapua Reports Unsaved Changes Although Refresh Button Is Pressed

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1277]
When user clicks on bottom **refresh** button several times (repeatedly), Kapua will show notification regarding **unsaved changes**, although there are not any, as user has just pressed **refresh** button several times. 

Testflow: 
1. Login as kapua-sys
2. Go to Chidl Accounts, create new child account (e.g. kapua-child1)
3. Press bottom **refresh** button repeatedly (look at the screenshot)
**After several presses, Kapua will show _unsaved changes_ error (look at the screenshot).**

Screenshot:
![screen shot 2018-01-11 at 08 04 34](https://user-images.githubusercontent.com/15121999/34813170-2b44c92e-f6a9-11e7-9d88-2f9a7bddb3b7.png)

Browsers used:
- Google Chrome (Version 63.0.3239.132 (Official Build) (64-bit)))
- Safari (Version 11.0.2 (13604.3.5))
- Mozilla Firefox (57.0.4 (64-bit))
- Opera (Version 50.0.2762.45)

**Comment by stefanomorson** [comment]
This issue could be related to #1210

**Comment by LeoNerdoG** [comment]
I have verified that this issue is resolved via #1098 .
