### ISSUE TITLE
Rephrasing Error When Inappropriate Parameters Entered Into Child Account Settings

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1281]
If user enters unexpected parameter in one of the settings (e.g. maxNumberChildJobs) so that it is in error _state_ and then _**Save**_ button is pressed, an error with message _**There are invalid channel values**_ pops up. 
Although the problematic box is outlined with bright red with added exclamation mark, so it is hard for user to ignore it, I think the message in error box should be handled more gracefully. 

This happens in all the field, described bellow: 
 - maxNumberChildAccounts
 - lockoutPolicy.maxFailures
 - lockoutPolicy.resetAfter
 - lockoutPolicy.lockDuration
 - maxNumberChildGroups
 - maxNumberChildRoles
 - dataTTL
 - rxByteLimit
 - maxNumberChildDevices
 - maxNumberChildTags
 - maxNumberChildUsers
 - maxNumberChildJobs

From end-user point of view there are two possible solutions: 
1. Disable _**Save**_ button if there are fields with errors or
2. Change the error text to something more appropriate. 

Testflow: 
1. Login as kapua-sys
2. Go to Child Accounts, create a child account (e.g. kapua-child1)
3. Select the newly created child account and go to its Settings
4. Change a setting (e.g. maxNumberChildJobs) to **-123**, which is wrong setting
5. Try to **Save** this settings
**At this point Kapua will return an error, stating _There are invalid channel values_ instead of something more appropriate (e.g. Value in maxNumberChildJobs not permited).**

Screenshot: 
<img width="1440" alt="screen shot 2018-01-11 at 10 20 52" src="https://user-images.githubusercontent.com/15121999/34817945-a1fe71ae-f6b9-11e7-9264-2b9451510e1d.png">

Browsers used:
- Google Chrome (Version 63.0.3239.132 (Official Build) (64-bit)))
- Safari (Version 11.0.2 (13604.3.5))
- Mozilla Firefox (57.0.4 (64-bit))
- Opera (Version 50.0.2762.45)

**Comment by lorthirk** [comment]
I'd say that we should only fix the error message in the box... the rest of the UX looks good to me.

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
