### ISSUE TITLE
Text For Displaying Results in Devices Not Shown Correctly

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1284]
If user narrows browser window so text for **Displaying results** cannot fit into window (look at the screenshot), Kapua still displays the text, but it is not shown correctly. 

Testflow: 
1. Login as kapua-sys
2. Narrow browser window to ~ 1/3 of screen width. 
3. Go to Devices and observe the **Displaying 1 - 1 of 1 results** text.
**If window is narrowed before users goes to _Devices_, the text is not displayed properly.**

Screenshot: 
![cuttextdevices](https://user-images.githubusercontent.com/15121999/34942643-a9342d32-f9f8-11e7-961f-98fecc9c0385.png)

Browsers used:
- Google Chrome (Version 63.0.3239.132 (Official Build) (64-bit)))
- Safari (Version 11.0.2 (13604.3.5))
- Mozilla Firefox (57.0.4 (64-bit))
- Opera (Version 50.0.2762.45)

**Comment by stefanomorson** [comment]
@LeoNerdoG : I'm not sure this is a bug it's related to how GWT handles the object in the layout. I would close this issue.

**Comment by stefanomorson** [comment]
The issue regarding the `»` is already covered by #1293 and others. Based on this I proceed to close this issue and all the others similar referring to this.

**Comment by LeoNerdoG** [comment]
Although this issue has not been fixed, we closed it due to not being a bug. Now that PR #1560 has been merged, which defines minimal window size, this issue is fixed.
