### ISSUE TITLE
Text For Displaying Results in Access Groups Not Shown Correctly

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1287]
If user narrows browser window so text for **Displaying results** cannot fit into window (look at the screenshot), Kapua still displays the text, but it is not shown correctly. 

Testflow: 
1. Login as kapua-sys
2. Go to Access Groups, add a group (e.g. group1), then go to **Welcome** tab
3. Narrow browser window to ~ 1/3 of screen width. 
4. Go to Access Groups again and observe the **Displaying 1 - 1 of 1 results** text.
**If window is narrowed before users goes to _Access Groups,_ the text is not displayed properly.**

Screenshot: 
![cuttextaccessgroups](https://user-images.githubusercontent.com/15121999/34943211-04af5504-f9fb-11e7-8ce3-a556a1bfaf91.png)

Browsers used:
- Google Chrome (Version 63.0.3239.132 (Official Build) (64-bit)))
- Safari (Version 11.0.2 (13604.3.5))
- Mozilla Firefox (57.0.4 (64-bit))
- Opera (Version 50.0.2762.45)

**Comment by stefanomorson** [comment]
#### Expected results:
Same as #1284

**Comment by LeoNerdoG** [comment]
Although this issue has not been fixed, we closed it due to not being a bug. Now that PR #1560 has been merged, which defines minimal window size, this issue is fixed.
