### ISSUE TITLE
Text For Displaying Results in Roles Not Shown Correctly

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1290]
If user narrows browser window so text for **Displaying results** cannot fit into window (look at the screenshot), Kapua still displays the text, but it is not shown correctly. 

Testflow: 
1. Login as kapua-sys
2. Narrow browser window to ~ 1/3 of screen width. 
3. Go to Roles and observe the **Displaying 1 - 1 of 1 results** text.
**If window is narrowed before users goes to Roles, the text is not displayed properly.**

Screenshot: 
![cuttextroles1](https://user-images.githubusercontent.com/15121999/34943052-3a9bbfa0-f9fa-11e7-94cb-0ae4e35b7ad4.png)

Browsers used:
- Google Chrome (Version 63.0.3239.132 (Official Build) (64-bit)))
- Safari (Version 11.0.2 (13604.3.5))
- Mozilla Firefox (57.0.4 (64-bit))
- Opera (Version 50.0.2762.45)

**Comment by stefanomorson** [comment]
#### Expected results:
Same as #1284

**Comment by LeoNerdoG** [comment]
Although this issue has not been fixed, we closed it due to not being a bug. Now that PR #1560 has been merged, which defines minimal window size, this issue is fixed.
