### ISSUE TITLE
Tab For Results in Devices Not Shown Correctly When Browser Window Narrowed

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1293]
When user narrows browser window, so that line with buttons for _**displaying results**_ cannot be fitted into one line, additional button appears with all the options, but there are no names beside each option (look at the screenshots). 
If user only narrows the window so text **Displaying 1 - 1 of 1** dissapears, the additional button has only one options, which is _**NONE**_, but it should be somethin like _**page 1 of 1**_ (screenshot No. 1).  

Testflow: 
1. Login as kapua-sys
2. Narrow browser window and go to Devices
3. Click on the button (orange circle in screenshots) and expand its options
**When user clicks on additional button, that appeared, all the buttons appear, but without a name.**

Screenshot No. 1 (Additional button - orange circle and _**NONE**_ options when only text _**Displaying 1 -1 of 1 results**_ cannot fit into line): 
![devices2](https://user-images.githubusercontent.com/15121999/34944495-2010762a-fa00-11e7-9e8f-c6469f5ec19b.png)

Screenshot No 2 (Additional button - orange circle and all additional options without name):
![devices](https://user-images.githubusercontent.com/15121999/34944598-91ebc916-fa00-11e7-8481-4c155fbfc104.png)

Browsers used:
- Google Chrome (Version 63.0.3239.132 (Official Build) (64-bit)))
- Safari (Version 11.0.2 (13604.3.5))
- Mozilla Firefox (57.0.4 (64-bit))
- Opera (Version 50.0.2762.45)

**Comment by stefanomorson** [comment]
#### Expected result:
When the resize makes the `»` appear (which is correct), if the user clicks on it I expect that the box contains the button and the hidden message (`Displaying 1 - 1 of 1 results`).

**Comment by stefanomorson** [comment]
@LeoNerdoG @muros-ct : in the comment above I was proposing to close these issues. Let me know your opinion.

**Comment by muros-ct** [comment]
1293 (et al.)  We discussed with Leo and decided that it is ok to close them with "won’t fix" and reason of GWT lack of functionality.
But, our new collegue Aleksandra could try to solve it.

**Comment by lorthirk** [comment]
@muros-ct I'd say to keep this as a low priority. We could try to fix it, but as you and @stefanomorson said it's probably ok to close it because of lacking GWT functionality if it takes too much time.

**Comment by LeoNerdoG** [comment]
@lorthirk @muros-ct @stefanomorson I am closing this because of low priority.
