### ISSUE TITLE
Tab For Results in Users Not Shown Correctly When Browser Window Narrowed

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1298]
When user narrows browser window, so that line with buttons for _**displaying results**_ cannot be fitted into one line, additional button appears with all the options, but there are no names beside each option (look at the screenshots). 
If user only narrows the window so text **Displaying 1 - 1 of 1** dissapears, the additional button has only one options, which is _**NONE**_, but it should be somethin like _**page 1 of 1**_ (screenshot No. 1).  

Testflow: 
1. Login as kapua-sys
2. Narrow browser window and go to Users
3. Click on the button (orange circle in screenshots) and expand its options
**When user clicks on additional button, that appeared, all the buttons appear, but without a name.**

Screenshot No. 1 (Additional button - orange circle and _**NONE**_ options when only text _**Displaying 1 -1 of 1 results**_ cannot fit into line): 
![users2](https://user-images.githubusercontent.com/15121999/34947176-a5f9898a-fa09-11e7-8f4d-d47e5a900eca.png)

Screenshot No 2 (Additional button - orange circle and all additional options without name):
![users](https://user-images.githubusercontent.com/15121999/34947180-a77e18ac-fa09-11e7-9af8-0afd4c6816db.png)

Browsers used:
- Google Chrome (Version 63.0.3239.132 (Official Build) (64-bit)))
- Safari (Version 11.0.2 (13604.3.5))
- Mozilla Firefox (57.0.4 (64-bit))
- Opera (Version 50.0.2762.45)

**Comment by stefanomorson** [comment]
#### Expected results:
Same as #1293

**Comment by LeoNerdoG** [comment]
I am closing this because of low priority (look at #1293 ).
