### ISSUE TITLE
Consider using another OSM tile source than Mapquest

### ISSUE THREAD

**Issue by kartben** [eclipse/kapua#13]
I don't think Mapquest supports free access to their tiles anymore, so the Kapua UI shows something like

![mapquest error](http://oi64.tinypic.com/w8ugsp.jpg)

Should another tile source be considered? 
I've had good success with: `http://c.tile.openstreetmap.org/${z}/${x}/${y}.png` but the terms of (fair) use would need to be double checked.
See also: http://wiki.openstreetmap.org/wiki/Tile_servers

**Comment by stefanomorson** [comment]
Hi Benjamin,


thanks for reporting.

We'll move immediately to openstreetsmap to fix the problem raised by the change. Actually the change was known and we already decided to move away from map quest. Looks that we missed to update that part.


Stefano

________________________________

**Comment by Coduz** [comment]
Hi @kartben  ,

as far as I know, on this issue we are waiting news from you about using Open Street Maps in console.
There is any update on this?

Regards,

Alberto

**Comment by Coduz** [comment]
Hi all,

as per discussion during the Kapua internal SCRUM, all issues related to the old console will be marked with "wontfix" label and closed.
We are already working on the new console implementation.

Regards,

Alberto
