### ISSUE TITLE
Error When Refreshing List of Devices Where Live Device Present

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1301]
When user has connected a live device to Kapua and then selects this device, Kapua starts returning Error as shown bellow: _**The entity is out of state as it has been modified or deleted by another transaction**_ if user contantly refreshes page. 

Testflow: 
1. Login as kapua-sys
2. Go to Devices, connect a live device to Kapua
3. Select live Kura device and navigate to _**Refresh button**_ in the page toolbar
4. With _**Enter**_ keyboard key start refreshing the device list. 
**At this point Kapua will start to return error as described above and shown bellow on the screenshot.**

Screenshot: 
<img width="1303" alt="screen shot 2018-01-16 at 09 55 48" src="https://user-images.githubusercontent.com/15121999/34980151-dedaa4e2-faa3-11e7-9a2d-ac6deb4badbf.png">

Browsers used:
- Google Chrome (Version 63.0.3239.132 (Official Build) (64-bit)))
- Safari (Version 11.0.2 (13604.3.5))
- Mozilla Firefox (57.0.4 (64-bit))
- Opera (Version 50.0.2762.45)

**Comment by stefanomorson** [comment]
@LeoNerdoG we were not able to reproduce this by following the instruction.  We connected a kura device and applied the steps and no errors pop up. Can you confirm this is still an issue and/or provide more details to reproduce it ?

**Comment by LeoNerdoG** [comment]
@stefanomorson Try to click on _**Configuration**_ and/or _**Asset**_ tab before continuously pressing _**enter**_ button. This way the error described above pops-up.

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
