### ISSUE TITLE
User Denied Login When Login Button Pressed Too Fast

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1302]
If user enters proper username and password and clicks _**Login**_ button several times very fast, Kapua reports _**Invalid username or password**_ and _**java.lang.IllegalStateException...**_ (look at the screenshot No. 1) or user logs in but Kapua reports _**Login Failed. An internal error occured:org.apache.shiro.ShiroException....**_ (look at screenshot No. 2). 

Testflow: 
1. When prompted for login credentials, set: 
 - username: kapua-sys
 - password: kapua-password
2. After that click _**Login**_ button several times. 
**At this point Kapua wil either log you in and report that login has failed or notlog you in becuase of error described above.**

Screenshot No. 1 (Error when Kapua does not login the user): 
<img width="1319" alt="screen shot 2018-01-17 at 10 12 14" src="https://user-images.githubusercontent.com/15121999/35041242-5e3fdc3a-fb84-11e7-9466-77315744461b.png">

Screenshot No. 2 (User logs in but Kapua returns an error): 
<img width="1320" alt="screen shot 2018-01-17 at 10 11 16" src="https://user-images.githubusercontent.com/15121999/35041243-5f670e6c-fb84-11e7-9190-416088567331.png">

Browsers used:
- Google Chrome (Version 63.0.3239.132 (Official Build) (64-bit)))
- Safari (Version 11.0.2 (13604.3.5))
- Mozilla Firefox (57.0.4 (64-bit))
- Opera (Version 50.0.2762.45)

**Comment by lorthirk** [comment]
Hi @LeoNerdoG,

I'm not able to replicate the issue. Do you have any hint on how to click the button fast enough?

**Comment by LeoNerdoG** [comment]
@lorthirk today I was not able to reproduce this issue as _**Login**_ button freezes after first click (which is OK) so I am closing this issue.
