### ISSUE TITLE
Kapua Implicitly Exposes Which Users Exist in Database And Which Do Not

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1303]
If user tries to sign in with proper credentials (e.g. kapua-sys, kapua-password) but misspels password, it takes approximatelly 0.5 seconds for Kapua to return an error _**Login failed. Invalid username or password.**_
But if user enters username, that does not exist in the database, Kapua returns _**Login failed**_ error instantly. 
This gives potential attacker insight in database - which username exist and which one don't. 

Testflow: 
1. Measure the time needed for Kapua to return _**Login failed**_ error when password for kapua-sys misstyped. 
2. Measure the time needed for Kapua to return _**Login failed**_ error when username entered does not exist (it is basically instantly). 

Browsers used:
- Google Chrome (Version 63.0.3239.132 (Official Build) (64-bit)))
- Safari (Version 11.0.2 (13604.3.5))
- Mozilla Firefox (57.0.4 (64-bit))
- Opera (Version 50.0.2762.45)

**Comment by lorthirk** [comment]
A random delay of about two or three seconds should be enough. Or we could just measure the difference between the two operations and add such delay (with a bit of random) so that their duration is more and less equal.

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved with random delays on various scenarios.
