### ISSUE TITLE
Text in Logout Info Box Cut Off

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1304]
When user logs out, Kapua for a moment shows info window in bottom right corner stating _**Logged out!**_, but the text in the box is cut off (look at the screenshot). 

Testflow: 
1. Login as kapua-sys
2. Logout
**When logging out look at bottom right corner, where this info box appears.**

Screenshot: 
![logoutscreenerror](https://user-images.githubusercontent.com/15121999/35043724-eeff81e0-fb8d-11e7-8100-37dfff80cfc6.png)

Browsers used:
- Google Chrome (Version 63.0.3239.132 (Official Build) (64-bit)))
- Safari (Version 11.0.2 (13604.3.5))
- Mozilla Firefox (57.0.4 (64-bit))
- Opera (Version 50.0.2762.45)

**Comment by stefanomorson** [comment]
#### Expected results:
The formula should be adjusted to add a bit of more space in the bottom. In this way the characters can be visualized completely. The height of the box is calculated in class ConsoleInfo.

**Comment by LeoNerdoG** [comment]
@lorthirk @stefanomorson I have verified that this issue is resolved.
