### ISSUE TITLE
"Upload and Apply" Info Box Has "x" Icon

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1307]
Upload and apply info box is the only one with _**cancel**_ and _**X**_ sign for cancelins/closing info box without saving changes, every other info window has only _**cancel**_ button. 

Testflow: 
1. Login as kapua-sys
2. Connect live Kura device to Kapua
3. Go to Devices, select the live device and navigate to Configuration -> Snapshots 
4. Click _**Upload and Apply**_
**In upper right corner there is _X_ sign that other windows do not have.**

![screen shot 2018-01-18 at 10 35 21](https://user-images.githubusercontent.com/15121999/35091071-e7d64c60-fc3b-11e7-87ab-d246133ecd13.png)

Browsers used:
- Google Chrome (Version 63.0.3239.132 (Official Build) (64-bit)))
- Safari (Version 11.0.2 (13604.3.5))
- Mozilla Firefox (57.0.4 (64-bit))
- Opera (Version 50.0.2762.45)

**Comment by stefanomorson** [comment]
#### Expected results:
The `Close` icon should be hidden

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been successfully fixed.
