### ISSUE TITLE
"Upload and Apply" Info Box Can Be Upsized and Resized

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1308]
Upload and apply info box is the only one that can be upsized and rezised (look at the screenshot). 

Testflow: 
1. Login as kapua-sys
2. Connect live Kura device to Kapua
3. Go to Devices, select the live device and navigate to Configuration -> Snapshots
4. Click _**Upload and Apply**_
**It is possible to change windows size, which is not possible with any other window.**

<img width="1434" alt="uploadandapplywindowsedapovecat" src="https://user-images.githubusercontent.com/15121999/35091163-1923551a-fc3c-11e7-8a7c-4deec88ef4a4.png">

Browsers used:
- Google Chrome (Version 63.0.3239.132 (Official Build) (64-bit)))
- Safari (Version 11.0.2 (13604.3.5))
- Mozilla Firefox (57.0.4 (64-bit))
- Opera (Version 50.0.2762.45)

**Comment by stefanomorson** [comment]
#### Expected results:
The windows shouldn't be resizable

**Comment by LeoNerdoG** [comment]
I have verified that this issue is resolved.
