### ISSUE TITLE
Wrong Text in Info Box When Adding Role To User

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1309]
When role is added to user, Kapua reports _**Role created successfully**_ although role has only been added and not created (look at the screenshot bellow). 

Testflow: 
1. Login as kapua-sys
2. Go to Roles, create a roel (e.g. role1)
3. Go to Users, create a user (e.g. kapua-user1) 
4. Add role1 to kapua-user1
**When role is added to user, the tet in info box is wrong.**

![napaceninforoledevices](https://user-images.githubusercontent.com/15121999/35091431-f4374eb8-fc3c-11e7-9002-1f9f5bc09342.png)

Browsers used:
- Google Chrome (Version 63.0.3239.132 (Official Build) (64-bit)))
- Safari (Version 11.0.2 (13604.3.5))
- Mozilla Firefox (57.0.4 (64-bit))
- Opera (Version 50.0.2762.45)

**Comment by stefanomorson** [comment]
#### Expected results
Tje correct message should be: `Role granted successfully`

**Comment by muros-ct** [comment]
PR #1324 solves this issue too.

**Comment by LeoNerdoG** [comment]
I have verified that this issue is resolved.
