### ISSUE TITLE
"Invisible" Browse Button in "Upload and Apply" Info Box

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1311]
There is an _**inivisible link**_ to the _**Browse**_ button on the left side, between the _**File:**_ and input field (look at the screenshot). If user clicks here, the result is same as if he clicked on _**Browse**_ button. 

Testflow: 
1. Login as kapua-sys
2. Connect live Kura device to Kapua
3. Go to Devices, select the live device and navigate to Configuration -> Snapshots
4. Click _**Upload and Apply**_
5. With mouse hoover between _**File:**_ and input field and press left mouse button.
**Although user has not clicked on _Browse_ button, Kapua opens window for selecting the input file.**

![screen shot 2018-01-18 at 14 11 49](https://user-images.githubusercontent.com/15121999/35100476-3966c378-fc5c-11e7-909c-a4ba0f5c2f6c.png)

Browsers used:
- Google Chrome (Version 63.0.3239.132 (Official Build) (64-bit)))
- Safari (Version 11.0.2 (13604.3.5))
- Mozilla Firefox (57.0.4 (64-bit))
- Opera (Version 50.0.2762.45)

**Comment by stefanomorson** [comment]
#### Expected results:
Likely the actual `Browse` button extends its active area on the left. In any case the browse functionality should be activated only by clicking over the visible button area.

**Comment by LeoNerdoG** [comment]
I have verified that this issue is resolved.
