### ISSUE TITLE
data view by topic - poor performance issue

### ISSUE THREAD

**Issue by riccardomodanese** [eclipse/kapua#1312]
The data view by topic is affected by a poor performance issue.
Since for each extracted record a new query should be done to get the last activity time for that topic, this lead to a huge amount of time needed to renderer just few thousands of records.

Moreover the extracted semantic topics are not grouped by the client ids leading to a redundand work to query and renderer the data.

**Comment by stefanomorson** [comment]
This is a Kapua issue. We captured a similar issue in https://github.com/eclipse/kapua/issues/1312.
I guess we should add a new one for the device view.

**Comment by Coduz** [comment]
Hi @riccardomodanese and @lorthirk ,

This can be closed, right?

_Alberto_

**Comment by lorthirk** [comment]
Yes, as far as I am concerned the implementations in #1605 close this issue.
