### ISSUE TITLE
Emtpy Errors From Kapua When Trying To Communicate With Offline Device Which Appears Online

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1316]
Because Device tab is not automatically refreshed, a problem emerges when user disconnects a live device from Kapua and wants to continue working with it. 
If user is working with device in Kapua, then goes to Kura device and disconnects it, comes back to Kapua and tries to continue working on device, Kapua will start returning empty error messages, that can be very confusing to end user (look at the screenshots), especially if (for example) user disconnected wrong device. 

Testflow: 
1. Login as kapua-sys
2. Connect a live device to Kapua (e.g. device1) 
3. Go to Devices, check if this device is available and navigate through its subtabs (Configuration, Packages, Bundles, Assets...)
4. Go to Kura device and disconnect it from kapua. 
5. Go back to Kapua (without refreshing the page) and again try to navigate through device's subtabs.
**At this point Kapua will start returning empty errors.**

Question: is it possible to put some info in this error messages, for example: _The selected device is offline_ or something similar?

Screenshot: 
![screen shot 2018-01-19 at 09 26 03](https://user-images.githubusercontent.com/15121999/35149962-942808e6-fd18-11e7-8a56-6e6ee5f124db.png)

Browsers used:
- Google Chrome (Version 63.0.3239.132 (Official Build) (64-bit)))
- Safari (Version 11.0.2 (13604.3.5))
- Mozilla Firefox (57.0.4 (64-bit))
- Opera (Version 50.0.2762.45)

**Comment by lorthirk** [comment]
We should intercept the correct exception and show an appropriate error message.

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
