### ISSUE TITLE
console - hide refresh button in pagination toolbar

### ISSUE THREAD

**Issue by stefanomorson** [eclipse/kapua#1317]
#### Description
The refresh button in the pagination toolbar (see image below) is redundant since all the views that require the refresh functionality already have a button created for this purpose.

![screen shot 2018-01-22 at 13 46 50](https://user-images.githubusercontent.com/11518067/35221610-157051ce-ff7b-11e7-91da-d691dcf8982d.png)

The refresh button in the image above should be hidden everywhere.

**Comment by stefanomorson** [comment]
By solving this issue the following can be closed since they will be no more valid:

* #1181 
* <other>

**Comment by lorthirk** [comment]
Should be fixed in e9fab73cc

**Comment by LeoNerdoG** [comment]
Hi @stefanomorson @lorthirk I know this is not my issue, but I tested it anyway and found out that _**Refresh**_ button is successfully hidden, until user resizes window (look at the screenshot) - the button then appears in the list and is fully functional. This happens for every service form Devices to Child Accounts.
Can you please test this on your side and confirm? 

![screen shot 2018-01-25 at 11 12 03](https://user-images.githubusercontent.com/15121999/35382866-e12b4138-01c0-11e8-9b56-94e8b834ccdb.png)

**Comment by lorthirk** [comment]
On the opposite, @LeoNerdoG: no apologies at all, but thanks for catching this!

It should be fixed in 8915270c1 now.

**Comment by LeoNerdoG** [comment]
@lorthirk @stefanomorson  I have verified that this issue is resolved so it can be closed.
