### ISSUE TITLE
Kapua GUI Moves Upwards if User Hits Bottom With Pop-up Windows

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1318]
Best way to describe this issue is through an example. Lets say user goes to Roles and tries to add (create) a new role (e.g. role1). If user holds the window frame for adding new role and drags it to the bottom (and tries to move it "out" of the browser window), so it hits window floor, the whole GUI jump up a little bit. 
If this process is repeated several times, GUI can literally dissapear from browser window (screenshot No. 4).
Nevertheless, when user clicks _**Submit**_ or _**Cancel**_, everything is back to normal. 

Testflow: 
1. Login as kapua-sys
2. Go to on of the services (Roles, Tags, Child Accounts...) and try to add new item
3. When window for adding new item appears, hit it to the bottom and observe how GUI moves up.

Screenshot No. 1 (When window hits bottom 2-3 times):
![screen shot 2018-01-22 at 12 50 54](https://user-images.githubusercontent.com/15121999/35274273-c750eeba-003b-11e8-9a6e-dcc764e91681.png)

Screenshot No. 2 (When window hits botom several times):
![screen shot 2018-01-22 at 12 52 24](https://user-images.githubusercontent.com/15121999/35274274-c7685ad2-003b-11e8-8380-9c3008921038.png)

Screenshot No. 3 (When user clicks Submit or Cancel, everything is back to normal - when the info box disappears):
![screen shot 2018-01-22 at 12 52 30](https://user-images.githubusercontent.com/15121999/35274276-c77e779a-003b-11e8-951f-d1e6fe24e124.png)

Screenshot No. 4 (GUI can go all the way up, so the background is fully white): 
![screen shot 2018-01-23 at 14 38 07](https://user-images.githubusercontent.com/15121999/35278901-ba9f410c-004b-11e8-8799-da81342def36.png)

Browsers used:
- Google Chrome (Version 63.0.3239.132 (Official Build) (64-bit)))
- Safari (Version 11.0.2 (13604.3.5))
- Mozilla Firefox (57.0.4 (64-bit))
- Opera (Version 50.0.2762.45)

**Comment by stefanomorson** [comment]
@LeoNerdoG This is the default behavior from GWT. Since the issue can be easily worked around, as you noticed, by the user, I would close this issue.

**Comment by LeoNerdoG** [comment]
Hi @stefanomorson ,
ok, no problem. Closing.
