### ISSUE TITLE
Error Messages Not in Same Style (Devices, Connections, Jobs, Groups, Tags)

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1319]
When user is createing devices, tags, jobs, etc. Kapua returns some kind of info message (if creation was successfull). Problem is, that these error messages are not in same style and therefore does not look uniform. 
Bellow is just one example, how these messages can be rewritted so Kapua would give more unified looks. 

Testflow: 
1. Login as kapua-sys
2. Go to Devices/Connections/Jobs/Groups/Tags
3. Create, edit and delete the appropriate items and observe error messages that pop-up at creation. 

| Error message now        | How it should be           |
| ------------------------|-----------------------|
| **_DEVICES_**    |                                                                         |
| Device successfully created! | Device successfully created!   |
| Device update succeeded!     | Device successfully updated! |
| Device deleted successfully!  |  Device sucessfully deleted!   |
| Tag added                                |  Tag successfully added!        |
| Tag removed                            | Tag successfully removed!     |
| **_CONNECTIONS_**                                                                    | 
| Conenction edited successfully.      |    Connection successfully updated!  |
| **_JOBS_**     | 
|Job successfully created | Job sucessfully created!|
|Job edited successfully. | Job successfully updated!|
|Job deleted successfully. |Job successfully deleted!|
|Job successfully started | Job successfully started!|
|Targets Successfully added | Targets successfully added!|
|Targets successfully deleted | Targets successfully deleted!|
|Step successfully created | Step successfully created!|
|Job edited successfully. | Step successfully updated!|
|Step successfully deleted | Step successfully deleted!|
|Schedule successfully created |Schedule successfully created!|
|Schedule successfully deleted | Schedule successfully deleted!|
| _**GROUPS**_|
|Access Group created successfully |Acess Group successfully created!|
|Access Group edited successfully. |Access Group successfully updated!|
|Access Group deleted successfully. |Access Group successfully deleted!|
| _**TAGS**_ |
|Tag created successfully | Tag successfully created!|
|Tag edited successfully. | Tag successfully updated!|
|Tag deleted successfully. | Tag successfully deleted! |

Browsers used:
- Google Chrome (Version 63.0.3239.132 (Official Build) (64-bit)))
- Safari (Version 11.0.2 (13604.3.5))
- Mozilla Firefox (57.0.4 (64-bit))
- Opera (Version 50.0.2762.45)

**Comment by stefanomorson** [comment]
#### Expected result:
Agree with the proposal except that messages must be closed with a full stop instead of the exclamation mark.

**Comment by LeoNerdoG** [comment]
I have verified that this issue is resolved by PR #1343 .
