### ISSUE TITLE
Error Messages Not in Same Style (Users, Roles, Child Accounts,Settings)

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1320]
When user is createing users, roles, child accounts, etc. Kapua returns some kind of info message (if creation was successfull). Problem is, that these error messages are not in same style and therefore does not look uniform. 
Bellow is just one example, how these messages can be rewritten so Kapua would give more unified looks. 

Testflow: 
1. Login as kapua-sys
2. Go to Users/Roles/Child Accounts/Settings
3. Create, edit and delete the appropriate items and observe error messages that pop-up at creation. 

| Error message now        | How it should be           |
| ------------------------|-----------------------|
| **USERS**    | 
|User created successfully| User successfully created!|
User edited successfully. | User successfully updated!|
|User deleted successfully. | User successfully deleted!
|Role created successfully | Role association successfully added!
|Role association deleted successfully.| Role association successfully deleted!  
|Permission granted successfully | Permission association successfully granted!
|Permission associoation revoked successfully | Permission association successfully revoked!|
|Credential created successfully | API key successfully created!| 
|Credential edited successfully. | API key successfully updated!| 
|Credential deleted successfully. | API key successfully deleted!| 
|Credential created successfully | Password succesfully created!|
|Credential edited successfully. | Password successfully updated!|
|Credential deleted successfully. | Password successfully deleted!|
| **ROLES**    | 
|Role created successfully |Role successfully created!|
|Role edited successfully. | Role sucessfully updated!|
|Role deleted successfully. | Role successfully deleted!|
| **CHILD ACCOUNTS**    |
The account [account-name] has been created. | Account <account-name> successfully created!|
The account [account-] has been updated. | Account <account-name> successfully updated!|
The account <account-name> has been deleted. | Account <account-name> successfully deleted|
User created successfully | User successfully created! |
User edited successfully. | User successfully updated! |
User deleted successfully. |  User successfully deleted! |
| **SETTINGS**    |   
|The account <account-name> has been updated. | Account <account-name> successfully updated! |

Browsers used:
- Google Chrome (Version 63.0.3239.132 (Official Build) (64-bit)))
- Safari (Version 11.0.2 (13604.3.5))
- Mozilla Firefox (57.0.4 (64-bit))
- Opera (Version 50.0.2762.45)

**Comment by stefanomorson** [comment]
#### Expected result:
Agree with the proposal except that messages must be closed with a full stop instead of the exclamation mark.

**Comment by LeoNerdoG** [comment]
I have verified that this issue is resolved.
