### ISSUE TITLE
Border/Frame Issues in Devices

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1323]
Tag, Events and Packages tabs in Devices have problems with borders. Tags have double border on top, Packages do not have borders in toolbar section and Events tab is missing border all around (look at the screenshots).

Testflow: 
1. Login as kapua-sys
2. Go to Devices -> Tags/Events/Packages
**Look for border issues at Tags, Events and Packages.**

Screenshot No. 1 (Double border on top):
![screen shot 2018-01-25 at 14 51 50](https://user-images.githubusercontent.com/15121999/35392369-efce4700-01e1-11e8-98cb-750f10ebffab.png)

Screenshot No. 2 (Missing border all aroun the Events tab):
![screen shot 2018-01-25 at 14 53 24](https://user-images.githubusercontent.com/15121999/35393025-1594ddb2-01e4-11e8-9757-476a5f46a451.png)

Screenshot No. 3 (MIssing borders in toolbar section):
![screen shot 2018-01-25 at 14 53 31](https://user-images.githubusercontent.com/15121999/35393035-196fcc08-01e4-11e8-9d60-877438067e94.png)

Browsers used:
- Google Chrome (Version 63.0.3239.132 (Official Build) (64-bit)))
- Safari (Version 11.0.2 (13604.3.5))
- Mozilla Firefox (57.0.4 (64-bit))
- Opera (Version 50.0.2762.45)

**Comment by lorthirk** [comment]
I noticed other similar issues in other views as well (at least in Jobs, IIRC). Could you please have a quick trip around the views and report here if some other views needs to be updated?

**Comment by LeoNerdoG** [comment]
@lorthirk 
I have examined all the windows in Kapua and this are the results (screenshots are bellow):
1. Device -> Configuration has bottom border that shouldn't be there (look at Packages for reference)
2. Device -> Assets have bottom border that shouldn't be there (look at Packages for reference)
3. Device -> Configuration have double border all around
4. Device -> Assets have double border all around
5. Device -> Command has double border between windows
6. Device -> Configuration/Assets have  line connecting the two windows at bottom
7.Connections -> Description has double border on the right side (only the "column" part)
8. Jobs -> top menu is too wide
9. Jobs -> double borders all around all the bottom window
10. Users -> Credentials double border left, right and bottom 
11. Users -> Roles double border left, right and bottom 
12. Users -> permissions double border left, right and bottom 
13. Roles -> Permissions double border left, right and bottom 
14. Roles -> Granted Users double border left, right and bottom 
15. Child Accounts -> Users double border left, right and bottom 
16. Child Accounts -> Account Settings no border at all
17. Settings -> Description double border left, right and bottom 
18. Settings -> Account Settings double border left, right and bottom 

Screenshot No. 1:
![screen shot 2018-02-14 at 10 38 33](https://user-images.githubusercontent.com/15121999/36199488-08f69d66-117a-11e8-9e90-89f320ba0aed.png)

Screenshot No. 2:
![screen shot 2018-02-14 at 11 02 41](https://user-images.githubusercontent.com/15121999/36199501-0dc03dac-117a-11e8-87f3-2de40dc96de0.png)

Screenshot No. 3:
![screen shot 2018-02-14 at 11 03 32](https://user-images.githubusercontent.com/15121999/36199667-88aa38ce-117a-11e8-94b8-ae0fe9d99665.png)

Screenshot No. 4:
![screen shot 2018-02-14 at 10 49 26](https://user-images.githubusercontent.com/15121999/36199700-a3883542-117a-11e8-9361-7c1dbac2244a.png)

Screenshot No. 5:
![screen shot 2018-02-14 at 11 09 53](https://user-images.githubusercontent.com/15121999/36199755-cce8d14e-117a-11e8-9aac-8a6265f8f13a.png)

Screenshot No. 6: 
![screen shot 2018-02-14 at 11 07 20](https://user-images.githubusercontent.com/15121999/36199815-f83a2c26-117a-11e8-80e4-b7347e9273ee.png)

Screenshot No. 7:
![screen shot 2018-02-14 at 11 11 07](https://user-images.githubusercontent.com/15121999/36199854-1b008534-117b-11e8-86c8-615ce2e3411d.png)

Screenshot No. 8:
![screen shot 2018-02-14 at 10 50 49](https://user-images.githubusercontent.com/15121999/36199867-295ecb86-117b-11e8-961e-d6a1a19ef586.png)

Screenshot No. 9:
![screen shot 2018-02-14 at 11 15 16](https://user-images.githubusercontent.com/15121999/36199868-2b3d9838-117b-11e8-82ab-8d7a3ff786be.png)

Screenshot No. 10:
![screen shot 2018-02-14 at 11 16 19](https://user-images.githubusercontent.com/15121999/36199964-78048690-117b-11e8-970d-7a88fd9048dc.png)

Screenshot No. 11:
![screen shot 2018-02-14 at 11 16 27](https://user-images.githubusercontent.com/15121999/36199973-7f009894-117b-11e8-9ed0-3ddc4d6acec8.png)

Screenshot No. 12:
![screen shot 2018-02-14 at 11 16 35](https://user-images.githubusercontent.com/15121999/36199979-86523300-117b-11e8-8087-e2c6db375cc6.png)

Screenshot No. 13:
![screen shot 2018-02-14 at 11 19 11](https://user-images.githubusercontent.com/15121999/36199983-8df9465c-117b-11e8-9d9f-c12f66b2dfd6.png)

Screenshot No. 14:
![screen shot 2018-02-14 at 11 19 19](https://user-images.githubusercontent.com/15121999/36200017-abbbbd14-117b-11e8-90a3-144967c1301b.png)

Screenshot No. 15:
![screen shot 2018-02-14 at 11 22 41](https://user-images.githubusercontent.com/15121999/36200047-c5611a0c-117b-11e8-8e7a-e82b2adc071b.png)

Screenshot No. 16:
![screen shot 2018-02-14 at 11 22 51](https://user-images.githubusercontent.com/15121999/36200055-c8d5fe82-117b-11e8-8bd5-712b86612029.png)

Screenshot No. 17:
![screen shot 2018-02-14 at 11 23 11](https://user-images.githubusercontent.com/15121999/36200075-d03f3bac-117b-11e8-814c-1040e646abc2.png)

Screenshot No. 18:
![screen shot 2018-02-14 at 11 23 21](https://user-images.githubusercontent.com/15121999/36200082-d25c6306-117b-11e8-973a-ecad6d39bf16.png)

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
