### ISSUE TITLE
No Client ID Column in Jobs

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1326]
When user is adding devices as targets to certain job, a list with devices appears (the _**Add targets**_ dialogue box) where devices can be added according to their Device ID (human readable name). 
But when the device is added to the target list, there is no _**Device ID**_ column, only _**Job Target Id**_, which are some _random_ characters and numbers. 
I suggest that a _**Job Target ID**_ is replaced with _**Device ID**_, because it is more user-friendly and easier to understand and relate to certain device. 

Testflow: 
1. Login as kapua-sys
2. Go to Jobs, create a job (e.g. job1)
3. Select job1 and add a target. 
**When target is added, user cannot see the name, because there is no Device ID oclumn available.**

![screen shot 2018-01-26 at 10 39 19](https://user-images.githubusercontent.com/15121999/35434233-b9007edc-0286-11e8-9f05-e4e27edecf70.png)

Browsers used:
- Google Chrome (Version 63.0.3239.132 (Official Build) (64-bit)))
- Safari (Version 11.0.2 (13604.4.7.1.6))
- Mozilla Firefox (58.0 (64-bit))
- Opera (Version 50.0.2762.67)

**Comment by lorthirk** [comment]
This is similar to the username resolution used in other views. You should somehow query the DeviceRegistryService to obtain the Client ID for that given target.

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
