### ISSUE TITLE
Different Icons For "Permissions" in Roles And Users

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1328]
There are two different icons for _**Permissions**_ in Users and Roles (look at the screenshots). 
I think this should be unified, as it is the same thing. 

Testflow: 
1. Login as kapua-sys
2. Go to Users and observe _**Permissions**_ tab
3. Go to Roles and observe _**Permissions**_ tab
_**Icon at Permissions tab are not the same.**_

Screenshot No. 1 (Permissions tab in Roles):
![screen shot 2018-01-26 at 11 33 12](https://user-images.githubusercontent.com/15121999/35436342-54c90792-028e-11e8-9c52-99e3d933a75c.png)

Screenshot No. 2 (Permissions tab in Users):
![screen shot 2018-01-26 at 11 35 54](https://user-images.githubusercontent.com/15121999/35436341-53bf5392-028e-11e8-9709-0c2f83ee89fc.png)

Browsers used:
- Google Chrome (Version 63.0.3239.132 (Official Build) (64-bit)))
- Safari (Version 11.0.2 (13604.3.5))
- Mozilla Firefox (57.0.4 (64-bit))
- Opera (Version 50.0.2762.45)

**Comment by lorthirk** [comment]
I'd say that the one in Screenshot 2 should be also used in Screenshot 1.

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
