### ISSUE TITLE
Add/Delete Buttons in Roles for Permissions Instead of Grant/Revoke

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1329]
There are two different sets of buttons _ for **Permissions**_  in Users and Roles (look at the screenshots). In Users we have _**Grant**_ and _**Revoke**_ and in Roles _**Add**_ and _**Delete**_. 
I think this should be unified as in Users (Grant/Revoke), as this is more appropriate for permissions in general. 

Testflow: 
1. Login as kapua-sys
2. Go to Users and observe _**Permissions**_ tab
3. Go to Roles and observe _**Permissions**_ tab
_**Icon at Permissions tab are not the same.**_

Screenshot No. 1 (Permissions buttons in Roles):
![screen shot 2018-01-26 at 11 48 29](https://user-images.githubusercontent.com/15121999/35436481-e8ae9fb2-028e-11e8-8d12-7d155e0c80ba.png)

Screenshot No. 2 (Permissions buttons in Users):
![screen shot 2018-01-26 at 11 48 21](https://user-images.githubusercontent.com/15121999/35436487-f1d5577a-028e-11e8-93ab-7222bcee69c5.png)

Browsers used:
- Google Chrome (Version 63.0.3239.132 (Official Build) (64-bit)))
- Safari (Version 11.0.2 (13604.3.5))
- Mozilla Firefox (57.0.4 (64-bit))
- Opera (Version 50.0.2762.45)

**Comment by lorthirk** [comment]
This is actually on purpose. We find that this wording is actually more correct, since a "Grant" is more appropriate to a user than to a role. I'm closing this, but feel free to comment if you don't agree 😄

**Comment by LeoNerdoG** [comment]
No problem, I thought that this was a mistake. If it was by design it was OK to close :)
