### ISSUE TITLE
Flume JMS-conection to kapua-broker fails 

### ISSUE THREAD

**Issue by kamir** [eclipse/kapua#1332]
I try to consume messages from a topic in Kapua via JMS-Flume-Source.
The Kapua web-console shows a successful connection. But finally, Flume fails.

The Kapua system i work with is **not modified**, just as shown in this docs:
https://www.eclipse.org/kapua/getting-started.php

The following Flume source configuration: 

_tier1.sources.r1.type = jms
tier1.sources.r1.channels = channel1
tier1.sources.r1.initialContextFactory = org.apache.activemq.jndi.ActiveMQInitialContextFactory
#tier1.sources.r1.connectionFactory = GenericConnectionFactory
tier1.sources.r1.providerURL = tcp://kapua-broker:kapua-password@localhost:61616
tier1.sources.r1.destinationName = app/my
tier1.sources.r1.destinationType = topic
tier1.sources.r1.userName = kapua-broker
tier1.sources.r1.passwordFile = pwd.txt_

gives the this error:

Caused by: java.lang.SecurityException: User 1:kapua-broker (ID:My-Great-MacBook-Pro.local-55436-1517091901264-0:1 - tcp://172.17.0.1:45296 - conn id 2358351460271866166) is not authorized to read from: ActiveMQ.Advisory.TempQueue,ActiveMQ.Advisory.TempTopic 

I have found this : https://issues.jboss.org/browse/ENTMQ-1208
But, the open question today: 

Is there any configuration required to enable JMS clients for ActiveMQ?

Or is it simply impossible to use the Flume JMS Source for a Kapua-Broker?
Using a standalone ActiveMQ broker with a JMS-Source worked well. Is the Flume-JMS-Source missing any connection details, which are needed for the Kapua broker?

**Comment by riccardomodanese** [comment]
Hi, could you confirm me that the advisory topic are disabled in your configuration? (https://github.com/eclipse/kapua/blob/develop/assembly/broker/src/main/resources/conf/broker/activemq.xml#L43)

**Comment by Coduz** [comment]
Hi @kamir ,

do you still need help on this? 

Regards, 

_Alberto_

**Comment by kamir** [comment]
Hi Alberto and Riccardo,
I will look into that topic again during the next week - it has not been solved yet, but a bit delayed by other activities.
Thanks already for the hint. Will look into this soon.
Cheers,
Mirko

**Comment by Coduz** [comment]
Hi @kamir ,

News on this? 

Regards, 

_Alberto_
