### ISSUE TITLE
"latest" tag for docker images on DockerHub pointing to 0.3.1 instead of 0.3.2

### ISSUE THREAD

**Issue by alezzandro** [eclipse/kapua#1335]
Hi all,

I want to report that the docker images on DockerHub have the "latest" tag pointing to "0.3.1" and not to the latest "0.3.2" version.

Example: https://hub.docker.com/r/kapua/kapua-console/tags/

Any reason for that?

**Comment by Coduz** [comment]
Hi @alezzandro,

It was just an oversight.
This has just been fixed and now `latest` tags refers `0.3.2` images.

Regards, 

_Alberto_
