### ISSUE TITLE
service api - KapuaException unable to log exception message

### ISSUE THREAD

**Issue by stefanomorson** [eclipse/kapua#1338]
#### Description
Sometimes the system reports stack trace with a warning in a bottom that does not report the actual reason. This is annoying because doesn't allow to identify the cause of the error.

`WARN  org.eclipse.kapua.KapuaException - Could not load Exception Messages Bundle for Locale en_US`

**Comment by lorthirk** [comment]
This is also reported as point 2 in #1466
