### ISSUE TITLE
datastore - elasticsearch index names should have an application prefix  

### ISSUE THREAD

**Issue by stefanomorson** [eclipse/kapua#1345]
#### Description
In current implementation elastic search index names follow the convention:
* **Data:** <account_id>-yyyy-ww
* **Registry:** .<account_id>

We should introduce a prefix like:
* **Data:** kapua-<account_id>-yyyy-ww
* **Registry:** .kapua-<account_id>

#this allow to identify Kapua index names among other indexes in the case when elasticsearch instance is shared between different applications . The prefix should be configurable through system settings.

**Comment by Coduz** [comment]
This has been implemented in #1845
