### ISSUE TITLE
Dialogue Box Closes if User Enters Groups/Tags/Roles/Accounts With Non-Unique Name

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1356]
If user enters non-unique name in Access Group/Tags/Roles/Child Accounts, Kapua does not close the dialogue box, but only shows an error that user has not used a non-unique name. 
But if user enters for example a job with non-unique name, after clicking **Submit** the dialogue box stays open and an error is shown (which is ok).
Problem here is non consistency and for end user is much better, if dialogue box does not close. 

Testflow: 
1. Login as kapua-sys
2. Go to Access Group/Tags/Roles/Child Accounts, add an item (e.g. role1, tag1) 
3. Try to add another item (with same name)
**At this point Kapua will close the dialogue box and show error, instead just showing the error and keeping the dialogue box open.**

Screenshot No. 1 (example of adding two same groups):
![screen shot 2018-02-05 at 09 17 33](https://user-images.githubusercontent.com/15121999/35794287-74d38818-0a55-11e8-9cf9-f02e6bbe5853.png)

Screenshot No. 2 (example of adding two same tags):
![screen shot 2018-02-05 at 09 17 42](https://user-images.githubusercontent.com/15121999/35794290-767cf0be-0a55-11e8-91fc-bd92372adc14.png)

Browsers used:
- Google Chrome (Version 64.0.3282.119 (Official Build) (64-bit)))
- Safari (Version 11.0.3 (13604.3.5))
- Mozilla Firefox (58.0.1  (64-bit))
- Opera (Version 50.0.2762.67)

**Comment by lorthirk** [comment]
@LeoNerdoG,

is this still an issue after #1111 has been fixed?

**Comment by LeoNerdoG** [comment]
@lorthirk Yes, I have verified that this issue has been resolved.
