### ISSUE TITLE
No Text in Dialogue Box When Creating New Device

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1359]
When user for example, creates new tag or new role/account/group...there is always a text in the dialogu box, that creates the item (e.g. _****_)

Testflow: 
1. Login as kapua-sys
2. Go to Devices -> Add 
_**Looka at the screenshot bellow; There is no text in the New Device dialogue box, as there is in every other Add New: item dialogue boxes.**_

![screen shot 2018-02-05 at 12 52 01](https://user-images.githubusercontent.com/15121999/35804854-c0d77c8c-0a79-11e8-80b9-383c2d06e0a1.png)

Browsers used:
- Google Chrome (Version 64.0.3282.119 (Official Build) (64-bit)))
- Safari (Version 11.0.3 (13604.3.5))
- Mozilla Firefox (58.0.1  (64-bit))
- Opera (Version 50.0.2762.67)

**Comment by lorthirk** [comment]
@LeoNerdoG could you provide a message to fill the space that is coherent with the other entity creation dialogs?

**Comment by LeoNerdoG** [comment]
@lorthirk I suggest that text should be similar to that in Users: **_Edit Device's information and its attributes._** 
Any thoughts on this?

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
