### ISSUE TITLE
Bring FilterPanel in main layout

### ISSUE THREAD

**Issue by lorthirk** [eclipse/kapua#1383]
In a standard EntityView a `FilterPanel` is shown to the right of said view, in the right side of its container. For UI/UX reason it's better to have a `FilterPanel` belonging directly from the main view.

**Comment by lorthirk** [comment]
Here is a screenshot of the current layout: 

<img width="2032" alt="schermata 2018-02-09 alle 16 31 17" src="https://user-images.githubusercontent.com/8140139/36036051-15bb5916-0db9-11e8-8eb0-6e2c1d931363.png">

While this is the implemented proposal:

<img width="2032" alt="schermata 2018-02-09 alle 16 30 41" src="https://user-images.githubusercontent.com/8140139/36036069-23d1a6f4-0db9-11e8-91c0-7cd943c80102.png">

Please notice that now the filter panel is aligned with the grid, not a child of it anymore.

The implementation is in branch `fix-filter_panel_in_main_layout`

**Comment by lorthirk** [comment]
@LeoNerdoG please do a deep test around the whole filtering feature, since I had to move some stuff around and I want to make sure that everything is in place.

**Comment by LeoNerdoG** [comment]
@lorthirk I have tested the filtering feature and haven't found any problems so this can be merged when ready.

**Comment by lorthirk** [comment]
Merged in develop with 93ab61b3c

**Comment by LeoNerdoG** [comment]
@lorthirk I have reteste this now that is merged in develop and i haven't found any problems. This issue can be closed.
