### ISSUE TITLE
Unable to login in after clean installation of Kapua 0.3.2

### ISSUE THREAD

**Issue by ctron** [eclipse/kapua#1392]
Logging in to Kapua with `kapua-sys` and `kapua-password` on a newly created Kapua 0.3.2 OpenShift installation triggers the following error message:

> Unable to provision, see the following errors: 1) Error injecting constructor, org.eclipse.kapua.service.certificate.exception.KapuaCertificateException: Error: at org.eclipse.kapua.service.certificate.internal.CertificateServiceImpl.<init>(CertificateServiceImpl.java:57) while locating org.eclipse.kapua.service.certificate.internal.CertificateServiceImpl at org.eclipse.kapua.locator.guice.KapuaModule.configure(KapuaModule.java:108) while locating org.eclipse.kapua.service.certificate.CertificateService 1 error

Login is not possible.

**Comment by ctron** [comment]
Sorry, it was my fault. I was using the deploy scripts from an older version. They have to be in sync with the docker images.

**Comment by kanerbis** [comment]
Could you know how to resolve it from kapua ?
I have same issue.
