### ISSUE TITLE
False Device Connection Status

### ISSUE THREAD

**Issue by Sealdolphin** [eclipse/kapua#1399]
Hi,
I encountered a problem, that I had a Raspberry Pi with a Kura connected to a Kapua. But after a while the Kura suddenly was shut down (probably due to missing requirements). The problem is, that the device is though not connected (not alive at all), Kapua says, that it's status is CONNECTED. Also I cannot access any configuration (for obvious reasons), but still I don't know if there is a way to tell Kapua that the device is MISSING to avoid errors.

I had another device, and when I normally disconnected it, it worked fine.
There is an image of the dead device (KuraMark) with no configurations.
![image](https://user-images.githubusercontent.com/26169252/36159330-ba49c03a-10de-11e8-8a75-82029a4e460e.png)

**Comment by LeoNerdoG** [comment]
This issue has already been addressed in #1316 and has already been fixed by @muros-ct (PR #1393 ). 
This does not directly solve the problem, but gives user a error message saying that the device list should be refreshed in order to get newest info regarding all the devices.

**Comment by lorthirk** [comment]
After a while (the standard MQTT keepalive period IIRC, but please @riccardomodanese or @Coduz correct me if I'm wrong) we should be showing the MISSING status anyway in such cases.

**Comment by riccardomodanese** [comment]
As @lorthirk said, the status should be updated after a while (ActiveMQ will wait 1,5 times the keep alive before considering the device missing).
To better define the issue you are experiencing, could you try to refresh the ui to verify if the device status changes after a while?

**Comment by lorthirk** [comment]
Hi @Sealdolphin, any update on this?

**Comment by Sealdolphin** [comment]
Hi,

Sorry for not answering earlier, but unfortunately the computer I have been
working with was taken away for maintenance. I recently installed Kapua to
another deivce, and now reproduced this issue.
I did the following:

1. Started Kapua
2. Connected a Kura Device (kuraTable)
3. Requesting some message via REST API (proof for connection)
4. Left them overnight (The Kura device was shut down from power supply,
the Kapua server as well)
5. Restarted Kapua
6. Current status seen on picture.

The Kura device is now offline, but Kapua probably did not check at start
for connection. Also I tried to reach 'kuraTable' via REST API, but got
KuraMqttDeviceCallException when requesting Data Messages. I hope these
information helps.




2018-02-28 10:40 GMT+01:00 Claudio Mezzasalma <notifications@github.com>:

**Comment by riccardomodanese** [comment]
From my understanding this issue sounds different from the original one.
Could you specify better the 4? Did you remove the power supply before shutting down the Kapua components?

**Comment by Sealdolphin** [comment]
I shut the power before I turned off Kura. Kapua has been running on a faraway virtual machine which automatically turned down afterwards,  without turnig off Kapua.

After about a day I restarted Kapua but I did not start the Kura device. On the web console that device seemed connected but was unreachable. After I started the Kura again, and disconnected the problem was solved.
_____________________________

**Comment by lorthirk** [comment]
I think that timing is a factor here. @Sealdolphin, could you please exactly define that "Afterwards" you were talking about, when you turned off Kapua?

Kapua needs to wait for at least 90 seconds before it can detect a timeout for a device and set it MISSING state. Of course, if you shut down Kapua (both cleanly or not), nothing can mark such device in MISSING state, and it will stay CONNECTED in the DB even after Kapua starts again.

Does this clarify your doubts?

**Comment by Sealdolphin** [comment]
I think this would be a good explanation, however I do not know exactly when the Kapua machine was shut down. It was probably about 2-3 hours but definitely more than 90 seconds.

________________________________
