### ISSUE TITLE
Icons For Values And Services Are The Same

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1403]
Icon at Values in Devices -> Configuration is the same as icon for Services in Devices -> Assets. 

Testflow: 
1. Login as kapua-sys
2. Go to Devices, connect a live device to Kapua
3. Select the live device and go to Configuration/Assets
**Icons for Values and Services are the same.**

Screenshot No. 1 (Icon for Values in Configuration):
![screen shot 2018-02-14 at 14 05 51](https://user-images.githubusercontent.com/15121999/36205926-d77a8f38-1190-11e8-9ae9-6d60621caf3d.png)

Screenshot No. 2 (Icon for Services in Assets):
![screen shot 2018-02-14 at 14 05 57](https://user-images.githubusercontent.com/15121999/36205930-d91e9122-1190-11e8-9435-92b843fe55ee.png)

Browsers used:
- Google Chrome (Version 64.0.3282.140 (Official Build) (64-bit)
- Safari (Version 11.0.3 (13604.3.5))
- Mozilla Firefox (58.0.2  (64-bit))
- Opera (Version 51.0.2830.26)

**Comment by lorthirk** [comment]
@LeoNerdoG Are we using [Tachometer](https://fontawesome.com/v4.7.0/icon/tachometer/) somewhere in the console already? Otherwise we could use this one

**Comment by LeoNerdoG** [comment]
@lorthirk Yes, we are using it in Jobs -> Steps.

**Comment by lorthirk** [comment]
In `fix-device_asset_tab_icon` branch I put the [Signal](https://fontawesome.com/v4.7.0/icon/signal/) icon. Could you check if it's ok?

**Comment by LeoNerdoG** [comment]
@lorthirk I have verified that changes made in `fix-device_asset_tab_icon` successfully resolves this issue (icon is not used anywhere else). And the icon is preety neet too. You can merge when ready.

**Comment by lorthirk** [comment]
Merged in develop with 643077d305c9cf438cc24b26eec9ddf38d00340d

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
