### ISSUE TITLE
Sonar analisys reports Blocker issues

### ISSUE THREAD

**Issue by Coduz** [eclipse/kapua#1410]
Sonar si reporting `Blocker` issues on develop.
https://sonar.eclipse.org/drilldown/issues/144827?severity=BLOCKER

Even if those are only test, move those into setting files, should solve those reports.

**Comment by lorthirk** [comment]
@muros-ct I see a PR has been merged. Can we close this issue?

**Comment by muros-ct** [comment]
@Coduz Can this issue be closed.

**Comment by muros-ct** [comment]
I am closing it, as it seams that Sonar is ok, and fix didn't break anything.
