### ISSUE TITLE
lambada coming from jar file need their interfaces on classpath to be compiled

### ISSUE THREAD

**Issue by noumanpowersoft19** [eclipse/kapua#1412]
AGPBI: {"kind":"error","text":"Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.lang.Runnable","sources":[{"file":"C:\Users\nouman.jamil\Downloads\Kapua_Client_Connection-master\TransportAsync.java","position":{"startLine":32,"endLine":33}}]}
AGPBI: {"kind":"error","text":"Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Consumer","sources":[{"file":"C:\Users\nouman.jamil\Downloads\Kapua_Client_Connection-master\AbstractClient.java","position":{"startLine":92,"endLine":93}}]}
AGPBI: {"kind":"error","text":"Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Consumer","sources":[{"file":"C:\Users\nouman.jamil\Downloads\Kapua_Client_Connection-master\AbstractClient.java","position":{"startLine":114,"endLine":115}}]}
AGPBI: {"kind":"error","text":"Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Consumer","sources":[{"file":"C:\Users\nouman.jamil\Downloads\Kapua_Client_Connection-master\AbstractClient.java","position":{"startLine":96,"endLine":97}}]}
AGPBI: {"kind":"error","text":"Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Consumer","sources":[{"file":"C:\Users\nouman.jamil\Downloads\Kapua_Client_Connection-master\AbstractClient.java","position":{"startLine":123,"endLine":124}}]}
AGPBI: {"kind":"error","text":"Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Consumer","sources":[{"file":"C:\Users\nouman.jamil\Downloads\Kapua_Client_Connection-master\AbstractClient.java","position":{"startLine":100,"endLine":101}}]}
AGPBI: {"kind":"error","text":"Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Consumer","sources":[{"file":"C:\Users\nouman.jamil\Downloads\Kapua_Client_Connection-master\AbstractClient.java","position":{"startLine":67,"endLine":68}}]}
AGPBI: {"kind":"error","text":"Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Consumer","sources":[{"file":"C:\Users\nouman.jamil\Downloads\Kapua_Client_Connection-master\AbstractClient.java","position":{"startLine":105,"endLine":106}}]}

FAILED

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':app:transformClassesWithPreJackPackagedLibrariesForDebug'.
com.android.build.api.transform.TransformException: com.android.builder.core.JackToolchain$ToolchainException: Jack compilation exception

Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

Get more help at https://help.gradle.org

BUILD FAILED in 7s

**Comment by noumanpowersoft19** [comment]
@ctron please have a look at my issue here

**Comment by Coduz** [comment]
Hi @noumanpowersoft19 ,

Do you still need help on this? 

Regards, 

_Alberto_
