### ISSUE TITLE
Add access checks in all UI element

### ISSUE THREAD

**Issue by Coduz** [eclipse/kapua#1432]
Currently there are many UI components that are missing access checks to determine whether or nor they are enabled or not. 

Each tab/grid/button should take into consideration usage of `GwtSession.hasPermission()` with their respective permission to determine if it its status is disabled/enabled.

**Comment by LeoNerdoG** [comment]
Hey @Coduz,
I have reviewed Device part of Permissions. 
So to understand, here is the testflow: 
1. Login as kapua-sys
2. Go to Child Account and create an account (e.g. kapu-child0)
3. Add a user to kapua-child0 (e.g. kapua-user0)
4. Add permissions to kapua-user0 according to test (User permissions, Tag permissions, Role poermissions...)

Devices:
1. If user has only Device:read or Device:read and a combination of Device:write and Device:delete permissions, only Description tab should be visible in bottom window (and not Packages, Bundles, Conf. and Assets).
2. Question: At this moment user needs Device, Device_management, Device_lifecycle, Device_events and Account:read permissions to see Packages, Bundles, Configuration and Assets tabs. Shouldn't be enaugh for user to have only Device, Device_management and Device_lifecycle permissions?
3. Device -> Command tab is shown only if Device:ALL permissions are assigned to user (it does not work if user adds read, write and delete permissions sepparatelly)
4. Device -> Tags can be deleted just with Tag:read and Tag:write permissions

**Comment by LeoNerdoG** [comment]
Hi @Coduz,
here are the test results for Roles, Jobs and Datastore.
**_Roles:_** 
1. If user has only Role:read or Role:read and a combination of Role:write and Role:delete permissions, only Description tab should be visible in bottom window (at the moment the Permission tab is also visible).
2. Permission tab should be visible when access_info:read permission is set or access_info:read in combination with others.
3. "Grant" button in Permission tab should be enabled only if access_info:write permission is set.
4. "Revoke" button in Permission tab should be enabled only if access_info:delete permission is set. 
5. 

**_Jobs:_**
1. If user has only Job:read permission and there are some jobs in job list, Kapua returns Job:write error, when user clicks on them.
2. If user has only Job:read or Job:read and combination of Job:write and Job:delete permissions only Decription, Steps and Execution tbas should be visible (and not Targets)

**_Datastore:_**
1. If user has only Datastore:read permissions, the should only be "By Topic" tab ("By Device" and "By Asset" should only be, if user has Device:read permissions)

**Comment by LeoNerdoG** [comment]
Hi @Coduz 
here are the test results for User, Tag and Connection Service. 
_**Users:**_

1. **_Grant_** and **_Revoke_** buttons in **_Permissions tab_** should be disabled when only **_access_info:read_** permission is added to user.
2. Only **_Grant_** button should be enabled, when **_access_info:read_**, **_access_info:write_**, **_domain:read_** and **_domain:write_** permissions are applied to user.
3. **_Revoke_** button should be enabled only if **_access_info:delete_** and **_domain:delete_** permissions are applied to user. 
4. **_Role tab_** should not be visible, if user does not have **_Role:read_** permissions
5. Roles's **_Assign_** button should be disabled when only **_access_info:read_** permissions are set. 
6. Roles's **_Remove_** button should be enabled only when **_access_info:delete_** permission is set. 
7. Credential's **_Add_** button should be disabled when only no **_Credentials:write_** permission is added.

_**Tags:**_ / 

_**Connections:**_
1. device_connection:delete permission is unnecessary as only broker can delete connections.

**Comment by LeoNerdoG** [comment]
Hi @Coduz,
this is last part of Access check tests.

_**Access Groups:**_ /

_**Child Accounts:**_
1. Kapua reports missing EndpointInfo:read permissions, although user has it. This tab only works if user has ALL ALL ALL permissions. Otherwise this tab is unaccessible.

_**Settings:**_
1. Same as for Child Accounts: Kapua reports missing EndpointInfo:read permission, although user hsa been granted this permission.

**Comment by bojanutkovic** [comment]
Hi @Coduz ,

I have few questions about permissions:

What permissions we need to see Packages, Bundles, Configuration and Assets tabs in devices?

Device -> Command tab is shown only if Device:ALL permissions are assigned to user (it does not work if user adds read, write and delete permissions separately). In app we check does user have device management permission. What is correct permission for this tab?

Roles -> Permission tab throw error "domain: read permission" if user have access_info:read permission. Do we need that domain:read permission here or it can be removed?

What permission we need for target tab inside Jobs?

**Comment by Coduz** [comment]
Hi @bojanutkovic ,

sorry for being late on the answer.

All device management tabs should refer to `device_management` permission. All of them require `read` to be enabled, but the Command Tab must match `device_management:execute` permission.

In role view I did not have any error for `domain:read`. Can you please tell me what are the step to reproduce the error? 

Job target requires `job:view`.

Regards, 

_Alberto_

**Comment by LeoNerdoG** [comment]
@Coduz I have rechecked this part of permissions that are mentioned here and everything is OK, so you can close this issue. I will test everyhing else and if I find something, I will report. 

Regards,

_Leonardo_
