### ISSUE TITLE
Add mor documentation to OpenShift (minishift) deployment

### ISSUE THREAD

**Issue by marziman** [eclipse/kapua#1442]
Hi Team,

I just quickly set up minishift locally and I think it should me mentioned, that you should log in
into OpenShift with admin user account. There are many ways to login but you wont see the project.
Just run into this and played beginner..so I can extend the docu, if you agree?

BR Mehmet

**Comment by Coduz** [comment]
HI @marziman ,

Please check the PR #1824 . 
It should be now well documented!

Regards, 

_Alberto_
