### ISSUE TITLE
User Can Delete Itself

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1445]
User can delete itself in a child account as _**Delete**_ button is not disabled. Consequently kapua crashes entirely, it is not even possible to login as kapua-sys. 

Testflow: 
1. Login as kapua-sys
2. Go to Child Accounts and create an account (e.g. child1) 
3. in child1 account add a user (e.g. kapua-user1) with _**ALL**_ permissions
4. Login as kapua-user1, go to _**Users**_, select kapua-user1 and delete it. 
_**After that kapua returns a lot of null and Persistance errors. After refresheing the browser, user cannot even login as kapua-sys.**_

Screenshot No. 1 (Errors after deleting user kapua-user1):
<img width="1254" alt="screen shot 2018-02-21 at 15 21 59" src="https://user-images.githubusercontent.com/15121999/36486146-1d4ab280-171e-11e8-9a8c-c7bff18eb617.png">

Screenshot No. 2 (Error when refreshing browser and trying to login as kapua-sys):
<img width="1218" alt="screen shot 2018-02-21 at 15 39 12" src="https://user-images.githubusercontent.com/15121999/36486168-29eb7894-171e-11e8-9a38-ea4d3ad49527.png">

Browsers used:
- Google Chrome (Version 64.0.3282.140 (Official Build) (64-bit)
- Safari (Version 11.0.3 (13604.3.5))
- Mozilla Firefox (58.0.2  (64-bit))
- Opera (Version 51.0.2830.26)

**Comment by Coduz** [comment]
Well... If a user deletes itself, it deserves this treatment! Ehehe

**Comment by lorthirk** [comment]
A fix is provided in `fix-user_can_delete_himself`. Please note that now the check for both the system user (for edit and delete) and the "self" user is done at backend rather than at frontend; this means that now the edit and delete button will always be enabled, but then an error will be thrown if needed.

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved with commit 3e99d6f.
