### ISSUE TITLE
certificates - check forwarded flag

### ISSUE THREAD

**Issue by stefanomorson** [eclipse/kapua#1451]
Description
Suppose an account does not have its own certificate for a given type of usage. While checking availability of a certificate required to execute a secure operation, if the closest ancestor account who holds a certificate of the same type either:

does not allow to forward the certificate to the child accounts
allows forwarding but (all) the certificate(s) is(are) disabled
then the certificate should not be considered available at all.

**Comment by lorthirk** [comment]
We actually don't need to manage this, since our current implementation only has a dummy `forwardable` flag. I'd say it's better to leave the `CertificateService` implementation to provide a custom logic to return ancestors certificates.
