### ISSUE TITLE
Docker Images root password?

### ISSUE THREAD

**Issue by CloudResearch** [eclipse/kapua#1465]
i want to make some changes inside the image to fit my needs, but root user is protected and i have no sudo rights as well, could your write down the password of root for me of your current docker hub hosted broker image?

**Comment by CloudResearch** [comment]
Found also this workaround, but though there is some better solution

**Comment by lorthirk** [comment]
Well, again, it's not up to us but to CentOS. Also, I don't think that provide a root password for such a base container is a smart move, so I really can't blame them :)
