### ISSUE TITLE
Allow creation of DeviceConnection as DISCONNECTED

### ISSUE THREAD

**Issue by Coduz** [eclipse/kapua#1472]
Currently is not possible to create a `DeviceConnection` with `status` set to `DISCONNECTED`. 
This is hardcoded in https://github.com/eclipse/kapua/blob/develop/service/device/registry/internal/src/main/java/org/eclipse/kapua/service/device/registry/connection/internal/DeviceConnectionDAO.java#L41

This means that if your application requires a 'pre-seeding' of a device connection you are required first to create the `DeviceConnection` and then update it as `DISCONNECTED`.

It would be easier to make this editable. Maybe we can set the `CONNECTED` status by default.

**Comment by LeoNerdoG** [comment]
This is connected to issue #1395.
