### ISSUE TITLE
A small format problem for md documents

### ISSUE THREAD

**Issue by zhang6321615** [eclipse/kapua#1497]
File location:
  doc/kuraKapuaDocs.md  （36 Lines）

Content: 
Go to Kapua folder and run command mvn clean install -DskipTests -Pconsole which will build the project with the Web Admin console. 5

One more number 5

**Comment by Coduz** [comment]
@zhang6321615 feel free to contribute this change, if you want. 
If you don't want to, I can fix it for you :)
