### ISSUE TITLE
can not use MariaDB with the kapua-console image

### ISSUE THREAD

**Issue by rbaumgar** [eclipse/kapua#1498]
when I try to switch to MariaDB I get

3079 [main] INFO  o.e.k.a.c.s.util.ConsoleListener - Initialize Liquibase embedded client.
3094 [main] ERROR o.e.k.s.l.KapuaLiquibaseClient - Error while running Liquibase scripts!
java.sql.SQLException: No suitable driver found for jdbc:MariaDB://172.30.41.164:3306/?useTimezone=true&useLegacyDatetimeCode=false&serverTimezone=UTC&characterEncoding=UTF-8&allowMultiQueries=true

Do I need to build a new image?
I tried to set following parameters
commons.db.name=$MYSQL_NAME
commons.db.username=$MYSQL_USER
commons.db.password=$MYSQL_PASSWORD
commons.db.jdbcConnectionUrlResolver=MariaDB
commons.db.jdbc.driver=org.mariadb.jdbc.Driver
commons.db.connection.scheme=jdbc:mariab

Documentation mentions that I can use MariaDB and H2, http://download.eclipse.org/kapua/docs/develop/developer-guide/en/database.html

**Comment by Coduz** [comment]
In Kapua there is no MariaDB driver. 
You have to provide it.
Other parameters seems correct.

**Comment by rbaumgar** [comment]
it' a pitty.
Kapua is using Liquibase, which supports many DBs, like MySQL, PostgreSQL, Oracle, Sql Server, Sybase, DB2, Apache Derby, HSQL, H2, Informix, Firebird and SQLite. I understand that Oracle, IBM, ... is not included. But why not the OpenSource one?
And even more, because it is documented, that Kapua support H2 and MariaDB

**Comment by Coduz** [comment]
In the source of Kapua we can include dependencies/code according to its licensing. 

Unfortunately MariaDB/MySQL connector licenses are not EclipseLicense-friendly, so we cannot ship all together.

We will update the documentation to match the actual situation.

**Comment by swensa** [comment]
See if this helps http://swensa.com/kapua/
