### ISSUE TITLE
Data export to CSV or Excel fails when query results more than 10000 rows

### ISSUE THREAD

**Issue by tovantti** [eclipse/kapua#1534]
Related to #1155 that limit data in table view to 10000 rows, data export to CSV or Excel fails when query results more than 10000 rows.

Similar 10000 row hard limit doesn't exist in DataExporterServlet

Affected version 0.3.2

Should be fixed by #1378

**Comment by lorthirk** [comment]
I write a proposal in #1566. While this is not a final solution, it should enable at least exporting in XLS or CSV queries with more than 10000 results. However, I may add a larger, configurable limit for the export before the PR gets merged.

**Comment by LeoNerdoG** [comment]
Hi @tovantti,
as this has been fixed - cna you please close this issue? I have checked the PR and also the Develop branch and it is OK. Now user gets proper files without errors when there are more than 10k results.

Regards,

Leonardo
