### ISSUE TITLE
Every Account:write Permisssion Should Be Automatically Forwardable

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1544]
This is mentioned in Uros's PR #1539.
Although user has Account:read, Account:write and Account:delete permissions, a child account cannot be edited, when logged in as this user - the best way to describe this issue is through an example. 

Login as kapua-sys and create a user (e.g. kapua-user1) and add Account permimissions to it (read, write and delete). At this point (from end-user standpoint) kapua-user1 should have all the premissions to create, edit and delete child accounts within kapua-sys account, when logged in as kapua-user1.
However, Kapua does not allow kapua-user1 to edit the child account parameters, because the Account:write permission is not set to Forwardable. 
My proposal:
When adding Account:write permission the Forwardable permission should be automatically selected and disabled (so it cannot be unselected). 

Testflow: 
1. Login as kapua-sys
2. Go to Users and create a user (e.g. kapua-user1) 
3. Grant Account:read, Account:write and Account:delete permissions to kapua-user1
4. Login as kapua-user1 and go to Accounts
5. Create an account (e.g. kapua-child1)
6. Try to edit paramteres of kapua-child1 
**When trying to submit changes, Kapua freezes and whole browser window needs to be refreshed.**

Screenshot: 
![screen shot 2018-03-23 at 13 56 16](https://user-images.githubusercontent.com/15121999/37830131-d4d606c6-2ea1-11e8-8e2b-c381200f4cc6.png)

Browsers used: 
- Google Chrome (Version 65.0.3325.162 (Official Build) (64-bit)
- Safari (Version 11.0.3 (13604.3.5))
- Mozilla Firefox (58.0.2  (64-bit))
- Opera (Version 51.0.2830.26)

**Comment by Coduz** [comment]
Hi @LeoNerdoG ,

I think that we may want only to handle that failure gracefully and not grant automatically `account:manage` with `forwardable` set to `true`. if the permission granted is `account:manage` with `forwardable` set as `false` means the used has chosen this behaviour. If the user wanted to be able also to manage its child account the user must have set `forwardable` to `true`.

What do you think? 

Regards,

_Alberto_

**Comment by LeoNerdoG** [comment]
Hi @Coduz,
partly I agree, but strictly looking from end-user standpoint, isn't that the purpose of _**write**_ permission - to be able to (in this case) add and edit child accounts? If not, why is then user able to add an account without _**Forwardable**_  permissions? Also, at this point I (as end-user) understand, that I cannot add Account permissions to my sub-users, as they are not forwardable. But if I set them to Forwardable, then I could.

I would think (if I put myself in end-user role) that _**Forwardable**_ permission is for enabling/disabling permission adding when we are logged in as this sub-user (example: If we set _**Forwardable**_ to True for Devices and Tags, this sub-user can also add this permission to its sub-user, otherwise it cannot).

We can leave this as it is, but the documentation should then include all of these examples for users to understand, what (in this case) _**Forwardable**_ field actually does.

**Comment by Coduz** [comment]
Hi @LeoNerdoG ,

Actually `forwardable` is likely not the best term. It means that a permission is granted to you on your `scopeId` and it  is `forwardable` that permission is granted also in all child scopes. 

Yeah you are right, we need to improve documentation on this.

Regards, 

_Alberto_

**Comment by ct-goranpalibrk** [comment]
Hi @Coduz I could make solution like Leonardo said. Is that okay or not?

**Comment by LeoNerdoG** [comment]
After our meeting where we discused this I am closing this. In the next several days I will create a PR that describes all the permissions in Kapua an we can add a detailed description of "Forwardable" permission there for users to understand what this options actually enables. 
@lorthirk can you please add "NOT AN ISSUE" label to it? 

Thank you!
