### ISSUE TITLE
Is it able to provide  JWT direct authorization support through role mapping?

### ISSUE THREAD

**Issue by miricy** [eclipse/kapua#1558]
Use this setting：
authentication.credential.jwt.audience.allowed=
authentication.credential.jwt.issuer.allowed=

Is it possible to directly provide authorization support through role mapping?

use keycloak manage user and users roles

**Comment by lorthirk** [comment]
Our current implementation of `kapua-servce-authentication` and `kapua-service-authorization` store authorization info in the database. In order to achieve what you're asking, you should probably provide new implementations for both modules.

**Comment by miricy** [comment]
Thank you very much for your answer. I will try it.

**Comment by lorthirk** [comment]
I'll close this issue for now. Feel free to add comments if you need to.
