### ISSUE TITLE
Same Permission Can be Added Multiple Times to a Role

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1575]
Although it should not be possible, user can add same role multiple times to the same role. 

Testflow: 
1. Login as kapua-sys
2. Go to Roles, create a role (e.g. role1)
3. Select role1 and add a permission (e.g. ALL:ALL:ALL)
4. Try to add sam permission again
**Adding two permissions twice should not be possible.**

![screen shot 2018-04-10 at 10 51 30](https://user-images.githubusercontent.com/15121999/38546521-2aa285b6-3cad-11e8-8483-aaedc3181b40.png)

Browsers used: 
- Google Chrome (Version 65.0.3325.162 (Official Build) (64-bit)
- Safari (Version 11.0.3 (13604.3.5))
- Mozilla Firefox (58.0.2  (64-bit))
- Opera (Version 51.0.2830.26)

**Comment by Coduz** [comment]
Hi @LeoNerdoG ,

This is actually not true. The console view is a bit misleading. 
In the table is not shown the `targetScopeId` of the permissions.
The default permission in the `admin` role is `*:*:*:*` while the one that you created is `*:*:1:*`. If you try this on a new role, it won't work. 

Maybe we can add the column of the `targetScopeId` to make this clear.

Regards, 

_Alberto_

**Comment by LeoNerdoG** [comment]
Hey @Coduz,
I have retested this and you are right. Maybe adding a `targetScopeId` is not such a bad idea, as user would then have additional info why he can add two ALL:ALL:ALL permissions. 

Regards,

Leonardo
