### ISSUE TITLE
Cannot Start events-broker docker container

### ISSUE THREAD

**Issue by scoppola84** [eclipse/kapua#1588]
Hi,
i'm trying to run up a kapua composite services..
I'm not able to run kapua events-broker

This is my docker file piece of code:

```xml
  events-broker:
    image: enmasseproject/activemq-artemis:2.2.0-4
    ports:
      - 5672:5672
    environment:
      - ARTEMIS_CONFIGURATION=/run/secrets
    secrets:
      - broker.xml
      - bootstrap.xml
      - artemis-users.properties
      - artemis-roles.properties
      - login.config
      - logging.properties
      - artemis.profile
```
Secrets are loaded correctly, my problems are with the configuration file that i took here: [Configuration ](https://github.com/eclipse/kapua/tree/develop/assembly/events-broker/etc)

I got errors on JAVA_ARGS. I think there's some problems with **artemis.profile** file.

``events-broker_1  | Invalid maximum heap size: -Xmx2G
events-broker_1  | Error: Could not create the Java Virtual Machine.
events-broker_1  | Error: A fatal exception has occurred. Program will exit.
``

If I add a space at the end of string **JAVA_ARGS** in **artemis.profile** as follow:
``JAVA_ARGS=" -XX:+PrintClassHistogram -XX:+UseG1GC -XX:+AggressiveOpts -XX:+UseFastAccessorMethods -Xms512M -Xmx2G "``

I got:

``events-broker_1  | Error: Could not find or load main class``

Thank you

**Comment by stefanomorson** [comment]
Hi,

- can you provide more details regarding the way containers are started ? For example 
 - the command line
 - wether you are using a local build or a container from docker

Another check regards the memory limits in your docker instance in order to be sure that the container has enough memory tu run.

**Comment by scoppola84** [comment]
Hi Stefano,

I start the containers with:
`docker-compose up -d`

I'm using image hosted on docker hub.
I have not set any memory limit on container.

I think memory message is misleading.
However if i don't provide configuration to events-broker cointainer it starts without problems.

**Comment by stefanomorson** [comment]
I just tried to deploy an instance using the Kapua reference docker deployment with 1.0.0-M3 images ([see here](https://github.com/eclipse/kapua/tree/develop/dev-tools/src/main/docker)) and it works as expected. So I would be surprised if there was an issue in the artemis.profile file.
Infact the docker deployment is also using docker compose, check this files:
* [docker-deploy.sh](https://github.com/eclipse/kapua/blob/develop/dev-tools/src/main/docker/docker-deploy.sh)
* [docker-comon.sh](https://github.com/eclipse/kapua/blob/develop/dev-tools/src/main/docker/docker-common.sh)

**Comment by scoppola84** [comment]
I really don't undestand what is going wrong, have you used the specified tag or latest?
Because I have noticed that latest TAG on Docker is pointing to 0.3.2.

**Comment by Coduz** [comment]
Hi @scoppola84 ,

Do you still need help on this? 

Regards, 

_Alberto_
