### ISSUE TITLE
"Login" Button Looks Disabled if User Logs Out

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1620]
If a user logs out, the **Login** button looks disabled, although it operates normaly. If user for example changes anything (username or password), button is shown as active. 

Testflow: 
1. Login as kapua-sys
2. After you login, logout (upper right corner -> logout)
**After you logout, Kapua should bring you to login screen. Look at the "Login" button - it looks disabled as if user did not entere username or password, which is not the case here.**

Screenshot:
![screen shot 2018-04-20 at 10 03 51](https://user-images.githubusercontent.com/15121999/39037885-26462c98-4482-11e8-807f-40f4e5eac181.png)

Browsers used: 
- Google Chrome (Version 65.0.3325.181 (Official Build) (64-bit)
- Safari (Version 11.1 (13604.3.5))
- Mozilla Firefox (59.0.2  (64-bit))
- Opera (Version 52.0.2871.64)

**Comment by Coduz** [comment]
Yeah I confirm that this is due to the fact that GWT does not "sense" the autocompletion from the browser. A simple TAB hit enables the buttons.

**Comment by LeoNerdoG** [comment]
Hi @ct-anaalbic,
I have found another problem with you fix; If user first enters unexisting user (e.g. 123/123), clicks "Login" and after that enters only username (without password) and click "Login", Kapua does not mark "Password" field as invalid, although it should (it is empty). 

Can you please take a look? 😺 

![Screenshot 2019-04-02 at 08 38 12](https://user-images.githubusercontent.com/15121999/55383378-55ea9300-5528-11e9-9a05-7ae26609e1ab.png)

**Comment by ct-anaalbic** [comment]
Hi @LeoNerdoG ,

I will check this now. :)

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
