### ISSUE TITLE
Timeout Field in Job Steps Error Message Contains Invalid Value

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1634]
Error message in Job Timeout Field in Steps say, that maximum value that can be entered is 9223372036854776000, but actual max value is 9223372036854776832. 
Error message hase to be changed. 

Testflow: 
1. Login as kapua-sys
2. Go to Batch Jobs and add a job (e.g. job1)
3. Select job1 and add a step with timeout value 9223372036854776832. 
**Kapua does not report any error, although value is too large.**

Screenshot No. 1 (Timetout value that definetelly exceeds limit):
![screen shot 2018-04-20 at 14 41 29](https://user-images.githubusercontent.com/15121999/39051389-d0227a52-44a8-11e8-9033-b5730dac6442.png)

Screensoht No. 2 (kapua should return an error for this value but it does not):
![screen shot 2018-04-20 at 14 41 35](https://user-images.githubusercontent.com/15121999/39051393-d2324e58-44a8-11e8-8fd4-bc5bdd956f4c.png)

Browsers used: 
- Google Chrome (Version 65.0.3325.181 (Official Build) (64-bit)
- Safari (Version 11.1 (13604.3.5))
- Mozilla Firefox (59.0.2  (64-bit))
- Opera (Version 52.0.2871.64)

**Comment by ct-ajovanovic** [comment]
Hi @Coduz @lorthirk 
Can you take a look at this?
It seems that the **maxValue** for this field is not rendered properly. It's set in the _JobStepAddDialog_ class like this:
```  
              numberField.setData(PROPERTY_NAME, property.getPropertyName());
                if (propertyType.equals(Long.class.getName())) {
                    numberField.setMaxValue(Long.MAX_VALUE);
                } else if (propertyType.equals(Integer.class.getName())) {
                    numberField.setMaxValue(Integer.MAX_VALUE);
                } else if (propertyType.equals(Float.class.getName())) {
                    numberField.setMaxValue(Float.MAX_VALUE);
                } else if (propertyType.equals(Double.class.getName())) {
                    numberField.setMaxValue(Double.MAX_VALUE);
                }
```
In the text of the issue we can see the problem when the Long.MAX_VALUE value is used.  It's true value is  922337203685477**5807**, in the error message its rounded to 922337203685477**6000**, but the actual rendered max value is 922337203685477**6832**. 
I found that similar thing happens with Integer.MAX_VALUE as well. Float and Double values should be checked as well.

What do you think? How should we solve this?

Thanks
_Aleksandra_

**Comment by Coduz** [comment]
Hi Aleksandra,

Uhmmm I think that any value set passed to `.setMaxValue(...)` will be rounded. 

Solution 1: could be to have a custom field validator that uses the `String` representation of the number and check on the `String` `char` by `char`.

Solution 2: Just leave like that. The chances of occurring in that small gap between the real and the rendered max values is negligible. 

Regards, 

_Alberto_

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
