### ISSUE TITLE
Filtering Through Kapa Not "Unified"

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1640]
For now, filtering is not "unified". For example, some of the fields require that searched string is exaclty the same as "target" string (e.g. Custom Attributes fields in Device filter), others require that a character entered is anywhere in the "target" string (e.g. Job name). Is this OK, or not? What is the proper filter operation? 

**_Connections:_**
**- Connection CLiend ID:** Finds match if character or string entered appears anywhere in Cliend ID
**- Conncetion Client IP:** Finds match if character or string entered appears anywhere in Connection Client IP

**_Devices:_** 
**- Device Client ID:** Finds a match if string of characters matches beginning of the target string (if a device's ID is "device123", Kapua will not find it, if users enters "evi" or "123", but will find if entered "d", "dev" or "devic")
**- Device Display Name:** Finds a match if string of characters matches beginning of the target string (if a device's Display Name is "device123", Kapua will not find it, if users enters "evi" or "123", but will find if entered "d", "dev" or "devic")
**- Serial Number:** / non-testable
**- IoT Framework Version:** String has to be complete match (e.g. KURA_3.1.1, not even "K" or "KURA" will suffice, user has to enter "KURA_3.1.1" into search field)
**- Applications:** Finds match if character or string entered appears anywhere in Applications field
**- Custom Attribute No. 1:** String has to be a complete match (e.g. if attribute is "device123", user has to enter "device123", "dev", "123", device12" will not work)
**- Custon Attribute No. 2:** String has to be a complete match (e.g. if attribute is "device123", user has to enter "device123", "dev", "123", device12" will not work)

**_Jobs:_**
**- Job Name:** Finds match if character or string entered appears in any job name

**_Tags:_**
**- Tag Name:** Finds match if character or string entered appears in any tag name

**_Users:_**
**- Username field:** Finds match if character or string entered appears in any username

**_Roles:_**
**- Role Name:** Finds match if character or string entered appears in any role name

**_Access Groups:_**
**- Access Group Name:** Finds match if character or string entered appears in any group name

**_Child Accounts:_**
**- Account Name:** Finds match if character or string entered appears in any account name
**- Account Organization Name:** Finds match if character or string entered appears in any organization name
**- Account Email:** Finds match if character or string entered appears any email name

Browsers used: 
- Google Chrome (Version 65.0.3325.181 (Official Build) (64-bit)
- Safari (Version 11.1 (13604.3.5))
- Mozilla Firefox (59.0.2  (64-bit))
- Opera (Version 52.0.2871.64)

**Comment by mgogic** [comment]
@muros-ct @Coduz @lorthirk 
Is it ok to return strings where character entered is anywhere in the "target" string ?
Regards,
Milan G.

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been successfully resolved.
