### ISSUE TITLE
No Error Message in Jobs -> Targets -> Error Message Column

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1651]
If job was not successfully started/completed, under "Status" in Jobs -> Targets there is _**PROCESS_FAILED**_ status, but "Error Message" column is empty (look at the screenshot).

Testflow: 
1. Login as kapua-sys or any other user that has Device and Job permissions)
2. Go to Devices, add a device (e.g. device0)
3. Go to Jobs, create new job (e.g. job1) and add device0 as Target to this job
4. Go to Steps and add several Bundle Start/Bundle Stop steps (with Bundle ID that does not exist)
5. Press Start 
**At this point Kapua will return message that the job has been _successfully started_, although device is offline and bundle ID does not exist. Also under Error Messave there is no explanation.**

Screenshot:
![screen shot 2018-04-26 at 10 15 59](https://user-images.githubusercontent.com/15121999/39294820-ff7bb9ec-493c-11e8-99d4-6028aea4bc2b.png)

Browsers used: 
- Google Chrome (Version 65.0.3325.181 (Official Build) (64-bit)
- Safari (Version 11.1 (13604.3.5))
- Mozilla Firefox (59.0.2  (64-bit))
- Opera (Version 52.0.2871.64)

**Comment by mgogic** [comment]
@coduz , @lorthirk , @muros-ct  
I have looked in database for Error Message and I can't find this field. 
When Targets tab is opened, Kapua pulls data from Database ( JOB_JOB_TARGET ), and as Error Message isn't field in table, it is always null.
Also, when Status for Target is changed to PROCES_FAILED, job in eclipse console is stil running.
How should we proceed with this issue?
I am sending you screnshoots of Eclipse console output, Database table and Kapua GUI.
Regards,
Milan


![kapuajob](https://user-images.githubusercontent.com/36038833/39746321-4ce131c8-52aa-11e8-8704-8d39a0ec503e.jpg)
![consolescr](https://user-images.githubusercontent.com/36038833/39746322-4d01d2f2-52aa-11e8-8397-383503eecb78.jpg)
![jobtargeth2](https://user-images.githubusercontent.com/36038833/39746323-4d1fc140-52aa-11e8-8fab-0d657d97172e.jpg)

**Comment by lorthirk** [comment]
We currently don't have a message stored somewhere if the job execution fails, so I'd say to remove the column. Do you agree @Coduz ?

**Comment by Coduz** [comment]
Yes, we can currently remove the column.

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
