### ISSUE TITLE
Console - Device Management tabs wrong permission

### ISSUE THREAD

**Issue by Coduz** [eclipse/kapua#1677]
Hi all, 

currently the permission checked to show or hide the Device Management tabs in the Device view are wrong and a user with `device:read` permission is allowed to see the Device Management tabs that should require `device_management` permission.

Regards ,

_Alberto_

**Comment by LeoNerdoG** [comment]
Hey @Coduz,
I did not notice this before, but this is part of issue #1432 which you reported and Bojan made a fix in PR  #1672. I have also mentioned you in that PR to check if everything is OK =) 
So there is no need for your PR (as @bojanutkovic PR contains this and other fixes for permissions).
