### ISSUE TITLE
hello! i met a question on predicate

### ISSUE THREAD

**Issue by miricy** [eclipse/kapua#1691]
i am inquiring according to the predicate,response is 200,but no data was queried.Data is present in the database

**Comment by miricy** [comment]
@Coduz Excuse me ,I am so sorry to bother you.Could you help me about dealing above problems.
Thank you very much!

**Comment by Coduz** [comment]
Hi @miricy ,

Sorry but I didn't get (actually find) the question... 
Can you please describe your scenario? What are you doing? What is the expected behaviour? And what is the actual behaviour instead?

Regards, 

_Alberto_

**Comment by miricy** [comment]
Thank you for your reply. I'm sorry, it's been so long. Can you give me a sample of the format of user query, or where can I see the format of the query?
 `{
  "fetchAttributes": [
    "string"
  ],
  "predicate": {},
  "scopeId": "string",
  "sortCriteria": {},
  "limit": 0,
  "offset": 0
}`
What is the format of this option ‘**predicate**’ and ‘**fetchAttributes**’

[
http://oss.izhiju.cn/tmp/faqimg/fetchuser.png](url)

**Comment by Coduz** [comment]
Hi @miricy ,

Currently "predicates" are not supported via REST API. `User` entity does not have and additional attribute to fetch (`Device`s instead have 2 additional attributes to fetch).

The example query that you can use is:

 ```
{
  "scopeId": "AQ",
  "offset": 0,
  "limit": 50
}
```

You can do some filtering using query parameters in the `/_/users` resource.
Available query parameters are:

- name - This works as exact match
- offset
- limit

There are plans to implement `predicates` filtering and `sortCriteria` in REST API. Please follow issue: https://github.com/eclipse/kapua/issues/803

Regards, 

_Alberto_

**Comment by miricy** [comment]
Ok,  Thanks!
