### ISSUE TITLE
Connecting kura powered devices to kapua

### ISSUE THREAD

**Issue by milan4java** [eclipse/kapua#173]
Hello, I have installed vagrant that created VM's and through VM's I have created the base box and necessary configuration. Now kapua is up and running using https://eclipse.org/kapua/getting-started.php.
On other hand I have configured my raspberry pi with kura. Now kura is up and running  raspberry pi using video https://www.youtube.com/watch?v=oVV5k9OwRt8.

My question is how to connect kura powered devices in kapua. I dont find any devices automatically added to kapua. Please show me the steps to configure kura powered device to kapua.

**Comment by Coduz** [comment]
Hi @milan4java ,

Here you can find the credentials and the URL to connect to the Kapua Broker instance that runs in the Demo Box.

https://github.com/eclipse/kapua/blob/develop/dev-tools/src/main/vagrant/README.MD#verifying-and-accessing-kapua-components

As it is not so clear, I'll add this informations to the [getting started](https://eclipse.org/kapua/getting-started.php.).

Thanks for your question.

Regards, 

_Alberto_

**Comment by milan4java** [comment]
Thanks for the prompt reply,
I am having an issue the directory of activemq is not in /usr/local. And i
am unable to start the broker using activemq start. The error is attached
below. Please help me out in the matter

**Comment by Coduz** [comment]
Hi @milan4java,

In the demo vagrant machine Tomcat and ActiveMQ are located under `/usr/local/kapua/`.

Currently broker in demo machine is not working and it will not start. 
We are trying to fix the problem. Related issue is #179

Regards, 

_Alberto_

**Comment by milan4java** [comment]
Thanx mate for the information. I was trying since week to figure out the problem in activemq and why it is not getting started.

**Comment by Coduz** [comment]
Question answered. Closing.
