### ISSUE TITLE
How to disable elasticsearch storage?

### ISSUE THREAD

**Issue by leinad87** [eclipse/kapua#1733]
I'm having a lot of problems with elasticsearch:

First is related with the number of variables to store. I raised the limit and this message started to appear:
`2018-05-23T07:37:46.440692174Z {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Limit of total fields [1000] in index [2004486053268846124-2018-21] has been exceeded"}],"type":"illegal_argument_exception","reason":"Limit of total fields [1000] in index [2004486053268846124-2018-21] has been exceeded"},"status":400}`

And with that error, this one:
`2018-05-23T07:37:46.440704137Z 07:37:46.440 [Camel (camelContext) thread #18 - JmsConsumer[Consumer.eurotech:mainRoutelisteners:EXACTLY_ONCE.VirtualTopic.%3E]] WARN  org.eclipse.kapua.KapuaException - Could not load Exception Messages Bundle for Locale en_US`

Camel is trying to store the message with exactly once policy (however, the messages arrives to kura with QoS 0) but it can't store the datum so after a while, the system colapses...

I don't want to store all the data in kapua, how can I configure it? Where is the camel routes? How can i disable elasticsearch?

**Comment by Coduz** [comment]
Hi @leinad87 ,

you can disable the camel route for the datastore which is the `mainKapuaRoute`. 

According to deployment used, you might have to rebuild containers/vagrant.

Regards, 

_Alberto_

**Comment by riccardomodanese** [comment]
Hi, if you want to disable ES storage you can remove the proper part of the route from [camel-routes](https://github.com/eclipse/kapua/blob/develop/assembly/broker/src/main/resources/conf/broker/camel-routes.xml)
So just removing the lines between 46-49 should soulve your issue

**Comment by Coduz** [comment]
Hi @leinad87 ,

can we close this? 

Regards, 

_Alberto_
