### ISSUE TITLE
Client ID Prefix Filter Not Working as Other Filters

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1740]
In one of the previous PRs Filter panel operation has been unified (PR #1685). However the problem persists in Dataview, where **Client ID Prefix** field has been added later. 
For now, user ahs to enter exact name, otherwise Kapua dose not find anything. I think it should be unified (operation should be as in all other filter panels).

Testflow: 
1. Login as kapua-sys or any other user with proper permission
2. Connect a live KURA device (e.g. device0) to Kapua with installed Example publisher or any other package that sends sample data
3. Go to Data -> By Device/By Asset
4. Try to use Client ID Prefix field for seracinh devices
**For now, Kapua will only return "device0" if user enters "d", "dev" or "devi", but no if entered "e", "v", "0" as in other filters.**

Screenshot No. 1 (If user entere for example "k", Kapua will find this device):
![screen shot 2018-05-25 at 14 38 25](https://user-images.githubusercontent.com/15121999/40544723-96b9613a-6029-11e8-9009-c4cd923e15e3.png)

Screenshot No. 2 (If user enters "u" (which is part of the name), Kapua will not find the device):
![screen shot 2018-05-25 at 14 38 34](https://user-images.githubusercontent.com/15121999/40544719-939d5cea-6029-11e8-9040-4037daee0c5b.png)

Browsers used: 
- Google Chrome (Version 66.0.3359.181 (Official Build) (64-bit)
- Safari (Version 11.1 (13604.3.5))
- Mozilla Firefox (60.0.1  (64-bit))
- Opera (Version 52.0.2871.64)

**Comment by lorthirk** [comment]
I'm afraid this is a limitation of the current Datastore implementation. I don't think we can do something about it, and this is why is called "Prefix" filter :)

**Comment by LeoNerdoG** [comment]
Ok, so should we close with "wontfix" label?

**Comment by lorthirk** [comment]
@riccardomodanese what do you think? Can we have an operator similar to "LIKE" in Elasticsearch?

**Comment by LeoNerdoG** [comment]
I a closing this due to comments in issue #2464. 
@lorthirk please add label "WONTFIX". 
Leo
