### ISSUE TITLE
After Editing API KEY, The List Gets Randomized

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1774]
If user creates several API_KEYs (without Expiration date set), and after that sets the expiration date, this API_KEY will jump to a random position in the list and also all others wills witch their positions. 
This also happens if user changes its status ti ENABLED/DISABLED and also if user just selects API_KEY, clicks Edit and the Cancel/Submit.

**Testflow:**
1. Login as kapua-sys or any other user that has proper permissions
2. Go to Users, create a user (e.g. kapua-user1)
3. Select kapua-user1 and go to its Credentials
4. Add several API_KEYs (10+) without specifying expiration date
5. After that select a random API_KEY and change its Expiration date 
**Observe how API_KEY list will randomize itsefl after editing just one API_KEY.**

**Expected behaviour:**
API_KEY list should not be randomized after an API_KEY changes its parameters.

**Screenshot No. 1 (Position of API_KEY before disabling it):**
![screen shot 2018-06-07 at 10 19 53](https://user-images.githubusercontent.com/15121999/41087292-8ad86236-6a3c-11e8-97e7-dfa8adefe5e0.png)

**Screenshot No. 2 (Position of API_KEY after disabling/editing it):**
![screen shot 2018-06-07 at 10 20 05](https://user-images.githubusercontent.com/15121999/41087298-8d32fbd6-6a3c-11e8-8742-498aacb821e4.png)

**Version of Kapua**
 - 1.0.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console 
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 66.0.3359.181 (Official Build) (64-bit)
- Safari (Version 11.1 (13604.3.5))
- Mozilla Firefox (60.0.1  (64-bit))
- Opera (Version 53.0.2907.57)

**Comment by Coduz** [comment]
I think that on this we are missing the sort order. I think that Credential.id as a sort order is fine :)
