### ISSUE TITLE
User Status Field Not Coloured in Red When User Wants to Disable Itself

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1777]
As the title of the issue implies, user can set its STATUS field to _DISABLED_, but Kapua returns an error in the bottom right corner (which is OK).The problem is, that field _STATUS_ is not coloured in red, so it si immediatelly visible, what the problem is. See testflow and screenshots for more information.

**Testflow:**
1. Login as kapua-sys or any other user that has proper permissions
2. Go to Users, create a user (e.g. kapua-user0)
3. Add ALL ALL ALL permissions to kapua-user0
4. Login as kapua-user0 and go to Users
5. Select kapua-user0 (user that is currently logged in) and click Edit
6. Try to change status to DISABLED and submit changes
**Observe the error on the right (which is OK), but the filed, that is causing this error (STATUS) is not coloured in red.**

**Expected behavior**
STATUS field should be coloured in red.

**Screenshots**
![screen shot 2018-06-07 at 17 07 12](https://user-images.githubusercontent.com/15121999/41108549-1da6a8a6-6a75-11e8-9c0d-b8d64da7e0f9.png)

**Version of Kapua**
1.0.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console 
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 66.0.3359.181 (Official Build) (64-bit)
- Safari (Version 11.1 (13604.3.5))
- Mozilla Firefox (60.0.1  (64-bit))
- Opera (Version 53.0.2907.57)

**Comment by LeoNerdoG** [comment]
@lorthirk @Coduz I have retested this now it is in develop and found out that for user kapua-sys this does not work. The "Edit user: kapau-sys" window inly blinks and that's it. 
But for every other user (within kapua-sys account or any other child account) this feature works properly. I haven't noticed this before. 
Should we reopen this or leave it like that as regular end-users wont be logged in as kapua-sys anyway?

**Comment by lorthirk** [comment]
I'm reopening it. I'll check it as soon as I can.

**Comment by lorthirk** [comment]
No, not yet, sorry. If anyone could step in he would be more than welcome!

**Comment by lorthirk** [comment]
in #1942 I restored the error message when trying to disable the admin user; however, the field is not yet marked as invalid since the involved field may be more than one (in this case, expiration date and/or status).

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
