### ISSUE TITLE
Refresh Button in Devices -> Tags Not in Proper Position

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1779]
If you look at the Device subtabs (Tags, Events, Packages...) you will see that in each of there **refresh** button is first, followed by tab specific buttons (look at the screenshots).

**Testflow:**
1. Login as kapua-sys or any other user with proper permissions
2. Connect a live KURA device to Kapua (e.g device0)
3. Explore the device's subtabs (Tags, Events...) and observe the button positions
**Refresh button in Tags should be first (on the left side) as it is in all other tabs.**

**Expected behavior:**
Refresh button in Tags should be first (on the left side) as it is in all other tabs.

**Screenshot No. 1 (Position of Refresh button in Events - same as in all other tabs):**
![screen shot 2018-06-08 at 08 15 23](https://user-images.githubusercontent.com/15121999/41141899-119cc386-6af4-11e8-81e7-237546d186c5.png)

**Screenshot No. 2 (Position of Refresh button in Tags):**
![screen shot 2018-06-08 at 08 15 28](https://user-images.githubusercontent.com/15121999/41141898-1026add2-6af4-11e8-929f-3d082f388683.png)

**Version of Kapua**
1.0.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 66.0.3359.181 (Official Build) (64-bit)
- Safari (Version 11.1 (13604.3.5))
- Mozilla Firefox (60.0.1  (64-bit))
- Opera (Version 53.0.2907.57)

**Comment by lorthirk** [comment]
Well... I'm not sure I agree. You can have a standard order if you have standard elements, as in the default Add / Edit / Delete / Refresh paradigm. In the Events view you only have Refresh and Export Data, so I see it as a view with Add, Edit and Delete hidden. So the Refresh is the first one.

**Comment by lorthirk** [comment]
Well... I don't know. After all... we're still creating and deleting a link between a Device and a Tag. Also, I don't think we have a quick way to move the four default buttons (Add, Edit, Delete, Refresh) without creating specific buttons, and having them managed seperately for all their features (enabled status, click listeners, etc.)

**Comment by LeoNerdoG** [comment]
Hey @lorthirk,
so the bottom line of this issue - should we proceed or close? From your last comment I can see, that you would like to close it?

**Comment by LeoNerdoG** [comment]
After a discussion with @lorthirk I am closing this.
