### ISSUE TITLE
Export Data Button in Devices -> Events Inactive

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1781]
Export button in Devices -> Events does nothing if user does not click on triangle symbol on his right side. 

**Testflow:**
1. Login as kapua-sys or any other user with proper permissions
2. Connect a live Kura device to Kapua (e.g. device0)
3. Go to its Events, click on  "Export Data" button.
**Observe, how nothing happens, if user does not click on triangle part of button.**

**Expected behavior**
If user clicks on Export Data buton, a "default" action should happen (e.g. downloading file in .csv format).

**Screenshot:**
![screen shot 2018-06-08 at 09 19 22](https://user-images.githubusercontent.com/15121999/41144356-f0e7c3e4-6afc-11e8-969d-299ad5f5d109.png)

**Version of Kapua**
1.0.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console 
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 66.0.3359.181 (Official Build) (64-bit)
- Safari (Version 11.1 (13604.3.5))
- Mozilla Firefox (60.0.1  (64-bit))
- Opera (Version 53.0.2907.57)

**Comment by lorthirk** [comment]
Instead of electing one of the two choices to default leaving only another one to the backup, I'd transform the whole button to a dropdown, removing the separation between the button itself and the arrow.
