### ISSUE TITLE
"Modified On" Field Not Updated Properly

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1795]
If user is loged in as kapua-sys, goes to Connections/Devices/Users/Tags..., selects an item, clicks Edit and without changing anything clicking Submit, the Modified On field does not get changed (which is OK, because no changes have been made), but Kapua reports tha field has been successfully updated.

**Testflow:**
1. Login as kapua-sys
2. Go to Child Accounts and add an account (e.g. child0)
3. Switch to child0 account and add two users (e.g. user0 and user1)
4. Connect a live Kura device ti child0 account
5. As user0 go to Connections and follow the instrucitons above. 
6. After that repeat the testflow while loged in as kapua-sys.
**Observe how Modified By field does not change if user0 executes the test and how it changes if kapau-sys does it.**

**Expected behavior**
Kapua should not report that fields have been successfully updated, if no changes have been made. Behaviour should be as that when "Cancel" button is pressed. 

**Screenshot No. 1 (Example of an open window and clicking Submit without changing anything):**
![screen shot 2018-06-12 at 11 22 17](https://user-images.githubusercontent.com/15121999/41281900-df7b8418-6e32-11e8-862c-62ed74290d5d.png)

**Screenshot No. 2(Example of info message saying "item successfully updated", although nothing changed):**
![screen shot 2018-06-12 at 11 22 23](https://user-images.githubusercontent.com/15121999/41281902-e16f784c-6e32-11e8-8a2d-9d28bb181e76.png)

**Version of Kapua**
1.0.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[X] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[X] Console
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 66.0.3359.181 (Official Build) (64-bit))
- Safari (Version 11.1 (13604.3.5))
- Mozilla Firefox (60.0.2  (64-bit))
- Opera (Version 53.0.2907.68)

**Comment by Coduz** [comment]
On this, We can check the original value (which is a `Field` property) against the value of the value of the same `Field`. And then decide if display an error or keep the Submit button disabled until changes are detected

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been successfully resolved.
