### ISSUE TITLE
Permission Errors After Revoking Them Should be Handled More Gracefully

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1796]
If user is revoked of permissions (e.g. from parent user) in working process, Kapua reports an error (look at the screenshot), which is OK, but I think this should be handled just like 30 minutes timeout is handled - user shuld be signed out and after the login new set of permissions should come into play. 

**Testflow:**
1) Login as kapua-sys or any other user with proper permissions in browser 1 (e.g. Firefox)
2) Go to Child Accounts and add a child account (e.g. child0)
3) Select child0 and add a user to it (e.g. user0)
4) Add some permissions to user0 (e.g. Role:Read, Role:Write, Job:Read, Job:Write...) 
5) Go to Browser 2 (e.g. Opera) and login as user0 
6) In Browser 1 revoke Roles permissions (if added previously) 
7) In Browser 2 try to open Roles tab on main menu on the left
**Kapua will start showing errors (which is OK, because user0 no longer has Role permissons) but I think user should get logged out with proper message.**

**Expected behavior**
After permission get revoked, user should get logged out with a proper message (e.g. "_This user no longer has these permissions. Signing out_" or something similar.

**Screenshot No. 1 (If user has proper permissions, everything is OK):**
![screen shot 2018-06-12 at 12 32 50](https://user-images.githubusercontent.com/15121999/41285572-e75fee44-6e3c-11e8-8e13-bf994ff8e5a4.png)

**Screenshot No. 2 (After we revoke permission from user, this happens):**
![screen shot 2018-06-12 at 12 24 05](https://user-images.githubusercontent.com/15121999/41285574-e8ed76a0-6e3c-11e8-8a4c-27bfa3a137b9.png)

**Version of Kapua**
1.0.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[X] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[X] Console
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 66.0.3359.181 (Official Build) (64-bit))
- Safari (Version 11.1 (13604.3.5))
- Mozilla Firefox (60.0.2  (64-bit))
- Opera (Version 53.0.2907.68)

**Comment by Coduz** [comment]
Hi @LeoNerdoG ,

I've looked at this issue and at the proposed solution.

The problem is that is currently not possible to determine if a missing permission has been removed during a session. 

I think that forcing the logout can be useful to refresh the list of available permission but it may be too much as a solution. In other web consoles (AWS, Openshift or others) if you try an action for which you don't have the permission to do so, only an error message is shown. 

I would propose to only change the message that is shown on the Console adding to the current one something like "Permission may have changed. Perform a new login to refresh them"/

What do you think?

Regards,

_Alberto_

**Comment by LeoNerdoG** [comment]
Hey @Coduz,
I think solutions you suggessted is OK. I agree that logout is a bit too much for end-user and if we can make a simple message regarding the permissions, this is perfectly OK. At the time it seemed like a good solution but that is more than hlaf a year ago 😄 

Changing message is also what i had suggessted to Ana  and not to perform the logout so I think we can proceed with this. if implementation in PR #2329 is not Ok, we can change it and create another PR (and close the existing one). 

Leo

**Comment by Coduz** [comment]
Hi @LeoNerdoG ,

good! 

Regards, 

_Alberto_

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.

**Comment by LeoNerdoG** [comment]
I am reopening this at it has not been properly fixed.

**Comment by ct-ajovanovic** [comment]
Hi @Coduz 
I have a question regarding the new error message for the `SUBJECT_UNAUTHORIZED` exception.
For now the message looks like this:
<img width="462" alt="41285574-e8ed76a0-6e3c-11e8-8a4c-27bfa3a137b9" src="https://user-images.githubusercontent.com/35954696/53480256-1fc67900-3a7b-11e9-8f85-5e7b68643153.png">

Should the information about the missing permission stay the same? Like in the example above `role:read:5198780178509481813:*`? Or would `role:read` be enough? Where the information about the id and forwardable state are hidden? 
I already talked with @LeoNerdoG  about this and we couldn't decide what the best solution would be. 
What do you think?
Thanks,
Aleksandra

**Comment by Coduz** [comment]
Hi @ct-ajovanovic ,

I would not hide informations about the permissions `targetScopeId`, because that could be helpful if you are accessing child accounts resources. 

What do you mean with this

> Where the information about the id and forwardable state are hidden?

Regards, 

_Alberto_

**Comment by ct-ajovanovic** [comment]
@Coduz 
Ok, than we will leave the information about the permission as it is. And update the rest of the message.

I just meant that the last two parameters `5198780178509481813:*` would not be shown, if we just use the `role:read` part. There was some discussion on our side whether the `targetScopeId` parameter should be visible to the user or not.

**Comment by Coduz** [comment]
Hi @ct-ajovanovic,

I think that `{targetScopeId}:{groupId}` part of the permission are important since those indicate also which scope and (optionally) the group you don't have access to. 

One thing that can be done could be the resolution of the `targetScopeId` and `groupId` to their respective `name`s . BTW This can have two problems. One is that a given `targetScopeId` could not exist. Secondly one can craft permission to guess account names by their IDs.

**Comment by ct-ajovanovic** [comment]
@Coduz Ok, understood. We'll leave the permission information as it is.

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved, all other issues are in issue 2490.
