### ISSUE TITLE
Wire Graph Configuration Marked as Invalid

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1800]
If user connects a live Kura device to Kapua, which contains a wire graph, Kapua will report an error if field value is longer than 255 characters. However, it will permit user to change tabs without asking for saving/discarding changes or informing user that there are fields with errors (as for example in ClockService if you leave clock.ntp.host field empty).

**Testflow:**
1) Login as kapua-sys or any other user that has proper permissions
2) Connect a live Kura device (e.g. device0) to Kapua, which contains a working Wire Graph
3) In Kapua, go to Devices, select device0 and go to Configuration
4) See Wire Service and on the right, the WireGraph field.
**The WireGraph field is coloured in red and Kapua rtports that this field should be limited to 255.**

**Expected Behaviour:**
WireGraph field should not be limited to 255 characters, but something greated (8192 or more), because some graphs can get very complex and so can their descriptions.

**Screenshot:**
![screen shot 2018-06-13 at 08 06 40](https://user-images.githubusercontent.com/15121999/41334065-700fda4a-6ee4-11e8-86b1-cbc92f68f162.png)

**Version of Kapua**
1.0.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 66.0.3359.181 (Official Build) (64-bit))
- Safari (Version 11.1 (13604.3.5))
- Mozilla Firefox (60.0.2  (64-bit))
- Opera (Version 53.0.2907.68)

**Comment by muros-ct** [comment]
I will put this issue back on hold. This is still an issue as it is not possible to edit long fields that are defined in Kura. One solution to this issue would be to increase length of field to a larger value and not just 255.
Only real solution would be for Kura to provide max length of field in this case text field.

**Comment by LeoNerdoG** [comment]
I have verified that PR #2592 has resolved this issue. The maximum length for this field has been increased to 1M, so this should solve all our problems with the wire graph (at least for now).
