### ISSUE TITLE
Permission Problems

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1801]
Bellow there is a list of issues that are connected to permissions. Keep in mind that for every test you must add just the permissions that are needed for the test (if you are testing Devices, assign only Device permissions and not for example Account or Group permissions).

Permission Problems

- [x] Edit Button in **Devices** does not work if user has **Device:Read** and **Device:Write** permissions

- [x] **Add** button in Devices -> Tags is enabled if _device seleceted - unselected - selected again_, although user has only **Device:Read** and **Tag:Read** permissions.

- [x] Jobs -> Step -> Edit button can be clicked although user has only Job:Read and Job:Delete permissions (a step must be selected and repeatedly selected - deselected)

- [x] **Add** button in **Steps** is enabled, although user has only **Job:read** permissions (you have to CMD+select/deselct a job first)

- [x] Why does user need **Role:Delete** permissions to delet a permission (not a role, but permission)?

- [x] Delete button in Users -> Permissions not enabled, although user has all user permissions and Access_Info:Read and Access_Info:Delete permissions.

- [x] Should **Roles** tab in **Users** be visible only with **Role:Read** or also **Access_Info:Read** permissions?

- [x] **Add** button in Roles -> Permissions should not be enabled unless user has **Access_info:Read**, **Access_info:Write** and **Domain:Read** permissions (also **Domain:Write** permission)

- [x] When in Roles, you cannot see Granted Users tab, although you have **Roles:Read** and **Users:Read** permissions (also tried with Forwardable set to true, but it did not work)

- [x] Why does user need "Endpoint_Info" permissions for viewing Child Accounts if there is no "EndpointService"? Because of Broker URIs in Settings tab? 

- [x] Why does user need "Scheduler:Read" Permissions for viewing Child Account Settings?

**Testflow:**
1) Login as kapua-sys or any other user with proper permission 
2) Go to Child Accounts and add a account (e.g. account0)
3) Select account0 and add a user (e.g. user0)
4) Switch to account0 and got to Users. Select user0 and follow the instructions above.
**The results for every test is different, but they should always be **

**Expected behavior:**
See description above - buttons/tabs/etc. should be enabled/disabled according to the permissions granted. 

**Version of Kapua**
1.0.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 66.0.3359.181 (Official Build) (64-bit))
- Safari (Version 11.1 (13604.3.5))
- Mozilla Firefox (60.0.2  (64-bit))
- Opera (Version 53.0.2907.68)

**Comment by ct-ajovanovic** [comment]
Hello @Coduz 
I would really appreciate your help with the last two items in this issue. I have a couple of questions:
Firstly, why is  **Endpoint_Info** permission needed for viewing Child Users-> Settings and Settings tab itself? Because of the Broker URI on the Settings tab? If so, why is the same permission needed for viewing the Settings tab in Child Accounts it there is no URI property displayed?
Second, why is the **Scheduler:Read** permission needed for viewing the Settings tabs? If there are no schedules displayed?
Thanks,
_Aleksandra_

**Comment by Coduz** [comment]
Hi @ct-ajovanovic ,

Yes, the `endpoint_info` permission is required when showing the Broker URIs  for the account. 
On this we can change the code to handle the `AuthorizationExeception` (not sure is called like that) and hide the informations about the URIs if the current user does not have the permissions.

On `ChildAccounts View>Settings Tab` I'm not sure why that is required. It should only be required on the `ChildAccounts View>Description Tab`.

While on `ChildAccounts View>Settings Tab` the `scheduler:read` permission is required to show the configurations available for the `TriggerService` which is a `ConfigurableService`. On this, we can manage the exception similarly to the first point of my answer.

Would that work for you?

Regards, 

_Alberto_

**Comment by ct-ajovanovic** [comment]
Hi @Coduz 
while working on the last two items on the list above - the permissions checks on Settings tabs, I came across a something I would really appreciate your input on.
It looks like the main problem there is the exception handling [HERE](https://github.com/eclipse/kapua/blob/5d93ac31cbd5296080135ce0697e574ea49a30cc/console/module/account/src/main/java/org/eclipse/kapua/app/console/module/account/server/GwtAccountServiceImpl.java#L430) . The exception is not being caught at all, as the `SubjectUnauthorizedException` is no longer the exception thrown when checking permissions and we get this:

<img width="960" alt="not_good1801" src="https://user-images.githubusercontent.com/35954696/53414770-c2c1b900-39cf-11e9-9d7d-d628dc6fa6ba.png">

I tracked the changes that caused that to this PR #2347. 
I tried to solve the problem by making [THESE CHANGES ](https://github.com/ct-ajovanovic/kapua/commit/c136eca154fa0b2cf35fed00b0bd407a76ba95b7), but it doesn't look like a good solution to me.
 It kind of works - there were no error messages and only the services for which the user has the permissions are displayed. What do you think? 
It is possible there are also some other references to that no longer used exception. 
Would it be a better idea change the exception handling when permissions checks fail? To perhaps return the `SubjectUnauthorizedException` again? That would also solve the problems here.
Thanks
_Aleksandra_

**Comment by Coduz** [comment]
Hi @ct-ajovanovic ,

Yes you tracked down the right problem. 

Changes on #2347 were not ok, I've also made the change request, but the PR was merged anyway. 
#2347 should be reverted and #1796 should be reopened and solved in a more appropriate way. I've made some suggestion in the issue and in the changes request. 

I think that the issue you are working on should wait for the actual code to properly throw the `SubjectUnauthorizedException` and then start to work on this. 

What do you think?

Regards, 

_Alberto_

**Comment by ct-ajovanovic** [comment]
@Coduz I agree. I'll start working on #1796. After that is fixed I'll return to this issue.
Regards,
_Aleksandra_

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
