### ISSUE TITLE
Endpoint info domain name validation error

### ISSUE THREAD

**Issue by Coduz** [eclipse/kapua#1812]
**Describe the bug**
From console is no longer possible to use `localhost` or any IP as a `domainName`

**To Reproduce**
Login into the console as `kapua-sys`
Go to Endpoint view
Add a new Enpoint
Write `localhost` or any IP (eg: `192.168.12.34`) and validation will fail.
 
**Expected behavior**
It should accept also those values

**Screenshots**
_None_

**Version of Kapua**
1.0.0-M6

**Type of deployment**
All

**Main component affected**
[ ] Console 

**Additional context**
This is preventing any local usage of endpoint

**Comment by ct-ajovanovic** [comment]
Hi @Coduz 
The part about using IP as a domain name is pretty clear, but I have a question about the localhost part.
Does this mean that only localhost value should pass? Are there any other specific values? 
Or should any one word value pass validation?
Thanks
_Aleksandra_

**Comment by Coduz** [comment]
Hi @ct-ajovanovic,

after a quick look at [RFC 6761](https://tools.ietf.org/html/rfc6761), we can safely assume that the only domain name without a `.` is localhost.

Regards, 

_Alberto_

**Comment by LeoNerdoG** [comment]
@Coduz I have verified that this issue has been resolved, so you can close it. 

Regards,
Leo
