### ISSUE TITLE
User Gets Logged Out If Start Button In Devices -> Bundles Pressed Repeteadly

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1843]
After the fix of issue #1805 a new bug emerged (which was previously camouflaged by the disabled window). If user constatly presses Start button in Devices -> Bundles, Kapua starts throwing error
**_Bundle cannot be started. Please check the device log for errors_**, which is OK. Then after few secconds of pressing Kapua starts to show error _**XSRF_INVALID_TOKEN**_ and after that _**You are not logged in**_ and user gets logged out. 

**Testflow:**
1) Login as kapua-sys or any other user with proper permissions
2) Connect a live Kura device to Kapua (e.g. device0)
3) Go to Devices, select device0 and go to its Bundles
4) Select a stopped bundle and try to start it (you have to chose one that cannot be started - e.g. org.eclipse.kura.sun.misc)
5) Press and hold Start button.
**After a few seconds Kapua will start showing errors described above and user will get logged out.**

**Expected behavior**
Kapua should not logout user if Start bundle is pressed repeteadly.

**Screenshot No. 1:**
<img width="1300" alt="screen shot 2018-06-28 at 09 57 40" src="https://user-images.githubusercontent.com/15121999/42030204-4f4ea27e-7ad2-11e8-8883-60e5d1237182.png">

**Screenshot No. 2:**
<img width="1120" alt="screen shot 2018-06-28 at 12 56 49" src="https://user-images.githubusercontent.com/15121999/42030314-ae3767f8-7ad2-11e8-88c4-0b67b04e96b1.png">

**Version of Kapua**
1.0.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 66.0.3359.181 (Official Build) (64-bit))
- Safari (Version 11.1 (13604.3.5))
- Mozilla Firefox (60.0.2  (64-bit))
- Opera (Version 53.0.2907.68)

**Comment by Coduz** [comment]
Hi @LeoNerdoG ,

The bug comes from the fact that no new XSRF token is set (or there are some problems with handling). 
When verification fails, user is logged out automatically. 

The actual bug is that the XSRF token is not properly managed. 
The log out is expected.

Regards, 

_Alberto_

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
