### ISSUE TITLE
Expose setters for KapuaEntity fields

### ISSUE THREAD

**Issue by Coduz** [eclipse/kapua#187]
Hi all, 

I would like to propose to expose setters that aren't available for all [KapuaEntity](https://github.com/eclipse/kapua/blob/develop/service/api/src/main/java/org/eclipse/kapua/model/KapuaEntity.java) and [KapuaUpdatableEntity](https://github.com/eclipse/kapua/blob/develop/service/api/src/main/java/org/eclipse/kapua/model/KapuaUpdatableEntity.java). 
This is required to avoid to do strange stuff on XML deserialization like [here](https://github.com/eclipse/kapua/blob/0a7ca9dda041271f440799830094b50dba4239ec/rest-api/src/main/java/org/eclipse/kapua/app/api/v1/resources/Users.java#L184). As we can see, the XML deserialization is not able to set the ScopeId property and so we need to use the implementation class to populate it. 
This has two problems:

- Reference to an implementation class 
- It is impossible to manage entities of another account as the scopeId is set always to the user's scopeId.

It wouldn't be such a problem of security as the service implementation code is checking all information and also security checks are performed.

Regards ,

_Alberto_

**Comment by mcarrer** [comment]
Fixed

**Comment by Coduz** [comment]
Fixed in c285936c114fce9e630b0a438696bc5b3f862518
