### ISSUE TITLE
Device Map tile and credit bug

### ISSUE THREAD

**Issue by Coduz** [eclipse/kapua#19]
Hi all, 

the device map has not working tiles and a credit that leads to a not correct website.

Regards, 

_Alberto_

**Comment by stefanomorson** [comment]
Successfully tested a solution with open street maps. 
It's necessary to double check the terms required by Open Street Maps for fair usage of tile servers (http://wiki.openstreetmap.org/wiki/Tile_servers)
For this reason the map is temporaneously disabled.

**Comment by Coduz** [comment]
Hi @kartben ,

as far as I know, on this issue we are waiting news from you about using Open Street Maps in console.
There is any update on this?

Regards,

_Alberto_

**Comment by Coduz** [comment]
Hi All,

as per discussion during the Kapua internal SCRUM, all issues related to the old console will be marked with "wontfix" label and closed.
We are already working on the new console implementation.

Regards,

Alberto
