### ISSUE TITLE
Edit Button In Devices Inactive

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1904]
If there is a certain user that has only Device:ALL:[group]:NO permissions, and no direct Group permissions, there is no way to edit a device when logged as this user. 

**Testflow:**
1) Login as kapua-sys
2) Go to Groups and add a group (e.g. group1)
3) Go to Users, create a user (e.g. user1)
4) Add Device:ALL:group1:NO permission to user1 and Broker:ALL permission (needed for conenctiong the device)
5) Connect a live KURA device (e.g. device1) to kapua-sys account via user1
6) Login as user1 and go to Device tab
7) Select device1 and click Edit button.
**Kapua does not react to this.**

**Expected behavior**
Kapua should open Edit window, because user has all the permissions necessary. 

**Screenshot No. 1:**
![screen shot 2018-07-27 at 14 02 06](https://user-images.githubusercontent.com/15121999/43319640-c52f3a3c-91a5-11e8-93fe-827b92e2e73a.png)

**Screenshot No. 2:**
![screen shot 2018-07-27 at 13 53 57](https://user-images.githubusercontent.com/15121999/43319649-ce2f9816-91a5-11e8-94cb-2379168812c9.png)

**Version of Kapua**
1.0.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 67.0.3396.99 (Official Build) (64-bit))
- Safari (Version 11.1 (13604.3.5))
- Mozilla Firefox (61.0 (64-bit))
- Opera (Version 54.0.2952.41)

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.

**Comment by Coduz** [comment]
Why the re is no PR linked to this?

**Comment by LeoNerdoG** [comment]
Hi @Coduz,
this is because this issue has been opened for so long and nobody did the fix and after some time it got resolved. It is almost impossible to track down the commit that fixed this.
