### ISSUE TITLE
Account Settings Not Accessible Although User Has All Permissions Needed

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1912]
Kapua reports _**User does not have permission to perfrom this action. Missing permisson: [permission]:read:[id]**_ when trying to see Account Settings in Child Accounts -> Account Settings (look at the screenshot for real example).

**Testflow:**
1) Login as kapua-sys
2) Go to Users, create a user (e.g. user1) 
3) Select user1 and add the following permissions:
 - account:read:ALL:YES
 - credential:read:ALL:YES
 - group:read:ALL:YES
 - role:read:ALL:YES
 - datastore:read:ALL:YES
 - device:read:ALL:YES
 - device_connection:read:ALL:YES
 - job:read:ALL:YES
 - user:read:ALL:YES
4) Go to Child Accounts and create a child account (e.g. account1)
5) Login as user1 and go to Child Accounts. 
6) Select account1 and click Account Settings
**Observe the error Kapua reports, although user has all the necessary permissions.**

**Expected behavior**
Kapua should dispaly Child Accounts -> Account Settings when added [permissions]:read. 

**Screenshot:**
<img width="1224" alt="screen shot 2018-07-30 at 13 51 10" src="https://user-images.githubusercontent.com/15121999/43395870-f444e86a-93ff-11e8-9d66-65c989a8824a.png">

**Version of Kapua**
1.0.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 67.0.3396.99 (Official Build) (64-bit))
- Safari (Version 11.1 (13604.3.5))
- Mozilla Firefox (61.0 (64-bit))
- Opera (Version 54.0.2952.41)

**Comment by lorthirk** [comment]
I'm self assigning this because of a side effect of this issue that I want to evaluate more carefully

**Comment by lorthirk** [comment]
Hey @LeoNerdoG,

Could you test #1948 and see if it fixes this issue?

**Comment by LeoNerdoG** [comment]
@lorthirk I have tested PR #1948 and verified that it resolves this issue. I also haven't noticed any other issues.

**Comment by LeoNerdoG** [comment]
I have verified that this issue is resolved.
