### ISSUE TITLE
Username Field Coloured When "Reset" Button Is Pressed

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1931]
If user at login screen presses Reset button when cursor is in Username Field, Kapua colours the filed in red, as it would be in error state. 

**Testflow:**
1) Start Kapua and go to Login screen
2) When cursor is in Username field, click Reset button several times and observe hor Username gets coloured

**Expected behavior**
Username field should not get coloured red if user clicks Reset.

**Screenshot:**
![screen shot 2018-08-08 at 10 45 54](https://user-images.githubusercontent.com/15121999/43827081-421d8cc2-9af9-11e8-8bce-34d68eef34b1.png)

**Version of Kapua**
1.0.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 67.0.3396.99 (Official Build) (64-bit))
- Safari (Version 11.1 (13604.3.5))
- Mozilla Firefox (61.0 (64-bit))
- Opera (Version 54.0.2952.41)

**Comment by muros-ct** [comment]
Issue shows only on certain version of Firefox. It is minor issue and can not be solved with current version of GWT.
