### ISSUE TITLE
Is "ID" column (in Credentials) needed?

### ISSUE THREAD

**Issue by ct-goranpalibrk** [eclipse/kapua#1969]
**Describe the bug**
 @Coduz  This bug is related to #1960 . When trying to sort Credentials by ID in Kapua GUI, they get sorted by Credentials ID from database. Should we eliminate the "id" column from Credentials(and all other views), because I don't see need for showing Id in GUI and because it can't be sorted properly?

**Testflow:**
1) Login as kapua-sys or any other user that has proper permissions
2) Go to Users, create a user (e.g. user1)
3) Select user1, add several API KEYs (e.g. 10 or more) - to some of them add expiration date
4) Try to sort credentials by ID, Credential Type, Expiration Date, Modified On, Modified By
**Observe how Kapua does not sort credentials, although columns are clickable.**

**Version of Kapua**
1.0.0 - SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants)
[ ] Others

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used:
- Google Chrome (Version 68.0.3440.106 (Official Build) (64-bit))
- Safari (Version 11.1.2 (13604.3.5))
- Mozilla Firefox (61.0.2 (64-bit))
- Opera (Version 55.0.2994.44)

**Comment by Coduz** [comment]
Hi @ct-goranpalibrk ,

Just hide the column (like in other grids) using `setVisible(false)` and disable sorting. 

I think that would be a good solution.

Regards,

_Alberto_
