### ISSUE TITLE
kapua-elasticsearch exited(64) on docker

### ISSUE THREAD

**Issue by RobertoAmador** [eclipse/kapua#1974]
I followed the steps on https://www.eclipse.org/kapua/getting-started.php, but kapua-elasticsearch container exited after a few seconds with code 64.

**Comment by LeoNerdoG** [comment]
Hi @RobertoAmador,
after building Kapua go to **_deployment/docker_** folder and run command _**./docker-deploy**_
After this, all the containers should start working and Kapua should be locally accessbile on localhost:8080 in one of your browsers. 
if you want to shut down all the containers, run command _**./docker-undeploy**_.

Regards,
Leonardo

**Comment by lorthirk** [comment]
Also, check how much memory you are assigning to your Docker environment. It looks like Elasticsearch is pretty eager in terms on RAM, so I recommend to reserve at least 6GB if you can.

**Comment by LeoNerdoG** [comment]
@RobertoAmador did you resolve the problem? Do you need any more help? =) 

Regards,
Leonardo

**Comment by lorthirk** [comment]
Closed due to inactivity. Feel free to reopen if you need further assistance!
