### ISSUE TITLE
"500 The Call Failed On The Server" Error If User Does Not have Proper Permissions

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1988]
If user has ALL:ALL:ALL:No permissions, Kapua throws an undescriptive server error instead a user-friendly error (see screeenshot bellow). 

**Testflow:**
1. Login as kapua-sys 
2. Go to Users, create a user (e.g. user1) 
3. Select user1, go to its Permissions, add ALL:ALL:ALL Permissions, set Forwardable to False
4. Login as user1 and go to Settings
5. Click Edit, change any of the fields and click Submit.
**At this point Kapua will return: _500 The call failed on the server; check server log for details_ (see screenshot bellow).**

**Expected behavior**
Kapua should display (handle) this error more gracefully. The error message should be more descriptive.

**Screenshot No. 1:**
![screen shot 2018-09-10 at 14 57 52](https://user-images.githubusercontent.com/15121999/45299086-c12c3380-b50a-11e8-9dac-679726cfa035.png)

**Version of Kapua**
1.0.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 68.0.3440.106 (Official Build) (64-bit))
- Safari (Version 11.1.2 (13604.3.5))
- Mozilla Firefox (61.0.2 (64-bit))
- Opera (Version 55.0.2994.44)

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.

**Comment by Coduz** [comment]
Why there is no PR linked?

**Comment by LeoNerdoG** [comment]
Hi @Coduz,
this is because this issue has been opened for so long and nobody did the fix and after some time it got resolved. It is almost impossible to track down the commit that fixed this.
