### ISSUE TITLE
Time Dropdown Menu Not Working Properly

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1989]
After user selects a specific Time in Jobs -> Scheduled -> Start/End Time, Kapua will only show the selected option when clicked again on the dropdown menu (see screenshots for more detail). 

**Testflow:**
1. Login as kapua-sys or any other user that has proper permissions
2. Go to Jobs, create a job (e.g. job1)
3. Select job1 and go to its Schedules
4. Click Add and select a Start Time (e.g. 01:15)
5. Now again click on the triangle to open 

**Expected behavior**
When user clicks on the dropdown menu after the time has been selected, all of the options should show (even after the first click).

**Screenshot No. 1 (Start time dropdown menu problem):**
![screen shot 2018-09-10 at 15 05 57](https://user-images.githubusercontent.com/15121999/45354892-2e999c00-b5bf-11e8-9b02-a47ad1d81f69.png)

**Screenshot No. 12(End time dropdown menu problem):**
![screen shot 2018-09-10 at 15 06 32](https://user-images.githubusercontent.com/15121999/45354895-30635f80-b5bf-11e8-8214-e69edbdd27ab.png)

**Version of Kapua**
1.0.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 68.0.3440.106 (Official Build) (64-bit))
- Safari (Version 11.1.2 (13604.3.5))
- Mozilla Firefox (61.0.2 (64-bit))
- Opera (Version 55.0.2994.44)

**Comment by Coduz** [comment]
This can be solved by tweaking the `ComboBox` object

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
