### ISSUE TITLE
"User Display Name" Field Missing In Roles -> Assigned Users

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1994]
There is only one column in Roles -> Assigned Users (Name). I think there should also be Display Name column available. 

**Testflow:**
1. Login as kapua-sys or any other user that has proper permissions
2. Go to Roles, select "admin" role, click on Assigned Users
**Observe the columns in this tab - there is only Name.**

**Expected behavior**
I suggest we add Display Name column. 

**Screenshot:**
![screen shot 2018-09-11 at 13 43 19](https://user-images.githubusercontent.com/15121999/45358218-02831880-b5c9-11e8-877e-16cdc841a7c0.png)

**Version of Kapua**
1.0.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 68.0.3440.106 (Official Build) (64-bit))
- Safari (Version 11.1.2 (13604.3.5))
- Mozilla Firefox (61.0.2 (64-bit))
- Opera (Version 55.0.2994.44)

**Comment by Coduz** [comment]
I would add maybe just the email and the display name

**Comment by LeoNerdoG** [comment]
Why should we add email column in Roles -> Assigned Users? Isn't Display Name anaugh? 😄

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
