### ISSUE TITLE
Should items in dataview lists be deselectable or not? 

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#2021]
In one of the previous issuse (#1780) was mentioned that Kapua starts throwin errors, if device is constantly selected and deselected. This was solved by disasbling the CMD/CTRL + click option, so no device can be deselected once selected. 
This has been solved with PR #1972 but not in Data view. My question is: should we also disable the deselect option in Data view (Availabel Topics/Devices/Assets) or not (for the sake of unification)?

**Testflow:**
1. Login as kapua-sys or any other user that has proper permissions
2. Connect a live Kura device to Kapua with installed Example Publisher and Example Asset deployment package.
3. In Kapua go to device view (Available Topics/Devices/Assets) and try to select/deselect topics/devices/assets. 
**For now deselecting is possible, but the question is if we keep it that way or disable it as this has been disabled in other views?**

**Expected behavior**
I suggest we disable deselecting items in the dataview so this will follow rest of the views. 

**Screenshots**
![screen shot 2018-09-17 at 11 46 02](https://user-images.githubusercontent.com/15121999/45616377-8d538f80-ba6f-11e8-968b-c86b856b36ce.png)

**Version of Kapua**
1.0.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 68.0.3440.106 (Official Build) (64-bit))
- Safari (Version 11.1.2 (13604.3.5))
- Mozilla Firefox (61.0.2 (64-bit))
- Opera (Version 55.0.2994.44)

**Comment by LeoNerdoG** [comment]
@lorthirk should we proceed with this or do you think that this is OK? 😄

**Comment by lorthirk** [comment]
Yes, I'd say to uniform the behaviour across the console. So go ahead forbidding deselection here as well.

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
