### ISSUE TITLE
User kapua-sys auto lockout for no apparent reason

### ISSUE THREAD

**Issue by gitsaycat** [eclipse/kapua#2031]
I'm running kapua-1.0.0M7 in docker and the user kapua-sys keeps getting locked out.
I have created another admin account to unlock the kapua-sys user but every time I log out and try to log back in again kapua-sys is locked out. 

The password credential is set up never to expire.
Is there any setting that turns on auto-expiry of an account?

**Comment by Coduz** [comment]
HI @gitsaycat ,

There is a lockout policy, which causes a user to get locked after 3 failed attempts.

This usually happens when a device is trying to connect to the broker with `kapua-sys`.

Can you please check if there is any failed connection attempt to the broker?

Regards, 

_Alberto_

**Comment by gitsaycat** [comment]
Hello Alberto
I have no users using kapua-sys directly for communication
However I see messages in the log that indicate that the system user is
being used for some part of transactions which are failing.
Unfortunately I’m unable to make out cause vs effect at this point
Thanks Saikat

**Comment by Coduz** [comment]
Hi @gitsaycat ,

Can you please provide the logs of the Broker container? Remember to hide sensible data, if there is any

Regards, 

_Alberto_

**Comment by gitsaycat** [comment]
Hello Alberto
The following is an excerpt from the log - does this help?

k1.0.0M7_bro | at
org.apache.activemq.transport.mqtt.MQTTNIOTransport$1.onSelect(MQTTNIOTransport.java:72)k1.0.0M7_bro
| at
org.apache.activemq.transport.nio.SelectorSelection.onSelect(SelectorSelection.java:98)k1.0.0M7_bro
| at
org.apache.activemq.transport.nio.SelectorWorker$1.run(SelectorWorker.java:118)k1.0.0M7_bro
| at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)k1.0.0M7_bro
| at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)k1.0.0M7_bro
| at java.lang.Thread.run(Thread.java:748)k1.0.0M7_bro | 06:17:34.323
[ActiveMQ NIO Worker 8] WARN o.a.a.b.TransportConnection.Service - Security
Error occurred on connection to: tcp://172.23.0.7:36064, User not
authorized!k1.0.0M7_bro | 06:17:34.351 [ActiveMQ NIO Worker 9] INFO
o.e.k.b.c.p.KapuaSecurityBrokerFilter - User name kapua-sys - client id:
KapuaPool-1537337853551-3642965902625121280, connection id:
ID:455bec92fd7e-45057-1537329507084-1:70k1.0.0M7_bro | 06:17:34.646
[ActiveMQ NIO Worker 9] WARN org.eclipse.kapua.KapuaException - Could not
load Exception Messages Bundle for Locale en_USk1.0.0M7_bro | 06:17:34.651
[ActiveMQ NIO Worker 9] WARN o.e.k.b.c.p.KapuaSecurityBrokerFilter - User
kapua-sys not authorized (Error: kapua-sys)k1.0.0M7_bro | 06:17:34.656
[ActiveMQ NIO Worker 9] WARN o.a.a.broker.TransportConnection - Failed to
add Connection id=ID:455bec92fd7e-45057-1537329507084-1:70,
clientId=KapuaPool-1537337853551-3642965902625121280 due to {}k1.0.0M7_bro |
java.lang.SecurityException: User not authorized!k1.0.0M7_bro | at
org.eclipse.kapua.service.authentication.shiro.AuthenticationServiceShiroImpl.handleTokenLoginException(AuthenticationServiceShiroImpl.java:350)k1.0.0M7_bro
| at
org.eclipse.kapua.service.authentication.shiro.AuthenticationServiceShiroImpl.login(AuthenticationServiceShiroImpl.java:154)k1.0.0M7_bro
| at
org.eclipse.kapua.broker.core.plugin.KapuaSecurityBrokerFilter.addExternalConnection(KapuaSecurityBrokerFilter.java:412)k1.0.0M7_bro
| at
org.eclipse.kapua.broker.core.plugin.KapuaSecurityBrokerFilter.addConnection(KapuaSecurityBrokerFilter.java:395)k1.0.0M7_bro
| at
org.apache.activemq.broker.BrokerFilter.addConnection(BrokerFilter.java:98)k1.0.0M7_bro
| at
org.apache.activemq.broker.BrokerFilter.addConnection(BrokerFilter.java:98)k1.0.0M7_bro
| at
org.apache.activemq.broker.MutableBrokerFilter.addConnection(MutableBrokerFilter.java:103)k1.0.0M7_bro
| at
org.apache.activemq.broker.TransportConnection.processAddConnection(TransportConnection.java:852)k1.0.0M7_bro
| at
org.apache.activemq.broker.jmx.ManagedTransportConnection.processAddConnection(ManagedTransportConnection.java:77)k1.0.0M7_bro
| at
org.apache.activemq.command.ConnectionInfo.visit(ConnectionInfo.java:139)k1.0.0M7_bro
| at
org.apache.activemq.broker.TransportConnection.service(TransportConnection.java:336)k1.0.0M7_bro
| at
org.apache.activemq.broker.TransportConnection$1.onCommand(TransportConnection.java:200)k1.0.0M7_bro
| at
org.apache.activemq.transport.MutexTransport.onCommand(MutexTransport.java:45)k1.0.0M7_bro
| at
org.apache.activemq.transport.mqtt.MQTTInactivityMonitor.onCommand(MQTTInactivityMonitor.java:162)k1.0.0M7_bro
| at
org.apache.activemq.transport.mqtt.MQTTTransportFilter.sendToActiveMQ(MQTTTransportFilter.java:106)k1.0.0M7_bro
| at
org.apache.activemq.transport.mqtt.MQTTProtocolConverter.sendToActiveMQ(MQTTProtocolConverter.java:181)k1.0.0M7_bro
| at
org.apache.activemq.transport.mqtt.MQTTProtocolConverter.onMQTTConnect(MQTTProtocolConverter.java:310)k1.0.0M7_bro
| at
org.apache.activemq.transport.mqtt.MQTTProtocolConverter.onMQTTCommand(MQTTProtocolConverter.java:205)k1.0.0M7_bro
| at
org.apache.activemq.transport.mqtt.MQTTTransportFilter.onCommand(MQTTTransportFilter.java:94)k1.0.0M7_bro
| at
org.apache.activemq.transport.TransportSupport.doConsume(TransportSupport.java:83)k1.0.0M7_bro
| at
org.apache.activemq.transport.mqtt.MQTTCodec$1.onFrame(MQTTCodec.java:65)k1.0.0M7_bro
| at
org.apache.activemq.transport.mqtt.MQTTCodec.processCommand(MQTTCodec.java:90)k1.0.0M7_bro
| at
org.apache.activemq.transport.mqtt.MQTTCodec.access$400(MQTTCodec.java:26)k1.0.0M7_bro
| at
org.apache.activemq.transport.mqtt.MQTTCodec$4.parse(MQTTCodec.java:213)k1.0.0M7_bro
| at
org.apache.activemq.transport.mqtt.MQTTCodec$3.parse(MQTTCodec.java:179)k1.0.0M7_bro
| at
org.apache.activemq.transport.mqtt.MQTTCodec$2.parse(MQTTCodec.java:138)k1.0.0M7_bro
| at org.apache.activemq.transport.mqtt.MQTTCodec.parse(MQTTCodec.java:76)k1.0.0M7_bro
| at
org.apache.activemq.transport.mqtt.MQTTNIOTransport.processBuffer(MQTTNIOTransport.java:132)k1.0.0M7_bro
| at
org.apache.activemq.transport.mqtt.MQTTNIOTransport.serviceRead(MQTTNIOTransport.java:120)k1.0.0M7_bro
| at
org.apache.activemq.transport.mqtt.MQTTNIOTransport.access$000(MQTTNIOTransport.java:43)k1.0.0M7_bro
| at
org.apache.activemq.transport.mqtt.MQTTNIOTransport$1.onSelect(MQTTNIOTransport.java:72)k1.0.0M7_bro
| at
org.apache.activemq.transport.nio.SelectorSelection.onSelect(SelectorSelection.java:98)k1.0.0M7_bro
| at
org.apache.activemq.transport.nio.SelectorWorker$1.run(SelectorWorker.java:118)k1.0.0M7_bro
| at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)k1.0.0M7_bro
| at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)k1.0.0M7_bro
| at java.lang.Thread.run(Thread.java:748)k1.0.0M7_bro | 06:17:34.656
[ActiveMQ NIO Worker 9] WARN o.a.a.b.TransportConnection.Service - Security
Error occurred on connection to: tcp://172.23.0.7:36066, User not
authorized!k1.0.0M7_bro | 06:17:36.323 [ActiveMQ
BrokerService[message-broker] Task-205] INFO
o.a.a.broker.TransportConnection - Stopping tcp://172.23.0.7:36064 because
Failed with SecurityException: User not authorized!k1.0.0M7_bro |
06:17:36.657 [ActiveMQ BrokerService[message-broker] Task-207] INFO
o.a.a.broker.TransportConnection - Stopping tcp://172.23.0.7:36066 because
Failed with SecurityException: User not authorized!k1.0.0M7_bro |
06:17:53.890 [Camel (camelContext) thread #9 -
JmsConsumer[Consumer.eurotech:mainRoutelisteners:EXACTLY_ONCE.VirtualTopic.%3E]]
WARN o.e.k.s.d.c.rest.RestDatastoreClient - Bad request for index
'1506392079497119213-2018-38' on action 'INSERT'! POST
http://es:9200/1506392079497119213-2018-38/message?id=48fd9272-9e46-49df-8b5f-80d5db3841c4&version=1&version_type=external:
HTTP/1.1 400 Bad Request

**Comment by Coduz** [comment]
Hi @gitsaycat ,

the log you provided is a bit messy for some reasons. 

BTW it seems that some device/code is trying to connect.

I can see this line: `java.lang.SecurityException: User not authorized!k1.0.0M7_bro at`

Does the `k1.0.0M7_bro` value get used by you or some of your devices? 

Regards, 

_Alberto_

**Comment by gitsaycat** [comment]
Hello Alberto
I've attached a screen shot of the log with this post - I feel the color coding etc makes it much easier to read. You will find that the value you refer to is just the name of the container in our docker composition - and the statement is refers to kapua-sys not to 1.0.0.M7_bro label. 

To me it seems that kapua-sys is trying to do something for which it is not authorized, more than the number of times allowed - and then the system locks it out. 

As mentioned, we do not use kapua-sys directly in any client, so its not obvious where the login attempt is coming from.

Please let me know how I can help you debug.
Thanks!

![broker](https://user-images.githubusercontent.com/14805543/45857368-ecc0e080-bd8a-11e8-9938-333b1fe72aff.jpg)

**Comment by gitsaycat** [comment]
Hi Alberto
Further to my previous post please note that this stacktrace pops up as soon as I click on any of the tabs in the Devices screen - on any one of the details panes like Configuration (please see attached screen shot)
As soon as I click on configuration tab - I see the 'Device not connected..' message on the kapua UI and the stacktrace is printed into the log.

I could be wrong of course but here is the scenario I believe is taking place:
- A process dependent on kapua-sys is trying to use it constantly - failing because the user is not authorized and eventually leading to kapua-sys getting locked out
- The request-response process triggered by this UI action then fails because kapua-sys is locked out 




![kapua-screen](https://user-images.githubusercontent.com/14805543/45857807-1d097e80-bd8d-11e8-9518-8ed007ba914e.jpg)

**Comment by gitsaycat** [comment]
Yes - default password was changed through the console.
Is there still a need to follow specific steps for that?
Thanks.

**Comment by Coduz** [comment]
Hi @gitsaycat ,

Yesh, so that's why.

Currently changing the `kapua-sys` password requires a restart of all containers. To the containers you should provide also the new password as environment variable override.

Value to override is: `transport.credential.password` 

We have plans to make this independent and more flexible in the future.

Regards, 

_Alberto_

**Comment by gitsaycat** [comment]
If it helps I can open an issue for this topic?

**Comment by lukas-bender-rodriguez** [comment]
Hi @gitsaycat, 

can you share the related part of your docker configuration. I'm a little unsure of what "provide also the new password as environment variable override" exactly means. Just adding:

```-e transport.credential.password=mynewpassword```  to the docker run command of each container?

I'm a bit confused due to #1475. 

Thanks!

**Comment by gitsaycat** [comment]
Hi @lukas-bender-rodriguez the following is a part of my docker-compose for the console - it shows how I'm using the environment variable:
```

 kapua-console:
    image: kapua/kapua-console:1.0.0-M7
    container_name: k1.0.0M7_con
    ports:
        - 8080:8080
    depends_on:
        - broker
        - db
        - es
        - events-broker
    environment:
        - 'transport.credential.password=<my-password>'
    logging:
        driver: "json-file"
        options:
            max-size: "200k"
            max-file: "10"
```

**Comment by lorthirk** [comment]
Also, please note that a solution has been already proposed in #2082, but in this current implementation, only the Kapua MQTT Client will be able to connect with the specified username... so it still needs some work. Anyway, just for testing purposes, you could give it a try to see if your scenarios are covered.

**Comment by aycanvargun** [comment]
> Hi @gitsaycat ,
> 
> Yesh, so that's why.
> 
> Currently changing the `kapua-sys` password requires a restart of all containers. To the containers you should provide also the new password as environment variable override.
> 
> Value to override is: `transport.credential.password`
> 
> We have plans to make this independent and more flexible in the future.
> 
> Regards,
> 
> _Alberto_

Hi, I have some doubts about security. Can't I change  or update kapua-sys's or kapua-broker's password when containers are running? If I can't, when someone knows my server's IP, he can reach to my Kapua by trying ports, then he can enter to kapua-sys or kapua-broker account.

**Comment by aycanvargun** [comment]
@Coduz 

Hi, I have some doubts about security. Can't I change or update kapua-sys's or kapua-broker's password when containers are running? If I can't, when someone knows my server's IP, he can reach to my Kapua by trying ports, then he can enter to kapua-sys or kapua-broker account.

**Comment by Coduz** [comment]
Hi @aycanvargun ,

sorry for the late answer.

Yeah currently that is the case. `kapua-sys` password must be changed when all containers are stopped.

There is a pull request that should change this (https://github.com/eclipse/kapua/pull/2082) but the development has been stopped for now and we are waiting to pick that item again.

Regards, 

_Alberto_

**Comment by gitsaycat** [comment]
hi @aycanvargun - not directly related to the topic - but if you're running docker containers for your kapua system, you should be able to isolate your broker etc fairly well. The passwords are for the interlinked kapua containers, which should be private.
Not ideal but not fully open and accessible to the internet as such
