### ISSUE TITLE
Incomplete Title Of Permissions Delete Dialog In Roles

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#2035]
When user revokes permission from a role, the title is: _**Revoke permission: [domain] [Action]**_, there is no [Group] and [Forwardable] paramter in the title. 
Is uggest these paramteres get added (if possible) or we completely remove the paramters, so the title would be like in Users (Screenshot No. 2).

Also the text for revoking permissions in Users and in Roles is not unified. I suggest we change the text in Roles to "Revoke the permission from the user?" (like it is in Users). 

**Testflow:**
1. Login as kapua-sys
2. Go to Roles and add a role (e.g. role1)
3. Select role1 and add a permission to it
4. Select the added permission and delete it
**Observe the Title and the text in the Delete permission dialog box.**

**Expected behavior**
Title should consist Action, Domain and Group paramteres (and also Forwardable, if possible) or there should be no parameters listed (as when revoking permission from a user - screenshot No. 2). 

**Screenshot No. 1:**
![screen shot 2018-09-20 at 09 14 46](https://user-images.githubusercontent.com/15121999/45805038-00524580-bcbe-11e8-868d-b7839e2df9dd.png)

**Screenshot No. 2:**
![screen shot 2018-09-20 at 10 17 24](https://user-images.githubusercontent.com/15121999/45805181-663ecd00-bcbe-11e8-93cc-18df9de97caf.png)

**Version of Kapua**
1.0.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 68.0.3440.106 (Official Build) (64-bit))
- Safari (Version 11.1.2 (13604.3.5))
- Mozilla Firefox (61.0.2 (64-bit))
- Opera (Version 55.0.2994.44)

**Comment by ct-goranpalibrk** [comment]
Hello @Coduz @lorthirk  I have one question for this issue. If we want to display Action, Domain and Group values in header message, then I have to make new method in KapuaDialog (because that is "base" class in which header messages are made) with 3 String parametres. But then, we have to override that method in all other delete dialogs. So, do you have any other suggestions about this issue?

**Comment by lorthirk** [comment]
@ct-goranpalibrk what is preventing you to simply compose the correct message in (as an example) `RolePermissionDeleteDialog` using all the fields from `GwtRolePermission`?

**Comment by ct-goranpalibrk** [comment]
@lorthirk I was looking into wrong class, I feel ashamed :)

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
