### ISSUE TITLE
xxx cannot be resolved to a type

### ISSUE THREAD

**Issue by Brianxia** [eclipse/kapua#2044]
hi, 

After I imported kupua project into Eclipse, I got a lot of erros as below screenshot; I guess there are some classes missing?
![errors](https://user-images.githubusercontent.com/4273991/45920209-a190f580-be90-11e8-836b-85b8138d1000.JPG)

thank you very much.

**Comment by Brianxia** [comment]
Is there anyone who can tell me how to fix it? thank you very much.

**Comment by lorthirk** [comment]
I'm closing this for now. Feel free to reopen it if you further informations.
