### ISSUE TITLE
Undefined API_KEY

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#2048]
When user creates an API_KEY credential in Users, Kapua reports "undefined" instead of a proper API_KEY (look at the screenshot). 

**Testflow:**
1. Login as kapua-sys or any other user that has proper permissions
2. Go to users, create a user (e.g. user0) 
3. Select user0, go to its Credentials and create an API_KEY
**Observe the error. **

**Expected behavior**
Kapua should return a proper API_KEY. 

**Screenshot:**
![screen shot 2018-09-24 at 10 47 47](https://user-images.githubusercontent.com/15121999/45944159-6ce48180-bfe9-11e8-86fb-9c841b1333d3.png)

**Version of Kapua**
1.0.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 68.0.3440.106 (Official Build) (64-bit))
- Safari (Version 11.1.2 (13604.3.5))
- Mozilla Firefox (61.0.2 (64-bit))
- Opera (Version 55.0.2994.44)

**Comment by lorthirk** [comment]
This is because of #2024. I will fix it soon.

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been successfully resolved.
