### ISSUE TITLE
Database schema: act_account table / parent_account_path length issue

### ISSUE THREAD

**Issue by andrejn-ct** [eclipse/kapua#205]
There is a possible inconsistency in the **act_account** table, specifically the **parent_account_path** field.
The current create script (**act_account_create.sql**) defines this field as a **VARCHAR(64)**. Given that there is no limit to the depth of sub-account creation this seems to be too short.
Specifically, this length is exceeded even with an account tree 3 levels deep. An example is as follows.
When creating 3 account levels, the resulting parent path is
'\1/-4796103609285693743/-4305601355848753009/-1017280879925618445'
Please note that this string is 65 characters long and as such it causes an JdbcSQLException.
As it looks it seems that this inconsistency was introduced when the old (and shorter) IDs were replaced with the new BigInteger (far longer) IDs.

**Comment by Coduz** [comment]
Hi @andrejn-ct ,

This should have fixed the problem. 1024 is enough for ~50 levels, which is a reasonably good number.

Regards,

_Alberto_
