### ISSUE TITLE
Account Service: double check the parent_account_path handling

### ISSUE THREAD

**Issue by andrejn-ct** [eclipse/kapua#206]
The construction of the parent_account_path in the account service (**org.eclipse.kapua.service.account.internal**) seems suspicious. When creating a chain of accounts such as **root->parent->child** the resulting parent path is **\1/ParentId/ChildId** (i.e. **'\1/8796103609285693743/-4305601355848753009**).
This raises two concerns. 
Firstly, the root account is simply 1, instead of the otherwise used BigInteger representation.
Secondly, the child account ID is included in the parent path. This is somewhat counter-intuitive, given the name of the field.

**Comment by Coduz** [comment]
This was fixed in dbf7fc2950873557307cb49a6561e6039d7b89b1
