### ISSUE TITLE
Parent Account Name In Settings -> Edit Not Correct

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#2066]
Parent Account name parameter is repaced with Account's name (Look at the screenshot).

**Testflow:**
1. Login as kapua-sys or any other user that has proper permissions
2. Go to Child Accounts, create an account (e.g. account0)
3. Add a user to account0 (e.g. user0) and add ALL:ALL:ALL:YES permission to it
4. Login as user0 and go to Settings -> Edit
**Parent Account parametere contins wrong name.**

**Expected behavior**
Parent account should have the correct name. 

**Screenshot (Parent account name here should be "kapua-sys" and not "123"):**
![screen shot 2018-09-28 at 13 47 28](https://user-images.githubusercontent.com/15121999/46208367-c7a01500-c32a-11e8-8c62-ec66bca8245e.png)

**Version of Kapua**
1.0.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 68.0.3440.106 (Official Build) (64-bit))
- Safari (Version 11.1.2 (13604.3.5))
- Mozilla Firefox (61.0.2 (64-bit))
- Opera (Version 55.0.2994.44)

**Comment by Coduz** [comment]
Closing this.
https://github.com/eclipse/kapua/pull/2062 has removed it.

**Comment by LeoNerdoG** [comment]
I have verified that this isseu has been resolved.
