### ISSUE TITLE
Database schema: General issue with IDs

### ISSUE THREAD

**Issue by andrejn-ct** [eclipse/kapua#207]
There is a general issue regarding the ID fields in the database.
The table creation scripts define all IDs as BIGINT(21) UNSIGNED (i.e. **scope_id    BIGINT(21)  UNSIGNED NOT NULL**).
Nevertheless it is possible to create an ID from a negative integer (i.e. **new KapuaEid(BigInteger.valueOf(-1))**) and the database will not complain. Searching the database with such ID is also successful.
This is somewhat counter-intuitive, as the field definition seems to imply that IDs with negative values should be rejected by the database.

**Comment by Coduz** [comment]
Hi @andrejn-ct ,

According to the [documentation](http://www.h2database.com/html/datatypes.html#bigint_type) It seems that H2 does not support the `UNSIGNED` keyword.

I'll try to add a `CHECK` clause to solve this.

Regards, 

_Alberto_
