### ISSUE TITLE
Kapua Develop Branch Does Not Build

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#2077]
Today I have deleted the .m2 repository and built Kapua from scratch (following the procedure [here](https://github.com/eclipse/kapua/blob/develop/docs/kuraKapuaDocs.md). As you can see bellow, there is a problem on project _**kapua-client-gateway-feature-karaf.**_

**Testflow:**
1. Delete the .m2 repository from home folder
2. Go to Kapua folder, checkout the develop branch and pull the changes (git pull <remote-branch> develop)
3. Run command _mvn clean install -f external/pom.xml_ (this is completed successfully)
4. Run command _mvn clean install -DskipTests_
**Build stops at point described above.**

**Expected behavior**
Build should be successfull. 

**Screenshot:**
<img width="1415" alt="screen shot 2018-10-03 at 09 33 37" src="https://user-images.githubusercontent.com/15121999/46396301-4e6c3d80-c6ef-11e8-9759-9d539a18a6fd.png">

**Version of Kapua**
1.0.0-SNAPSHOT

**Comment by Coduz** [comment]
I've found something on this: https://issues.apache.org/jira/browse/MINSTALL-152

**Comment by LeoNerdoG** [comment]
I am using Apache Maven 3.5.0

**Comment by Coduz** [comment]
I'm using maven 3.5.4 and 3.5.3 and the error still occur.
But downgrading `maven-install-plugin` version to `2.5.2` makes everything work.

```
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-install-plugin</artifactId>
                <version>2.5.2</version>
            </plugin>
```  

Adding this to the `build` section of the module will solve temporally the problem. I'll search the correct configuration for `maven-install-plugin` with `3.0.0-M1` version

**Comment by Coduz** [comment]
Just looking at the "old" builds, 

https://travis-ci.org/eclipse/kapua/jobs/436127969
https://hudson.eclipse.org/kapua/job/develop/386/consoleFull

the `maven-install-plugin` used was version `2.4`

```
[INFO] --- maven-install-plugin:2.4:install (default-install) @ kapua ---
[INFO] Installing /home/travis/build/eclipse/kapua/pom.xml to /home/travis/.m2/repository/org/eclipse/kapua/kapua/1.1.0-SNAPSHOT/kapua-1.1.0-SNAPSHOT.pom
```

But now, building a Kapua with a clean `.m2` results in a different version: `3.0.0-M1`

```
[INFO] --- maven-install-plugin:2.4:install (default-install) @ kapua ---
[INFO] Installing /Users/alberto.codutti/dev/git/kapua/develop/pom.xml to {somePath}/.m2/repository/org/eclipse/kapua/kapua/1.1.0-SNAPSHOT/kapua-1.1.0-SNAPSHOT.pom
```

This version seem have some changes that are not compatible with our current configurations.
The `3.0.0-M1` version has been release on 23rd September 2018. It is likely that by default  Maven uses the `LATEST` or `RELEASE` keywords when specifying the `maven-install-plugin` version and so, if you clean the `.m2` repo you'll get the newest version of the plugin, which is now `3.0.0-M1`.

I will set the version of the plugin at the latest `2.x` version (currently `2.5.2`) for all projects.

**Comment by Coduz** [comment]
Upon further investigation, for some reasons only modules under `kapua-client` are affected by this... I was not able to find why this happens BTW

**Comment by Coduz** [comment]
Found more resources on this:

https://support.mulesoft.com/s/article/Mule-Maven-Plugin-fails-during-deploy-with-error-Failed-to-execute-goal-org-apache-maven-plugins-maven-deploy-plugin-3-0-0-M1-deploy

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been successfully resolved.
