### ISSUE TITLE
Disabled Tabs On Connected Device

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#2081]
If user adds another cloudService (e.g. org.eclipse.kura.cloud.CloudService-2), enters all the correct parameters and then connects to Kapua, _**Packages, Bundles, Configuration**_ and _**Command**_ tabs are disabled. 

**Testflow:**
1. Login as kapua-sys
2. Connect a live Kura device to Kapua (e.g. device0)
3. On device0, create another cloudService (e.g. org.eclipse.kura.cloud.CloudService-2), enter the correct credentials and connect to Kapua (change the name of device to e.g. device2)
4. In Kapua go to Devices, select device2 and observe the disabled tabs.

**Expected behavior:**
If device is connected, all the tabs should be enabled. 

**Screenshot:**
![screen shot 2018-10-04 at 13 14 40](https://user-images.githubusercontent.com/15121999/46470635-9e263400-c7d7-11e8-8fe4-dd6b0fc24d30.png)

**Version of Kapua**
1.1.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 68.0.3440.106 (Official Build) (64-bit))
- Safari (Version 11.1.2 (13604.3.5))
- Mozilla Firefox (61.0.2 (64-bit))
- Opera (Version 55.0.2994.44)

**Comment by ClementChotard** [comment]
I have a similar problem. 
In my setup I only miss Packages and Bundles tab in Kapua interface. I also deleted the "org.eclipse.kura.cloud.CloudService" connection service and can't create it any more (with this exact name)

**Screenshot:**
![Kapua_screenshot](https://user-images.githubusercontent.com/39368988/55711632-5c2bb400-59ed-11e9-9e53-fb7742300f1e.png)

**Comment by lorthirk** [comment]
Hi @ClementChotard,

It looks like the Kura client is only advertising CONF-V1, CMD-V1 and ASSET-V1 as available applications when connecting to Kapua. Have you checked the BIRTH event in the Events tab?

**Comment by ClementChotard** [comment]
That's correct. DEPLOY-V2 is missing. In the BIRTH message there is only:
```
getApplicationIdentifiers()=CONF-V1,CMD-V1,ASSET-V1
```

**Comment by lorthirk** [comment]
So the problem is that DEPLOY-V2 is not running in Kura. Kapua disables those tabs because DEPLOY-V2 would be required for them to work.

**Comment by ClementChotard** [comment]
Is there a way to enable DEPLOY-V2 in Kura? I can't find any... Shouldn't it be activated by default?

**Comment by lorthirk** [comment]
Yes, it should. Since the issue is most likely on Kura, the best thing to do is to file an issue in [eclipse/kura](https://github.com/eclipse/kura)

**Comment by LeoNerdoG** [comment]
I am closing this due to upper comment.

**Comment by activey** [comment]
@LeoNerdoG did you resolve it somehow? I cant find any ticket in eclipse/kura repo for that ...

**Comment by LeoNerdoG** [comment]
Hey @activey,
I have reported this now](https://github.com/eclipse/kura/issues/2556).
I have to be honest with you and say that I haven't been using Kapua a lot lately so I kind of forgot on this. 
If this is a blocker for you, please refer to [Eclipse/Kura](https://github.com/eclipse/kura) project - they should be able to help you fast.

**Comment by activey** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: #646464;}                                                                                                                                        Hey, Many thanks for pushing it forward. BR                                                                                                                                                                          Od: notifications@github.comWysłano: 15 października 2019 13:44Do: kapua@noreply.github.comOdp. do: reply@reply.github.comDW: activey@doaplatform.org; mention@noreply.github.comTemat: Re: [eclipse/kapua] Disabled Tabs On Connected Device (#2081)  Hey @activey,
I have reported this now](eclipse/kura#2556).
I have to be honest with you and say that I haven't been using Kapua a lot lately so I kind of forgot on this.
If this is a blocker for you, please refer to Eclipse/Kura project - they should be able to help you fast.
