### ISSUE TITLE
Travis tests random fails

### ISSUE THREAD

**Issue by lorthirk** [eclipse/kapua#2088]
A lot of Travis builds are failing due to random errors in tests. Usually retrying the job some times fixes the builds, but this is not always the case. Also, the same branch may fail on a fork while building correctly on others.

**To Reproduce**
1. Launch a build in Travis
2. Check build results

**Expected behavior**
The build result should be consistent across the same branch in all forks 

**Screenshots**
N/A

**Version of Kapua**
1.0.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[ ] Docker
[ ] Openshift (in its variants) 
[x] Others - Travis

**Main component affected**
[ ] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[X] - Others

**Additional context**
Travis logs of failing builds are more than welcome. The more we collect, the better should be to identify the cause

**Comment by lorthirk** [comment]
Here's the log of a failing build on my fork. Please note that EVERY build on my fork has failed so far for various reasons.

[log.txt](https://github.com/eclipse/kapua/files/2450199/log.txt)

**Comment by muros-ct** [comment]
sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install oracle-java8-installer" failed and exited with 100 during .

Travis can not install java!

**Comment by Coduz** [comment]
Hi all,

is this still an issue? Or we can close it? 

Regards, 

_Alberto_

**Comment by LeoNerdoG** [comment]
Hi @Coduz,
I have been following tests on Travis regarding PRs and for now it looks ok. We have to restart maybe one or two tests every month (which is negelctable in my opinion) but I think it is safe to say that tests now do not fail when we create PRs, so I think this can be closed.
