### ISSUE TITLE
Package Installation Problem

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#2115]
If user enteres slash symbol ("/") in Package Name or Package Version, package does not get installed on Kura device. I have also tried with other special symbols but found that only this one is problematic. 

**Testflow:**
1. Login as kapua-sys or any other user that has proper pemrissions
2. Connect a live Kura device to Kapua (e.g device0)
3. Go to Devices, select device0 and go to its Packages. From Eclipse Marketplace copy URL "http://download.eclipse.org/kura/releases/3.2.0/org.eclipse.kura.example.publisher_1.0.300.dp" and paste it into "Package URL". 
4. In package Version and into Package Name enter first only "123". Package should be successfully installed. 
5. Now try to enter only slash "/" symbol on one, other or both fields. Kapua will report that "packages install request has been sent to device" but in kura device logs you can see an error.

**Expected behavior**
Either package should be installed without problems or special symbosl should not be permitted in package Name and Package Version (or Kapua should report that there are unpermitted symbols in the installation fields).

**Screenshot No. 1:**
![screen shot 2018-10-15 at 10 48 25](https://user-images.githubusercontent.com/15121999/46939897-be6fb180-d067-11e8-9fa7-aa6e1004a985.png)

**Screenshot No. 2:**
![screen shot 2018-10-15 at 10 49 11](https://user-images.githubusercontent.com/15121999/46940043-14445980-d068-11e8-94c5-673bd2e2b879.png)

**Screenshot No. 3:**
<img width="1386" alt="screen shot 2018-10-15 at 10 50 34" src="https://user-images.githubusercontent.com/15121999/46940048-160e1d00-d068-11e8-9328-5dbac2129c53.png">

**Version of Kapua**
1.1.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 68.0.3440.106 (Official Build) (64-bit))
- Safari (Version 11.1.2 (13604.3.5))
- Mozilla Firefox (61.0.2 (64-bit))
- Opera (Version 55.0.2994.44)

**Comment by Coduz** [comment]
On this, we can add some validation, but I think that the device should return an error at the beginning.

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
