### ISSUE TITLE
Retrieval of sorted messages via REST

### ISSUE THREAD

**Issue by markoer** [eclipse/kapua#2123]
**Describe the bug**
If we have too much data in Kapua (> 10000 entries), its REST API doesn’t allow us to get the last sent payload. But it does allow to get the first. In web UI the logic is reversed – we can only get the most recent 10000 entries. A solution where sort order would be requested doesn't work i.e. still returns oldest messages in ascending order.

**To Reproduce**
1. Connect a device to Kapua
2. Fill some data e.g. 10 messages by Kura's ExamplePublisher
3. Authenticate and fetch 5 most recent messages through REST:
```
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Authorization: Bearer <fill it>' -d '{
  "limit": 5,
  "scopeId": {
    "id": "<fill it>"
  },
  "predicate": {},
  "fetchAttributes": [
    "string"
  ],
  "fetchStyle": "FIELDS",
  "askTotalCount": true,
  "sortFields": [
    {
      "sortDirection": "DESC",
      "field": "sentOn"
    }
  ],
  "offset": 0
}' 'https://<host>/v1/<fill it>/data/messages/_query'
```

**Expected behavior**
Messages are returned in descending order of `sentOn` i.e. most recent first.

**Screenshots**
In web UI results up to now are available. Result from REST instead of screenshots:
```
{
  "type": "storableListResult",
  "limitExceeded": false,
  "size": 5,
  "items": [
    {
      "type": "jsonDatastoreMessage",
      "capturedOn": "2018-10-04T08:34:30.651Z",
      "channel": {
        "semanticParts": [
          "heater",
          "data"
        ]
      },
      "clientId": "B8:27:EB:33:A7:1A",
      "deviceId": "PZtzsLMAPXQ",
      "payload": {
        ...
      },
      "receivedOn": "2018-10-04T08:39:09.009Z",
      "scopeId": "...",
      "sentOn": "2018-10-04T08:34:30.651Z",
      "datastoreId": "6d6d2707-1534-4631-9ca0-c21128f62215",
      "timestamp": "2018-10-04T08:34:30.651Z"
    },
    {
      "type": "jsonDatastoreMessage",
      "capturedOn": "2018-10-04T08:34:31.649Z",
      "channel": {
        "semanticParts": [
          "heater",
          "data"
        ]
      },
      "clientId": "B8:27:EB:33:A7:1A",
      "deviceId": "PZtzsLMAPXQ",
      "payload": {
        ...
      },
      "receivedOn": "2018-10-04T08:39:10.055Z",
      "scopeId": "...",
      "sentOn": "2018-10-04T08:34:31.649Z",
      "datastoreId": "733e0c40-e8c8-44c2-aab0-49507d9e4e8e",
      "timestamp": "2018-10-04T08:34:31.649Z"
    },
    <additional 3 more recent messages>
  ]
}
```

**Version of Kapua**
current

**Main component affected**
[ ] REST API

**Comment by lorthirk** [comment]
Hi,

#2121 is supposed to fix this. You could try that one and see if it fits your needs.

**Comment by LeoNerdoG** [comment]
Hi @lorthirk,
I have tested this within your PR #2121 and it successfully fixes it. So from this issue's point of view PR #2121 can be merged (I haven't tested anything else though).
