### ISSUE TITLE
Wrong Error Messages In Devices -> Configuration

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#2124]
This issue is made of 4 very similar issues.
First part of this issue contains a list of fields where "For input String..." error appears. I suggest this error gets removed and is replaced with something more useful for end user. 

Simple Artemis MQTT Broker:
 - MQTT Port

ClockService:
 - clock.ntp.host

CommandService:
 - command.timeout

DataService:
 - connect.retry-interval
 - connection.recovery.max.failures
 - disconnect.quiesce.timeout
 - store.housekeeper-interval
 - store.purge-age
 - store.capacity
 - in-flight-messages.max-number
 - in-flight-messages.congestion-timeout
 - rate.limit.average
 - rate.limit.time.unit
 - rate.limit.burst.size

MQTTDataTransport:
 - keep-alive
 - timeout

WatchdogService:
 - watchdog refresh interval

Second part of this issue contains a list where the errors are not clear/descriptive enaugh for end user ("value must be smaller than 256"). I suggest we modify these messages to be more descriptive. 

Simple Artemis MQTT Broker:
 - MQTT Address
 - User Name

ActiveMQ Artemis Broker:
 - Broker XML
 - Required Protocols
 - User Configuration 
 - Defualt User name 

ClockService:
 - clock.ntp.port
 - clock.ntp.timeout
 - clock.ntp.max-retry
 - clock.ntp.retry.interval
 - clock.ntp.refresh-interval

DeploymentService:
 - downloads.directory
 - deployment.hook.associations

CloudService:
 - device.custom-name
 - topic.control-prefix

CommandService:
 - command.working.directory
 - command.environment

WebConsole:
 - console.password.value

DataService
 - store.db.service.pid

H2DbService
 - db.connector.url
 - db.user

MQTTDataTransport:
 - broker-url
 - topic.context.account-name
 - username
 - iwt.topic
 - iwt.payload
 - ssl.default.protocol
 - ssl.default.cipherSuites
 - ssl.certificate.alias

RestService:
 - user.name (all three fields)
 - roles (all three fields)

SSLManagerService
 - ssl.default.protocol
 - ssl.default.trustStore
 - ssl.default.cipherSuites

WatchdogService:
 - Watchdog device path
 - Reboot Cause File Path

CamelXML router
 - Javascript init code

Third part of this issue contains a list of fields where there is no error at all (these are password fields) which errors should be specific enaugh so user could understand them (and also compatible with Kura error messages and rules):

 - Password of the user in "Simple Artemis MQTT Broker"
 - command.password.value in "CommandService"
 - console.password.value in "WebConsole"
 - password in "MQTTDataTransport"
 - password (all three fields) in "RestService"
 - ssl.keystore.password in "SSLManagerService"

Special case are error messages in PositionService. if user enters invalid numbers into these fields, kapua reports: "The maximum value for this field is 1.7976931348623157e+308" which is wrong, since position coordinates cannot accept such long number (Screenshot No. 3)

**Testflow:**
1. Login as kapua-sys 
2. Connect a live Kura device to Kapua (e.g device0)
3. Go to Devices and 

**Expected behavior**

**Screenshot No. 1 (Example of "value must be smaller than 256" error):**
![screen shot 2018-10-16 at 11 09 53](https://user-images.githubusercontent.com/15121999/47005456-18d64400-d134-11e8-8510-6cf236104a1c.png)

**Screenshot No. 2 ("Example of "Error for string..." error):**
![screen shot 2018-10-16 at 11 11 01](https://user-images.githubusercontent.com/15121999/47005457-1aa00780-d134-11e8-8168-589c1a0af947.png)

**Screenshot No. 3 (Example of PositionService error messages):**
![screen shot 2018-10-16 at 11 09 03](https://user-images.githubusercontent.com/15121999/47005320-ca28aa00-d133-11e8-8529-2f5cb51b41dd.png)

**Version of Kapua**
1.1.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 68.0.3440.106 (Official Build) (64-bit))
- Safari (Version 11.1.2 (13604.3.5))
- Mozilla Firefox (61.0.2 (64-bit))
- Opera (Version 55.0.2994.44)

**Comment by muros-ct** [comment]
@Coduz and @lorthirk this is open topic for a very long time. How to handle validation of configuration data that comes from Kura device. This configuration data is based on key / value pairs. I am not sure about the type of data.
This becomes problematic, as kapua UI is created based on these k/v pairs. This doesn't allow any value validation on kapua side, and this brings all the issues described.

What shall we do? Should we bring in some kind of validator information, that would be send from kura configuration? I can't see any other option, all assumptions on kapua side just add more problems.

Any ideas?

**Comment by Coduz** [comment]
Hi all, 

on this, only the device actually knows how to validate that data and what those fields actually means. For us, they are just a list of entries that have `names` `type` and a `value`. Kura sends some metadata about minimal validation, but we don't have any other useful data (e.g. on a "url" field that it must be an URL, since for us is only a `String` field named `url`.

So we need Kura to provide those informations.

Regards, 

_Alberto_

**Comment by LeoNerdoG** [comment]
I am closing this due to upper comment.
