### ISSUE TITLE
"CamelXML router" Fields Not Limited

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#2125]
Three fields in Device -> Configuration -> CamelXML router are not limited so Kapua can effectievely stop working - I suggest we limit these fileds in order to prevent Kapua from crashing.

**Testflow:**
1. Login as kapua-sys or any other user that has proper permissions
2. Connect a live Kura device to Kapua (e.g. device0)
3. Select device0 in Devices and go to Configurations -> CamelXML router
4. Observe the "Router XML", "Required Camel Components" and "Clude Service Mappings" fields - they are not limited.

**Expected behavior**
All the fields mentioned above should be somehow limited. 

**Screenshot:**
![screen shot 2018-10-16 at 13 23 52](https://user-images.githubusercontent.com/15121999/47015030-3c0ced80-d14c-11e8-8ae6-e1e79024087e.png)

**Version of Kapua**
1.1.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 68.0.3440.106 (Official Build) (64-bit))
- Safari (Version 11.1.2 (13604.3.5))
- Mozilla Firefox (61.0.2 (64-bit))
- Opera (Version 55.0.2994.44)

**Comment by ct-anaalbic** [comment]
@Coduz Can you please tell me which limit is good solution for this fields in issue? 
Thanks.

Regards.

**Comment by LeoNerdoG** [comment]
Hey @coduz,
do you have any ideas regarding this matter? 

Leo

**Comment by Coduz** [comment]
Hi all, 

on this I don't think that there is a reasonable limit. It's a Javascript-type field so it can be as long as the user needed. If we really want to put a limit, set it very high! Or otherwise refer to the max length on the metadata of the config component.

Regards, 

_Alberto_

**Comment by LeoNerdoG** [comment]
I am closing this due to upper comment - because it is Javascript type field, its limit is very high.
I tried to test fix for this couple of times (made by @ct-anaalbic) but everytime Kapua craashed.

I think the best thing here is to leave things as they are.
