### ISSUE TITLE
Merging "Info" and "Welcome" Tabs

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#2126]
I suggest we merge Welcome and Info tabs into one, as Info tab contains almots all the info that is also in Welcome tab.

**Testflow:**
1. Login as kapua-sys or any other user that has proper permissions
2. Go to Welcome and Info tabs and observe the similarities.

**Expected behavior**
Welcome and Info tabs should be merged into one.

**Screenshot No. 1 (Welocme tab):**
![screen shot 2018-10-16 at 13 48 09](https://user-images.githubusercontent.com/15121999/47014269-06ff9b80-d14a-11e8-9341-2358a976375c.png)

**Screenshot No. 2 (Info tab):**
![screen shot 2018-10-16 at 13 48 04](https://user-images.githubusercontent.com/15121999/47014263-0404ab00-d14a-11e8-8795-0f8f5f7d6a65.png)

**Version of Kapua**
1.1.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 68.0.3440.106 (Official Build) (64-bit))
- Safari (Version 11.1.2 (13604.3.5))
- Mozilla Firefox (61.0.2 (64-bit))
- Opera (Version 55.0.2994.44)

**Comment by Coduz** [comment]
Hi @LeoNerdoG ,

those two views have different purposes. 

I personally wouldn't merge them.

Regards, 

_Alberto_

**Comment by LeoNerdoG** [comment]
Hi @Coduz, what different purposes do you have in mind? I know that maybe a single page could be a bit "overcrowded" but I think it would be nice. 
Nevertheless - do you have any detailed idea(s) about these tabs and why not to merge them?

Regards,
Leo

**Comment by LeoNerdoG** [comment]
After our meeting where we discused this I am closing this - @lorthirk can you please add "NOT AN ISSUE" label to it? 

Thank you!
