### ISSUE TITLE
Kapua Build Failing On "kapua-assembly-jetty-base"

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#2139]
When today I tried to build Kapua, an error poped up saying: 
`'/bin/sh -c useradd -u 1000 -g 0 -d '/var/opt/jetty' -s '/sbin/nologin' jetty &&     mkdir -p /opt/jetty /var/opt/jetty/lib/ext /var/opt/jetty/start.d /var/opt/jetty/tls &&     curl -Ls https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-distribution/9.4.12.v20180830/jetty-distribution-9.4.12.v20180830.tar.gz -o /tmp/jetty.tar.gz &&     tar --strip=1 -xzf /tmp/jetty.tar.gz -C /opt/jetty &&     rm -f /tmp/jetty.tar.gz &&     cd /var/opt/jetty &&     java -jar /opt/jetty/start.jar --approve-all-licenses --create-startd --add-to-start=http,http2,https,jsp,jstl,websocket,deploy,logging-logback,jmx,ssl,stats &&     chown -R 1000:0 /opt/jetty /var/opt/jetty &&     chmod -R g=u /opt/jetty /var/opt/jetty returned a non-zero code: 247'
`
I tried on three different machines and all three produced same result. 

**Testflow:**
1. Delete the .m2/ repository
2. Checkout kapua/develop branch 
3. Pull latest changes from kapua/develop
4. Run `mvn clean install -f external/pom.xml` command
5. Run `mvn clean install -DskipTests -Pconsole,docker` command
**Build fails at "kapua-assembly jetty-base".**

**Expected behavior**
Build should not fail. 

**Screenshots**
![screenshot 2018-10-23 at 09 35 33](https://user-images.githubusercontent.com/15121999/47345005-05822600-d6aa-11e8-9b7c-88a47ff6786a.png)

**Version of Kapua**
1.1.0-SNAPSHOT

**Type of deployment**
[x] Docker
[x] Openshift (in its variants) 
[x] Others

**Main component affected**
[x] Build

**Comment by lorthirk** [comment]
Nothing changed in that regard recently. I think it could be a temporary error in downloading Jetty.

**Comment by Coduz** [comment]
Lets see if this disappear with the time.

I think that we can create an issue to provide multiple mirrors for download resources.

**Comment by lorthirk** [comment]
After some investigation I think I found the root cause. It's not about downloading Jetty, but the startup of Jetty itself is failing:

```
java.lang.IllegalStateException: Cannot read file: modules/alpn-impl/alpn-1.8.0_191.mod
	at org.eclipse.jetty.start.Modules.registerModule(Modules.java:202)
	at org.eclipse.jetty.start.Modules.enable(Modules.java:355)
	at org.eclipse.jetty.start.Modules.enable(Modules.java:360)
	at org.eclipse.jetty.start.Modules.enable(Modules.java:377)
	at org.eclipse.jetty.start.Modules.enable(Modules.java:377)
	at org.eclipse.jetty.start.Modules.enable(Modules.java:286)
	at org.eclipse.jetty.start.BaseBuilder.build(BaseBuilder.java:129)
	at org.eclipse.jetty.start.Main.start(Main.java:435)
	at org.eclipse.jetty.start.Main.main(Main.java:77)

Usage: java -jar $JETTY_HOME/start.jar [options] [properties] [configs]
       java -jar $JETTY_HOME/start.jar --help  # for more information
```

This happens because OpenJDK has been upgraded on yum, the CentOS repository manager. Now the latest available version is 1.8.0_191, but Jetty has no related ALPN module among its modules. I'm going to file a new issue in Jetty; in the meanwhile we could fix it with a workaround:

```
ln -s /opt/jetty/modules/alpn-impl/alpn-1.8.0_181.mod /opt/jetty/modules/alpn-impl/alpn-1.8.0_191.mod
```
since `alpn-1.8.0_181.mod` is the latest ALPN module in Jetty.

**Comment by lorthirk** [comment]
Reported issue at eclipse/jetty.project#3028

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been successfully resolved.
