### ISSUE TITLE
Kapua-sys Account Can Have Expiration Date

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#2149]
For now kapua-sys user cannot have an expiration Date as this is root user. On the other hand, kapua-sys account can have an Expiration Date, which is (in my opinion) dangerous as user can accidentally set Expiration date in the past and then everything gets locked. 
I suggest we disabled the Expiration Date field for kapua-sys user or at least show error if anything is entered in the field. 

**Testflow:**
1. Login as kapua-sys
2. Go to Settings view and try to set an Expiration date 
**kapua does not return any kind of error.**

**Expected behavior**
I suggest we disabled the Expiration Date field for kapua-sys user or at least show error if anything is entered in the field. 

**Screenshot:**
![screenshot 2018-10-26 at 11 56 44](https://user-images.githubusercontent.com/15121999/47561467-a0ce0200-d91b-11e8-802f-061c7bcd9743.png)

**Version of Kapua**
1.1.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 69.0.3497.100 (Official Build) (64-bit))
- Safari (Version 12.0 (13604.3.5))
- Mozilla Firefox (63.0 (64-bit))
- Opera (Version 55.0.2994.44)

**Comment by lorthirk** [comment]
Does this happen in REST API as well?

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
