### ISSUE TITLE
How to send device information and data payload to Kapua via MQTT protocol?

### ISSUE THREAD

**Issue by jiekechoo** [eclipse/kapua#2153]
I have a smart device (like esp8266), want to send device info and data payload (custom json payload format) to Kapua, is there any simple device management protocol? and, I want to save data payload in Kapua Data (elasticsearch).

**Comment by Coduz** [comment]
Hi @jiekechoo ,

we currently do not support custom JSON payload. 
We are compatible with the Protobuf format of Kura. 

If you send a MQTT message with a body that is not Kura Protobuf encoded, we fallback to put all the content you sent into the `body` field of the `payload` of the `KapuaMessage`, but it will be available only as a raw binary payload. 

If your message is sent as a telemetry messages (using the telemetry specific topics) this message will be available to be retrieved from the `DatastoreService`, with the limitations described above.

Hope that this informations helps. 

Feel free to ask more! 

Regards, 

_Alberto_

**Comment by jiekechoo** [comment]
Thanks for your reply,  @Coduz 

I have got some information about `payload` from issues, I know it must be Protobuf encoded.
I have installed Kura application in Raspbian device,  and sent device registry and data payload to Kapua, it works fine. 
But, in my case, I want to manage smart devices (like a nodemcu, esp8266) in Kapua, just like some items in the `Devices` list, and smart devices send data payload to Kapua, then save to `Data` section.

So, I mean, I use Kura devices as EDGE computing in Kapua, I also want to use smart devices in Kapua. Is there any way to help me ?

Best regards.
jiekechoo

**Comment by Coduz** [comment]
Hi @jiekechoo ,

To integrate with other devices there are many ways. Here are the two main ones:

First thing is to write protocol adapters or wrappers around those devices to adapt them to the Kapua/Kura protocol.

Second, is to write integrations on Kapua side. This require to create new Kapua modules that enable Kapua to talk with these devices, while adhering to the Kapua API.

Both ways have their pros and cons, but none of them is ready to be used nor "ready in few days", unfortunately

Regards, 

_Alberto_

**Comment by Coduz** [comment]
Hi @jiekechoo 

I'll close this due to inactivity. 

Feel free to reopen this issue or create a new one if you need more help.

Regards,

_Alberto_
