### ISSUE TITLE
Asset Names Not Properly Displayed If Names Too Long

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#2183]
If user creates a driver/assets/channels that have very long names, Kapua does not display the names properly in Devices -> Configuration (look at the screenshots) and in Devices -> Assets (Screenshot No. 3).

**Testflow:**
1. Login as kapua-sys or any other user that has proper permissions
2. Connect a live Kura device to Kapua (e.g. device0) with driver, asset and channels that have 150+ characters long names
3. Go to Kapua -> Devices and select device0
4. Go to its Configuration and select previously created 

**Expected behavior:**
Driver/Asset/Channel names should be limited in Kura and/or properly displayed in Kapua.

**Screenshot No. 1 (Kura configuration):**
![screenshot 2018-11-15 at 09 13 58](https://user-images.githubusercontent.com/15121999/48539326-14c64f00-e8b7-11e8-8ced-5bbdef7dfae5.png)

**Screenshot No. 2 (Result of long driver/asset/channel names in Kapua):**
![screenshot 2018-11-15 at 09 02 35](https://user-images.githubusercontent.com/15121999/48539318-0f690480-e8b7-11e8-87a1-9e4c13a1c7c4.png)

**Screenshot No. 3:**
![screenshot 2018-11-15 at 09 49 07](https://user-images.githubusercontent.com/15121999/48541008-e434e400-e8bb-11e8-8cad-f30fabe73fa6.png)

**Version of Kapua**
1.1.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others
**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 69.0.3497.100 (Official Build) (64-bit))
- Safari (Version 12.0 (13604.3.5))
- Mozilla Firefox (63.0 (64-bit))
- Opera (Version 55.0.2994.44)

**Comment by ct-anaalbic** [comment]
Hi @lorthirk.
One idea for this issue is to break word in label. This looks like on screen shot bellow.
![image](https://user-images.githubusercontent.com/45655642/55314808-3d687300-546b-11e9-8849-1ee981f9e660.png)
Is this a good solution?

_Regards_,
Ana

**Comment by lorthirk** [comment]
@ct-anaalbic LGTM :)

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved. Maybe we should brainstorm for a better solution in the future, but for now I think it is OK.
