### ISSUE TITLE
Wrong error message when creating an already existing user

### ISSUE THREAD

**Issue by lorthirk** [eclipse/kapua#2186]
**Describe the bug**
A wrong error message is shown when creating a new user whose name is already used by another user already in the system (even in a different scope)

**To Reproduce**
1. Create a user, i.e. `name-1`
2. Create another user, in any account, and name it `name-1`
3. Check the error message

**Expected behavior**
The error message should report that such username already exists

**Screenshots**
![unknown](https://user-images.githubusercontent.com/8140139/48568359-78746a80-e8ff-11e8-871e-7df720c12bca.png)

**Version of Kapua**
1.0.0

**Type of deployment**
[x] Local Vagrant deployment
[x] Docker
[x] Openshift (in its variants) 
[x] Others

**Main component affected**
[x] Console
[ ] REST API
[ ] Message Broker
[ ] - Others

**Additional context**
N/A

**Comment by Coduz** [comment]
Don't close this! PR #2261 has not fixed the bug properly.

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
