### ISSUE TITLE
can not assign admin role to user

### ISSUE THREAD

**Issue by minikiller** [eclipse/kapua#2190]
**Describe the bug**
I operate on kapua based on this issue :https://www.opensourcerers.org/connecting-kura-to-kapua/
When i want to assign admin role to user, it show following error:
![image](https://user-images.githubusercontent.com/5356570/48657680-c4deb800-ea6f-11e8-9276-abd1237951b9.png)

**Version of Kapua**
[1.0.0]

**Type of deployment**
[ ] Docker

**Main component affected**
[ ] Console (in case of console please report info on which browser you encountered the problem)

**Comment by LeoNerdoG** [comment]
Hey @minikiller,
Can you add a _**Testflow**_ to the upper issue because I was not able to reproduce it on the newest develop. 

Regards,
LeoNerdo

**Comment by minikiller** [comment]
1.add account “ACME123”:

   Account Name: ACME123
   Organization Name: ACME Org
   Email: admin@acme123.org
2.add a User:

    Username: user123
    Password: Kapu@12345678
3.Switch Accounts to User ACME123
4.assign admin role to user
then when you want to select admin role, it will show errors.

**Comment by minikiller** [comment]
Thank for you very much! It works base on your order. I think this maybe fixed.

**Comment by Coduz** [comment]
Hi all, this has been fixed with https://github.com/eclipse/kapua/pull/2171
