### ISSUE TITLE
Generic Error For Cron Schedule If Start Date And End Date Are The Same

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#2195]
If user creates a schedule for a job which has same parameters for start/end date and start/end time, Kapua reports a generic error (Persistence error) if Cron schedule is defined as the interval for periodic execution of the job. 

**Testflow:**
1. Login as kapua-sys or any other user that has proper permissions
2. Go to Jobs, create a job (e.g. job1)
3. Select job1 and go to its Schedules, add a schedule with the following paramters:
 - Schedule Name: sch1
 - Starts On: 22/11/2018
 - Start time: 00:00
 - Ends On: 22/11/2018
 - End time: 00:00
 - Retry interval: / (empty)
 - Cron schedule: 0 0 12 * * ?
4. Press Submit and observ the error. 

**Expected behavior**
Kapua should not return an error, since the schedule with the upper parameters is valid.

**Screenshot:**
![screenshot 2018-11-20 at 12 54 21](https://user-images.githubusercontent.com/15121999/48772055-8b9e8600-ecc3-11e8-8f0d-2a62f90e5ede.png)

**Version of Kapua**
1.1.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 69.0.3497.100 (Official Build) (64-bit))
- Safari (Version 12.0 (13604.3.5))
- Mozilla Firefox (63.0 (64-bit))
- Opera (Version 55.0.2994.44)

**Comment by LeoNerdoG** [comment]
@Coduz @lorthirk 
I have a few question about this issue I reported. 
1) Should this case be an error case (if start/end time and start/end date are set in the same point in time)?
2) If this is not an error case, should we throw an error if user enters retry interval/Cron or not (again - becasue start and endare at the same point in time 
3) Or should we just replace this error from the issue's screenshot with a more suitable one?

**Comment by Coduz** [comment]
That persistence error is very odd! 

I think also that the parameters used are invalid. The _cron expression_ is based on UTC so it should be 2 hours behind (CET timezone). Moreover 12 (as 3rd token in the cron) should be 0 to identify mid-night i think.

**Comment by LeoNerdoG** [comment]
Hey @Coduz,
so should we throw an error e.g. "Start and End paramters must not be in same point on time" or something similar, regardles of what user enters into Retry interval and Cron schedule?

**Comment by Coduz** [comment]
Uhmm yes I think that is convenient and could sove this problem

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
