### ISSUE TITLE
Text Error In Devices -> Configuration -> WatchDogService

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#2213]
There is a error in the text (see the screenshot) at WatchdogService description. 

**Testflow:**
1. Login as kapua-sys or any other user that has proper permissions
2. Connect a live Kura device to kapua (e.g. device0)
3. In Kapua go to Devices -> Configuration -> WatchdogService

**Expected behavior**
There should be no errors in text. 

**Screenshot:**
![screenshot 2018-11-27 at 14 15 25](https://user-images.githubusercontent.com/15121999/49084374-93c06d80-f24f-11e8-9550-620dd92cf240.png)

**Version of Kapua**
1.1.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 69.0.3497.100 (Official Build) (64-bit))
- Safari (Version 12.0 (13604.3.5))
- Mozilla Firefox (63.0 (64-bit))
- Opera (Version 55.0.2994.44)

**Comment by Coduz** [comment]
I think is coming from the device, isn't it?

**Comment by LeoNerdoG** [comment]
Maybe, we will check.

**Comment by Coduz** [comment]
If so I think should be reported to Kura :)

**Comment by lorthirk** [comment]
Yes, it should come from Kura; nonetheless, since this is XML encoded data, we should probably convert the XML entities into actual characters in the console.

**Comment by Coduz** [comment]
Hi @LeoNerdoG ,

news on this?

Regards,

_Alberto_

**Comment by LeoNerdoG** [comment]
Hi @Coduz,
we did not yet started working on this. So you can take over if you have time 😸

**Comment by Coduz** [comment]
Hi @LeoNerdoG ,

verified that is an issue on our side. 

The device sends a OCD with the correct text:

`The WatchdogService handles the hardware watchdog of the platform.  The parameter define the ping periodicity of the hardware watchdog to ensure it doesn't reboot.`

We have a problem with escaping the `'`.

Regards, 

_Alberto_

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
