### ISSUE TITLE
"Not Available" Client ID When Device Deleted Before Adding It To a Job

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#2221]
If user deletes a device just before it is added as a target to a job, Kapua adds the device anyway and the _name_ of the device is "No available" (look at the screenshot).

**Testflow:**
1. Login as kapua-sys or any other user that has proper permissions
2. Go to Devices, add a device (e.g. device0)
3. Go to Jobs create a job (e.g. job0) and go to its Target tab, click Add
4. Now open kapua in new browser (e.g. Chrome or Opera), login as kapua-sys and go to Devices. 
5. Select device0 and delete it. 
6. Now go back to the first browser and try to add the deleted device. 

**Expected behavior**
Kapua should close the Add Targets window and report that "device is not available/missing" or soemthing similar.

**Screenshots**
![screenshot 2018-11-30 at 09 40 02](https://user-images.githubusercontent.com/15121999/49288448-0c6a3880-f4a1-11e8-935e-399ae8ab5d44.png)

**Version of Kapua**
1.1.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 69.0.3497.100 (Official Build) (64-bit))
- Safari (Version 12.0 (13604.3.5))
- Mozilla Firefox (63.0 (64-bit))
- Opera (Version 55.0.2994.44)

**Comment by LeoNerdoG** [comment]
I have checked status of this issue in latest develop but it seems that it has not been fixed - @lorthirk, @muros-ct  can you check on your side please?
I have successfully reproduced this issue on two different machines (2 Firefox browsers, 2 Opera browsers) on latest develop.

**Comment by LeoNerdoG** [comment]
@lorthirk @muros-ct 
I have rebuild the develop branch once again and now I get the following error if I just go to Jobs -> Targets:
![screenshot 2019-01-07 at 09 49 05](https://user-images.githubusercontent.com/15121999/50758187-c3589180-1261-11e9-98d9-4891329ba34f.png)

Can you check on your side if you can encounter this issue?

**Comment by lorthirk** [comment]
It seems to work for me...

Chrome 71.0.3578.98 on MacOS 10.14.2

<img width="2032" alt="schermata 2019-01-07 alle 10 13 02" src="https://user-images.githubusercontent.com/8140139/50759282-e0429400-1264-11e9-9586-2dd47df5cfbb.png">

**Comment by LeoNerdoG** [comment]
Hey,
It looks like there was a problem on my side. After clearing caches, history, rebooting machine, rebulding project and deployin again everything works fine. I am closing.
