### ISSUE TITLE
Generic Error If User Enters Valid CRON Schedule

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#2231]
If user enters retry interval and CROn schedule parameters and tries to submit changes, Kapua will return an error (which is OK). But if user then deletes the retry interval and enters invalid CRON expression following by pressing the Submit button and then enters a valid CRON expression, Kapua will return a generic error instead of accepting the changes (see the screenshot).

**Testflow:**
1. Login as kapua-sys or any other user that has proper permissions
2. Go to jobs, create a job (e.g. job1)
3. Select job1, go to its Schedules tab and add a schedule with the following parameters:
 - Schedule Name: 123
 - Starts On: "today", 00:00
 - Ends On: "today", 00:00
  - Retry interval: 1
 - CRON schedule: 0 0 12 * * ?
5. Click Submit (Kapua will return an error at this point saying that schedule cannot have retry and cron at the same time).
6. Delete Retry interval parameter and in CRON schedule enter a invalid paramater (e.g. "123") 
7. Click Submit and observe the generic error that pops-up

**Expected behavior**
Kapua should accept CRON schedule after it is 
**Screenshots**
![screenshot 2018-12-06 at 09 02 36](https://user-images.githubusercontent.com/15121999/49570109-08716700-f936-11e8-8182-b33cbca4dd8b.png)

**Version of Kapua**
1.1.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 69.0.3497.100 (Official Build) (64-bit))
- Safari (Version 12.0 (13604.3.5))
- Mozilla Firefox (63.0 (64-bit))
- Opera (Version 55.0.2994.44)

**Comment by LeoNerdoG** [comment]
I have veirfied that this issue has been resolved.

**Comment by LeoNerdoG** [comment]
Hi @Coduz,
this is because this issue has been opened for so long and nobody did the fix and after some time it got resolved. It is almost impossible to track down the commit that fixed this.

**Comment by Coduz** [comment]
Hi @LeoNerdoG ,

that you for the explanation. Can we just make that clear when closing? So we know if this has been closed because it was no longer an issue or it has been actually fixed somewhere?

Thanks,

_Alberto_
