### ISSUE TITLE
Travis Build Failing Because Of Insufficient Heap Space

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#2243]
Currrently Travis builds are failing due to insufficient heap space (look at the screenshots bellow). 

**Testflow:**
/

**Expected behavior**
Travis build should not be failing due to lack of heap space (value should be increased).

**Screenshot No. 1:**
![screenshot 2018-12-07 at 09 04 14](https://user-images.githubusercontent.com/15121999/49635289-8f3e4680-f9ff-11e8-8ae2-b6ecf4313309.png)

**Screenshot No. 2:**
![screenshot 2018-12-07 at 09 04 32](https://user-images.githubusercontent.com/15121999/49635292-91080a00-f9ff-11e8-8fa9-e57754d6d3fb.png)

**Version of Kapua**
kapua 1.1.0

**Type of deployment**
[ ] Travis build

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[x] REST API
[x] Message Broker
[x] - Others

**Comment by Coduz** [comment]
Travis build is now passing.
This can be closed

**Comment by muros-ct** [comment]
Successfully solves the travis build.
All failing PRs need to be rebased to this.
