### ISSUE TITLE
Generic Error Message If End Time Before Start Time In Jobs

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#2276]
If user sets end time before start time, Kapua returns a generic error (but fields are marked as invalid, which is ok). 

**Testflow:**
1. Login as kapua-sys or any other user that has proper permissions
2. Go to Jobs, create a job (e.g. job0)
3. Select job0 and create a schedule with end Time before start Time.

**Expected behavior**
Error message should not be generic in this case, but should be more specific (e.g. "End time cannot be before start time".)

**Screenshot:**
![screenshot 2018-12-19 at 15 25 31](https://user-images.githubusercontent.com/15121999/50225990-55c3ee80-03a2-11e9-8cbf-f7257293d347.png)

**Version of Kapua**
1.1.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 69.0.3497.100 (Official Build) (64-bit))
- Safari (Version 12.0 (13604.3.5))
- Mozilla Firefox (63.0 (64-bit))
- Opera (Version 55.0.2994.44)

**Comment by LeoNerdoG** [comment]
I have checked this in Develop branch and now Kapua returns an error if Start and End dates are the same (look at the screnshot bellow). 
I did not notice this in PR #2283.

@ct-anaalbic can you please fix this as you have been working on this? 

**Screenshot:**
![screenshot 2019-01-17 at 07 41 08](https://user-images.githubusercontent.com/15121999/51301017-0f5bc100-1a2e-11e9-9b1b-666a85899df9.png)

**Comment by ct-anaalbic** [comment]
@LeoNerdoG Yes, I can fix this.

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
