### ISSUE TITLE
How can I compile this many pom.xml files?

### ISSUE THREAD

**Issue by maul5** [eclipse/kapua#228]
Hello.

I want kapua compile in Eclipse Neo with Maven Tool.

This project has a lot of pom.xml.

How can I compile this many pom.xml file?

**Comment by Coduz** [comment]
Hi @maul5 ,

Each project inside Kapua has its own pom.xml file with its configurations. 
This is because Kapua has a lots of different components inside and they are organized to ensure maximum flexibility of each single component.

If you want to compile the whole Kapua project, you can run the command 
`mvn clean install`
from the Kapua root project.

Regards, 

_Alberto_

**Comment by maul5** [comment]
Thank you Alberto.

After git clone, I tried `mvn clean install` and I get an error like below.


`$ mvn clean install`
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.eclipse.kapua:kapua-commons:jar:0.2.0-SNAPSHOT
[WARNING] The expression ${artifactId} is deprecated. Please use ${project.artifactId} instead.
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.eclipse.kapua:kapua-guice:jar:0.2.0-SNAPSHOT
[WARNING] The expression ${artifactId} is deprecated. Please use ${project.artifactId} instead.
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.eclipse.kapua:kapua-console:war:0.2.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.apache.maven.plugins:maven-dependency-plugin @ org.eclipse.kapua:kapua-console:[unknown-version], C:\Users\Administrator\git\kapua\console\pom.xml, line 287, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] kapua
[INFO] kapua-service
[INFO] kapua-service-api
[INFO] kapua-security
[INFO] kapua-security-authorization
[INFO] kapua-security-authorization-api
[INFO] kapua-security-authentication
[INFO] kapua-security-authentication-api
[INFO] kapua-commons
[INFO] kapua-locator
[INFO] kapua-guice
[INFO] kapua-user
[INFO] kapua-user-api
[INFO] kapua-account
[INFO] kapua-account-api
[INFO] kapua-test
[INFO] kapua-security-shiro
[INFO] kapua-message
[INFO] kapua-message-api
[INFO] kapua-datastore
[INFO] kapua-datastore-api
[INFO] kapua-message-internal
[INFO] kapua-datastore-internal
[INFO] kapua-device
[INFO] kapua-device-api
[INFO] kapua-device-registry
[INFO] kapua-device-registry-api
[INFO] kapua-transport
[INFO] kapua-transport-api
[INFO] kapua-device-call
[INFO] kapua-device-call-api
[INFO] kapua-translator
[INFO] kapua-translator-api
[INFO] kapua-device-call-kura
[INFO] kapua-device-commons
[INFO] kapua-transport-mqtt
[INFO] kapua-translator-kura
[INFO] kapua-translator-kura-mqtt
[INFO] kapua-device-call-test
[INFO] kapua-device-configuration
[INFO] kapua-device-configuration-api
[INFO] kapua-device-configuration-internal
[INFO] kapua-device-packages
[INFO] kapua-device-packages-api
[INFO] kapua-device-packages-internal
[INFO] kapua-user-internal
[INFO] kapua-device-registry-internal
[INFO] kapua-device-bundle
[INFO] kapua-device-bundle-api
[INFO] kapua-device-bundle-internal
[INFO] kapua-device-command
[INFO] kapua-device-command-api
[INFO] kapua-device-command-internal
[INFO] kapua-account-internal
[INFO] kapua-device-command-test
[INFO] kapua-transport-jms
[INFO] kapua-transport-test
[INFO] kapua-translator-kapua
[INFO] kapua-translator-kapua-kura
[INFO] kapua-translator-kura-jms
[INFO] kapua-broker-core
[INFO] kapua-qa
[INFO] kapua-console
[INFO] kapua-rest-api
[INFO] kapua-assembly
[INFO] kapua-dev-tools
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building kapua 0.2.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: https://repo.maven.apache.org/maven2/org/jacoco/jacoco-maven-plugin/0.7.4.201502262128/jacoco-maven-plugin-0.7.4.201502262128.pom
Downloaded: https://repo.maven.apache.org/maven2/org/jacoco/jacoco-maven-plugin/0.7.4.201502262128/jacoco-maven-plugin-0.7.4.201502262128.pom (4 KB at 1.0 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/jacoco/org.jacoco.build/0.7.4.201502262128/org.jacoco.build-0.7.4.201502262128.pom
Downloaded: https://repo.maven.apache.org/maven2/org/jacoco/org.jacoco.build/0.7.4.201502262128/org.jacoco.build-0.7.4.201502262128.pom (36 KB at 42.9 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/jacoco/jacoco-maven-plugin/0.7.4.201502262128/jacoco-maven-plugin-0.7.4.201502262128.jar
Downloaded: https://repo.maven.apache.org/maven2/org/jacoco/jacoco-maven-plugin/0.7.4.201502262128/jacoco-maven-plugin-0.7.4.201502262128.jar (50 KB at 90.8 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.pom (4 KB at 10.9 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/22/maven-plugins-22.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/22/maven-plugins-22.pom (13 KB at 32.2 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/21/maven-parent-21.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/21/maven-parent-21.pom (26 KB at 64.5 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/apache/10/apache-10.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/apache/10/apache-10.pom (15 KB at 33.5 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.jar (25 KB at 69.1 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-install-plugin/2.4/maven-install-plugin-2.4.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-install-plugin/2.4/maven-install-plugin-2.4.pom (7 KB at 18.1 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/23/maven-plugins-23.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/23/maven-plugins-23.pom (9 KB at 24.6 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/22/maven-parent-22.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/22/maven-parent-22.pom (30 KB at 71.0 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/apache/11/apache-11.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/apache/11/apache-11.pom (15 KB at 40.2 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-install-plugin/2.4/maven-install-plugin-2.4.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-install-plugin/2.4/maven-install-plugin-2.4.jar (27 KB at 70.8 KB/sec)
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ kapua ---
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-plugin-api/2.0.6/maven-plugin-api-2.0.6.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-plugin-api/2.0.6/maven-plugin-api-2.0.6.pom (2 KB at 3.0 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven/2.0.6/maven-2.0.6.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven/2.0.6/maven-2.0.6.pom (9 KB at 25.5 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/5/maven-parent-5.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/5/maven-parent-5.pom (15 KB at 37.0 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/apache/3/apache-3.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/apache/3/apache-3.pom (4 KB at 9.9 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/3.0/plexus-utils-3.0.pom
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/3.0/plexus-utils-3.0.pom (4 KB at 11.5 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/sonatype/spice/spice-parent/16/spice-parent-16.pom
Downloaded: https://repo.maven.apache.org/maven2/org/sonatype/spice/spice-parent/16/spice-parent-16.pom (9 KB at 24.6 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/sonatype/forge/forge-parent/5/forge-parent-5.pom
Downloaded: https://repo.maven.apache.org/maven2/org/sonatype/forge/forge-parent/5/forge-parent-5.pom (9 KB at 24.6 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-plugin-api/2.0.6/maven-plugin-api-2.0.6.jar
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/3.0/plexus-utils-3.0.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-plugin-api/2.0.6/maven-plugin-api-2.0.6.jar (13 KB at 32.3 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] kapua .............................................. FAILURE [ 18.247 s]
[INFO] kapua-service ...................................... SKIPPED
[INFO] kapua-service-api .................................. SKIPPED
[INFO] kapua-security ..................................... SKIPPED
[INFO] kapua-security-authorization ....................... SKIPPED
[INFO] kapua-security-authorization-api ................... SKIPPED
[INFO] kapua-security-authentication ...................... SKIPPED
[INFO] kapua-security-authentication-api .................. SKIPPED
[INFO] kapua-commons ...................................... SKIPPED
[INFO] kapua-locator ...................................... SKIPPED
[INFO] kapua-guice ........................................ SKIPPED
[INFO] kapua-user ......................................... SKIPPED
[INFO] kapua-user-api ..................................... SKIPPED
[INFO] kapua-account ...................................... SKIPPED
[INFO] kapua-account-api .................................. SKIPPED
[INFO] kapua-test ......................................... SKIPPED
[INFO] kapua-security-shiro ............................... SKIPPED
[INFO] kapua-message ...................................... SKIPPED
[INFO] kapua-message-api .................................. SKIPPED
[INFO] kapua-datastore .................................... SKIPPED
[INFO] kapua-datastore-api ................................ SKIPPED
[INFO] kapua-message-internal ............................. SKIPPED
[INFO] kapua-datastore-internal ........................... SKIPPED
[INFO] kapua-device ....................................... SKIPPED
[INFO] kapua-device-api ................................... SKIPPED
[INFO] kapua-device-registry .............................. SKIPPED
[INFO] kapua-device-registry-api .......................... SKIPPED
[INFO] kapua-transport .................................... SKIPPED
[INFO] kapua-transport-api ................................ SKIPPED
[INFO] kapua-device-call .................................. SKIPPED
[INFO] kapua-device-call-api .............................. SKIPPED
[INFO] kapua-translator ................................... SKIPPED
[INFO] kapua-translator-api ............................... SKIPPED
[INFO] kapua-device-call-kura ............................. SKIPPED
[INFO] kapua-device-commons ............................... SKIPPED
[INFO] kapua-transport-mqtt ............................... SKIPPED
[INFO] kapua-translator-kura .............................. SKIPPED
[INFO] kapua-translator-kura-mqtt ......................... SKIPPED
[INFO] kapua-device-call-test ............................. SKIPPED
[INFO] kapua-device-configuration ......................... SKIPPED
[INFO] kapua-device-configuration-api ..................... SKIPPED
[INFO] kapua-device-configuration-internal ................ SKIPPED
[INFO] kapua-device-packages .............................. SKIPPED
[INFO] kapua-device-packages-api .......................... SKIPPED
[INFO] kapua-device-packages-internal ..................... SKIPPED
[INFO] kapua-user-internal ................................ SKIPPED
[INFO] kapua-device-registry-internal ..................... SKIPPED
[INFO] kapua-device-bundle ................................ SKIPPED
[INFO] kapua-device-bundle-api ............................ SKIPPED
[INFO] kapua-device-bundle-internal ....................... SKIPPED
[INFO] kapua-device-command ............................... SKIPPED
[INFO] kapua-device-command-api ........................... SKIPPED
[INFO] kapua-device-command-internal ...................... SKIPPED
[INFO] kapua-account-internal ............................. SKIPPED
[INFO] kapua-device-command-test .......................... SKIPPED
[INFO] kapua-transport-jms ................................ SKIPPED
[INFO] kapua-transport-test ............................... SKIPPED
[INFO] kapua-translator-kapua ............................. SKIPPED
[INFO] kapua-translator-kapua-kura ........................ SKIPPED
[INFO] kapua-translator-kura-jms .......................... SKIPPED
[INFO] kapua-broker-core .................................. SKIPPED
[INFO] kapua-qa ........................................... SKIPPED
[INFO] kapua-console ...................................... SKIPPED
[INFO] kapua-rest-api ..................................... SKIPPED
[INFO] kapua-assembly ..................................... SKIPPED
[INFO] kapua-dev-tools .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 24.830 s
[INFO] Finished at: 2017-02-05T15:24:20+09:00
[INFO] Final Memory: 20M/149M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-clean-plugin:2.5:clean (default-clean) on project kapua: Execution default-clean of goal org.apache.maven.plugins:maven-clean-plugin:2.5:clean failed: Plugin org.apache.maven.plugins:maven-clean-plugin:2.5 or one of its dependencies could not be resolved: Could not transfer artifact org.codehaus.plexus:plexus-utils:jar:3.0 from/to central (https://repo.maven.apache.org/maven2): handshake alert:  unrecognized_name -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException

**Comment by maul5** [comment]
Alberto found out the cause.

When I run `git clone`, local branch is developer.

Change to `master` and run normally.

**Comment by maul5** [comment]
Is it possible to compile with **master**?
