### ISSUE TITLE
I can not find "KAPUA_BOX_NAME=trusty64/kapua-dev-box-0.1"

### ISSUE THREAD

**Issue by maul5** [eclipse/kapua#229]
Hello,

I want to demo this.

But I can not find "KAPUA_BOX_NAME=trusty64/kapua-dev-box-0.1"
(Vagrant is installed)

kapua/dev-tools/src/main/vagrant/start.sh has failed.

What can I do?

**Comment by Coduz** [comment]
Hi @maul5 ,

Running the script `kapua/dev-tools/src/main/vagrant/start.sh` is expecting a parameter to know which type of pre-configured machine to start. 

You can specify: 

demo: Is an image that is used by the `kapua/dev-tools/src/main/bin/start-demo.sh` to start a demo deployment of kapua.
develop-box: Is an image that is used to develop purposes. This image does not start any service.
base-box: Is a base image for the other two images.

To run both 'demo' and 'develop' machine you have to build first 'base-box', which installs the machine named "trusty64/kapua-dev-box-0.1" into the local vagrant box library.

If you want some help you can follow the _getting started_ [here](https://www.eclipse.org/kapua/getting-started.php).

Regards,

_Alberto_

**Comment by maul5** [comment]
Thank you.
