### ISSUE TITLE
Kapua Console Connections Tab fails to load 

### ISSUE THREAD

**Issue by gitsaycat** [eclipse/kapua#2301]
**Describe the bug**
Connections Tab fails to load 

**To Reproduce**
Click on 'Connections' tab

**Expected behavior**
Tab with current connections should load

**Screenshots**
Error notification pops up (see screenshot) and tab 'Loading' never ends
![kapua-bug](https://user-images.githubusercontent.com/14805543/51069140-66dfe280-1664-11e9-989e-8cfeb46a1c7e.png)

**Version of Kapua**
1.0.3

**Type of deployment**
[ ] Docker

**Main component affected**
[ ] Console (in case of console please report info on which browser you encountered the problem)

**Comment by LeoNerdoG** [comment]
Hi @gitsaycat,
I have pulled latest develop and built it and did not notice this issue. All other tabs work fine as well. Can you please undeploy current Docker containers (`./docker-undeploy.sh`), delete all docker containers and images (`docker system prune -a`), pull the latest develop and build it?

Note that this will delete all docker images and containers so if you have anything else running in docker be sure that this is acceptable. If it is not, report back and we will find another solution.

**Comment by gitsaycat** [comment]
Hi
Many thanks for your prompt attention!!!
I am unable to reproduce after a deep clean of the environment - I don't understand why only this tab among all others would have a problem like this. 
It seems we managed a successful upgrade of our 1.0.0.M7 setup to 1.0.3!
But lets close this issue for now.
Regards, Saycat

**Comment by LeoNerdoG** [comment]
Hey @gitsaycat,
please close the issue if this is resolved - you can do this, because you have opened the issue 😄
