### ISSUE TITLE
Error Message Regarding Job Name Not Specific Enough

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#2308]
When a user tries to create a job and a schedule for it, Kapua checks jobs in scope if a schedule with the same name already exists. 
If it does, Kapua returns an error (look at the screenshot) which is OK, but the message itself is not specific enough - Kapua should report something similar to: "An entity with the same value for field already exists here or in another job".

**Testflow:**
1. Login as kapua-sys or any other user that has proper permissions
2. Go to Jobs, create a job (e.g. job1) and go to its Schedules.
3. Create a schedule with name "schedule1" (also enter all other necessarry parameters)
4. Create another job (e.g. job2) and go to its Schedules. 
5. Try to add a schedule with name "schedule1" to it. 
**Kapua returns an error, which is ok, but the message within it is not somehow logical, because if user has for example 50 jobs with 30 schedules in each - it is impossible to trace and change it.**

**Expected behavior:**
Kapua should return error with a more specific message. A better solution would be to add info about where schedule with this name is located (in which job). 

**Screenshot:**
![screenshot 2019-01-14 at 09 12 24](https://user-images.githubusercontent.com/15121999/51182263-e6bcb580-18cd-11e9-8062-f2344b582a44.png)

**Version of Kapua**
1.1.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 71.0.3578.98 (Official Build) (64-bit))
- Safari (Version 12.0 (14606.3.4))
- Mozilla Firefox (64.0 (64-bit))
- Opera (Version 57.0.3098.110)

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been partially solved. 
Error message has been changed, which is OK, but the "Schedule Name" is not in error state as it should be (see screenshot bellow).

@ct-anaalbic can you fix this as you have been working on this issue? 

![screenshot 2019-01-22 at 11 40 58](https://user-images.githubusercontent.com/15121999/51530270-d7dc8280-1e3a-11e9-9455-f7c090c1a6fd.png)

**Comment by ct-anaalbic** [comment]
@LeoNerdoG Yes, i can

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
