### ISSUE TITLE
Wrong Status Of Packages That Are Being Installed

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#2319]
When user tries to install a lot of packages (which all have same URL paramter but/and different/same version and name) Kapua displays some of them as "In Progress..." but these packages cannot be found in "In Progress" subtab. 

**Testflow:**
1. Login as kapua-sys or any other user that has proper pemissions
2. Connect a live Kura device to Kapua (e.g. device0) 
3. Go to Devices, select device0 and try to install multiple packages (e.g. example publisher) in a row
4. Sort them by heir "Status" and observe the result
5. Go to "In Progress" subtab and observe the emptiness of its list although there should be some packages listed, as their status is "In Progress" in History subtab

**Expected behavior**
If package's status in History tab is "In Progress", the package should also be listed in "In Progress" tab. 

**Screenshot No. 1:**
![screenshot 2019-01-17 at 13 41 40](https://user-images.githubusercontent.com/15121999/51320148-37afe380-1a5f-11e9-8f31-c76009c12fd7.png)

**Screenshot No. 2:**
![screenshot 2019-01-17 at 13 41 53](https://user-images.githubusercontent.com/15121999/51320151-3a123d80-1a5f-11e9-9bf4-88e987cbfdc7.png)

**Version of Kapua**
1.1.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 71.0.3578.98 (Official Build) (64-bit))
- Safari (Version 12.0 (14606.3.4))
- Mozilla Firefox (64.0 (64-bit))
- Opera (Version 57.0.3098.110)

**Comment by Coduz** [comment]
Hi all,

the "In Progress" tabs shows the status of progress from the device. Currently "Deploy-v2" can only handle one operation at a time. To show something in there you have to install a package which is large enough to make the download last few seconds.

The actual bug is that operations remain "In progress..." while they are (likely) finished.
Is that the case? 

Regards, 

_Alberto_

**Comment by ct-anaalbic** [comment]
Hi,

Yes, operations stays in progress state while they are finished. That is one case. But in this issue, if user send request for package installation this request is not shown in progress tab. I tried to sent request for installation of package which is large enough, but in some reason, status of package always is none, and information about request can not be shown in this tab. Do you have idea why this happens? Maybe problem is on back end side.

Regards,
Ana

**Comment by Coduz** [comment]
Which version of Kura are you using?

**Comment by ct-anaalbic** [comment]
I use 3.2.0 version of Kura.

**Comment by Coduz** [comment]
I'll have a test on it to try to diagnose the actual problem :)

**Comment by ct-anaalbic** [comment]
Ok, thank you.

Regards.

**Comment by Coduz** [comment]
Hi all,

I've tried to reproduce it but I was not able to reproduce the situation you had with packages on the "Histroy" tab left as "In progress..." while they are not.

Any advice on how to reproduce? 

Regards, 

_Alberto_

**Comment by LeoNerdoG** [comment]
Hi @Coduz,
after testing this for some time I could not reproduce it either so I am closing this. 
If I encounter this in the future, I will reopen it. 

I tried this with Kura 4.1.0. since this is the newest version so if it works for this version I think it is safe to close this.
