### ISSUE TITLE
SQL schema incomplete

### ISSUE THREAD

**Issue by ctron** [eclipse/kapua#232]
To me it looks like the current SQL schema is incomplete. Setting up a new instance of Kapua it is not possible to login, the following error is shown in the console of "kura-console":

```
Caused by: org.h2.jdbc.JdbcSQLException: Table "USR_USER" not found; SQL statement:
SELECT attributes, created_on, display_name, email, modified_on, name, optlock, phone_number, properties, status, created_by, id, modified_by, scope_id FROM usr_user WHERE (name = ?) [42102-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.readTableOrView(Parser.java:5389)
        at org.h2.command.Parser.readTableFilter(Parser.java:1257)
```

**Comment by Coduz** [comment]
Hi @ctron ,

build procedure you followed? 

_Alberto_

**Comment by ctron** [comment]
This one:

https://github.com/eclipse/kapua/tree/develop/dev-tools/src/main/openshift

Do you any other?

**Comment by ctron** [comment]
Maybe I should mention that I also tried the docker containers in "assembly". However I didn't find any working guide, so I did just try out different approaches. With the same result.

**Comment by Coduz** [comment]
yes we have this:

[https://www.eclipse.org/kapua/getting-started.php](https://www.eclipse.org/kapua/getting-started.php)

Is linked from the Eclipse Kapua website and also in the Readme.md file in the root folder of the repo.

And is fully working :) 

Hope that helps.

_Alberto_

**Comment by Coduz** [comment]
Note: Rest API still broken as per issue #230. 
Anyway there is already a PR waiting to be merged that fixes the problem.

**Comment by ctron** [comment]
Unfortunately I cannot use Vagrant. I can go with all kind of "libvirt", local or docker based approaches. But Vagrant is not working for me.

If is see it correctly, this is the only approach in this document you mentioned.

So how does this setup perform its database setup? If this works, which I cannot test, then there must be some database schema as well.

**Comment by Coduz** [comment]
The getting started guide sources the sql files from the projects. 
I don't know much about the build procedure that you followed. 
@hekonsek  has developed that and maybe knows the answer.

**Comment by ctron** [comment]
So if you mean this guide [1], then I don't see any SQL files in there or linked to.

Or am I looking at the wrong document?

[1] https://github.com/eclipse/kapua/blob/develop/dev-tools/src/main/vagrant/README.MD

**Comment by Coduz** [comment]
I mean that the process described on the getting started guide sources the sql from the projects by running `start-demo.sh`. As I said, sql files are sourced from the projects.

**Comment by ctron** [comment]
So there is no SQL file which can be used as a reference for setting up Kapua?

**Comment by Coduz** [comment]
We don't have a single SQL file with all statement to seed the database. 
Each projects its own SQL scripts under {sub-projectFolder}/src/main/sql/H2/. 
When running `mvn clean install -Psql` command those script are executed from each project.

**Comment by hekonsek** [comment]
Please take a look at this [1] PR. It is the way we gonna solve SQL schema management issues.

[1] https://github.com/eclipse/kapua/issues/232

**Comment by Coduz** [comment]
@hekonsek  you referenced this issue

**Comment by hekonsek** [comment]
Sorry :) Here is the issue - #323.

I will close this ticket and propose to track Liquibase migration in #323.
