### ISSUE TITLE
Incomplete Text In Jobs -> Step Definition

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#2379]
Currently there is "Configuration Put" step definition as one of the possibilities in Jobs -> Steps -> Step Definition. 
It looks like this is an incomplete text - see bellow for suggestions. 

**Testflow:**
1. Login as kapua-sys or any other user that has proper permissions
2. Go to Jobs, create a job (e.g. job0) 
3. Select job0 and go to its Steps. Click Add and go to "Step definition" and click it.
**There is "Configuration Put" option. It looks like a part of text is missing.**

**Expected behavior**
I suggest we change "Configuration Put" to "Change configuration", "Configuration change", "New configuration" or somethng similar. 

**Screenshot:**
![screenshot 2019-02-11 at 10 21 10](https://user-images.githubusercontent.com/15121999/52567101-c23ff480-2e0b-11e9-9729-7c488df8bb01.png)

**Version of Kapua**
1.1.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 72.0.3626.81 (Official Build) (64-bit))
- Safari (Version 12.0.3 (14606.4.5))
- Mozilla Firefox (65.0 (64-bit))
- Opera (Version:57.0.3098.116)

**Comment by muros-ct** [comment]
@Coduz Is this possible to change in database? Does it make sense to you to do this change?
@LeoNerdoG

**Comment by LeoNerdoG** [comment]
@Coduz any new on this? Can we change this parameters in the database?

**Comment by Coduz** [comment]
There was a change on the database.

https://github.com/eclipse/kapua/pull/2368

**Comment by ct-ajovanovic** [comment]
Hi @Coduz 
The "Configuration Put" step definition remains in the database and the GUI. Should this be changed?
I agree with @LeoNerdoG , and it just doesn't seem complete or very intuitive.

**Comment by LeoNerdoG** [comment]
I am closing this as it is not an issue. 
Can one of the commiters put "wont fix" label on it?
