### ISSUE TITLE
Description Fields In Roles, Tags And Access Groups

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#2387]
For now, only Jobs have Description field when adding/editing them, which is very convenient for end user, because two fields can contain more info than only one. 
I suggest we add these Description field also in Roles, Access Groups and Tags. 
Consequently new column should be added and new filter fields. 

**Testflow:**
1. Login as kapua-sys or any other user that has proper permissions
2. Go to Roles/Tags/Access Groups
3. Click Add and observe the Dialogue box - there is not "Description" field.

**Expected behavior:**
As I explained above, I think this would be good because of 2 reasons:
 1. Job add window already has Description field
 2. It is better to have 2 fields (one for name and one for description) because user can put more info into two fields than in one (en it is more descriptive)

**Screenshot No. 1 (Current job Add window fields):**
![screenshot 2019-02-12 at 10 52 45](https://user-images.githubusercontent.com/15121999/52626889-7301ce80-2eb4-11e9-82f6-7cc52705898c.png)

**Screenshot No. 2 (Current role/tag/group Add window fields)**
![screenshot 2019-02-12 at 10 52 50](https://user-images.githubusercontent.com/15121999/52626892-7432fb80-2eb4-11e9-8496-e4f529fd28e2.png)

**Version of Kapua**
1.1.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 72.0.3626.81 (Official Build) (64-bit))
- Safari (Version 12.0.3 (14606.4.5))
- Mozilla Firefox (65.0 (64-bit))
- Opera (Version:57.0.3098.116)

**Comment by ct-anaalbic** [comment]
Hi @Coduz. 
Tables Role, Group and Tag don't have Description column. Is it a good idea, to add Description column in database model or not? 
Thank's.
Regards.

**Comment by Coduz** [comment]
Hi @ct-anaalbic , 

yes we can add the field. 

Since this change require also some SQL changes, can I take over this issue for the backend side? 
I'll let you integrate the UI side after changes on the backend are done.

Regards, 

_Alberto_

**Comment by ct-anaalbic** [comment]
@Coduz Ok, after changes on backend side I'll work on UI side. 

Regards. 
Ana

**Comment by LeoNerdoG** [comment]
I have verified that these features have been succesfully implemented.
