### ISSUE TITLE
kapua-sys User Endpoint Permission Problem

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#2392]
**Describe the bug**
If kapua-sys is stripped of default "admin" role and user adds "ALL:ALL:ALL:Yes" permision to kapua-sys, the Endpoints tab dsappears and there is no way to add endpoints in Kapua after this. 

**Testflow:**
1. Login as kapua-sys
2. Go to Roles, create a role (e.g. superAdmin)
3. Set ALL:ALL:ALL:YES permissions to superAdmin
4. Go to its Permissions and add ALL:ALL:ALL:Yes permission to it. 
5. Go to Users, select kapua-sys and remove "admin" role from it
6. Reload the page and observe Endpoints - the tab is gone!
**Kapua reports an error, although kapua-sys user has ALL permissions.**
7. Now go to its Roles tab and add superAdmin role. Delete ALL:ALL:ALL:Yes permission in Permission
**The end result is the same when user navigates to Endpoints.**

**Expected behavior**
Kapua-sys should never be unable to see Endpoints since thi is the only user that can add/edit Endpoints.

**Screenshots**
![screenshot 2019-02-13 at 13 19 53](https://user-images.githubusercontent.com/15121999/52711444-196fd180-2f92-11e9-8d81-89a66ca8db33.png)

**Version of Kapua**
1.1.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 72.0.3626.81 (Official Build) (64-bit))
- Safari (Version 12.0.3 (14606.4.5))
- Mozilla Firefox (65.0 (64-bit))
- Opera (Version:57.0.3098.116)

**Comment by ct-ajovanovic** [comment]
Hi @Coduz 
Can you take a look at this issue? 
As far as I can see the problem is the value of the `targetScopeId` parametar of the role permission . The only case when the user can see the Endpoints is if he has the admin role, and if this role is deleted the Endpoints tab becomes invisible for all users. 
A similar thing happened in issue [1596](https://github.com/eclipse/kapua/issues/1596), where no changes made.
What do you think? Should any changes be made here? Or not?
Regards,
_Aleksandra_

**Comment by lorthirk** [comment]
Well, I don't think we should allow an user to delete the "admin" role in the first place.

**Comment by LeoNerdoG** [comment]
Ok,
As agreed I am closing this and will open a new issue describing that "admin" role cannot be deleted. 
Can somebody put "wontfix" label on this issue?
