### ISSUE TITLE
Use hosted elasticsearch in combination with docker deployment 

### ISSUE THREAD

**Issue by lukas-bender-rodriguez** [eclipse/kapua#2403]
I want to substitute the elasticsearch docker container with the [hosted version](https://www.elastic.co/cloud/elasticsearch-service). I'm a little lost how to hand over the connection parameters (url, pwd, ...) to Kapua. I have found the corresponding parameters (properties file) [here](https://github.com/eclipse/kapua/blob/release-1.0.x/service/datastore/client-rest/src/main/resources/kapua-datastore-rest-client-setting.properties) and I guess I need to pass them as environment variables to the corresponding container. But which one? events-broker?  
Do I overlook a documentation where I can find this information? 

Thanks !

**Comment by lorthirk** [comment]
Hi @lukas-bender-rodriguez,

You should override such variables in every container who is interfacing with Elasticsearch, so the Console, the REST API and the Broker. The Event Broker does not talk with Elasticsearch at all.

**Comment by lukas-bender-rodriguez** [comment]
It seems I'm missing something obvious. Where to put username and password of elasticsearch? (Basic Auth Credentials)

**Comment by lukas-bender-rodriguez** [comment]
looking at : https://github.com/eclipse/kapua/blob/8b0e249aaa3915d4a3b3ca406f2c47bdcfd50d2d/service/datastore/client-rest/src/main/java/org/eclipse/kapua/service/datastore/client/rest/EsRestClientProvider.java#L228

it seems that providing basic auth credentials is not yet supported?!

The idea to fix this missing feature would be: 

To add the additional parameters

`datastore.elasticsearch.basic_auth.enabled`
`datastore.elasticsearch.basic_auth.user`
`datastore.elasticsearch.basic_auth.pwd`

here:
https://github.com/eclipse/kapua/blob/8b0e249aaa3915d4a3b3ca406f2c47bdcfd50d2d/service/datastore/client-rest/src/main/java/org/eclipse/kapua/service/datastore/client/rest/ClientSettingsKey.java#L22

and here:

https://github.com/eclipse/kapua/blob/8b0e249aaa3915d4a3b3ca406f2c47bdcfd50d2d/service/datastore/client-rest/src/main/resources/kapua-datastore-rest-client-setting.properties#L15

and to extend 

https://github.com/eclipse/kapua/blob/8b0e249aaa3915d4a3b3ca406f2c47bdcfd50d2d/service/datastore/client-rest/src/main/java/org/eclipse/kapua/service/datastore/client/rest/EsRestClientProvider.java#L228

as given here:

https://www.elastic.co/guide/en/elasticsearch/client/java-rest/5.6/_basic_authentication.html

Are further modifications necessary?

The docker deployment of kapua uses elasticsearch version 5.3. The hosted version of elasticsearch only supports 5.6.15. Do you expect any problems here?

Thank you very much for your support! My Java knowledge is unfortunately not very good.

**Comment by lorthirk** [comment]
I can confirm that our Elasticsearch client doesn't currently support basic authentication. For sure those three properties would be needed, but also some more code since we would need to pass the basic authentication stuff with any HTTP call.

About the version, I honestly never tried with 5.6, but I did with 5.4 and I had no issue at all.

**Comment by lukas-bender-rodriguez** [comment]
okay, thanks for the fast response. I'll do my best to provide the feature.

**Comment by lukas-bender-rodriguez** [comment]
Ok, something is not working as expected:

I implemented the Basic Authorization as suggested see: 

https://github.com/lukas-bender-rodriguez/kapua/blob/fde12c21315a7acbe8ec56d83fbd49f507615815/service/datastore/client-rest/src/main/java/org/eclipse/kapua/service/datastore/client/rest/EsRestClientProvider.java#L261

Basically the implementation seems to work:


``14:57:13.966 [qtp913190639-11] WARN  o.e.k.c.metric.MetricsServiceImpl - Unable to load Default Metric Registry - creating a new one``

``14:57:13.966 [qtp913190639-11] INFO  o.e.k.s.d.c.rest.RestDatastoreClient - Starting Elasticsearch rest client...``

``14:57:13.968 [qtp913190639-11] INFO  o.e.k.s.d.c.r.EsRestClientProvider - >>> Initializing ES rest client...``

``14:57:14.013 [qtp913190639-11] INFO  o.e.k.s.d.c.r.EsRestClientProvider - ES Rest Client - SSL enabled``

``14:57:14.022 [qtp913190639-11] INFO  o.e.k.s.d.c.r.EsRestClientProvider - ES Rest Client - Keystore path: none``

``14:57:14.022 [qtp913190639-11] INFO  o.e.k.s.d.c.r.EsRestClientProvider - ES Rest Client - SSL trust server certificate NOT enabled``

``14:57:14.022 [qtp913190639-11] INFO  o.e.k.s.d.c.r.EsRestClientProvider - ES Rest Client - Truststore path: none``

``14:57:14.109 [qtp913190639-11] INFO  o.e.k.s.d.c.r.EsRestClientProvider - ES Rest Client - Basic Authentication enabled``

``14:57:14.109 [qtp913190639-11] INFO  o.e.k.s.d.c.r.EsRestClientProvider - Basic Auth User: elastic``

``14:57:14.109 [qtp913190639-11] INFO  o.e.k.s.d.c.r.EsRestClientProvider - Basic Auth pwd: ***``

``14:57:14.197 [qtp913190639-11] INFO  o.e.k.s.d.c.r.EsRestClientProvider - >>> Initializing ES rest client... DONE``

``14:57:14.197 [qtp913190639-11] INFO  o.e.k.s.d.c.rest.RestDatastoreClient - Starting Elasticsearch rest client... DONE``


but the console throws the following error:

``
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":".1","index_uuid":"_na_","index":".1"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":".1","index_uuid":"_na_","index":".1"},"status":404}
`` 

and after connecting a kura gatway the broker throws errors like:

``15:36:08.338 [Camel (camelContext) thread #18 - JmsConsumer[Consumer.eurotech:mainRoutelisteners:EXACTLY_ONCE.VirtualTopic.%3E]] WARN  org.eclipse.kapua.KapuaException - Could not load Exception Messages Bundle for Locale en_US``


``15:36:08.338 [Camel (camelContext) thread #18 - JmsConsumer[Consumer.eurotech:mainRoutelisteners:EXACTLY_ONCE.VirtualTopic.%3E]] WARN  o.a.c.processor.DeadLetterChannel - Failed delivery for (MessageId: ID:4168ba7bb4d6-34873-1551711175229-5:1:-1:1:23 on ExchangeId: ID-4168ba7bb4d6-36113-1551711183663-0-25). On delivery attempt: 0 caught: org.eclipse.kapua.service.datastore.internal.mediator.DatastoreException: An internal error occurred: {0}.``


``15:36:09.342 [Camel (camelContext) thread #24 - JmsConsumer[storeGenericException]] INFO  o.e.k.b.c.l.DataStorageMessageProcessor - Message datastoreId: 'aec77ff8-85b9-47b1-a99e-60a034949ab7' - Message Id 'null'``

Any ideas where the problem might be?

I'am using a slightly modified version of the docker deployment 1.0.4
