### ISSUE TITLE
Should "Start", "Stop" and "Restart" Buttons Be Enabled If User Does Not Have Device Permissions?

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#2411]
I would like community input on this issue. 
I have been working on jobs tab in console and I came across a interesting problem. If user has job:read, job:write and job:execute permissions, user can add and "execute" jobs (well not really since there are no targets added). 
The question here is: should we disable "Start", "Stop" and "Restart" buttons if user does not have (at least( device:read permissions to see the Targets tab? 
Because from end-user standpoint it is not logical to have all the buttons mentioned enabled, if there is no Target tab for viewing/editing/deleting targets. 
Even if the user is a low-level user and "should not see targets, because this is 'super' user's domain" it is not logical to give this user "power" for running jobs (if user does not know on which devices this is run this is eve worse).
What do you others think?

**Testflow:**
1. Login as kapua-sys or any other user that has proper permissions
2. Go to user, create a user (e.g. user123) 
3. Select user123 and add Job:Read, Jobs:Write and Job:Execute permissions to it
4. Login as user123 and go to Jobs, create a job (e.g. job0)
5. Select job0 and go to its Steps, add a sample step and try to run the job 
**Observe the error thrown (Error starting  job: The job does not have targets configured).**

**Expected behavior**
I think the correct behaviour should be that "Start", "Stop" and "Restart" buttons are not visible or at least disabled if user does not have Device:Read permissions (or even Device:Write permissions). 

**Screenshot:**
![screenshot 2019-02-18 at 13 07 38](https://user-images.githubusercontent.com/15121999/52950488-9bd80700-337f-11e9-9b7b-6f014cca3fd3.png)

**Version of Kapua**
1.1.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 72.0.3626.81 (Official Build) (64-bit))
- Safari (Version 12.0.3 (14606.4.5))
- Mozilla Firefox (65.0 (64-bit))
- Opera (Version:57.0.3098.116)

**Comment by LeoNerdoG** [comment]
Hey @Coduz,
@ct-ajovanovic and I are brainstorming about this task/issue but would like your input - because it is a permission matter. 
Can you go through the issue and report what you think? It would help a lot 😄 

Regards,
Leo

**Comment by Coduz** [comment]
Hi all, 

I would said that the permission is not required. 

A User can be in charge of running a configured batch job, but does not need to know which are the target involved. 

Regards, 

_Alberto_

**Comment by LeoNerdoG** [comment]
Hi @Coduz,
I am closing this because of the comment above. Please add label `WONT FIX.`
