### ISSUE TITLE
Wrong Error Message When Trying To Update Users's Credentials

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#2420]
If user is trying to change its credentials, Kapua reports that "All the fields with * are mandatory" although Passwords fields here are not mandatory (if user changes only Expiration date). 
The changes are saved successfully but the error message should not be there. 
@ct-anaalbic can you please check this as you were the one to introduce this fix? 😄 

**Testflow:**
1. Login as kapua-sys or any other user that has proper permissions
2. Go to users, create a user (e.g. user123) and add User:Read, User:Write, Credential:Read, Credential:Write permissions
3. Login as user123 and go to users, try to change user123's credentials (e.g. Expiratio Date for Password)

**Expected behavior**
Kapua should not return the error "All fields wiwth * are required" since here are no required fields.

**Screenshot:**
![screenshot 2019-02-19 at 10 13 17](https://user-images.githubusercontent.com/15121999/53006084-d5b71500-3434-11e9-938b-4d8c1d8ab327.png)

**Version of Kapua**
1.1.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 72.0.3626.81 (Official Build) (64-bit))
- Safari (Version 12.0.3 (14606.4.5))
- Mozilla Firefox (65.0 (64-bit))
- Opera (Version:57.0.3098.116)

**Comment by ct-anaalbic** [comment]
@LeoNerdoG Yes, I can fix this.

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
