### ISSUE TITLE
"Step Index" Number Not Reset After Steps Are Deleted From Job

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#2425]
If user deletes on of the steps in Jobs, the step index does not get reset, so there can be only one step indexed with "3" which is not ok, if there is only one step. 

**Testflow:**
1. Login as kapua-sys or any other user that has proper permissions
2. Go to Jobs, create a job (e.g. job0) 
3. Select job0 and go to its Steps, create 3 sample steps
4. Delete steps with index 1 and 2

**Expected behavior**
If step is deleted from a job, the step indexes should be reset (look at the screenshot).

**Screenshot:**
![screenshot 2019-02-19 at 14 49 07](https://user-images.githubusercontent.com/15121999/53019830-e9bf3e80-3455-11e9-9c56-5e068e91cd61.png)

**Version of Kapua**
1.1.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 72.0.3626.81 (Official Build) (64-bit))
- Safari (Version 12.0.3 (14606.4.5))
- Mozilla Firefox (65.0 (64-bit))
- Opera (Version:57.0.3098.116)

**Comment by ct-anaalbic** [comment]
Hi @Coduz.
in this issue, problem is step index. If we have steps with index 0, 1, 2 and if step with index 1 is deleted, than step indexes are not reset, and we have steps with index 0 and 2.
This problem is in database. Can this issue can be resolved on back end side? 

Thank you.
_Regards,
Ana_

**Comment by Coduz** [comment]
Hi @ct-anaalbic ,

yes it can be solved on the backend. 
Can I take over this?

Regards, 

_Alberto_

**Comment by ct-anaalbic** [comment]
@Coduz Yes, you can.

Regards.

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been successfully resolved.
