### ISSUE TITLE
Future Integrations

### ISSUE THREAD

**Issue by maul5** [eclipse/kapua#243]
Hello,

I have question.

Do you happen to know when does Eclipse Kapua integrate with Eclipse Hono, Eclipse hawkBit, Eclipse Californium, Eclipse Leshan?

**Comment by tenderitaf** [comment]
is there any update on this one ?
thanks

**Comment by robenj** [comment]
Hello,

Is there a roadmap on the integration of other technologies from the eclipse foundation ?

**Comment by mbratz** [comment]
Hello,
Any update about the Eclipse Leshan / LWM2M integration?

Thank you

**Comment by mcarrer** [comment]
Eclipse Leshan / LWM2M integration is the roadmap but there is not specific release date as of yet.

**Comment by mbratz** [comment]
Thank you @mcarrer.
