### ISSUE TITLE
"Different" Function Of Refresh Button In Devices -> By Assets -> By Topic 

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#2436]
For now all the refresh buttons have the same function - if user presses them, certain views and fields get refreshed. 
But in Data -> By Device/By Asset refresh button acts like Submit button. If user enters something in "Client ID Prefix" filter field and presses enter, nothing happens - user has to press Refresh. 
i think this should be redesigned or at least renamed. 

**Testflow:**
1. Login as kapua-sys or any other user that has proper pemissions
2. Connect a live Kura device with installed Example Publisher or a similar package that sends (fake) data
3. Go to By Device/By Asset view and enter something into "Cliend ID Prefix" filter field and press Enter key. 
4. Now press Refresh button - observe the difference.

**Expected behavior**
Refresh buttons should always have same function - that is to refresh things. In this case button also works as "submit" button - I think this should be "fixed" and/or enhanced.

**Screenshot:**
![screenshot 2019-02-21 at 10 48 32](https://user-images.githubusercontent.com/15121999/53159503-4c374c80-35c6-11e9-8f5c-42ff6e6ffcb5.png)

**Version of Kapua**
1.1.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 72.0.3626.81 (Official Build) (64-bit))
- Safari (Version 12.0.3 (14606.4.5))
- Mozilla Firefox (65.0 (64-bit))
- Opera (Version:57.0.3098.116)

**Comment by ct-anaalbic** [comment]
Hi @Coduz.

Refresh button in this case works like filter button. Maybe the solution for this problem is to change button from refresh to filter button, and when user press enter key, grid also be filtered. Is it a good idea? 

Thank you.
Regards.

**Comment by lorthirk** [comment]
Yep, sounds fine. You can use `IconSet.FILTER` as the icon and change the name to "Filter". If it looks like a filter and sounds like a filter... then it should be a filter 😆

**Comment by LeoNerdoG** [comment]
I have verified that this issue ahs been resolved.
