### ISSUE TITLE
EndPoints Explained

### ISSUE THREAD

**Issue by gitsaycat** [eclipse/kapua#2442]
Hi - 
We started working with Kapua last year and we're amazed at the functionality thats already available and running stably for months - thank you!

We have a working implementation of a Kapua client based on Node-Red (with request-response conversations for commands and configurations working) i.e. instead of Kura which is heavy for our devices.

We started using Node-Red on the server side as well now to handle application logic end points and are wondering if we're missing the benefit of Kapua EndPoints?
**We wanted to understand Kapua Endpoints functionality but are not very clear on it. Is there any material explaining the basic functionality that we can refer to?**

**Comment by Coduz** [comment]
Hi @gitsaycat ,

`kapua-endpoint` module is a service module that brings into Kapua the capability to register endpoints available of different resources. 

In some demo deployment we used it to register the Broker URL informations.

All the endpoint registered are available in the "Account Setting" view as read-only property.

You need more insight on this feature?

Regards, 

_Alberto_

**Comment by gitsaycat** [comment]
Hi Alberto
Would it be the right way to create application specific end points? For example we're currently creating application specific end points through node-red and internally using the kapua-api to get things done.
Thanks!

**Comment by Coduz** [comment]
Hi @gitsaycat ,

currently that service is able to store created Endpoint infos but it does not do any other task. Other components are not currently using that service to do anything.

So, if you need a place where store your applications endpoint and then retrieve them to do something, you can use that service. 

Some improvements will be done to extend the `EndpointInfo` entity to accept more information, but there is noETA for this.

Regards, 

_Alberto_

**Comment by gitsaycat** [comment]
Hi Alberto - do you mean that we could store the EndPoints and then use the API to access the stored values for different purposes? Essentially use the system as a synchronized store of endpoint information but not much more?

**Comment by Coduz** [comment]
Hi @gitsaycat ,

Yes, correct. The `EndpointInfoService` is just a list of endpoint available. You can build features on them and use their `id` to refer to them, but nothing more.

Regards, 

_Alberto_

**Comment by Coduz** [comment]
Hi @gitsaycat ,

Any news on this?

Regards,

_Alberto_

**Comment by Coduz** [comment]
Hi @gitsaycat ,

Closing this.
Feel free to reopen the issue if you need more help.

Regards, 

_Alberto_
