### ISSUE TITLE
AccessGroups Vs Tags

### ISSUE THREAD

**Issue by gitsaycat** [eclipse/kapua#2443]
Hi 
We understand Devices and AccessGroups to have a 1-1 relationship and a Device can only belong to one group. 
A device can have multiple tags assigned to it on the other hand. 
Apart from this relationship feature are there other system implications of using AccessGroups vs Tags?

**Comment by Coduz** [comment]
Hi @gitsaycat 

With *tags* you can group devices at your preference and then you can use those groups to search for devices with one or more tags.
As you saw a device can have one or more tags assigned.

With *groups* instead you can assign each_device_ to a single group. Then you can assign permission on those groups.

**For example**

| Device  | Group  |
|---------|--------|
| Device1 | Group1 |
| Device2 | Group2 |
| Device3 | null   |

And 

| User  | Permission         |
|-------|--------------------|
| User1 | device:read:group1 |
| User2 | device:read:group2 |
| User3 | device:read:group1 |
| User3| device:read:group2 |
| User4 | device:read:*      |

In this scenario, when *User1* will perform a _query_ to the _DeviceRegistryService_ without any filter will find only *Device1*
The same goes for *User2* which will only find *Device2*
Then *User3* has access to two groups so will find  *Device1* and *Device2*.
While *User4* that has access to all _groups_ will found all three devices. 

This filtering is performed by the implementation of the service, so no special user intervention is required when querying.

Hope that this simple example explains everything.

Regards, 

_Alberto_

**Comment by gitsaycat** [comment]
Perfectly clear now - had another look at Granting Permissions to Users and now it makes sense to see 'AccessGroups' in the dialog there.
Appreciate the detailed explanation...
Thanks!
