### ISSUE TITLE
Refresh/Search Button In Data Not Working Normally

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#2464]
As for now, the "search" button in Devices finds works like this: If user enters any character  or string of charaters that are part of a device's unique client ID, Kapua returns all the devices that have this character in their name. 
So for example if we have "device0", "kapua" and "eth" devices, if user enters "ev", "u" or "th", Kapua will return "device", "kapua" and "eth" respectivelly. 
But in Data user has to enter exact device name/ID in order to be found (if there is device named "device0", there will be no results if user enters "ev", "evic" or "evice0").
This could potentially be solved in PR #2463 but we decided that it would be iasier to trac, implement and test the changes. 

**Testflow:**
1. Login as kapua-sys or any other user that has proper permissions
2. Connect a live Kura device (with several different names) to kapua with installed Demo Heater or Example publisher (for random data) - names should be something similar to "device0", "device1",...
3. in "Client ID Prefix Filter" enter "ev", "evic" or "evice0" nad click search button - Kapua does not show anything

**Expected behavior**
Kapua should show all the devices that have searched character/string in their client ID.

**Screenshot No. 1:**
![screenshot 2019-02-27 at 13 27 40](https://user-images.githubusercontent.com/15121999/53490671-9c198600-3a94-11e9-94fb-585322749ea5.png)

**Screenshot No. 2:**
![screenshot 2019-02-27 at 13 27 49](https://user-images.githubusercontent.com/15121999/53490680-9e7be000-3a94-11e9-8e5b-9eb82f1c03c1.png)

**Version of Kapua**
1.1.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 72.0.3626.81 (Official Build) (64-bit))
- Safari (Version 12.0.3 (14606.4.5))
- Mozilla Firefox (65.0 (64-bit))
- Opera (Version:57.0.3098.116)

**Comment by lorthirk** [comment]
This seems to be closely related to #1740, I'd say almost a duplicate. I think we could leave this as it is now, since I suspect that having that "LIKE" predicate on datastore could take some time. @riccardomodanese, any thoughts?

**Comment by riccardomodanese** [comment]
@lorthirk I confirm, this is the expected behavior of the backend service that retrieves data from ES.
This behavior should be kept as it is unless we will have clear use cases or requests to change it.
And anyway such change will have performance impact for sure.

**Comment by LeoNerdoG** [comment]
I am closing this. 
@lorthirk can you please add "WONTFIX" label to it? 
Thank you,
leo

**Comment by lorthirk** [comment]
I also think the same resolution applies to #1740. What do you think @LeoNerdoG?

**Comment by LeoNerdoG** [comment]
Hey @claudio, I agree.
