### ISSUE TITLE
"N/A" Instead "kapua-sys"In Endpoints And In Settings

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#2465]
If kapua-sys user creates an Endpoint in a child account, under "Created by" there is "N/A" but it should be "kapua-sys" since kapua-sys is absolute admin user and should be able to see everything. 
In bottom Description part there is "kapua-sys" so problem is only in "Created by" column. 
The second problem is that there is "N/A" in Settings which is again not ok (look at second testflow). 

The third problem is that there is "N/A" at Expiration date - it should be "Never". 

**Testflow:**
1. Login as kapua-sys
2. Go to Child Accounts, create an account (e.g. account0)
3. Switch to account0 and go to Endpoints and create an endpoint
**Observe the "Created by" column.**

**Expected behavior**
There should not be "N/A" in Created By column, but "kapua-sys".

**Screenshot:**
![screenshot 2019-02-27 at 08 17 59](https://user-images.githubusercontent.com/15121999/53492426-206e0800-3a99-11e9-99a6-685a98fe5981.png)

**Testflow for Settings:**
1. Login as kapua-sys
2. Go to Child Accounts, create an account (e.g. account0)
3. Switch to account0 and go to its Settings
**Observe the "Created by"  and "Modified By" parameters.**

**Expected behavior**
There should not be "N/A" in Created By column, but "kapua-sys".

**Screenshot:**
![screenshot 2019-02-27 at 14 08 47](https://user-images.githubusercontent.com/15121999/53493295-54e2c380-3a9b-11e9-9e74-b84f88de6ff8.png)

**Version of Kapua**
1.1.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 72.0.3626.81 (Official Build) (64-bit))
- Safari (Version 12.0.3 (14606.4.5))
- Mozilla Firefox (65.0 (64-bit))
- Opera (Version:57.0.3098.116)

**Comment by muros-ct** [comment]
This issue has been closed with PR #2554.

**Comment by LeoNerdoG** [comment]
Hi @muros-ct,
I have checked this and everything is OK except "N/A" in Settings - it should be "Never" if Expiration date is not set (as in Users - see the screenshto bellow). 
Can you please check this also and fix? 

![Screenshot 2019-05-03 at 09 59 13](https://user-images.githubusercontent.com/15121999/57126139-2380bf80-6d8c-11e9-9215-af1cf4449659.png)
