### ISSUE TITLE
Should User See His Account If He Has No "Account:Read" Permissions?

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#2469]
This is probably more a question than an issue. 
If user does not have Account:Read permissions, he can still see his account in the upper right corner (e.g. user0@acccunt0) - is this OK? 

**Testflow:**
1. Login as kapua-sys or any other user with proper permissions
2. Go to Child Accounts, create an account (e.g. account0)
3. Switch to account0 and create a user (e.g. user0) and add for example Device_connection:Read permission to him.
4. Login as user0 and observe the account name in the upper right corner. 

**Expected behavior**
Should account name be visible to user, although he does not have Account:Read permission?

**Screenshot:**
![screenshot 2019-02-28 at 08 37 04](https://user-images.githubusercontent.com/15121999/53549273-19480800-3b34-11e9-9388-99cc550f8c99.png)

**Version of Kapua**
1.1.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 72.0.3626.119 (Official Build) (64-bit))
- Safari (Version 12.0.3 (14606.4.5))
- Mozilla Firefox (65.0.1 (64-bit))
- Opera (Version:58.0.3135.79)

**Comment by ct-ajovanovic** [comment]
Hi @Coduz 
Can you please take a look at this issue? 
Should the account name in question be visible, if the user does not have the `account:read` permission?
Thanks
_Aleksandra_

**Comment by lorthirk** [comment]
I'd say that he should be able to see it. It's its account after all; the `account:read` permission is to allow him to see its *child* accounts rather than its own account. Also, most usernames are resolved pretty much everywhere on the "Created By" and "Modified By" columns regardless of the authorization.
