### ISSUE TITLE
Edit Windows Too Small For Long Device/User Names

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#2477]
If device or user name is too long, they are not displayed properly when editing them (see screenshot bellow).

**Testflow:**
1. Login as kapua-sys or any other user that has proper permissions
2. Go to Device/Users and create an item with verey long name (dashes must be included)
3. Select the newly created item and click Edit

**Expected behavior**
Either windows should be enlarged or names should be shortened in order to see all the info in edit windows.

**Screenshot:**
![screenshot 2019-03-04 at 10 15 43](https://user-images.githubusercontent.com/15121999/53722999-0c465400-3e67-11e9-9ef5-be498aa1cea6.png)

**Version of Kapua**
1.1.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 72.0.3626.119 (Official Build) (64-bit))
- Safari (Version 12.0.3 (14606.4.5))
- Mozilla Firefox (65.0.1 (64-bit))
- Opera (Version:58.0.3135.79)

**Comment by ct-anaalbic** [comment]
Hi @lorthirk.
I'am workint on this issue. With device dialogs i didn't have any problem, but in user edit dialog when I set auto height shadow not disappeared. It looks like this:
![image](https://user-images.githubusercontent.com/45655642/53941093-83722700-40b7-11e9-92cd-519fe765e7cf.png)
I tryed to remove this shadow, but unsuccessful. My idea is to set some limit to user name, like in accounts. Is this good solution? 

Thank's.
Regards.

**Comment by ct-anaalbic** [comment]
Hi @lorthirk. I found other solution for this problem. Like I commented, this shadow on screenshot above can not be removed. My second solution is on screenshot bellow.

![image](https://user-images.githubusercontent.com/45655642/55713564-39030380-59f1-11e9-9119-d5616627d179.png)

Are you agree with this?

Regards,
_Ana_

**Comment by lorthirk** [comment]
LGTM! @LeoNerdoG, do you think this is coherent enough with the rest of the UI?

**Comment by LeoNerdoG** [comment]
Hey @lorthirk,
I would rather see that we use method `autoheugth`, but as we saw, this does not work, so from my perspective looks OK. Also this is in style with rest of Kapua.

**Comment by LeoNerdoG** [comment]
@ct-anaalbic,
I have found one more problem with this solution. If username/device name contains only "O" letter (look at the screenshot), part of the name is outside of the tootlitp. 
Can you please check this (maybe it is a GWT issue?)? 

This happens in Chrome, Mozilla, Safari and Opera. 

![Screenshot 2019-05-03 at 12 33 50](https://user-images.githubusercontent.com/15121999/57132487-0fdf5400-6da0-11e9-9ca6-b5d4d890e246.png)

**Comment by ct-anaalbic** [comment]
@LeoNerdoG ,
I will check now.

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
