### ISSUE TITLE
MQTT Topic / Message

### ISSUE THREAD

**Issue by Sladjan-Tissa** [eclipse/kapua#248]
Hi,

I do not want to use kura client for sending mqtt messages.
I would like to use any software, like windows mqtt_publish.exe from mosquito, to send a message to kapua.

What is the exact topic that I should use in order for kapua, ActiveMQ, to accept it?

Probably something like #account/client-id/etc….

Thanks, Tissa.

**Comment by Coduz** [comment]
Hi @Sladjan-Tissa,

If you don't wanna to use kura framework you can. 
Until now, Kura is the only framework that we support. 
In your scenario you can emulate the Kura messaging protocol and you'll be able to publish messages on Kapua.
You can refer to this [document](https://eclipse.github.io/kura/ref/mqtt-namespace.html) for more information.

Regards, 

_Alberto_

**Comment by Sladjan-Tissa** [comment]
Thanks...

**Comment by kartben** [comment]
A couple months ago I put together a quick&dirty simulator in Node.js that you may want to use as a basis for understanding how the payload of the messages shoud look like. See https://github.com/kartben/kura-simulator

**Comment by Sladjan-Tissa** [comment]
Indeed, it is very useful.
Thank you Kartben.
