### ISSUE TITLE
Internal Error When call rest api /{scopeId}/data/messages

### ISSUE THREAD

**Issue by 274336317** [eclipse/kapua#2514]
**Describe the bug**
I invoke /{scopeId}/data/messages from my code, and the server returned HTTP/1.1 500 Internal Server Error .
I reviewed the  runtime log of kapua-api, there was a http 404 error after I invoke /{scopeId}/data/message and ERROR o.e.k.a.a.c.e.ThrowableMapper - Severe error!

**[Stacktrace]**

383725 [I/O dispatcher 1] DEBUG org.elasticsearch.client.RestClient - request [GET http://es:9200/1475789760546563171-*/message/_search] returned [HTTP/1.1 200 OK]
383725 [I/O dispatcher 1] DEBUG o.a.h.i.n.client.InternalIODispatch - http-outgoing-0 [ACTIVE] [content length: 445; pos: 445; completed: true]
383745 [qtp913190639-18] ERROR o.e.k.a.a.c.e.ThrowableMapper - Severe error!
javax.ws.rs.NotFoundException: HTTP 404 Not Found
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:323)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)

**Version of Kapua**
docker-Latest

**Comment by lorthirk** [comment]
Hi,

Is the Elasticsearch container running? If so, is the url `http://es:9200` correct? Can you reach that REST API from an external HTTP client?

**Comment by 274336317** [comment]
> Hi,
> 
> Is the Elasticsearch container running? If so, is the url `http://es:9200` correct? Can you reach that REST API from an external HTTP client?

I copied http://localhost:9200/1475789760546563171-*/message/_search to my firefox, and the request returned data in json format.
**RETURNED DATA**
{"took":2,"timed_out":false,"_shards":{"total":1,"successful":1,"failed":0},"hits":{"total":560,.......

**Comment by lorthirk** [comment]
Could you please share the original request you're executing in your code?

**Comment by 274336317** [comment]
**Login**
http://192.168.0.111:8081/v1/authentication/user

**Fetch Devices**
http://192.168.0.111:8081/v1/FHsO99iJZGM/devices?status=DISCONNECTED&offset=0&limit=50
**Fetch Channels**
http://192.168.0.111:8081/v1/FHsO99iJZGM/data/channels
**Fetch Data Of Given Device**
http://192.168.0.111:8081/v1/data/messages?scopeId=FHsO99iJZGM&clientId=test1&channel=tFb2n1F%2Bjf2MugH8H55pPDgyC4cXc%2BylC343sboYrzQ%3D&strictChannel=true&startDate=2019-01-19T03%3A15%3A05.903&endDate=2019-09-19T03%3A15%3A05.903Z&offset=0&limit=50
HTTP/1.1 500 Internal Server Error [Access-Control-Allow-Origin: *, Access-Control-Allow-Methods: GET, POST, DELETE, PUT, Access-Control-Allow-Headers: X-Requested-With, Content-Type, Authorization, Content-Length: 52, Server: Jetty(9.4.12.v20180830)] org.apache.http.conn.BasicManagedEntity@ea1a8d5

**Comment by lorthirk** [comment]
Does the interaction end here? No other REST calls after the one to `/data/messages`?

**Comment by 274336317** [comment]
> Does the interaction end here? No other REST calls after the one to `/data/messages`?

yes, the interaction end here.

**Comment by 274336317** [comment]
**My Docker Containers**
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS              PORTS                                                                                                     NAMES
46a412a8ea08        kapua/kapua-console:latest         "/bin/sh -c /var/o..."   50 minutes ago      Up 50 minutes       0.0.0.0:8080->8080/tcp, 0.0.0.0:8443->8443/tcp, 8778/tcp                                                  compose_kapua-console_1
e488b767e65a        kapua/kapua-api:latest             "/bin/sh -c /var/o..."   50 minutes ago      Up 50 minutes       8778/tcp, 0.0.0.0:8081->8080/tcp, 0.0.0.0:8444->8443/tcp                                                  compose_kapua-api_1
bb0f791e1bb0        kapua/kapua-broker:latest          "/bin/sh -c /var/o..."   50 minutes ago      Up 50 minutes       8161/tcp, 0.0.0.0:1883->1883/tcp, 0.0.0.0:8883->8883/tcp, 8778/tcp, 0.0.0.0:61614->61614/tcp, 61615/tcp   compose_broker_1
b5fe0bcb3f2e        elasticsearch:5.4.0                "/docker-entrypoin..."   50 minutes ago      Up 50 minutes       0.0.0.0:9200->9200/tcp, 0.0.0.0:9300->9300/tcp                                                            compose_es_1
50304061be24        kapua/kapua-events-broker:latest   "/run-artemis"           50 minutes ago      Up 50 minutes       0.0.0.0:5672->5672/tcp                                                                                    compose_events-broker_1
053a780968d8        kapua/kapua-sql:latest             "/bin/sh -c /var/o..."   50 minutes ago      Up 50 minutes       0.0.0.0:3306->3306/tcp, 0.0.0.0:8181->8181/tcp, 8778/tcp                                                  compose_db_1

**Comment by lorthirk** [comment]
It looks like the `scopeId` is missing from the URL after `/v1` in your last call. Could you please check?

**Comment by 274336317** [comment]
I'm very sorry for my mistake!
Thank you so much for your patient!
**It's very kind of you!**

**Comment by lorthirk** [comment]
You're welcome! Don't worry, even the best make mistakes :)
