### ISSUE TITLE
New user cannot log on

### ISSUE THREAD

**Issue by ctron** [eclipse/kapua#253]
Creating a new user in state "enabled" creates a user which cannot log on to the system.

When the user tries to log on the following message is shown instead: Subject does not have permission [user:read:1:*]

```
11:42:03,291 [qtp1145319246-115] WARN  KapuaExceptionHandler:90  - RPC service non-application error
org.apache.shiro.authz.UnauthorizedException: Subject does not have permission [user:read:1:*]
	at org.apache.shiro.authz.ModularRealmAuthorizer.checkPermission(ModularRealmAuthorizer.java:334)
	at org.apache.shiro.mgt.AuthorizingSecurityManager.checkPermission(AuthorizingSecurityManager.java:141)
	at org.apache.shiro.subject.support.DelegatingSubject.checkPermission(DelegatingSubject.java:210)
	at org.eclipse.kapua.service.authorization.shiro.AuthorizationServiceImpl.checkPermission(AuthorizationServiceImpl.java:60)
	at org.eclipse.kapua.service.user.internal.UserServiceImpl.find(UserServiceImpl.java:170)
	at org.eclipse.kapua.app.console.server.GwtAuthorizationServiceImpl.establishSession(GwtAuthorizationServiceImpl.java:178)
	at org.eclipse.kapua.app.console.server.GwtAuthorizationServiceImpl.login(GwtAuthorizationServiceImpl.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

**Comment by Coduz** [comment]
On create user you have to associate the permissions. 
In order to be able to login you need some basic permissions.
Anyway until #254 is not fixed and #218 are closed is not possible to add permission to console.

This has happened because we were focusing with the development of the new console with Patternfly. Then the Patternfly-based console has encountered a stopper issue, so now we are working to fix all the things that we have not take care into the GXT-based console, that will be released on the first Kapua release. 

So I ask you to not open new issues on the GXT-based console as we are already aware of most of them and we are already working to six them.

Thanks, 

_Alberto_

**Comment by ctron** [comment]
Well I think it is important to document all issues which come up, as I am not aware of what you know and don't know. Unless of course you consider GXT deprecated.

**Comment by maul5** [comment]
Where can I find GXT 2.2.5 documentation?

**Comment by Coduz** [comment]
@ctron I think its important too, but I would avoid to generate a issu-hell for problems that we already adressing. It would make more sense if you collect all problems in a single issue with a checkbox list of problem that you encountered.

@maul5  GXT 2.2.5 documentation has been discontinued and is no longer available from the manufacturer site. Also for this reason we first planned to do the first release of Kapua with a patternfly-based console and deprecate the GXT-based one, but a missing feature on Patternfly side forced us to continue the development with the GXT-based console and postpone the release of the Patternfly one.

**Comment by maul5** [comment]
Thank you.

When is the first release of Kapua?

and

Why are Administration Console Capture Image of this page(http://projects.eclipse.org/projects/iot.kapua) and Kapua demo different?

**Comment by ctron** [comment]
@Coduz The problem for me is that I don't know, which issues you already know and which not. Adding multiple issues in a single issue has never been a good approach and beside that I cannot add any additional information which I have with this approach. So in the end you will have a list, full of missing information, which IMHO doesn't help either.

If you are already working on this, then this is great. And there is no need to waste any time commenting on those issues. But if in the final release it is not possible to stop a bundle on the gateway, because the issues was not tracked, then IMHO this is a bigger problem than a few issues opened in GitHub.

**Comment by maul5** [comment]
@Coduz Excuse me, Is there any other way without using the console?
