### ISSUE TITLE
Modifying user permissions does not work

### ISSUE THREAD

**Issue by ctron** [eclipse/kapua#254]
Opening a user and modifying permissions does not work:

Steps to reproduce:
* Open user details
* Check previously unchecked user permission
* Press "Submit"

→ Nothing happens

Expected result: record gets updated or error message shown instead

**Comment by lorthirk** [comment]
Hi @ctron,

The Users view is currently being refactored (issue #218). I'm working on this right now.

**Comment by ctron** [comment]
Ok cool. So maybe the two additional issues I just opened help you then. Or maybe you already know about them. Just close them if you already covered those.
