### ISSUE TITLE
Validation errors may be hidden from the user

### ISSUE THREAD

**Issue by ctron** [eclipse/kapua#255]
Validation errors, blocking the dialog to "submit", may stay out of sight for a user:

* Open user edit dialog
* Switch to "Permissions"
* Press "Submit"

→ Nothing happens
→ The first tab (when switching back) shows two field validation errors (password)

Expected result: The user should be made aware of the fact that the dialog cannot be submitted due to validation errors.

**Comment by Coduz** [comment]
Please, see answer in [here](https://github.com/eclipse/kapua/issues/253) and stop opening issue.

**Comment by lorthirk** [comment]
This will be indirectly fixed when #271 will be merged, since there will be no tabs in the User Add / Edit dialogs.
