### ISSUE TITLE
How Does Grafana Access The Data Stored In ElasticSearch By Kapua 

### ISSUE THREAD

**Issue by 274336317** [eclipse/kapua#2555]
I plan to use grafana to analysis the data stored in elasticsearch by kapua.
I googled the solutions, and some guys suggested that grafana can get the data stored in elasticsearch of kapua by "proxy"(eg:https://github.com/ctron/simulating-iot/issues/2).
Does the kapua provide api to grafana to get data stored in elasticsearch?
If not, Should I create a "proxy"?Are there other solutions?
Thanks!

**Comment by lorthirk** [comment]
Currently we have no API specific to Grafana. However you can access the Elasticsearch API directly from the ES container, who is listening on ports 9200 and 9300:

**Comment by muros-ct** [comment]
Try to check out this video tutorials.
https://www.youtube.com/playlist?list=PL9se1QsZWBnX02Nb53G0n2l1rw3F4MjMR

Uroš
