### ISSUE TITLE
Unable to edit user details without entering a new password

### ISSUE THREAD

**Issue by ctron** [eclipse/kapua#256]
When you want to edit user details it is currently required to also assign a new password. It is possible to enter the same password though.

However, traditionally, editing user information (like permissions and telephone number) is different tasks and should not also require to update the password. Which should not be known by the person editing the current user anyway.

**Comment by Coduz** [comment]
Please, see answer in [here](https://github.com/eclipse/kapua/issues/253) and stop opening issue.

**Comment by lorthirk** [comment]
The refactored User Edit dialog won't show the Password and Confirm Password field anymore after #271 is merged.
