### ISSUE TITLE
Calling the REST API from Javascript to set device configuration fails

### ISSUE THREAD

**Issue by gitsaycat** [eclipse/kapua#2605]
Hi 
Firstly I should thank you all for helping get me to this point - the whole confusion between deviceId and clientId ( #2467  )  was a big hurdle and thats behind us now.

1.0.3:
Currently we are facing problems when sending configuration change requests from Javascript to the REST API.

                        devicesApi.deviceConfigurationComponentUpdate(scopeId, deviceId, "MYPID", 
                            componentConfig, opts, callback);                        

The target device receives the request as follows, but the request is lacking the actual property names:

> 
> <?xml version="1.0" encoding="UTF-8"?>
> <esf:configurations xmlns:esf="http://eurotech.com/esf/2.0" xmlns:ns0="http://www.osgi.org/xmlns/metatype/v1.2.0" xmlns:ocd="http://www.osgi.org/xmlns/metatype/v1.2.0">
>    <esf:configuration pid="MYPID">
>       <esf:properties/>
>    </esf:configuration>
> </esf:configurations>

I've tried sending the properties as follows:

                        componentConfig.properties = {};
                        componentConfig.properties["KEY1"] = "VAL1";

Can you please confirm if I'm doing something wrong?

Thanks, gitsaycat

**Comment by lorthirk** [comment]
The schema of the body depends on the Configuration Component itself, so it's hard to provide a default schema. You could check the current schema by just reading a Device Configuration (`/{scopeId}/devices/{deviceId}/configurations` for all configurations, or /{scopeId}/devices/{deviceId}/configurations/{componentId} for a single component), and then issue a new Device Configuration PUT request by following the same schema.

**Comment by gitsaycat** [comment]
Hi @lorthirk - that is a great idea and I tried it out immediately. 
Strangely - the device always gets that same empty configuration block:

> 
> esf:configurations xmlns:esf="http://eurotech.com/esf/2.0" xmlns:ns0="http://www.osgi.org/xmlns/metatype/v1.2.0" xmlns:ocd="http://www.osgi.org/xmlns/metatype/v1.2.0">
> <esf:configuration pid="MYPID">
> esf:properties/
> </esf:configuration>
> </esf:configurations>

I tried sending back the exact response of a full configuration dump - but still no luck. 
The API does use the PID part - so if I change it to something else, the device gets it, but it gets none of the properties 
Any ideas?

**Comment by lorthirk** [comment]
So, are you saying that you have this behaviour with all the services installed? Also with the ones that comes out of the box with the device?

**Comment by gitsaycat** [comment]
Not sure what you mean by 'out-of-the-box' - but brief background:
Our Kapua client is pure Node_red. 
We have all interactions working - can register birth, send data, receive data, register CMD-V1, CONF-V1 through Kapua as well as through API.  
The only bit that is now not working is when we send configuration update through the API. 
Does that clarify things?

**Comment by lorthirk** [comment]
Oh, yeah, sorry. I was talking about a standard Kura device, not thinking you're working on Node RED. And this actually the answer: in order to use the Configuration endpoint the app must support the CONF-V1 application from Kura, and in order to do so it has to publish a BIRTH message where it advertise Kapua that he supports it.

You can read more about Kura applications [here](http://eclipse.github.io/kura/ref/mqtt-namespace.html).

**Comment by gitsaycat** [comment]
Hi Claudio
As mentioned earlier - BIRTHs etc are all working fine. 
We have got CONF-V1 working fine with our client. 
We can seamlessly edit / view configurations through Kapua and you can also GET configurations through the API. 
**We are only missing SET configurations through the API.**
Thanks, gitsaycat

**Comment by lorthirk** [comment]
Sorry for having misunderstood. I have to investigate a bit further then. Of course I guess you have no errors in logs, isn't it?

**Comment by gitsaycat** [comment]
Hi Claudio - no problem at all - as Kapua users we all appreciate your patience with us.
Indeed there are no errors as far as I can see. Everything works as expected - just that the device side does not get the property elements.

Would just highlight 2 points again:

- The client gets the configuration update message - just that the message does not contain the nested property elements
- The configuration XML seems to only get the PID value from the JSON object we construct for the API call. Nothing else.

Thanks, gitsaycat

**Comment by Coduz** [comment]
Hi @gitsaycat ,

have you find a way to get around this issue? 

Regards, 

_Alberto_

**Comment by gitsaycat** [comment]
Hi Alberto 
Unfortunately no workaround to this one yet - we will give this one another go and then report back to this forum.
Thanks.
