### ISSUE TITLE
 Failure to find org.eclipse.kapua.external:swagger-ui:jar:2.1.4-CQ-10792

### ISSUE THREAD

**Issue by Xingxv** [eclipse/kapua#2639]
Hello,
following error occurred when i `mvn clean install`

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.0.1:unpack (unpack-swagger-ui) on project kapua-rest-api-web: Unable to find/resolve artifact.: Failure
 to find org.eclipse.kapua.external:swagger-ui:jar:2.1.4-CQ-10792 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until th
e update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :kapua-rest-api-web

**Comment by lorthirk** [comment]
As stated in [developer-guide/en/building.md](https://github.com/eclipse/kapua/blob/develop/docs/developer-guide/en/building.md):

> Kapua is being compiled with Maven.
>
> In order to perform a full build of Kapua first you have to build the external resources of Kapua with the following command in the root of the Git repository:
>
> `mvn clean install -f external/pom.xml`
> Then you can run the Kapua full build issuing the command:
>
> `mvn clean install`
> Don't forget to also add the console Maven profile if you are interested in building the Web Console as well:
>
>`mvn clean install -Pconsole`

**Comment by Xingxv** [comment]
thank you.
