### ISSUE TITLE
"compose_broker_1" container not properly started

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#2654]
After running all the commands necessary to run the docker, "compose_broker_1" container does not start properly. Docker prints out that "creating compose_broker_1.....DONE" but when running "docker ps" command, there is no broker container running. After executing command "docker-deploy.sh" command again, the container starts properly. 
Can anybody confirm this? This happens on MAC and Windows machines. 

**Testflow:**
1. Remove .m2 repository from local machine
2. Go to kapua folder (or clone it if you do not have it yet)
3. Run command `mvn clean install -f external/pom.xml`ž
4. Run command `mvn clean install -DskipTests -Pconsole,docker`
5. After the build completes, start docker containers in `deployment/docker/unix/docker-deploy.sh` (if you are on windows machine run them in folder `deployment/docker/win/`)
6. Run command `docker ps` and observe the containers

**Expected behavior**
If user runs docker deploy command, all the containers should be started properly and not partially. This happens after clean install on MAC and Windows machines.

**Screenshot:**
![Screenshot 2019-07-12 at 16 10 34](https://user-images.githubusercontent.com/15121999/61134739-88f5d880-a4c0-11e9-982d-bd6697a37d9c.png)

**Version of Kapua**
1.1.0-SNAPSHOT

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 74.0.3729.131 (Official Build) (64-bit))
- Safari (Version 12.1)
- Mozilla Firefox (66.0.3 (64-bit))
- Opera (Version:60.0.3255.70)

**Comment by Coduz** [comment]
Hi Leo,

this should have been fixed by this https://github.com/eclipse/kapua/pull/2650

You still have the problem even after using the latest `develop`?

Regards, 

_Alberto_

**Comment by LeoNerdoG** [comment]
hey Alberto, I am having troubles today the whole day. I am figuring what is the problem exaclty. If/when I found out, i will report. Please leave it open until then. 

Regards,
leo

**Comment by Coduz** [comment]
Hi @LeoNerdoG ,

Any update on this issue? 

Regards, 

_Alberto_

**Comment by LeoNerdoG** [comment]
Hey @coduz, 
I think there was a problem on my machine (if I remember correctly I rebooted it and it was OK). I will close this for now and if it happens again, I will investigate it.

**Comment by Coduz** [comment]
We should add the message that before submit an issue, reboot your machine and try again 😂😂😂
