### ISSUE TITLE
Kapua UI can show inconsistent connection state

### ISSUE THREAD

**Issue by ctron** [eclipse/kapua#267]
The Kapua UI can show a device as "disconnected" and "connected" at the same time (see screenshot):

![screenshot from 2017-02-09 14-06-17_sim](https://cloud.githubusercontent.com/assets/202474/22784697/5c583112-eed1-11e6-9a52-5b997ad7ac35.png)

**Comment by Coduz** [comment]
duplicate #68

**Comment by ctron** [comment]
It turned out to be a corrupt database. Not sure how the system managed to get into this state though. Clearing the database and restarting the broker did work.

**Comment by kcsj17** [comment]
I'm having a similar issue. i have the openshift setup. which is the database that has to be cleared. is it the elasticsearch?

**Comment by lorthirk** [comment]
@kcsj17 no, it's H2
