### ISSUE TITLE
Is there a best-practice to upgrade to a newer Kapua Version?

### ISSUE THREAD

**Issue by MEGLALS** [eclipse/kapua#2680]
We are currently using Kapua version 1.0.0-M7 and are wondering if there is a 'official' way or best practice to upgrade to the current version without loosing our entire configuration. 
We have tried multiple methods but always ran into issues regarding the kapua-sys user or the events-broker.

**Comment by lorthirk** [comment]
Well... the general rule is to simply let Liquibase perform its migrations when launching the new version. Anyway, since 1.0.0-M7 is quite an old version, I can see that something may go wrong. It would be great if you could post some logs in order to understand your issues.

**Comment by MEGLALS** [comment]
So we are deploying Kapua via docker. How exactly would we have to do an update to use Liquibase for the migrations? We only tried to back up the whole database, redeploy the docker containers with a newer kapua version and then restore the database manually which led to the problems but apparently this is not the way an upgrade should be done.

**Comment by lorthirk** [comment]
My suggestion is to stop all the containers but the SQL one (so using `docker stop` and `docker rm` instead of `docker-undeploy.sh`), and then deploy again with the new images. Liquibase is set to run by default.

**Comment by MEGLALS** [comment]
I tried this method with multiple configurations (1.0.0-M7  -> 1.0.6; 1.0.0 -> 1.0.6; 1.0.0-M7 -> 1.0.0)  an the following execution:
1. stopping and removing all containers except SQL
2. changing the  IMAGE_VERSION to the desired version
3. runnig the deploy script
However after every run the entire configuration was gone and the database wiped. Is it necessary to deploy all containers except the sql one manually in order to keep the data? And if so how can the enviroment variables like a custom kapua-sys password be set?
In addition to this I noticed an error when going from 1.0.0-M7 to versions >=1.0.0: 
After the update when trying to navigate to certain menu points  in the web console (connections, users, endpoints) I get the following error message:

![grafik](https://user-images.githubusercontent.com/54319494/63421895-abf1a180-c409-11e9-99ed-f0656f495fa8.png)

I only noticed this after updating in this specific way.

**Comment by lorthirk** [comment]
Well, all SQL data is in the SQL container (`compose_db_1`), so if you keep the container from being removed (i.e. you **don't** use `docker-undeploy.sh`) all data should still be there when you deploy again. Are you sure the container doesn't get deleted somehow?

For the GWT error, have you tried cleaning your browser's cache when changing version?

**Comment by MEGLALS** [comment]
I was able to find out why the sql container kept getting removed:
In the deployment script, the command used to deploy the containers is 'docker-compose -f ${SCRIPT_DIR}/../compose/docker-compose.yml up -d'. This however also stops and recreates all containers whose images have changed even when they are currently running. In order to prevent this and keep the database I just added the '--no-recreate' option to the command which prevents it from altering running containers. For now everything seems to have worked out but I have yet to test this with an altered kapua-sys user password and enabled ssl encryption. This obviously also prevents the database container from being updated so after an update that container stays at version 1.0.0-M7. Could that become a problem?

**Comment by lorthirk** [comment]
Well, it's very unlikely that the DB container will change in the future. However, once the other containers have been upgraded, you can do that backup and restore on the new image you were talking about.

**Comment by MEGLALS** [comment]
After trying this method with a test system that is similar to our productive system (ssl, changed passwords) everything seems to have worked out. But I noticed that the kapua-broker user, which seems to be a default user account in versions >1.0.0, was not created. That is different from my previous test runs were it was created after updating the containers.  What could cause this behaviour and will this interfere with the systems functionality?

**Comment by lorthirk** [comment]
`kapua-broker` user should definitely be seeded by default. There's no Liquibase migration that deletes it in any version, so again, you should definitely have it. Anyway is by no means a special user; should you need it, you can create another user named `kapua-broker` with the `broker:connect` permission.

**Comment by MEGLALS** [comment]
What kind of functionality does the kapua-broker user exactly provide? And is it necessary to deposit it's password in an environment variable like with the kapua-sys user? 
Also, I still have the problem that the kapua-sys user gets locked after some time. Is the procedure for changing the password of the kapua-sys user still the same as described in #2031 or have there been changes to how changing the user's password works?

**Comment by lorthirk** [comment]
the `kapua-broker` is simply a pre-seeded user with the `broker:connect` permission, so that it can be used on a device to connect to the broker and send data. In any aspect is a normal user, just like the ones you can create on Kapua; so, no, there's no special treatment for its password whatsoever.

I can't understand exactly what you mean with the second part of your comment, about the `kapua-sys` user being locked out. If you think this could be a potential bug please file a new issue; otherwise let me direct to our [Gitter room](https://gitter.im/eclipse/kapua) to talk anything about Kapua. I'm going to close this issue now; feel free to reopen it if you have something to add regarding the original question.
