### ISSUE TITLE
Full support of DEPLOY-V2 request parameters.

### ISSUE THREAD

**Issue by stefanomorson** [eclipse/kapua#2689]
In order to execute a package deployment interactively through the UI I needed to specify the credentials required to securely connect to the remote http repo where the package was stored. I realized then that the UI does not support this use case. However, as defined in Kura doc, DEPLOY-V2 cloudlet not only allows to specify repo credentials in the request, but has many other request parameters that allow to fine tune the way package artifacts are downloaded and installed.  

I would like that more of the available parameters are supported by the UI, the API and the device jobs. The complete list of parameters is reported in Kura documentation for namespace [DEPLOY-V2 namespace](https://eclipse.github.io/kura/ref/mqtt-namespace.html#deploy-v2)

By looking at all the parameters there are some that a user may find *too technical*, for example **dp.download.notify.block.size**. Nonetheless they are sometimes useful to make the deployment work in particular situations. In these cases good average defaults should be adopted. Some of these have been defined already such as in the case of the above mentioned **dp.download.notify.block.size**  which is 5% of the whole size if it is not overridden by the caller.

**Comment by Coduz** [comment]
| Metric | Supported | Will be supported? |
|--------|-----------|--------------------|
| dp.job.id | Yes | Already supported |
| dp.uri | Yes | Already supported |
| dp.name | Yes | Already supported |
| dp.version | Yes | Already supported |
| dp.download.protocol | No | Maybe? |
| dp.download.block.size | No | No |
| dp.download.block.delay | No | No |
| dp.download.notify.block.size | No | No |
| dp.download.timeout | No | Maybe? |
| dp.download.resume | No | No |
| dp.download.force | No | No |
| dp.download.username | No | Yes |
| dp.download.password | No | Yes |
| dp.download.hash | No | Yes |
| dp.install | Yes | Already supported |
| dp.install.system.update | No | Yes |
| dp.install.verifier.uri | No | Maybe? |
| dp.reboot | Yes | Already supported |
| dp.reboot.delay | Yes | Already supported |

**Comment by Coduz** [comment]
Next version

| Metric | Supported | Will be supported? |
|--------|-----------|--------------------|
| dp.job.id | Yes | Already supported |
| dp.uri | Yes | Already supported |
| dp.name | Yes | Already supported |
| dp.version | Yes | Already supported |
| dp.download.protocol | No | No |
| dp.download.block.size | No | Advanced. |
| dp.download.block.delay | No | Advanced. |
| dp.download.notify.block.size | No | Advanced.  |
| dp.download.timeout | No | Advanced |
| dp.download.resume | No | No |
| dp.download.force | No | No |
| dp.download.username | No | Yes |
| dp.download.password | No | Yes |
| dp.download.hash | No | Yes |
| dp.install | Yes | Already supported |
| dp.install.system.update | No | Yes. Show it as "Type" Combo with `dp` or `executable` |
| dp.install.verifier.uri | No | Advanced |
| dp.reboot | Yes | Already supported |
| dp.reboot.delay | Yes | Already supported |
