### ISSUE TITLE
Use non-root users for docker images

### ISSUE THREAD

**Issue by ctron** [eclipse/kapua#277]
Docker containers allow the use of non-root users, which is especially important when running inside of OpenShift. However our images (as many others) don't take care of this.

I would suggest to:
* Rebase the provided docker images to be based on `java:8-alpine` which is only ~40MB for the whole image
* Create a new user inside this image (with `adduser`)
* Use this dedicated user inside this image for running

This way we can prepare the docker containers during build time to use this user and won't run into any permission issues later on.

**Comment by hekonsek** [comment]
+1

**Comment by mcarrer** [comment]
Closed
