### ISSUE TITLE
Missing APP_NAME inTranslatorAppConfigurationKapuaKura

### ISSUE THREAD

**Issue by muros-ct** [eclipse/kapua#279]
Before committing device registry integration tests, I rebased to develop and tests are failing.
I found out that there was change to TranslatorAppConfigurationKapuaKura, where
 
`propertiesDictionary.put(DeviceConfigurationAppProperties.APP_NAME, ConfigurationMetrics.APP_ID);`
  
was removed from static initializer.

This APP_NAME is used in translateChannel method, just couple of lines further that class and it causes NPE.

**Comment by Coduz** [comment]
Yes, this bug has introduced by the refactoring of @ctron .

**Comment by Coduz** [comment]
Thanks for the fix @muros-ct
