### ISSUE TITLE
web-console and rest-api unable to log

### ISSUE THREAD

**Issue by riccardomodanese** [eclipse/kapua#28]
I don't know exactly from when but currently, both the web-console and the rest-api, don't log anything in the tomcat log file.
Looking at the web-apps startup log and at the libraries inside the wars we are missing to include the log4j bridge (so slf4j-log4j12 arctifact).
This arctifact is already included in the root pom (toghether with slf4j-api), but for some reason in the generated war it's present only the slf4j-api arctifact.

**Comment by hekonsek** [comment]
I have added `slf4j-log4j12` to those two module. We should also add `slf4j-log4j12` in test scope for the unit tests.

**Comment by hekonsek** [comment]
Done.
