### ISSUE TITLE
DeviceRegistryServiceImpl::update does not process 'connectionId'

### ISSUE THREAD

**Issue by ctron** [eclipse/kapua#292]
To me it looks as if there is a missing update/set for the `connectionId` when the entity gets updates in [/DeviceRegistryServiceImpl.java:63](https://github.com/eclipse/kapua/blob/36a029eace8d0eeac41b9dd6b12b25b88ce64c70/service/device/registry/internal/src/main/java/org/eclipse/kapua/service/device/registry/internal/DeviceRegistryServiceImpl.java#L63).

Looking at a caller, like [DeviceLifeCycleServiceImpl.java:105](https://github.com/eclipse/kapua/blob/ddd3d4f835175a081492c0bb78bf143d99b99909/service/device/registry/internal/src/main/java/org/eclipse/kapua/service/device/registry/lifecycle/internal/DeviceLifeCycleServiceImpl.java#L105) one can see that the `connectionId` is set, but following the call path inside the actual update method, it never gets assigned to the entity.

**Comment by Coduz** [comment]
This issue has been fixed in 7326ea064c3673c5aadfb8bcc408395522e5b848 as part of other changes to the Device and DeviceConnection model and services.

Now the connectionId is set correctly.

We can close this.

Regards, 

_Alberto_
