### ISSUE TITLE
Inconsistent internal state when gateway connects with 'kapua-sys' account

### ISSUE THREAD

**Issue by ctron** [eclipse/kapua#294]
When a gateway (accidentally) connects with the credentials of the user `kapua-sys` the internal device and device connection state gets inconsistent.

Additionally a few NPEs get thrown, which already got fixed in PR #290 

However, there still is the following message in the log:

```
10:39:19,346 [qtp2083951216-41] ERROR KapuaSecurityBrokerFilter:526  - Cannot find connection id for client id 172-17-0-2-9 on connection map. Currect connection id is ID:kapua-broker-1-cum84-44868-1487673237717-3:10 - IP: ws://172.17.0.1:53176
```

Devices get auto-created, but are marked as "disconnected".

**Comment by Coduz** [comment]
This is by design until now. 

`kapua-sys` is a special credential that is currently treated in a special way when connecting with it. For sure we need to implement another mechanism to handle special treatment for some connections. 

Regards,

_Alberto_
