### ISSUE TITLE
WebSockets fails with java.lang.NoClassDefFoundError: org/apache/activemq/transport/ws/jetty9/StompSocket

### ISSUE THREAD

**Issue by jamesfalkner** [eclipse/kapua#310]
Trying websockets in the latest kapua results in some NCDFE's and CNFE's. I found that by adding `lib/optional/activemq-stomp-5.14.0.jar` to the kapua distro it works, so I think this needs to be included in order to complete the Stomp-over-WebSockets support.

**Comment by dejanb** [comment]
Hi James, can you tell us a bit more about your use case? Where are you using Stomp?

**Comment by mcarrer** [comment]
Closed due to inactivity.
