### ISSUE TITLE
Remove dependencies on 'kapua_addons' Maven repository

### ISSUE THREAD

**Issue by ctron** [eclipse/kapua#328]
Currently there are three dependencies on the `kapua_addons` repository:

```xml
<repository>
  <id>kapua_addons</id>
  <name>Kapua Addons Maven Repository</name>
  <url>https://raw.github.com/eurotech/kapua_addons/mvn-repo/</url>
</repository>
```

Which are:

```
com.extjs:gxt:2.2.5
io.swagger:swagger-ui:2.1.4-CQ-10792
io.swagger:swagger-ui-lib:2.1.4
```

So beside the fact that adding another Maven repository slows down the build, I think that it should be possible to re-build Kapua by using Maven Central dependencies only.

For `swagger-ui` we could go with the `org.webjars` version, which provides all the necessary files. We could also go with a more recent version (2.2.8).

For `gxt` it looks a bit more problematic, as it seems that GXT is no longer maintained (at least on Maven Central). Version 2.2.5, as used by Kapua, is not available. There are only some 2.3.1 versions and some 3.x versions by different providers. But I think as Kapua want to adopt Patternfly anyway, we can ignore this for the moment and simply remove it once the switch to Patternfly is complete.

And don't worry about CQs for the moment. I am volunteering to do the "paperwork".

**Comment by mcarrer** [comment]
io.swagger has been imported by PR #543.

com.extjs:gxt:2.2.5 cannot be imported because of IP issues.
