### ISSUE TITLE
Weaving not active

### ISSUE THREAD

**Issue by ctron** [eclipse/kapua#335]
I spotted the following message in the log:

```
[EL Warning]: metadata: 2017-02-28 16:14:25.523--ServerSession(1308536565)--Reverting the lazy setting on the OneToOne or ManyToOne attribute [lastEvent] for the entity class [class org.eclipse.kapua.service.device.registry.internal.DeviceImpl] since weaving was not enabled or did not occur.
```

I am not sure if this is import or not. If we can ignore please simply close this issue.

**Comment by Coduz** [comment]
Hi @ctron ,

weaving would be nice to have. 
According to this [document](https://www.eclipse.org/eclipselink/documentation/2.6/concepts/mappingintro002.htm#CEGCJEHD) from Eclipse Link, lazy OneToOne (we use this one) and lazy ManyToOne relationships are not supported on Java SE environments. 
It is possible to support them using weaving.
There are two types of weaving:

- dynamic: it requires using "-javaagent=[...]" argument on launching the JVM. See [here](https://wiki.eclipse.org/EclipseLink/UserGuide/JPA/Advanced_JPA_Development/Performance/Weaving/Dynamic_Weaving)
- static:  it involves byte-code manipulation through some additional operations when building. See [here](https://wiki.eclipse.org/EclipseLink/UserGuide/JPA/Advanced_JPA_Development/Performance/Weaving/Static_Weaving)

Actually, I did not dig too much into those options.

You know how to deal and use weaving on Eclipse Link?

**Comment by ctron** [comment]
I tried to enable static weaving yesterday as dynamic weaving seems to be rather difficult with EclipseLink. It requires the use of a Java agent.

Static linking did partially work. But I ran into a few limitations/issues/bugs of EclipseLink. It has issues with `@MappedSuperclass` and `@Embeddable`. For the first one there is a workaround. For the latter one there isn't. The first one will be fixed with EclipseLink 2.7.0, I am not sure if this will also fix the latter one.

In the end I would guess that those bugs will also be triggered by dynamic weaving, as the generated classes should be the same. So I guess weaving is out of the question for the moment with EclipseLink.

**Comment by ctron** [comment]
Also see: https://bugs.eclipse.org/bugs/show_bug.cgi?id=466271

**Comment by Coduz** [comment]
Yes I some tries to make it work but with no success. Specifying "-javaagent" property is probably fine with  small application but not in our platform IMO.
So I ended up with the same conclusion. 

I fixed programmatically the problems that no-weaving produces.

**Comment by Coduz** [comment]
Can I close this?

**Comment by ctron** [comment]
If that is closed, then yes.
