### ISSUE TITLE
Deploy Kapua into root context of Tomcat

### ISSUE THREAD

**Issue by ctron** [eclipse/kapua#338]
Currently Kapua gets deployed under the context `/console` in the Tomcat instance. Additionally there are the other WARs installed like `manager`, …

I would suggest to only deploy `console` and deploy it to the root of Tomcat.

**Comment by ctron** [comment]
This is done properly for Jetty.

**Comment by mcarrer** [comment]
Tomcat will be deprecated in favor of Jetty by Kapua 1.0 running only in docker.

**Comment by ctron** [comment]
I think we can close this as tomcat is no longer provided.
