### ISSUE TITLE
Liquibase scripts not generating the correct schema

### ISSUE THREAD

**Issue by lorthirk** [eclipse/kapua#346]
Hi all,

It seems that after commit 6028beddbf95a5538668d84a7ee2cec582e977cf running `mvn clean install -P sql` only creates four tables in the database (`ACT_ACCOUNT`, `DVC_DEVICE`, `DVC_DEVICE_CONNECTION`, `DVC_DEVICE_EVENT`). By looking at that commit, I see that all tables are being dropped in [dvc_device_connection_drop.sql](https://github.com/eclipse/kapua/commit/6028beddbf95a5538668d84a7ee2cec582e977cf#diff-306a9d7ad9e2f0d20d7de1851bdeb266). Is that correct?

**Comment by hekonsek** [comment]
SQL Maven plugin should not be needed anymore, as we should switch to embedded Liquibase. As I understand you are working in a Vagrant environment and you are blocked by #329? Right?

**Comment by lorthirk** [comment]
I don't think this is related to #329, since that one seems to be related to schema modification permissions.

Probably I missed something, but isn't `-p SQL` still required to reseed the database when doing `maven clean install`, even if using Liquibase?

**Comment by hekonsek** [comment]
No, embedded Liquibase plugin can replace Maven SQL entirely. It is only broker process responsibility to scan classpath for scripts and applying those. You should not need SQL Maven plugin anymore, as it is broker process responsibility now to apply changes to schema - you should not perform manual updates anymore.

Just set the proper schema when starting your broker in Vagrant (as described here [1]) and you will be good without SQL Maven plugin. 

[1] https://github.com/eclipse/kapua/issues/329#issuecomment-283961117

**Comment by hekonsek** [comment]
Done. I have added [1] support for non-public schema for Liquibase. Now it reads the value from Kapua configuration and doesn't try to resolve it from JDBC URL. 

[1] https://github.com/eclipse/kapua/commit/914a83bf5e1179b0616aa09c12c3603c899190ed
