### ISSUE TITLE
Create simple OpenShift installation script 

### ISSUE THREAD

**Issue by hekonsek** [eclipse/kapua#350]
@ctron @dejanb I'd like to create a simple bash script which can be used to download OpenShift Origin and install it in a `/tmp` by default, start server, log into a project and create default Kapua project.

This is not intended to be production ready. I think of it more like a development helper, so you can easily set up local OpenShift installation before deploying Kapua into it. This could also be used as a startup guide for people not familiar with OpenShift.

**Comment by hekonsek** [comment]
Done. We could also create an alternative script using minishift, but I'd personally prefer to using real origin instance if possible.

**Comment by kartben** [comment]
It might be useful to name the script slightly differently? I was all excited to try it, and then it just failed because I happen to be on a Mac :-) So either name the script with "linux64" somewhere in it, or adapt it so as it supports other platforms? Otherwise I think it is confusing.

**Comment by ctron** [comment]
Well the script should work in all versions as long as you have the "oc" client installed. Which is available for Mac OS X IIRC.

**Comment by BcGovBrian** [comment]
@ctron - isn't the script trying to install oc client then create the OpenShift project?

**Comment by kartben** [comment]
Well the script *is* installing a linux-64 oc client and then uses is. I guess at a minimum maybe the script could re-use the oc client that I already have in my PATH (since yes, Mac has an oc client, and I have it installed already)

**Comment by ctron** [comment]
Sorry, I was thinking of a different script. You are right.

The easiest way really is to fire up a Fedora 25 in a VM an run 'oc cluster up' as root.

**Comment by hekonsek** [comment]
I think that since we Linux as production platform for OpenShift, we should recommend installing OpenShift in virtual machine for non-Linux development environments. I have documented it here [1]. 

[1] https://github.com/eclipse/kapua/commit/2ed0f975a88ab75b5b71f559ab915c96f1fcabc9
