### ISSUE TITLE
Vagrant images seem to miss 'mvn'

### ISSUE THREAD

**Issue by ctron** [eclipse/kapua#361]
After setting up a new Vagrant image it seems that Maven is not installed:

```
vagrant@vagrant-ubuntu-trusty-64:/kapua$ mvn clean install -Psql -DskipTests
The program 'mvn' can be found in the following packages:
 * maven
 * maven2
Ask your administrator to install one of them
```

**Comment by Coduz** [comment]
Current configured vagrant machines does not have Maven installed, and until now we never need it. 
Which Vagrant machine are you using? 
Why you need Maven into the vagrant machine?

**Comment by ctron** [comment]
Because [1] tells you to run a maven build:

```
$ mvn clean install -Psql -DskipTests
```

[1] https://github.com/eclipse/kapua/blob/develop/dev-tools/src/main/vagrant/README.md#running-the-kapua-dev-box

**Comment by Coduz** [comment]
On the **note** just above it tells to run the build of the project and it means that you have to run build of the project that is outside of the vagrant box. 

Is miss-leading indeed. I will update it to make clear that the command must be run outside of the box.

**Comment by ctron** [comment]
It also works from inside the box though ;-)
