### ISSUE TITLE
REST API improve exception handling

### ISSUE THREAD

**Issue by Coduz** [eclipse/kapua#365]
Hi all, 

we need to improve exception handling on REST API.
Now the code does:

```
try {
 // do stuff
}
catch (Throwable t) {
  // Manage exception
}
```

It would much better to use the exception mapping supported by JAX-RS. 
Documentation is [here](https://jersey.java.net/documentation/latest/representations.html#d0e6754)

Regards, 

_Alberto_

**Comment by mcarrer** [comment]
Closed by PR #639
