### ISSUE TITLE
Improve support for Kapua developer cluster

### ISSUE THREAD

**Issue by hekonsek** [eclipse/kapua#371]
We should support OpenShift Origin installation process for developers. By such support I understand:
- providing OpenShift cluster download, installation and startup scripts
- documenting those
- helping folks in community in case of any issues related to the above

My goal here would be to:
- help OpenShift newbies to start playing with Kapua on OpenShift
- automate local OpenShift environment installation for regression testing

**Comment by hekonsek** [comment]
I think we should favor using `oc cluster up` for cluster installation, however it is Docker based and OpenShift on Docker tends to work in some environments only. So I propose to rely on `oc cluster up` by default:

    sudo kapua/dev-tools/src/main/openshift/openshift-start.sh

And fall back to binary installation on demand:

    sudo DOCKERIZED=FALSE kapua/dev-tools/src/main/openshift/openshift-start.sh

**Comment by hekonsek** [comment]
The other reason to have option to fall back to binary installation are issues like this one - https://github.com/openshift/origin/issues/13202 .

**Comment by ctron** [comment]
Maybe we should consider using Ansible for that (or something different), which automates this process. I've seen a few nice example how you can setup and modify a cluster with Ansible, which is much more reproducible than shell scripts.

**Comment by hekonsek** [comment]
+1

Would we expect users to have Ansible client installed in such case?

**Comment by hekonsek** [comment]
Adding @dejanb to the thread.

**Comment by hekonsek** [comment]
I have migrated documentation to [1] and improved it.

IMHO We should support the following Kapua deployment sequence...

    cd kapua/dev-tools/src/main/openshift     
    sudo ./openshift-start.sh
    ./openshift-initialize.sh
    ./openshift-deploy.sh

...recommend it to our users, so they can start deploying Kapua to OpenShift without learning OpenShift in advance. This is not production setup of course, but it demonstrates to users our opinionated view on OpenShift deployments.

Also I would like to use those steps to easily restart OpenShift installation for regression testing purposes. What do you think, guys?

[1] https://github.com/eclipse/kapua/blob/develop/docs/developer-guide/en/running.md#openshift

**Comment by hekonsek** [comment]
@ctron The idea of using Ansible here is inside our scripts our as a replacement for them?

**Comment by hekonsek** [comment]
Closing this one. We can open new tickets for further improvements.
