### ISSUE TITLE
Broker dependencies deployed on Vagrant demo

### ISSUE THREAD

**Issue by lorthirk** [eclipse/kapua#400]
Hi all,

After #399, jars from both `assembly/target/broker_dependency` and `broker-core/target/dependency/` (excluding the ones starting with `jaxb-*`, `activemq-*` and `kapua-*`) are copied in the broker's lib directory. However probably not all of them are needed, since a lot of them should be build time dependencies and not runtime depdencies.

As far as I can see, in the Docker deployment the libraries are coming from the `kapua-broker.xml` descriptor, is that right? If so, I guess we should use the same set of libraries in both deployments.

**Comment by ctron** [comment]
Couldn't we simply re-use those deployment descriptors?

**Comment by lorthirk** [comment]
Yes, that's what I meant with "use the same set of libraries in both deployments" 😄

**Comment by ctron** [comment]
Ok 😉  Because we could actually re-use those packed artifacts and understood "the same set" more in a way to duplicate it.

But that is great!

**Comment by lorthirk** [comment]
Closing as no longer valid
