### ISSUE TITLE
Fix ERRORs about missing skin files

### ISSUE THREAD

**Issue by ctron** [eclipse/kapua#434]
Currently every time I load the Kapua Web Console the following errors are shown:

```
7252889 [qtp1798286609-159] ERROR o.e.k.a.c.s.KapuaErrorHandlerServlet - Processed HTTP error! Code: 404 - Request: /console/skin/skin.css - Error: Not Found 
7252896 [qtp1798286609-21] ERROR o.e.k.a.c.s.KapuaErrorHandlerServlet - Processed HTTP error! Code: 404 - Request: /console/skin/skin.js - Error: Not Found 
```

First of all, I don't think it is an `ERROR` as the Web Console works pretty well despite the errors. But also, if those files are optional, then no error/warning/info should be issues in the log every time the page is loaded.

**Comment by mcarrer** [comment]
Issue has been addressed by PR #485
