### ISSUE TITLE
'KapuaSerializable' is not 'Serializable'

### ISSUE THREAD

**Issue by ctron** [eclipse/kapua#440]
The marker interface `KapuaSerializable` is not actually `Serializable`. While this is also confusing, it causes warnings about unnecessary `serialVersionUID` fields throughout Kapua.

I would suggest to either make `KapuaSerializable` actually `Serializable` or drop the `serialVersionUID` field.

**Comment by riccardomodanese** [comment]
Hi Jens, I already did this change to solve the issue #164. Unfortunately it is not merged yet. I'm working to port the fix done for this issue in the current develop branch so this fix should be available soon.

**Comment by riccardomodanese** [comment]
pr #503 should solve the issue

**Comment by riccardomodanese** [comment]
fixed by #503
