### ISSUE TITLE
Vagrant version 1.9.3 problem fix

### ISSUE THREAD

**Issue by ct-mtomic** [eclipse/kapua#441]
Problem with startup vagrant develop machine

`C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/util/is_port_open.rb:21:in "initialize": The requested address is not valid in its context. - connect(2) for "0.0.0.0" port 3306 (Errno::EADDRNOTAVAIL)
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/util/is_port_open.rb:21:in "new"
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/util/is_port_open.rb:21:in "block in is_port_open?"
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:88:in "block in timeout"
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:32:in "block in catch"
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:32:in "catch"
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:32:in "catch"
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:103:in "timeout"
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/util/is_port_open.rb:19:in "is_port_open?"
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb:248:in "port_check")`
`. . .`

For fix add `host_ip: "127.0.0.1"` in `/kapua/dev-tools/src/main/vagrant/develop/develop-Vagrantfile.sh`

`# dbms`
  `config.vm.network "forwarded_port", guest: 3306, host_ip: "127.0.0.1", host: 3306`

  `#activemq`
  `config.vm.network "forwarded_port", guest: 1883, host_ip: "127.0.0.1", host: 1883`
  `config.vm.network "forwarded_port", guest: 8883, host_ip: "127.0.0.1", host: 8883`
 ` config.vm.network "forwarded_port", guest: 5005, host_ip: "127.0.0.1", host: 5005`

  `#elasticsearch`
 ` config.vm.network "forwarded_port", guest: 9300, host_ip: "127.0.0.1", host: 9300`
  `config.vm.network "forwarded_port", guest: 9200, host_ip: "127.0.0.1", host: 9200`

  `#tomcat`
  `config.vm.network "forwarded_port", guest: 8080, host_ip: "127.0.0.1", host: 8080`
  `config.vm.network "forwarded_port", guest: 8443, host_ip: "127.0.0.1", host: 8443`
  `config.vm.network "forwarded_port", guest: 8000, host_ip: "127.0.0.1", host: 8000`

This version have a problem with connecting device to broker.

**Comment by mcarrer** [comment]
Vagrant has been upgraded to version 1.9.6 and the problem has not been reproduced.
Closing the issue.
