### ISSUE TITLE
Fix broken website layout

### ISSUE THREAD

**Issue by ctron** [eclipse/kapua#454]
For Firefox, Chrome and IE (Edge and classic) the current Kapua website layout it broken. The outcome is the same on all browsers:

![kapua_www_1](https://cloud.githubusercontent.com/assets/202474/24862916/04477fac-1dff-11e7-8cc4-d7e06ab386e5.jpg)

To me this looks like the HTML theme which is being issue is being using in a way it wasn't intended to be used.

However this causes some annoying scrolling issues and IMHO looks not really professional. I suggest to get this fixed before the initial release.

**Comment by lorthirk** [comment]
It looks good to me now. Can we close this?
