### ISSUE TITLE
Port activemq version to version 5.14.5 in Kapua projects

### ISSUE THREAD

**Issue by stefanomorson** [eclipse/kapua#469]

**Comment by ctron** [comment]
I started the CQ for this: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=13263

**Comment by riccardomodanese** [comment]
@ctron can I upgrade the activemq version to 5.14.5 or its better to wait for the cq progress?

**Comment by ctron** [comment]
@riccardomodanese I would say you can do that already.

**Comment by ctron** [comment]
This is done.
