### ISSUE TITLE
Change icons in user menu of the console

### ISSUE THREAD

**Issue by stefanomorson** [eclipse/kapua#475]
Login into the console and click on the user menu in the upper right corner of the UI.
The icons for the items:

* Switch to account
  * Your Account
* Logout

should be changed with others more meaningful.

**Comment by ctron** [comment]
We have the full FontAwesome set available. Do you have recommendations?

**Comment by lorthirk** [comment]
It seems that this issue is already fixed on 0a699965a14a9f5cccdfa8ab55c6e23fd78252d2. @ctron can you confirm you already covered this?

**Comment by ctron** [comment]
Well there are no more broken icons. However I am not sure the icons I picked are meaningful. If you have any suggestions here, it can easily be changed now.

**Comment by lorthirk** [comment]
I suggest [USER](http://fontawesome.io/icon/user) for the self account and [USER_O](http://fontawesome.io/icon/user-o/) for child accounts.

**Comment by ctron** [comment]
It looks like we are missing `user-o` though. Not sure if this is just missing in the enum or also in the FA version.

**Comment by lorthirk** [comment]
Right, `user-o` comes in FA 4.7.0. Let's stick with `user-md` then. At this point I think we can close this.
