### ISSUE TITLE
Refresh the list of child accounts in the user menu

### ISSUE THREAD

**Issue by stefanomorson** [eclipse/kapua#476]
The list of child accounts in user menu doesn't get updated after a new child account is created.
* Login to the console as admin (use kapua-sys)
* Add a new child account
* Right after the creation of the child account go to the user menu (upper right of the screen). 
* Drop down the list of the child account. 

The new child account is not present. 

* Refresh the page

The new child account appears in the user menu.

If possible, the child account should appear in the list after it is created without the need to refresh the whole page.

**Comment by ctron** [comment]
We have to consider the fact here that users could be created outside of the current GWT session as well. Either through the API or another session.

**Comment by lorthirk** [comment]
A first implementation is in #512. Althoug @ctron is right, the main target for this issue was to avoid to log out and log in again just to see an account that was just created. We could improve this later on to evaluate also accounts created from outside the console
