### ISSUE TITLE
Login of an externally authenticated user should succeed only if the user has a valid account

### ISSUE THREAD

**Issue by stefanomorson** [eclipse/kapua#479]
Suppose Kapua is deployed with an external authentication provider. A user has a valid identity in the authentication provider but he's not enlisted in any of the accounts available in Kapua, then the user shouldn't be able to connect. 
The administrator of the account have to add the externally authenticated user into the account and associate proper roles/permissions to him, then the user can login.   

A new UI workflow will be implemented to allow a user to register e new account, this way the process can be initiated.

**Comment by ctron** [comment]
I think there should be two ways to handle this. One is the way you described, but the other one should be an automatic creation of the user. This allows the external authentication provider to be configured in a way to handle the decision (and keep it at a single place) while Kapua auto-provisions a new user based on some sort of template settings.

**Comment by lorthirk** [comment]
I have opened issue #481 with a proposal on how could manage self account registration. Any feedback welcome!

**Comment by lorthirk** [comment]
Since #486 is already merged and #481 already exists for future scenarios, I think we might close this issue. What do you think?

**Comment by lorthirk** [comment]
Future implementations will be discussed in #481, and #486 currently forbids SSO login to non existing users. Closing!
