### ISSUE TITLE
Error while adding new device

### ISSUE THREAD

**Issue by rougeo** [eclipse/kapua#488]
Hello i am using the last updated docker images to run kapua. Yet i have an error while adding a new device 

![screen shot 04-20-17 at 10 57 am](https://cloud.githubusercontent.com/assets/12080962/25222327/77474e9a-25b8-11e7-8697-1623fdec8f23.PNG)

I wouldlike to connect a Kura raspberry pi device to kapua. Some ideas ??

**Comment by lorthirk** [comment]
Hi @rougeo,

Could you provide Tomcat logs?

However, you can simply connect your device via Kura: it will automatically created in Kapua.

Thanks!

**Comment by rougeo** [comment]
I added the configuration in the kapua device using the broker url. it is connected but i don't find the device in the kapua program
![screen shot 04-20-17 at 11 20 am](https://cloud.githubusercontent.com/assets/12080962/25223332/6baf221c-25bb-11e7-9e3d-e0e1304e6e25.PNG)


i don't know if i missed something on the Kura configuration too

Thanks

**Comment by rougeo** [comment]
Do we need to deploy another  special bundle on the kura device in order to make the connexion work ?

**Comment by lorthirk** [comment]
No, you don't need any bundle.

I see you're using "account-name" as the account. Have you already created such account in Kapua? Otherwise you should try using "kapua-sys" first, that is the default root account.

**Comment by rougeo** [comment]
Hello thank you so much for this response !! it's working now.  Is it possible to deploy one package for many kura client once ? I wouldlike actually confing a lot of kura devices at the same time.

Thanks

**Comment by lorthirk** [comment]
Currently your only option is to user REST APIs to get the devices list first and then use the devices management to perform the tasks you need.

**Comment by rougeo** [comment]
Ok thank you !! I will check that then !! 

Thanks for your helpfull answers !!
