### ISSUE TITLE
Device event date bug

### ISSUE THREAD

**Issue by Coduz** [eclipse/kapua#49]
Hi all, 

while working on issue #47 I discovered that the broker deployend into develop vagrant machine stores device events two hours before the actual time. 

Then by looking at the SQL db table I saw that actually seems that the console stores events in UTC+2 rather than use UTC+0. 

We need to find from where this timezone issue generates.

Regards, 

_Alberto_

**Comment by Coduz** [comment]
Hi all, 

after some debugging and try&error strategy with @lorthirk, we discover a funny thing that is what's causing the problem. 

For some (unknown) reasons, timestamp timezone does not work properly. 
Using console launched from Eclipse locally was causing all timestamps retrieved by the H2, that have not being inserted by the console itself, to be wrong. 
It has to be something related to the "?gwt.codesvr=127.0.0.1:9997" parameter that is used on debug mode. 
From the following screenshot it is clear that with the same Browser and same session there are different behaviour if that query parameter is used.

![screen shot 2016-10-26 at 5 42 28 pm](https://cloud.githubusercontent.com/assets/3942036/19735586/20589862-9ba4-11e6-9f71-b6750025059a.png)

I was not able to found an actual configuration/setup in order to have all situation working. The best set up that I managed to have is to have that query param removed and "-Duser.timezone=UTC" added to the launch configurations of console.

Anyway the deployment in demo and develop machine works fine.

I'll close the issue. If someone knows the reason please comment below 😄 

Regards, 

_Alberto_

**Comment by elbert3** [comment]
Perhaps this explains it: http://stackoverflow.com/questions/22953276/gwt-behaves-differently-when-url-has-gwt-codesvr

**Comment by Coduz** [comment]
Hi @elbert3 

Good spot on this one! 
I'll see if I can make some changes in order to always have dates working as expected.

Thanks!

_Alberto_

**Comment by stefanomorson** [comment]
@Coduz : can you update the status of this issue ?

**Comment by lorthirk** [comment]
I think we should remove this issue from the milestone, since it's not strictly related to development but it's rather something about the debug environment. What do you think?

**Comment by Coduz** [comment]
I think that this issue can be closed. 
It is something that affects Console only when running from IDE.
