### ISSUE TITLE
Kura to Kapua connection problem?

### ISSUE THREAD

**Issue by GogicM** [eclipse/kapua#490]
Hello.

When I try to connect Kura to Kapua, kapua-broker throws exception .. On Kura side service status is connected, but on kapua side there isn't any devices or data.
Telnet to ports works fine.

Also, when I open Data section in Kapua I got "Error
An internal error occurred: no such index. "
Kura print screen:

![kura](https://cloud.githubusercontent.com/assets/13328581/25228420/ae6d2138-25cc-11e7-97b9-304600e3de9a.png)

Kapua print screen: 

![kapua](https://cloud.githubusercontent.com/assets/13328581/25228466/d92ca27c-25cc-11e7-80b2-a529ce14b323.png)

Result of docker logs kapua-broker command (name of account is blacked) : 
![kapua-broker](https://cloud.githubusercontent.com/assets/13328581/25228728/d744a490-25cd-11e7-8543-d85db32ab2aa.png)

**Comment by lorthirk** [comment]
Hi @GogicM,

What account are you using to connect to Kapua?

**Comment by GogicM** [comment]
I am using kapua-sys / kapua-password credentials.

**Comment by lorthirk** [comment]
@GogicM I assume you're talking about username and password. But what about the account?

**Comment by GogicM** [comment]
Ouch. I feel dumb. I didn't create any user. Thank you, you can close this topic.

**Comment by lorthirk** [comment]
Great 😄 Thanks for the report anyway!

**Comment by ctron** [comment]
@GogicM You will need to use `kapua-broker` and `kapua-password` as credentials. Using `kapua-sys` allows you to connect to the broker, but internally screws up the database state.

I would suggest to drop and re-created the database and connect using the credentials mentioned above. And use `kapua-sys` as "account name".
