### ISSUE TITLE
Exception management when no messages are present

### ISSUE THREAD

**Issue by Coduz** [eclipse/kapua#495]
Hi all, 

just saw how it was solved in PR #487 . 
I think that should have been solved on the datastore implementation side as the solution proposed does not solve the problem but just hides it. And the problem is not solved when using REST API.

I propose to switch back to the simple management of the exception and catch and manage properly this exception on Message store service implementation, and simply return an empty list of messages.

Regards, 

_Alberto_

**Comment by ctron** [comment]
I agree this could be solved better. But at least, for the moment, the UI doesn't seem to hang.

**Comment by Coduz** [comment]
This has been fixed in PR #540
