### ISSUE TITLE
Device registry should be available as a standalone microservice

### ISSUE THREAD

**Issue by hekonsek** [eclipse/kapua#497]
Hi,

Several people in a community seem to be interested in running Kapua in a microservice oriented fashion. Device registry is probably the first thing that comes to mind for microservices architecture and Kapua. I think it is reasonably low hanging fruit to provide a way to run device registry as a self-contained service in Docker/Kubernetes environment.

I would like to provide a support for standalone device registry microservice with pluggable transport support, so you could access it using MQTT, AMQP or REST.

I would like to create a dedicated `kapua-device-registry-standalone` module (here [1]) containing bootstrap code for device registry and initial version of a transport binding logic (which we can later extract to a common module to share it among other Kapua microservices).

What do you think?

[1] https://github.com/eclipse/kapua/tree/develop/service/device/registry

**Comment by Coduz** [comment]
Closing this because this specific task has been split in multiple minor issues and also it has been spread across all services.
