### ISSUE TITLE
Error when exporting device event !!!

### ISSUE THREAD

**Issue by rougeo** [eclipse/kapua#501]
Hello 
i have errors when exporting device events ! any idea ?
I am using the docker deployment method to run kapua.

![screen shot 04-24-17 at 10 56 am](https://cloud.githubusercontent.com/assets/12080962/25330033/72975308-28de-11e7-9298-c0df955f49a7.PNG)

**Comment by lorthirk** [comment]
It looks like the exporter servlet is missing. I'll work on that!

**Comment by rougeo** [comment]
Hi @lorthirk  thanks for this update !! the export is now working from a localhost call !!!

Actually i am using docker containers,  and if i run kapua on the localhost hosting the docker containers with localhost:8080, the export is working fine. But if i have noticed that if run from another computer in the same network for instance 192.168.1.16:8080, kapua is runing well and evrything works like it use to do but the export part.  

Thanks !

**Comment by lorthirk** [comment]
Ok, I'm reopening the issue until I can investigate it

**Comment by rougeo** [comment]
Yep it is a browser issue actually !! I was using "google chrome" on the distant host. Now it"s working both side with firefox. 

Thank you @lorthirk !! :+1:
