### ISSUE TITLE
Prevent NPE with SortFieldImpl

### ISSUE THREAD

**Issue by ctron** [eclipse/kapua#507]
As most users of the `SortFieldImpl` probably can't handle `null` field names, this should be prevented in the first place.

The should be no default constructor allowing to set the field name to `null`.

**Comment by ctron** [comment]
Ideally it could be prevented to use an `Impl` class at all by:

```java
interface SortField {
   public static SortField ascending( Field field ) {
     …
   }
   public static SortField ascending( String  field ) {
     …
   }
}
```

**Comment by riccardomodanese** [comment]
May I don't understand your snippet, are you suggesting to add a constructor in an interface? From my knowledge java 1.8 (or 1.7?) added static methods and default methods to the interfaces but not the constructors. Am I wrong?
If I'm understanding your concern, we can handle the use case through replacing the SortField interface with an abstract class SortField with a default constructor that validates the field.
So every possible future implementation must call the SortField(String field) constructor.

public abstract class SortField {

     private SortField() {
     }

     protected SortField(String field) throws SomeException {
           if (org.apache.commons.lang3.StringUtils.isEmpty(field)) {
                  throw new SomeException();
           }
           this.field = field;
     }
}

**Comment by ctron** [comment]
No, I am not talking about a constructor, but a static method, much like the comparator methods in Java 8 (which should also be possible before Java 7 IIRC): https://docs.oracle.com/javase/8/docs/api/java/util/Comparator.html#comparing-java.util.function.Function-

The way you describe it now make a class instead of a field out of this, but from what I've understood it should be an interface.

Not handling this in a constructor has the advantage that you can actually have different paths of handling different situations **before** the constructor is called. e.g. like returning `null` from that call.

So you can also leave this with your custom implementation (if required) or use the static methods on the interface.

**Comment by ctron** [comment]
I made an example in PR #554

**Comment by riccardomodanese** [comment]
Sorry, may I explained myself badly, in my opinion there is no reason to have an interface for that Object.
Moreover, talking also with @Coduz, there is no need to have an abstract class for that. We can just provide a default concrete SortableField implementation.
In any case I'll take a look to your pr

**Comment by ctron** [comment]
I amended the PR to go with a simple class instead of an interface then.

**Comment by riccardomodanese** [comment]
Hi @ctron the fix is already included in the codebase so I close the issue.

Regards
