### ISSUE TITLE
Some tags missing for kapua-api-jetty docker image

### ISSUE THREAD

**Issue by stefanomorson** [eclipse/kapua#518]
Looking at the docker images generated using 

mvn -Pdocker

the following is created:

- kapua/kapua-api-jetty       latest

whiel the following are not:

- kapua/kapua-api-jetty       x.y.z-SNAPSHOT
- kapua/kapua-api-jetty       yyyy-mm-dd

**Comment by ctron** [comment]
IIRC correctly, those tags will only be added when the images are pushed. And `latest` should only be pushed for actual releases.

**Comment by ctron** [comment]
Please forget what I just wrote. I can reproduce the issue locally.

I will dig into this.
