### ISSUE TITLE
Request header field Authorization is not allowed by Access-Control-Allow-Headers in preflight response.

### ISSUE THREAD

**Issue by jamesfalkner** [eclipse/kapua#525]
With JavaScript running in the browser, I can successfully authenticate users with the Kapua API using `/v1/authentication/user`.

I then issue subsequent requests to the API by setting `Authorization: Bearer XXXX` in the requests, however the browser first does a CORS Preflight to Kapua, which returns a list of acceptable headers, none of which include `Authorization` so the browser rejects all calls with `Request header field Authorization is not allowed by Access-Control-Allow-Headers in preflight response.`.

The list of acceptable headers returned is `Access-Control-Allow-Headers:X-Requested-With, Content-Type, X-Access-Token`

If I instead use `X-Access-Token` and pass the token, then the call fails with HTTP 401 Unauthorized.

I believe you need to add Authorization to [CORSResponseFilter](/eclipse/kapua/blob/develop/rest-api/src/main/java/org/eclipse/kapua/app/api/CORSResponseFilter.java).

**Comment by lorthirk** [comment]
Thanks for spotting this @jamesfalkner. Actually, `Authorization` should replace `X-Access-Token` that is no longer used since we switched to `Authorization`.
