### ISSUE TITLE
Unit tests messed up?

### ISSUE THREAD

**Issue by ctron** [eclipse/kapua#531]
To me it looks a little bit as if the unit tests are messed up, or I simply don't understand what is going on.

For example in the project `kapua-account-internal` the `locator.xml` specifies an API `<api>org.eclipse.kapua.service.authentication.UsernamePasswordTokenFactory</api>` which does not exist. If the unit tests are run locally with Eclipse, the unit test runner fails with a CNFE, looking up this class.

However if run with Maven those tests succeed. So it looks like as if the classpath is messed up and the unit tests of `kapua-account-internal` actually use some different `locator.xml`.

Removing this entry for the `locator.xml` then fails the unit tests with the next exception:

```
java.lang.ClassCastException: org.eclipse.kapua.locator.guice.GuiceLocatorImpl cannot be cast to org.eclipse.kapua.test.MockedLocator
	at org.eclipse.kapua.service.account.internal.AccountServiceTestSteps.beforeScenario(AccountServiceTestSteps.java:128)
```

So maybe there is a simple explanation or a fix needed for this.

**Comment by muros-ct** [comment]
Yes it is true, it is not obvious.
Tests were first made in IDE and then made to work with maven. But in between we forgot to "mention" this small configuration issue.
As this tests are testing single service in isolation, other services are mocked. But for mocks to work we need custom Locator. This locator is configured from command line with

`-Dlocator.class.impl=org.eclipse.kapua.test.MockedLocator`

This is specified in pom.xml file for surefire tests.

What would be the best option to document this?  
Could we automate this somehow? How to create run / debug configuration in eclipse?  
Suggestions?

```xml
<build>
  <plugins>
    <plugin>
      <groupId>org.apache.maven.plugins</groupId>
      <artifactId>maven-surefire-plugin</artifactId>
      <configuration>
        <systemPropertyVariables>
          <locator.class.impl>org.eclipse.kapua.test.MockedLocator</locator.class.impl>
        </systemPropertyVariables>
      </configuration>
    </plugin>
  </plugins>
</build>
```

**Comment by ctron** [comment]
I think this should be somehow coded into the unit test instead of relying on the existence of a system property. As we just saw, this can cause problems.

Maybe `@BeforeClass`, some custom unit runner, explicitly using this locator, …

**Comment by Coduz** [comment]
Hi @muros-ct,

#557 has fixed this. 
Is it ok to close this issue? 

Regards 

_Alberto_

**Comment by muros-ct** [comment]
Yes, it is ok to close this. Tests now run without maven set locator.
Locator is set in cucumber test itself.
