### ISSUE TITLE
Missing 'break'

### ISSUE THREAD

**Issue by ctron** [eclipse/kapua#538]
Looking at [AbstractDeviceApplicationCallResponseHandler.java:54](https://github.com/eclipse/kapua/blob/d91f04c31f1e1dc5a0f3de6b023cf0ef5a9431fc/service/device/commons/src/main/java/org/eclipse/kapua/service/device/management/commons/call/AbstractDeviceApplicationCallResponseHandler.java#L54) I think there are some `break`s missing. I picked this up while adding a checkstyle check for fallthroughs.

While I think this is a bug, I would ask someone familiar with this piece of code to have a look and maybe fix it. I will mark this as "fall through" for the moment.

**Comment by bensari** [comment]
Hi,
This should not be a problem as long as the methods are throwing Exceptions.
The only thing is, if something happen (like an null pointer exception) before throwing the  target exception, we do not have that information for debugging. However the break won't change anything.
For me this piece of code make sense.
Have a nice day.

**Comment by ctron** [comment]
However sub-classes can override this behavior and still return. Which would break this behavior.
