### ISSUE TITLE
Kapua Build broken with -Pdeploy

### ISSUE THREAD

**Issue by Coduz** [eclipse/kapua#541]
Hi all, 

the build with `-Pdeploy` is broken. 
Therefore the build of the vagrant demo machine is broken too.

Error is a long list of:

```
[ERROR] /Users/alberto.codutti/dev/git/kapua/develop/service/api/src/main/java/org/eclipse/kapua/KapuaRuntimeException.java:117: warning: no description for @param
```

This was introduced with forcing of generating Javadocs on build with profile `deploy` with commit: 6be70f3d6aad5ffb5698313e26fa574f7c8abf4f.

Regards, 

_Alberto_

**Comment by ctron** [comment]
This looks like a warning, are you sure this is what breaks the build?

**Comment by ctron** [comment]
To me it looks like as if the javadoc refers to a missing method.

So I guess we should enabled javadoc generation on travis in order to be aware of such issues.

**Comment by ctron** [comment]
Ok, it looks like there is a whole bunch of broken Javadoc. It is not a single issue.

**Comment by ctron** [comment]
The javadoc plugin is now moved to the `javadoc` profile, which is also run during a release build. The profile is inactive by default, but active on travis, so that we are aware of any serious javadoc issues.

I also fixed all of the serious (error) level javadoc issues.

**Comment by Coduz** [comment]
Hi @ctron ,

I probably forgot to assign the issue to me. 
I started to fix this fixing all of them with the previous set up...

**Comment by ctron** [comment]
Sorry for that. But now we should have fixed this all and have proper validation for future errors, so this should be an improvement. Or did you have anything different in mind?

**Comment by Coduz** [comment]
No problem. Just rebasing on your work. 
There are some differenced. 
I've only fixed errors like you, but did not changed how the javadoc plugin is managed.
I've added a override of the configuration on the console to not scan autogenerated code for the localization messages.

**Comment by ctron** [comment]
I did that as well, using the pluginManagement element. I agree this should not be processed as the generated Javadoc is broken.

**Comment by Coduz** [comment]
There is any way to be more specific on the exclusion? `*.messages` could match some real code that might need to be validated instead. 
I tried with the `sourceFileExcludes` tag and the value `**/generated-sources/gwt/**` but with no luck eheh

**Comment by ctron** [comment]
Let's fix that when it comes to that.
