### ISSUE TITLE
Sorting devices view by "Last Event On" results in incorrect ordering

### ISSUE THREAD

**Issue by kartben** [eclipse/kapua#55]
See screenshot below, the column is supposed to be sorted by date and yet the ordering seems pretty random (no matter whether it's ASC or DESC)

![image](https://cloud.githubusercontent.com/assets/128251/19659903/1150b362-9a2e-11e6-8082-25ce15f0acda.png)

**Comment by Coduz** [comment]
HI @kartben,

I noticed this yesterday while adding new columns to device event view. 
I'll promote this as bug and work on it

Regards, 

_Alberto_

**Comment by kartben** [comment]
Awesome! Thanks :)

Le mar. 25 oct. 2016 10:30, Alberto Codutti <notifications@github.com> a
écrit :

**Comment by Coduz** [comment]
Hi all,

update on this issue. 
This issue is waiting resolution of issue #68 . 
Last event on and last event type are properties of the device event.

Regards, 

_Alberto_

**Comment by Coduz** [comment]
The issue #68 has been merged and closed, so then this has been fixed
