### ISSUE TITLE
If a birth certificate message has its MessagePayload.position set, it should be used to set the position of the device

### ISSUE THREAD

**Issue by kartben** [eclipse/kapua#56]

**Comment by kartben** [comment]
Looks like the code is supposed to do just that. I may be sending bogus birth certificates so let me double check on my end first :)

**Comment by kartben** [comment]
OK so it does not seem to work with Birth Certificate posted from Kura either, so definitely a problem on Kapua.

**Comment by kartben** [comment]
fwiw the device events in the database have the correct latitude/longitude set, so maybe just a UI issue.

**Comment by Coduz** [comment]
Hi @kartben,

Yes that is. I'll add showing of the last GPS position based on the Birth. 
Maybe that position retrieval can be also merged with position in the last data message (if it is available)

Regards, 

_Alberto_

**Comment by Coduz** [comment]
Hi @kartben ,

This issue has been solved. Now the position in the description view is retrieved from the position of the last BIRTH event found.

Regards, 

_Alberto_
