### ISSUE TITLE
*nix-specific absolute paths 

### ISSUE THREAD

**Issue by AnaScarlet** [eclipse/kapua#578]
When running `mvn -Pdocker` from the assembly folder on Windows 10, I got the following errors:

![assemblywinproblem](https://cloud.githubusercontent.com/assets/26636906/26195487/3a5a5096-3b79-11e7-8281-df9b2aad0be6.PNG)

The build was nonetheless successful.

**Comment by ctron** [comment]
Thanks for reporting this! I will try to get a fix.
