### ISSUE TITLE
You have an error in your SQL syntax of comment,when use mariadb

### ISSUE THREAD

**Issue by miricy** [eclipse/kapua#584]
--liquibase formatted sql

--changeset domain_actions:1

add a spacing char is ok

-- liquibase formatted sql

-- changeset domain_actions:1

 Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '--liquibase formatted sql

--changeset domain_actions:1

CREATE TABLE athz_domai' at line 13
Query is : -- *******************************************************************************
-- Copyright (c) 2011, 2016 Eurotech and/or its affiliates and others
--
-- All rights reserved. This program and the accompanying materials
-- are made available under the terms of the Eclipse Public License v1.0
-- which accompanies this distribution, and is available at
-- http://www.eclipse.org/legal/epl-v10.html
--
-- Contributors:
--     Eurotech - initial API and implementation
-- *******************************************************************************

--liquibase formatted sql

--changeset domain_actions:1

CREATE TABLE athz_domain_actions (
  domain_id                 BIGINT(21)    UNSIGNED NOT NULL,
  action                                        VARCHAR(255)  NOT NULL,
  
  PRIMARY KEY (domain_id, action)
 
) DEFAULT CHARSET=utf8;

**Comment by Coduz** [comment]
Hi @miricy ,

Is this something that needs to be changed in all Liquibase formatted SQL files? 

Thanks,

_Alberto_

**Comment by Coduz** [comment]
Hi @miricy,

Any news? 

Regards, 

_Alberto_

**Comment by miricy** [comment]
Hi @Coduz ,
   there is some fix like this:
# 1. The file commons/src/main/resources/kapua-environment-setting.properties

commons.db.name=kapuadb
commons.db.username=kapua
commons.db.password=kapua
commons.db.jdbcConnectionUrlResolver=mysql

commons.db.jdbc.driver=com.mysql.jdbc.Driver
commons.db.connection.scheme=jdbc:mysql

# 2.The file commons/src/main/java/org/eclipse/kapua/commons/jpa/JdbcConnectionUrlResolvers.java
modify code:


package org.eclipse.kapua.commons.jpa;

import static org.slf4j.LoggerFactory.getLogger;

import org.eclipse.kapua.commons.setting.system.SystemSetting;
import org.eclipse.kapua.commons.setting.system.SystemSettingKey;
import org.slf4j.Logger;

public final class JdbcConnectionUrlResolvers {

    private static final Logger LOG = getLogger(JdbcConnectionUrlResolvers.class);

    private JdbcConnectionUrlResolvers() {
    }

    public static String resolveJdbcUrl() {
        SystemSetting config = SystemSetting.getInstance();
        String connectionUrlResolverType = config.getString(SystemSettingKey.DB_JDBC_CONNECTION_URL_RESOLVER, "DEFAULT");
        LOG.debug("The following JDBC connection URL resolver type will be used: {}", connectionUrlResolverType);
        if (connectionUrlResolverType.equals("DEFAULT")) {
            return new DefaultConfigurableJdbcConnectionUrlResolver().connectionUrl();
        } else if (connectionUrlResolverType.equals("H2")) {
            return new H2JdbcConnectionUrlResolver().connectionUrl();
        } else if (connectionUrlResolverType.equals("mysql")) {
            return new MariaDBJdbcConnectionUrlResolver().connectionUrl();
        } else {
            throw new IllegalArgumentException("Unknown JDBC connection URL resolver type: " + connectionUrlResolverType);
        }
    }
}

**Comment by miricy** [comment]
# Mariadb not support "CREATE INDEX IF NOT EXISTS ":

./commons/src/main/resources/liquibase/0.2.0/system_configuration.sql:
CREATE INDEX IF NOT EXISTS idx_configurationScopeId ON sys_configuration (scope_id);
./service/security/shiro/src/main/resources/liquibase/0.2.0/athz_role-configuration.sql:
CREATE INDEX IF NOT EXISTS idx_configurationScopeId ON sys_configuration (scope_id);
./service/security/shiro/src/main/resources/liquibase/0.2.0/athz_group-configuration.sql:
CREATE INDEX IF NOT EXISTS idx_configurationScopeId ON sys_configuration (scope_id);
./service/account/internal/src/main/resources/liquibase/0.2.0/account-configuration.sql:
CREATE INDEX IF NOT EXISTS idx_configurationScopeId ON sys_configuration (scope_id);
./service/user/internal/src/main/resources/liquibase/0.2.0/user-configuration.sql:
CREATE INDEX IF NOT EXISTS idx_configurationScopeId ON sys_configuration (scope_id);
./service/device/registry/internal/src/main/resources/liquibase/0.2.0/device-configuration.sql:
CREATE INDEX IF NOT EXISTS idx_configurationScopeId ON sys_configuration (scope_id);

**Comment by Coduz** [comment]
Hi @miricy ,

I've fixed the problem about comments but is seems that you still have problems. 
If you want to propose a solution I think that is better that you use Pull Requests.

On the problem about indexes on MariaDB I think that the problem is elsewhere. 
According to [MariaDB Documentation](https://mariadb.com/kb/en/mariadb/create-index/) the syntax `CREATE INDEX IF NOT EXISTS` is supported.
Which version are you using? 

Regards, 

_Alberto_

**Comment by miricy** [comment]
Hi @Coduz ,
  I use the MariaDB5.5 and mysql 5.6, there has some problems at crreate index script.
 " CREATE INDEX IF NOT EXISTS"

and the script file:
 kapua/commons/src/main/resources/liquibase/configuration.sql
CREATE TABLE IF NOT EXISTS sys_configuration (
  scope_id          		 BIGINT(21) 	  UNSIGNED,
  id                         BIGINT(21) 	  UNSIGNED NOT NULL,
  pid						 VARCHAR(255) 	  NOT NULL,
  configurations			 TEXT,
  created_on                 TIMESTAMP(3) 	  DEFAULT 0,
  created_by                 BIGINT(21) 	  UNSIGNED NOT NULL,
  modified_on                TIMESTAMP(3) 	  NOT NULL,
  modified_by                BIGINT(21) 	  UNSIGNED NOT NULL,
  optlock                    INT UNSIGNED,
  attributes				 TEXT,
  properties                 TEXT,
  **PRIMARY KEY  (id),**
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

and end of the PRIMARY KEY (id),   can't add a ',' char to the create table last item  in mysql 5.6 or mariadb5.5

**Comment by Coduz** [comment]
Hi @miricy ,

It seems that MariaDB/MySQL are strict than H2 that we use on tests. 
I'll try to build with scripts against a MySQL instance to address all this problems :) 
If you want you can create pull request with fixes if you want to contribute yourself to Kapua.

Regards, 

_Alberto_

**Comment by Coduz** [comment]
Hi @miricy ,

found the problem :) 

I think that the problem is that we are running multiple statements on the same SQL script.
According to many post on google and MySQL documentation you need to explicitly allow multiple queries to be performed on the JDBC URL.

Adding `allowMultiQueries=true` to the JDBC URL solves the problem. 

I'll fix that and further errors that will came out :) 
I'll get back to you when it will be possible to run scripts against MySQL/MariaDB and H2 at the same time.

Regards, 

_Alberto_

**Comment by Coduz** [comment]
Hi @miricy ,

Can you please check the PR branch? I was able to have Kapua seeded and running on a MySQL instance. 

Now should work both with MySQL/MariaDB and H2.

Regards, 

_Alberto_

**Comment by Coduz** [comment]
Any news on this one?

**Comment by Coduz** [comment]
Hope that issue was solved.
Please open another issue if you still have problems.

Regards, 

_Alberto_
