### ISSUE TITLE
Liquibase script refactoring

### ISSUE THREAD

**Issue by Coduz** [eclipse/kapua#586]
Hi all, 

while working on #583 I discovered something odd on Liquibase.
By default it uses absolute path name as a key to know if a file has been executed already or not. 
This means that If the same script is executed from a different directory Liquibase wouldn't be able to recognize that is has already been executed and try to execute it again.

There is a property to override this called `logicalFilePath`, which value is used as a key instead of the absolute path. This property must be added to all file with changeset to execute. 
I was not able to add it to the plan SQL file and I suspect that we have to convert them to XML|YAML|JSON format to be able to specify that property. 

BTW the current layout works fine for tests and demo deployment. It could be a problem in case of more complex usage.

Regards,

_Alberto_

EDIT: 
Documentation page of this property: http://www.liquibase.org/documentation/databasechangelog.html

**Comment by Coduz** [comment]
Task list:

- [ ] set default collation to recommended one (uft8_unicode_ci?)
- [ ] check existing indexes

**Comment by mcarrer** [comment]
Closed, now tracked by DB migration enhancement PR #788.
