### ISSUE TITLE
The service should be located under service/api instead of locator/service

### ISSUE THREAD

**Issue by stefanomorson** [eclipse/kapua#6]
The service project contains the blueprint for all the services in Kapua. I think the right place for it in the layout is under the a service/api subproject.  Locator could group all the locator implementations.

**Comment by hekonsek** [comment]
Just to be sure I get it, Stefano - do you propose to move module `kapua/locator/service` to `service/api`? I'm OK with that, I just would like to check if I understand your correctly. :)

**Comment by stefanomorson** [comment]
Yes correct.

Under project "service" for sure, so at this point under service/api to separate it from the others (if I have understood well the pattern), it that correct ?



S

________________________________

**Comment by hekonsek** [comment]
Done.
