### ISSUE TITLE
Elasticsearch index creation

### ISSUE THREAD

**Issue by kcsj17** [eclipse/kapua#604]
I have Kapua running using the docker containers method. Further i have Kura on a raspberry pi polling a simulated modbus slave ( modbuspal ) and publishing the data to the kapua-broker. I also have a Grafana container with kapua-elasticsearch as a data source  to visualize the data being polled by Kura.

 In grafana, to add the kapua-elasticsearch as a datasource, the index has to be specified. The initial elasticsearch index to which kura published data is stored was "1-2017-21". Ive since noticed that another index was added with the name "1-2017-22". This name seem not to be date related except for the year part. 

Grafana has the ability to update the datasource index, if it has a format that is dependent on the current date. Is it possible to have the indexes in kapua-elasticsearch be named relative to the current date?

**Comment by lorthirk** [comment]
Hi @kcsj17,

currently he Elasticsearch index is composed as:

`Scope ID-Year-Week`

Does Grafana support such scenario?

**Comment by kcsj17** [comment]
Great.  With the Index name pattern " [1-]GGGG-WW " in Grafana's Elasticsearch details I've managed to get the issue resolved. Thank you for the prompt attention...

**Comment by lorthirk** [comment]
Great to hear :) 

I'm closing the issue, feel free to reopen it should you have the need.
