### ISSUE TITLE
Test failures in Windows environment

### ISSUE THREAD

**Issue by andrejn-ct** [eclipse/kapua#638]
Unit tests for a number of packages consistently fail in a Windows environment, even if the build process alone (_-DskipTests_) completes successfully.

The affected packages are:
kapua-liquibase
kapua-user-internal
kapua-security-shiro
kapua-device-registry-internal
kapua-datastore-internal
kapua-account-internal
kapua-qa

The error message is consistently:
_java.io.IOException: Unable to delete file: specific_path_to_temp_folder\tmp\kapua-liquibase\changelog-user-master.xml_ (the exact file name varies with the test cases).

This seems to be a Windows-specific issue, since the error cannot be reproduces neither in Linux nor in macOS.

After some debuggin, the issue seems to be traceable to the _KapuaLiquibaseClient_ method _loadResourcesStatic()_, more specifically the call to _FileUtils.deleteDirectory(changelogTempDirectory)_.

**Comment by ctron** [comment]
A typical problem on Windows is that file cannot be deleted when they are not properly closed. Could that be the case here?

**Comment by andrejn-ct** [comment]
Yes, it looks exactly like that. The Java garbage collector seems to dispose of (and close) the output stream  too late, so the file is still considered open and locked when the next test tries to delete it.

**Comment by andrejn-ct** [comment]
Fixed with PR #640.

**Comment by ctron** [comment]
I just saw your PR. You should have references this issue. 😉 

Java doesn't close by garbage collecting, that is what the close method is for. It has to be done explicitly. And Windows doesn't allow to delete files which are still open.
