### ISSUE TITLE
Support for the Simple Json payload.encoding

### ISSUE THREAD

**Issue by rougeo** [eclipse/kapua#661]
Hello
If i change the payload.encoding to Simple Json in the kapua device Cloud Services, kapua cannot manage the device anymore.

**Comment by Coduz** [comment]
Hi @rougeo ,

Kapua does not currently support device management with devices that uses json payload format. 

Json payload format in Kura is meant to be used when integrating with other platform that cannot work with Kura Protobuf but supports Json formatted payload. 

Regards, 

_Alberto_

**Comment by rougeo** [comment]
Hi @Coduz 
Actually i wanted to use the same connexion to do  the management and sending json pyload to a webServer !! Really bad idea. But i have created a second connexion on the kura device which use json payload and set my java bundles to use this one to send messages. Now evrything works fine

Thank you
