### ISSUE TITLE
Activemq on kapua

### ISSUE THREAD

**Issue by tenderitaf** [eclipse/kapua#679]
Hi,
I would like to use kura simulator with amqp [link](https://hub.docker.com/r/ctron/kura-emulator-artemis/) , but wondering if there is a way to activate amqp on kapua.

Regards

**Comment by riccardomodanese** [comment]
Hi, 
      amqp is one of the protocols supported by activemq broker even though it is not currently configured.
However, support for amqp connections in Kapua, is in the project roadmap.

Regards

**Comment by riccardomodanese** [comment]
Hi @tenderitaf I'm closing the issue.
If you have any questions please feel free to open a new issue.

Regards
