### ISSUE TITLE
Add support for join entities in the same service

### ISSUE THREAD

**Issue by Coduz** [eclipse/kapua#68]
Hi all,

we need to add the support of join in our Query wrapper over JPA. 

Currently queries are restricted to one entity domain a time. 
This is fine when a service has only one domain, but can limit querying flexibility that we are trying to pursue. 

An example is the DeviceRegistryService. 
It has 3 domains:
- Device
- DeviceConnection
- DeviceEvent

It is fine for queries on single domains, but what if I need to find all connected devices? That would require two domains (Device and DeviceConnection) to be joined and filtered at the same time. 

Regards,

_Alberto_

**Comment by lorthirk** [comment]
The new console (hence the REST APIs) needs this to show the same columns in the Devices view, since we have both a Connection indicator and Last Event data
