### ISSUE TITLE
Tag Service cucumber test

### ISSUE THREAD

**Issue by Coduz** [eclipse/kapua#680]
CRUD tests on TagService

Device tag add
Device tag search
Device tag removal

**Comment by muros-ct** [comment]
You can add test tag on this, as it can't be assigned on me.

**Comment by muros-ct** [comment]
Just to be shure. Implementation is in feature/entityTags?
I will get to it now. I had other tests in queue. Better late.... ;)

**Comment by LeoNerdoG** [comment]
I have added Device tag Removal (PR#787 and PR#790). 
@Coduz  Is there anything else to do on TagService?

**Comment by Coduz** [comment]
Hi @LeoNerdoG ,

I think that they are good for now.

We can close this issue.

Regards, 

_Alberto_

**Comment by LeoNerdoG** [comment]
Hi @Coduz ,
I could not response earlier - i agree with the closure. 
Regards,
leo
