### ISSUE TITLE
ACL publish to unallowed topic

### ISSUE THREAD

**Issue by muros-ct** [eclipse/kapua#685]
If user that is not allowed to publish, based on ACL rule, publishes to certain topic (channel), no error message or exception is triggred. Only result of that publish is that message doesn't arrive to that channel.

Steps to reproduce:
User with broker/connect profile connects to broker and publishes to topic $EDC/{0}.>.
{0} is account name. Message doesn't arrive to broker. And no error is returned to publishing client.
As upposed to subscribing to unallowed topic, where message is thrown by mqtt client calling broker.

@riccardomodanese 
Is this correct behaviour?

**Comment by riccardomodanese** [comment]
Hi Uros, this behavior is correct.
The MQTT specs for both the 3.1 and 3.1.1 say:
"...  It must therefore make a positive acknowledgement with a SUBACK, and the client will not be informed that it was not authorized to subscribe."
3.1 - http://public.dhe.ibm.com/software/dw/webservices/ws-mqtt/mqtt-v3r1.html#publish
3.1.1 - http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/errata01/os/mqtt-v3.1.1-errata01-os-complete.html#_Toc442180850

So to test that the message is not really published we should connect another client with the rights to subscribe that topic and check if no message is received by that client.

**Comment by muros-ct** [comment]
Ok.
Test is implemented in exactely the way that you described. Admin is listening on topic that sould b e published on and no message is received.

I just wanted to be shure this is correct behaviour.
I will colose this issue.
