### ISSUE TITLE
Build and test dependencies for Kapua 0.3.0

### ISSUE THREAD

**Issue by ctron** [eclipse/kapua#695]
I would like to use this issue to track build and test dependencies for Kapua 0.3.0:

We should file this CQ at least two before filing for the IP log approval:

```
Name - Version - License
-----------------------------------------------------------------
de.dentrassi.maven:jacoco-extras  - 0.1.1 - EPLv1
```

**Comment by stefanomorson** [comment]
Add these two more from project kapua-client-gateway-feature-karaf:

org.apache.karaf.features:framework - 4.1.1 - Apache License, Version 2.0
org.apache.karaf.features:standard - 4.1.1 - Apache License, Version 2.0

**Comment by stefanomorson** [comment]
Build and Test dependencies submitted with CQ:
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=14169
