### ISSUE TITLE
Some problems in the rest-api 

### ISSUE THREAD

**Issue by StevenWash** [eclipse/kapua#698]
excuse me，I have a problem when I use the rest-api.I use the post method in Credentials to create a credential and I have input the param as required.But there has an error like 'An illegal null value was provided for the argument credentialCreator.userId.'.Then I have tried to check if the params have been converted correctly.So I found the value of userId and some other param was null in the rest-api.I think it may be the CredentialCreator can not convert the params correctly ,especially the userId(big int).I don`t know whether I have state my problems clearly,but I wish someone can help me !Thank you very much!

**Comment by Coduz** [comment]
Hi @StevenWash ,

KapuaIds on rest API must be expressed in their "compact" version (i.e: id `1` is `AQ`).

Here is an example that creates a new password credential for `kapua-sys`.

```
{
    "scopeId": "AQ",
    "userId": "AQ",
    "credentialType": "PASSWORD",
    "credentialKey" : "Password!123456789"
}
```

Regards,

_Alberto_

**Comment by StevenWash** [comment]
Hi @Coduz ,
I am very happy that you answerd my problems .Here is my params as you suggested:
![input](https://user-images.githubusercontent.com/18731292/27580311-c7ca25a2-5b5c-11e7-8e1c-18fda848d803.png)

But it doesn`t work,and it returns like this:
![response](https://user-images.githubusercontent.com/18731292/27580402-0505f964-5b5d-11e7-9ec5-089c927c7952.png)

And I have an autnentication before using this api!So can you give a another suggetions about this issues?
Thank you very much!

**Comment by Coduz** [comment]
Hi @StevenWash ,

it seems that Swagger is reporting the wrong format for the object. 
I'll try to fix it. 

For now please use the format I showed before. 

KapuaIds object should be specified like a simple String field (i.e. `"userId": "AQ"`) and not as reported by Swagger (`"userId": { "id": 0  }`)

It seems that is using the `KapuaId` definition instead of the adapter object.

Regards, 

_Alberto_

**Comment by StevenWash** [comment]
Hi @Coduz ,
I have tried to use the format you showed before.And the response is correct.Thank you very much for give the advice!I sincerely hope that you can fix it !
Thank you very much!
