### ISSUE TITLE
Some problems about the rest API's introduction

### ISSUE THREAD

**Issue by StevenWash** [eclipse/kapua#710]
Excuse me , I have a problem in how to use the '_query' in the rest API . For example,I find it is little difficult to understand  the introduction of _query in Credential's API . I have try to use params like this:
![image](https://user-images.githubusercontent.com/18731292/27718306-cd5b2840-5d7d-11e7-92d7-e78862dad646.png)
I have deleted some other unused params.The result is correct.
But ,if I want to query userId="AQ" ,so what params should I input？
I have tried like this:
![image](https://user-images.githubusercontent.com/18731292/27718394-42b119c4-5d7e-11e7-8977-ebc5f56296f8.png)
But the result was the same as above result(without the param userId="AQ").
So can you give me a suggestion?
And I also hope that the introduction of each API should be more detail.
Thank you so much!

**Comment by Coduz** [comment]
Hi @StevenWash ,

As said in #714  we don't currently support filtering with query.
Filtering parameters available are those exposed by the GET method

Regards,

_Alberto_

**Comment by ctron** [comment]
So maybe we should create a new issue for tracking this.

**Comment by lorthirk** [comment]
This implementation will be tracked in #803. Please use that issue to continue the discussion.
