### ISSUE TITLE
Some problems in rest-API

### ISSUE THREAD

**Issue by StevenWash** [eclipse/kapua#714]
These days ,I find a new problem in rest-API.I know that the api like "Credential" has a 'query' method.Firstly,I find it is difficult to use it because it's params is not clearly.So I try to learn it ,I find that the param in the swagger that i input was not converted correctly.I print the 'CredentialQuery' of the query method in the 'Credentials',but the 'predicate' and 'fetchAttributes' was null.The value was not converted to the CredentialQuery's object.
The method like this:
![image](https://user-images.githubusercontent.com/18731292/27777016-c58075ba-5fe1-11e7-931d-42d0b7566397.png)
The output in the consle like this:
![image](https://user-images.githubusercontent.com/18731292/27777028-e34723f0-5fe1-11e7-87c5-390efd9ec45c.png)
And  I input these values like these:
![image](https://user-images.githubusercontent.com/18731292/27777255-b27defe0-5fe3-11e7-8b44-2caf15542bd2.png)
And if I use the param like above ,the response is the all records,in a nother word,the predicate doesn't work.
Hope some one can help me !
Thank you very much!

**Comment by StevenWash** [comment]
@Coduz Excuse me ,I am so sorry to bother you.Could you help me about dealing above problems.
Thank you very much!

**Comment by Coduz** [comment]
Hi @StevenWash ,

we do not currently support filtering with the query method. 
This is something that we have on plannings, but we are focusing on other items tight now.

Regards ,

_Alberto_

**Comment by lorthirk** [comment]
This implementation will be tracked in #803. Please use that issue to continue the discussion.
