### ISSUE TITLE
build error kapua in ubuntu from both running from terminal and from Eclipse

### ISSUE THREAD

**Issue by Roopa-Siddaveerappa** [eclipse/kapua#715]
hello,
i am trying set up Eclipse Kapua in my Ubuntu system
i tried to build the it both from terminal and From Eclipse by taking latest source code from git 
today 
1.There is compile error of 
import org.eclipse.kapua.app.console.shared.service.GwtCredentialServiceAsync;
when i checked in code GwtCredentialServiceAsync is not available in the code from Git 

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building kapua-console 0.2.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.eclipse.kapua:kapua-device-registry-internal:jar:0.2.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.eclipse.kapua:kapua-security-shiro:jar:0.2.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.eclipse.kapua:kapua-device-call-kura:jar:0.2.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.eclipse.kapua:kapua-device-commons:jar:0.2.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.eclipse.kapua:kapua-device-bundle-internal:jar:0.2.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.eclipse.kapua:kapua-device-command-internal:jar:0.2.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.eclipse.kapua:kapua-device-configuration-internal:jar:0.2.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.eclipse.kapua:kapua-device-packages-internal:jar:0.2.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.eclipse.kapua:kapua-datastore-api:jar:0.2.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.eclipse.kapua:kapua-datastore-internal:jar:0.2.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.eclipse.kapua:kapua-datastore-client-transport:jar:0.2.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.eclipse.kapua:kapua-translator-kura-mqtt:jar:0.2.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.eclipse.kapua:kapua-translator-kapua-kura:jar:0.2.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.eclipse.kapua:kapua-transport-mqtt:jar:0.2.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.eclipse.kapua:kapua-broker-core:jar:0.2.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.eclipse.kapua:kapua-sso-api:jar:0.2.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.eclipse.kapua:kapua-sso-provider:jar:0.2.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.eclipse.kapua:kapua-sso-provider-generic:jar:0.2.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.eclipse.kapua:kapua-sso-provider-keycloak:jar:0.2.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.301 s
[INFO] Finished at: 2017-07-03T17:03:07+05:30
[INFO] Final Memory: 16M/89M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project kapua-console: Could not resolve dependencies for project org.eclipse.kapua:kapua-console:war:0.2.0-SNAPSHOT: The following artifacts could not be resolved: org.eclipse.kapua:kapua-device-registry-internal:jar:0.2.0-SNAPSHOT, org.eclipse.kapua:kapua-security-shiro:jar:0.2.0-SNAPSHOT, org.eclipse.kapua:kapua-device-call-kura:jar:0.2.0-SNAPSHOT, org.eclipse.kapua:kapua-device-commons:jar:0.2.0-SNAPSHOT, org.eclipse.kapua:kapua-device-bundle-internal:jar:0.2.0-SNAPSHOT, org.eclipse.kapua:kapua-device-command-internal:jar:0.2.0-SNAPSHOT, org.eclipse.kapua:kapua-device-configuration-internal:jar:0.2.0-SNAPSHOT, org.eclipse.kapua:kapua-device-packages-internal:jar:0.2.0-SNAPSHOT, org.eclipse.kapua:kapua-datastore-api:jar:0.2.0-SNAPSHOT, org.eclipse.kapua:kapua-datastore-internal:jar:0.2.0-SNAPSHOT, org.eclipse.kapua:kapua-datastore-client-transport:jar:0.2.0-SNAPSHOT, org.eclipse.kapua:kapua-translator-kura-mqtt:jar:0.2.0-SNAPSHOT, org.eclipse.kapua:kapua-translator-kapua-kura:jar:0.2.0-SNAPSHOT, org.eclipse.kapua:kapua-transport-mqtt:jar:0.2.0-SNAPSHOT, org.eclipse.kapua:kapua-broker-core:jar:0.2.0-SNAPSHOT, org.eclipse.kapua:kapua-sso-api:jar:0.2.0-SNAPSHOT, org.eclipse.kapua:kapua-sso-provider:jar:0.2.0-SNAPSHOT, org.eclipse.kapua:kapua-sso-provider-generic:jar:0.2.0-SNAPSHOT, org.eclipse.kapua:kapua-sso-provider-keycloak:jar:0.2.0-SNAPSHOT: Failure to find org.eclipse.kapua:kapua-device-registry-internal:jar:0.2.0-SNAPSHOT in https://raw.github.com/eurotech/kapua_addons/mvn-repo/ was cached in the local repository, resolution will not be reattempted until the update interval of kapua_addons has elapsed or updates are forced -> [Help 1]

**Comment by Coduz** [comment]
Hi @Roopa-Siddaveerappa ,

`GwtCredentialServiceAsync` and all `*Async` classes are generated by the build. 
Can you please try to rebuild using the following commands from the root of the project?

```
git checkout develop
git pull origin develop
mvn clean install -U
```

Regards, 

_Alberto_

**Comment by Roopa-Siddaveerappa** [comment]
sorry even i am getting same issue
even i am trying run kapua with doker but i am getting [Installing error: Docker cannot link. #656](https://github.com/eclipse/kapua/issues/656)
i am using running ubuntu in virtual box 16GRAM

**Comment by Coduz** [comment]
So You are running all docker inside a VM?

**Comment by Roopa-Siddaveerappa** [comment]
yes, i am running doker in VM
As i couldn't build Form Eclipse

**Comment by ctron** [comment]
So do you have an issue building or running Kapua? Because the initial issue comment describes a build error while the issue #656 refers to running Kapua.

So if you have not enough memory in your Ubuntu VM, then the startup will fail. Assigning more memory to the VM will solve this issue.

What issue do you have building with Eclipse? Kapua is built by running maven by using `mvn clean install` from the root of the project. And then you can build and start docker images as described by: https://github.com/eclipse/kapua/blob/develop/assembly/README.md

**Comment by Roopa-Siddaveerappa** [comment]
Thanks @ctron @Coduz 
Finally i could able to Run kapua access Admin Console and RestAPi

**Comment by ctron** [comment]
So we can close this?
