### ISSUE TITLE
How To connect Android Device to Kapua using MQTT

### ISSUE THREAD

**Issue by VivekPowar** [eclipse/kapua#719]
```
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.widget.Toast;

import org.eclipse.paho.android.service.MqttAndroidClient;
import org.eclipse.paho.client.mqttv3.IMqttActionListener;
import org.eclipse.paho.client.mqttv3.IMqttToken;
import org.eclipse.paho.client.mqttv3.MqttClient;
import org.eclipse.paho.client.mqttv3.MqttConnectOptions;
import org.eclipse.paho.client.mqttv3.MqttException;

public class MainActivity extends AppCompatActivity {

    public String MQTTHOST="tcp://kapua-broker:kapua-password@localhost:1883";
    public String USERNAME = "********";
    public String PASSWORD = "********";

    MqttAndroidClient client;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        String clientId = MqttClient.generateClientId();
         client =new MqttAndroidClient(this.getApplicationContext(), MQTTHOST,
                        clientId);


        try {
            MqttConnectOptions options = new MqttConnectOptions();
           // options.setUserName(USERNAME);
           // options.setPassword(PASSWORD.toCharArray());
            IMqttToken token = client.connect(options);

            token.setActionCallback(new IMqttActionListener() {
                @Override
                public void onSuccess(IMqttToken asyncActionToken) {
                    // We are connected
                    Toast.makeText(MainActivity.this,"Connected",Toast.LENGTH_LONG).show();
                }

                @Override
                public void onFailure(IMqttToken asyncActionToken, Throwable exception) {
                    // Something went wrong e.g. connection timeout or firewall problems
                    Toast.makeText(MainActivity.this,"Connection Failed",Toast.LENGTH_LONG).show();

                }
            });
        } catch (MqttException e) {
            e.printStackTrace();
        }
    }
}
```
______________OUTPUT________________
Connection Failed

**Comment by lorthirk** [comment]
Hi @VivekPowar, could you provide some logging from the Android app and/or from the broker maybe? Which MQTT library are you using to connect to Kapua?

**Comment by VivekPowar** [comment]
@lorthirk i am using Paho Android Service from this link :- http://www.hivemq.com/blog/mqtt-client-library-enyclopedia-paho-android-service

**Comment by lorthirk** [comment]
Ok. Have you tried removing username and password from the URI and setting them in the options (i.e. uncommenting those two lines)?

**Comment by lorthirk** [comment]
By the way, another thing: I see you're pointing to localhost. Are you trying this on the emulator or an actual device? If emulator, are you sure the network is not sandboxed somehow and that you can reach the broker via localhost properly?

**Comment by VivekPowar** [comment]
currently doing for local server now i got connection actually made change in broker url its needs only server ip :- tcp://192.168.1.200:1883 but now m unable to send data

**Comment by lorthirk** [comment]
What do you mean by "unable to send data" exactly? 

Please note that topic must start with `<account_name>/<client_id>` and the payload must be protobuf-encoded.

**Comment by VivekPowar** [comment]
@lorthirk my code is like this also its not showing in Device list   
String topic = "account_name";
        String payload = "the payload";
        byte[] encodedPayload = new byte[0];
        try {
            encodedPayload = payload.getBytes("UTF-8");
            MqttMessage message = new MqttMessage(encodedPayload);
            message.setRetained(true);
            client.publish(topic, message);
        } catch (UnsupportedEncodingException | MqttException e) {
            e.printStackTrace();
        }

**Comment by VivekPowar** [comment]
@lorthirk  my clientId is Vivek so i have to change like String topic = "Vivek"; but still it's not working my connection with clientId Vivek is done but its not showing Data and Device list also

**Comment by Coduz** [comment]
Hi @VivekPowar ,

In order to have a device register you have to publish a BIRTH message. This creates a new device entry. 

BIRTH message is a concept of Kura that has been endorsed also by Kapua.

Kapua is fully compatible with Kura (only some things are missing, but they are on plans)

I would suggest you to have a look at Eclipse Kura project. 
You can also find examples of usage.

Regards, 

_Alberto_

**Comment by VivekPowar** [comment]
@Coduz  Thanks for prompt reply. Is there any android api available for kura client . So that I can create my kura android client and connect to kapua. I have already connect kura simulator to kapua.

**Comment by ctron** [comment]
You can have a look at https://github.com/ctron/kapua-gateway-client which should provide you with a basic client.

**Comment by VivekPowar** [comment]
@Coduz how to register device and publish a BIRTH message ? my device connection is done please help

**Comment by VivekPowar** [comment]
@Coduz i want Android dependency this is maven dependency so how can i use it in android ?
 <dependency>
  <groupId>de.dentrassi.kapua</groupId>
  <artifactId>kapua-gateway-client-provider-mqtt-fuse</artifactId>
  <version></version>
</dependency>

**Comment by ctron** [comment]
@VivekPowar Please understand that this the issue tracker of an open source project and we are trying to help on a best effort basis. We cannot offer you instant consulting and training here. But of course we are willing to understand your problem and try to improve the documentation and Kapua itself in order to support you. For this it is necessary to understand your problem as good as possible and you can help us by providing as much information as possible from the start and educate yourself with the technologies required.

There are numerous tutorials on Google (or other search engines) which explain how to use maven dependencies with Android and I think that this is the wrong place to write another tutorial. If there is a specific issue using "kapua-gateway-client", then please report this either here or in the "kapua-gateway-client" project issue tracker and I am willing to look into this.

But at this moment it is not really clear to me what the issue actually is. So maybe you can provide some sort of error report or describe what is going wrong or what you are missing. Provide some code of what you are doing in order to understand your problem and I am willing to look into this as soon as I can.

**Comment by VivekPowar** [comment]
hi @ctron 
i tried with following code and still getting some ERROR java.lang.NoSuchMethodError so is there any solution for this 
       try (Client client = KuraMqttProfile.newProfile(FuseClient.Builder::new)
                .accountName("kapua-sys")
                .clientId("foo-bar")
                .brokerUrl("tcp://192.168.1.200:1883")
                .credentials(userAndPassword("kapua-broker", "kapua-password"))
                .build()) {

            Application.Builder builder=client.buildApplication("app");
            try {
                final Application application = builder.build();
                // wait for connection

                waitForConnection(application.transport());

                // subscribe to a topic

                application.data(Topic.of("my", "topic")).subscribe(message -> {
                    System.out.format("Received: %s%n", message);
                });

                // example payload

                final Payload.Builder payload = new Payload.Builder();
                payload.put("foo", "bar");
                payload.put("a", 1);

                try {
                    // send, handling error ourself
                    application.data(Topic.of("my", "topic")).send(payload);
                } catch (final Exception e) {
                    logger.info("Failed to publish", e);
                }

                // send, with attached error handler

                application.data(Topic.of("my", "receiver")).subscribe(new MessageHandler() {
                    @Override
                    public void handleMessage(Payload payload) {
                        System.out.format("Received: %s%n",payload );
                    }
                });

                // ignoring error

                application.data(Topic.of("my", "topic")).errors(ignore()).send(payload);

                // cache sender instance

                final Sender<RuntimeException> sender = application.data(Topic.of("my", "topic")).errors(ignore());

                int i = 0;
                while (i < 10) {
                    // send
                    sender.send(Payload.of("counter", i++));
                    Thread.sleep(1_000);
                }

                // sleep to not run into Paho thread starvation
                // Thread.sleep(100_000);
            }
            catch (Exception e)
            {
                e.printStackTrace();
                e.getMessage();
            }

            Thread.sleep(1_000);

        }
        catch (Exception e)
        {
            e.printStackTrace();
            e.getMessage();
        }

**Comment by ctron** [comment]
So what is the exact stack trace and error message that you get? `java.lang.NoSuchMethodError` point to a missing method, so the information which method is missing it important. Without it, it is impossible to understand the cause for that.

Is this maybe the same issue as #732? Then the explanation would already be there.

**Comment by ctron** [comment]
If you could provide (e.g in some git repository) provide a reproducer for this issue, then this would help us replicate and maybe fix the issue. The reproducer shouldn't be your full application, but just the portion which causes the error, but still be self-contained.

**Comment by VivekPowar** [comment]
@ctron https://github.com/VivekPowar/Kapua_Client_Connection this is my git repository and i am doing kapua device registration and publishing message so it will be very helpful for me if my issue will be solved

**Comment by ctron** [comment]
So when I import your project into Android Studio 2.3.3 I get an error about two missing projects:

![import_error](https://user-images.githubusercontent.com/202474/27958676-837e1898-6324-11e7-8fe9-7d9f0f7dbd4c.png)

It really is important that you check your setup and give proper instructions how to reproduce the issue. Otherwise this will cost others extra time, time which is missing to dig into your actual issue.

**Comment by VivekPowar** [comment]
@ctron select Keep All so these 2 modules will be loaded and then you can go ahead

**Comment by ctron** [comment]
So from what I see you are using the "Jack" toolchain, which is deprecated. [1] Did you follow the instructions from Android Studio and go with a most recent preview version of Android Studio 3.0?

[1] https://developer.android.com/studio/write/java8-support.html#supported_features

**Comment by VivekPowar** [comment]
@ctron u need java 8 so it will work my android version is Android Studio 2.3.3
    defaultConfig {
        ...
        // Remove this block.
        jackOptions {
            enabled true
            ...
        }
    }

    // Keep the following configuration in order to target Java 8.
    compileOptions {
        targetCompatibility 1.8
        sourceCompatibility 1.8
    }
}

**Comment by ctron** [comment]
Again, "jack" is deprecated, that is why is says "Remove this block.". Android Studio asks you to upgrade to Android Studio 3.0 for Java 8 support. I don't know how complete this support is. In any case following a deprecated way it probably the option with the least chance for success here.

I suggest you give it a try and dig into the issue. I will try to do the same if I can fine some spare time for this. Maybe there is a simple way to properly use Java 8 with Android.

**Comment by ctron** [comment]
So once I start this up in Android Studio, running on a virtual Android O instance, I don't see any error in the logcat view. How would you see the error?

**Comment by ctron** [comment]
Is that the expected outcome?

![screenshot](https://user-images.githubusercontent.com/202474/27960439-967577b4-632b-11e7-9c2c-fbfca315141a.png)

**Comment by VivekPowar** [comment]
@ctron yes this is the output now you can see in logcat Error for this program connection is not working change broker url with your kapua broker url it worked for maven with there dependency and I made some changes for Android for kapua device registration but this code having some Error that's why this application is crash. If it's possible then let me know what change this code need for kapua device registration and message publish

**Comment by ctron** [comment]
But as you can see, there is no error. I really don't know how I can help you without a proper error description or a reproducer.

**Comment by VivekPowar** [comment]
@ctron is there any change you have done or run as it is ? If you have no errors then you mean to say your device connection and registration  is done with as I mentioned client id is foo-bar ? I got Error of java.lang.NoSuchMethodError and also my application is crash

**Comment by VivekPowar** [comment]
@ctron hi , i got ERROR 
                                                                                java.lang.NoSuchMethodError: No static method join(Ljava/lang/CharSequence;Ljava/lang/Iterable;)Ljava/lang/String; in class Ljava/lang/String; or its super classes (declaration of 'java.lang.String' appears in /system/framework/core-oj.jar)
                                                                                    at org.eclipse.kapua.gateway.client.kura.KuraBirthCertificateModule.sendBirthCertificate(KuraBirthCertificateModule.java:160)
                                                                                    at org.eclipse.kapua.gateway.client.kura.KuraBirthCertificateModule.applicationAdded(KuraBirthCertificateModule.java:125)
                                                                                    at org.eclipse.kapua.gateway.client.spi.AbstractClient.org_eclipse_kapua_gateway_client_spi_AbstractClient_lambda$notifyAddApplication$1(AbstractClient.java:93)
                                                                                    at org.eclipse.kapua.gateway.client.spi.-$Lambda$KStGMhXnF-IIdxWAA04teiOckp0$5.$m$0(Unknown Source)
                                                                                    at org.eclipse.kapua.gateway.client.spi.-$Lambda$KStGMhXnF-IIdxWAA04teiOckp0$5.accept(Unknown Source)
                                                                                    at org.eclipse.kapua.gateway.client.spi.AbstractClient.fireModuleEvent(AbstractClient.java:85)
                                                                                    at org.eclipse.kapua.gateway.client.spi.AbstractClient.notifyAddApplication(AbstractClient.java:93)
                                                                                    at org.eclipse.kapua.gateway.client.spi.AbstractClient.internalBuildApplication(AbstractClient.java:148)
                                                                                    at org.eclipse.kapua.gateway.client.spi.AbstractClient$2.build(AbstractClient.java:134)
                                                                                    at com.example.vivek.mqttconnection.MainActivity.Connect(MainActivity.java:67)
                                                                                    at com.example.vivek.mqttconnection.MainActivity.onCreate(MainActivity.java:46)
                                                                                    at android.app.Activity.performCreate(Activity.java:6679)
                                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                                    at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                    at android.os.Looper.loop(Looper.java:154)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by ctron** [comment]
I just validated the setup. Using Android Studio 3.0 Canary 5, disabling the Jack toolchain, using Android target SDK 24, running on Android O, using the Android Gradle Plugin 3.0-alpha5 **does** work!

I suggest to replicate this and then start modifying your environment towards your target settings.

**Comment by VivekPowar** [comment]
@ctron i updated  Android Studio 3.0 Canary 5 and using Android target SDK 24, running on Android O still getting ERROR To publish message using Payload 

java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Instant;
org.eclipse.kapua.gateway.client.Payload$Builder.<init>(Payload.java:34)
com.example.vivek.mqttconnection.MainActivity.Connect(MainActivity.java:78)
com.example.vivek.mqttconnection.MainActivity.onCreate(MainActivity.java:45)
android.app.Activity.performCreate(Activity.java:6679)
android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
android.app.ActivityThread.-wrap12(ActivityThread.java)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
android.os.Handler.dispatchMessage(Handler.java:102)
android.os.Looper.loop(Looper.java:154)
android.app.ActivityThread.main(ActivityThread.java:6119)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
java.lang.ClassNotFoundException: Didn't find class "java.time.Instant" on path: DexPathList[[zip file "/data/app/com.example.vivek.mqttconnection-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.vivek.mqttconnection-1/lib/x86, /system/lib, /vendor/lib]]
dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
java.lang.ClassLoader.loadClass(ClassLoader.java:380)
java.lang.ClassLoader.loadClass(ClassLoader.java:312)

**Comment by ctron** [comment]
Did you disable jack?

**Comment by ctron** [comment]
And did you update to the 3.0 version of the Gradle build plugin?

**Comment by VivekPowar** [comment]
@ctron as u given reply of screenshot of android application is not the expected output actually you that application is not executed properly because output is like  
![screenshot from 2017-07-12 11-55-00](https://user-images.githubusercontent.com/25997057/28104528-2bdaa088-66f9-11e7-928f-471ef61d898f.png)

as you can see my clientId is mobile_vivek so that client is connected to kapua server its shows in Devices 
![image](https://user-images.githubusercontent.com/25997057/28104675-f451def0-66f9-11e7-91b2-f2c4297b18b2.jpg)

also that client will show in Connection 
![image 1](https://user-images.githubusercontent.com/25997057/28104741-33856e02-66fa-11e7-9a91-5ae4dc80d4b4.jpg)

but in Data its not show the Data which is published in program with Topic name as you can see it is Mobile Data 
![image 2](https://user-images.githubusercontent.com/25997057/28104870-b6108b68-66fa-11e7-8c60-8d6f35c8733d.jpg)

so that is my current output i need Data which is published from program. and i think you run the application as it is please show me the connection with your local kapua server and then check my issue of message publish to kapua server
can you getting my point what is my issue and i am expecting output ?

**Comment by ctron** [comment]
Maybe you can point me to the location of your program where you are actually publishing telemetry data.

**Comment by VivekPowar** [comment]
@ctron what is telemetry data what you exactly mean ?

**Comment by ctron** [comment]
Measurement data you send to Kapua.

**Comment by VivekPowar** [comment]
@ctron this is my code 
                Application application=client.buildApplication("android").build();


                final Sender<RuntimeException> sender = application.data(Topic.split("random")).errors(ignore());

                System.out.format("Message ", "Waiting for Connection");
                Toast.makeText(MainActivity.this,"Waiting for Connection",Toast.LENGTH_LONG).show();
                // wait for connection
                Transport.waitForConnection(client.transport());
                // subscribe to a topic

                System.out.format("Message ", "Connection Done...!!!");
                Toast.makeText(MainActivity.this,"Connection Done...!!!",Toast.LENGTH_LONG).show();

                final Random r=new Random();

                while (true)
                {
                    sender.send(Payload.of("input",r.nextDouble()));
                    Thread.sleep(1_000);
                }

**Comment by ctron** [comment]
Looks good to me.

**Comment by VivekPowar** [comment]
@ctron ok then its good for me If you could provide (e.g in some git repository) so i can find out what exactly the issue is

**Comment by ctron** [comment]
Please see https://github.com/eclipse/kapua/issues/738#issuecomment-314686902 for that

**Comment by VivekPowar** [comment]
@ctron yes actually i made same changes like this but its not working is there any changes or any dependency need to add for that ?

**Comment by VivekPowar** [comment]
@ctron @lorthirk @Coduz Thanks for the help now i get the expected output with your help thanks for support 

Thanks & Regards,
Vivek

**Comment by TheBeachMaster** [comment]
Hey   guys... 👋  

Interesting discussion. 

Based on this thread... 

I have this setup:  
1. Client :  ***MQTT-Spy*** 
2. Broker: ***Kapua***  
3. Setup : ***Docker*** 


Then 
  Topic : /kapua-sys/Kennedy/someTopic 
 
> Now , I've been able to publsih data to Kapua as well as subscribe; however, the data node of Kapua console does not show anything...Meaning it blank...No devices, no connections...nothing. 
 
# Help needed. 
Thanks @ctron  , @lorthirk  for the awesome work
 
![kapua](https://user-images.githubusercontent.com/9129843/29559717-84a93b34-8738-11e7-8bf1-4f2545c8a994.png)
![kapua-console](https://user-images.githubusercontent.com/9129843/29559716-84a90f4c-8738-11e7-8a89-6403226edfbe.png)
![kapua-data](https://user-images.githubusercontent.com/9129843/29559718-84ab2af2-8738-11e7-9854-543c22a7bb19.png)

**Comment by ctron** [comment]
The problem is that you cannot just send plain text messages. You will need to use the binary format from Kapua/Kura.

**Comment by noumanpowersoft19** [comment]
AGPBI: {"kind":"error","text":"Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.lang.Runnable","sources":[{"file":"C:\\Users\\nouman.jamil\\Downloads\\Kapua_Client_Connection-master\\TransportAsync.java","position":{"startLine":32,"endLine":33}}]}
AGPBI: {"kind":"error","text":"Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Consumer","sources":[{"file":"C:\\Users\\nouman.jamil\\Downloads\\Kapua_Client_Connection-master\\AbstractClient.java","position":{"startLine":92,"endLine":93}}]}
AGPBI: {"kind":"error","text":"Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Consumer","sources":[{"file":"C:\\Users\\nouman.jamil\\Downloads\\Kapua_Client_Connection-master\\AbstractClient.java","position":{"startLine":114,"endLine":115}}]}
AGPBI: {"kind":"error","text":"Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Consumer","sources":[{"file":"C:\\Users\\nouman.jamil\\Downloads\\Kapua_Client_Connection-master\\AbstractClient.java","position":{"startLine":96,"endLine":97}}]}
AGPBI: {"kind":"error","text":"Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Consumer","sources":[{"file":"C:\\Users\\nouman.jamil\\Downloads\\Kapua_Client_Connection-master\\AbstractClient.java","position":{"startLine":123,"endLine":124}}]}
AGPBI: {"kind":"error","text":"Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Consumer","sources":[{"file":"C:\\Users\\nouman.jamil\\Downloads\\Kapua_Client_Connection-master\\AbstractClient.java","position":{"startLine":100,"endLine":101}}]}
AGPBI: {"kind":"error","text":"Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Consumer","sources":[{"file":"C:\\Users\\nouman.jamil\\Downloads\\Kapua_Client_Connection-master\\AbstractClient.java","position":{"startLine":67,"endLine":68}}]}
AGPBI: {"kind":"error","text":"Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Consumer","sources":[{"file":"C:\\Users\\nouman.jamil\\Downloads\\Kapua_Client_Connection-master\\AbstractClient.java","position":{"startLine":105,"endLine":106}}]}

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithPreJackPackagedLibrariesForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.core.JackToolchain$ToolchainException: Jack compilation exception

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s

Please help me on it @VivekPowar i am using same source code which i download from your repository
