### ISSUE TITLE
How to connect and register  android device with kapua and publish message ?

### ISSUE THREAD

**Issue by amitghodke90** [eclipse/kapua#722]

**Comment by lorthirk** [comment]
Hi @amitghodke90,

Please see #719. I'm closing this as duplicate.

**Comment by amitghodke90** [comment]
i am able to connect to kapua but device is not showing in connected devices list so the message sent from  android is not received at kapua server what should i do?

**Comment by amitghodke90** [comment]
the issue is not solved and you closed it

**Comment by lorthirk** [comment]
I closed it because it's a duplicate of #719, as I already told you. Since you're asking the same question of the other issue, it's for the best to keep questions and answers in a unique place rather then having to track them in multiple issues.
