### ISSUE TITLE
how to publish birth message from android mqttclient to kapua server?

### ISSUE THREAD

**Issue by amitghodke90** [eclipse/kapua#724]
```
String topic = "kapua-sys/"+clientId;
String payload = "the payload";
byte[] encodedPayload = new byte[0];
try {
    encodedPayload = payload.getBytes("UTF-8");
    MqttMessage message = new MqttMessage(encodedPayload);
    message.setRetained(true);

    client.publish(topic, message);
} catch ( Exception e) {
    e.printStackTrace();
    showToast(clientId+" Error\n"+e.getMessage());
}
```

able to send message but no message received at server end plz help.

**Comment by amitghodke90** [comment]
String topic = "kapua-sys/"+clientId;
        String payload = "the payload";
        byte[] encodedPayload = new byte[0];
        try {
            encodedPayload = payload.getBytes("UTF-8");
            MqttMessage message = new MqttMessage(encodedPayload);
            message.setRetained(true);

            client.publish(topic, message);
        } catch ( Exception e) {
            e.printStackTrace();
            showToast(clientId+" Error\n"+e.getMessage());
        }

able to send message but no message received at server end plz help.

**Comment by amitghodke90** [comment]
@Coduz @lorthirk ??

**Comment by lorthirk** [comment]
@amitghodke90, please follow the advices in #719 about using a Kapua client ([this comment specifically](https://github.com/eclipse/kapua/issues/719#issuecomment-312848805))

**Comment by amitghodke90** [comment]
i downloaded the example but unable to execute it and i want to import this client in android so how can i achieve it because the library is in java is there any lib or sdk for android??

**Comment by amitghodke90** [comment]
@lorthirk @Coduz

**Comment by amitghodke90** [comment]
@lorthirk ??

**Comment by lorthirk** [comment]
Could you provide some more detail? What does it mean that you are "unable to execute"?

**Comment by amitghodke90** [comment]
ok..
i have open maven project in eclipse and run maven install command the project is successfully build as shown
[INFO] 
[INFO] Eclipse Kapua :: Gateway Client .................... SUCCESS [  0.369 s]
[INFO] Eclipse Kapua :: Gateway Client :: API ............. SUCCESS [  2.592 s]
[INFO] Eclipse Kapua :: Gateway Client :: SPI ............. SUCCESS [  1.133 s]
[INFO] Eclipse Kapua :: Gateway Client :: Provider :: MQTT  SUCCESS [  0.147 s]
[INFO] Eclipse Kapua :: Gateway Client :: Provider :: MQTT :: FUSE SUCCESS [  0.172 s]
[INFO] Eclipse Kapua :: Gateway Client :: Provider :: MQTT :: Eclipse Paho SUCCESS [  0.137 s]
[INFO] Eclipse Kapua :: Gateway Client :: Profile :: Eclipse Kura SUCCESS [  1.549 s]
[INFO] Eclipse Kapua :: Gateway Client :: Features ........ SUCCESS [  0.006 s]
[INFO] Eclipse Kapua :: Gateway Client :: Features :: Karaf SUCCESS [  1.262 s]
[INFO] Eclipse Kapua :: Gateway Client :: Examples ........ SUCCESS [  0.006 s]
[INFO] Examples :: Eclipse SmartHome ...................... SUCCESS [  0.339 s]
[INFO] Eclipse Kapua :: Gateway Client :: Features :: Karaf (Examples) SUCCESS [  0.461 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.286 s
[INFO] Finished at: 2017-07-06T14:35:19+05:30
[INFO] Final Memory: 54M/415M
[INFO] ------------------------------------------------------------------------
but i dont know what to do next.
i have got an jar file generated in side target folder @ path =/kapua-gateway-client-master/gateway-client-profile-kura/target
and i am running it as java -jar <jar_file_name>.jar

getting error no main manifest attribute

 where i went wrong ??

**Comment by lorthirk** [comment]
Have you tried following the [kapua-device-client](https://github.com/ctron/kapua-gateway-client) README.md?

**Comment by amitghodke90** [comment]
@lorthirk 
yes read and followed and used in my another separate maven project .there is  only one main function with public class App 
{
	public static void main( String[] args )
	{
		//  System.out.println( "Hello World!" );

		try  {
			final Client client = KuraFuseMqttProfile.newProfile()
					.accountName("kapua-sys")
					.clientId("foo-bar-1")
					.brokerUrl("tcp://192.168.1.200:1883")
					.credentials(userAndPassword("kapua-broker", "kapua-password"))
					.build();
					try  {

						// wait for connection
						final Application application = client.buildApplication("app1").build().
								waitForConnection(application.transport());

						// subscribe to a topic

//						application.data(Topic.of("my", "topic")).subscribe(message -> {
//							System.out.format("Received: %s%n", message);
//						});

						// example payload

						final Payload.Builder payload = new Payload.Builder();
						payload.put("foo", "bar");
						payload.put("a", 1);

						try {
							// send, handling error ourself
							application.data(Topic.of("my", "topic")).send(payload);
						} catch (final Exception e) {
							logger.info("Failed to publish", e);
						}

						// send, with attached error handler

						application.data(Topic.of("my", "topic"))
						//.errors(handle((e, message) -> System.err.println("Failed to publish: " + e.getMessage())))
						.send(payload);

						// ignoring error

						application.data(Topic.of("my", "topic")).errors(ignore()).send(payload);

						// cache sender instance

						final Sender<RuntimeException> sender = application.data(Topic.of("my", "topic")).errors(ignore());

						int i = 0;
						while (i < 10) {
							// send
							sender.send(Payload.of("counter", i++));
							Thread.sleep(1000);
						}

						// sleep to not run into Paho thread starvation
						// Thread.sleep(100_000);
					}
			catch (Exception e) {
				// TODO: handle exception
			}
			Thread.sleep(1000);

		}
		catch (Exception e) {
			// TODO: handle exception
		}
	}
}

added dependency in pom.xml 
<dependency>
			<groupId>de.dentrassi.kapua</groupId>
			<artifactId>kapua-gateway-client-provider-mqtt-fuse</artifactId>
			<version>0.2.1</version>
		</dependency>


but after saving pom.xml i am getting errors
Description	Resource	Path	Location	Type
KuraFuseMqttProfile cannot be resolved	App.java	/gdf/src/main/java/fv/gdf	line 20	Java Problem
logger cannot be resolved	App.java	/gdf/src/main/java/fv/gdf	line 48	Java Problem
The method ignore() is undefined for the type App	App.java	/gdf/src/main/java/fv/gdf	line 59	Java Problem
The method ignore() is undefined for the type App	App.java	/gdf/src/main/java/fv/gdf	line 63	Java Problem
The method userAndPassword(String, String) is undefined for the type App	App.java	/gdf/src/main/java/fv/gdf	line 24	Java Problem
The method waitForConnection(Transport) is undefined for the type Application	App.java	/gdf/src/main/java/fv/gdf	line 30	Java Problem


i guess version i specified the not correct   what is the current version for dependency ?

**Comment by amitghodke90** [comment]
@lorthirk what should be the version
<dependency>
  <groupId>de.dentrassi.kapua</groupId>
  <artifactId>kapua-gateway-client-provider-mqtt-fuse</artifactId>
  <version></version>
</dependency>

**Comment by lorthirk** [comment]
0.2.1 is the latest version currently, according to Maven Central.

It seems from your snippet that you're using a class named `KuraFuseMqttProfile`; however, from the README of kapua-gateway-client I see that the initialization is quite different:
```
try (Client client = KuraMqttProfile.newProfile(FuseClient.Builder::new)
  .accountName("kapua-sys")
  .clientId("foo-bar-1")
  .brokerUrl("tcp://localhost:1883")
  .credentials(userAndPassword("kapua-broker", "kapua-password"))
  .build()) {
...
}
```
So I would try that approach first. Also, I think you have to include the full project in your pom.xml, not just kapua-gateway-client-provider-mqtt-fuse.

**Comment by amitghodke90** [comment]
oh .. its mistake  changed it to KuraMqttProfile but still result is same.

can you tell which specific project should i include or whose 8 projects and how??

**Comment by lorthirk** [comment]
As I said (and also the README says), just include
```
<dependency>
  <groupId>de.dentrassi.kapua</groupId>
  <artifactId>kapua-gateway-client-provider-mqtt-fuse</artifactId>
  <version>0.2.1</version>
</dependency>
```

**Comment by lorthirk** [comment]
I would try including
```
<dependency>
  <groupId>de.dentrassi.kapua</groupId>
  <artifactId>kapua-gateway-client</artifactId>
  <version>0.2.1</version>
</dependency>
```

**Comment by amitghodke90** [comment]
@lorthirk  this is my pom.xml dependencies
<dependencies>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>3.8.1</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>de.dentrassi.kapua</groupId>
			<artifactId>kapua-gateway-client-provider-mqtt-fuse</artifactId>
			<version>0.2.1</version>
		</dependency>

	</dependencies>

have already added

**Comment by amitghodke90** [comment]
@lorthirk its giving error  
Missing artifact de.dentrassi.kapua:kapua-gateway-client:jar:0.2.1	pom.xml	/gdf	line 30	Maven Dependency Problem
after adding 
<dependency>
  <groupId>de.dentrassi.kapua</groupId>
  <artifactId>kapua-gateway-client</artifactId>
  <version>0.2.1</version>
</dependency>

**Comment by lorthirk** [comment]
Well, that's strange since it is on Maven Central: http://search.maven.org/#artifactdetails%7Cde.dentrassi.kapua%7Ckapua-gateway-client%7C0.2.1%7Cpom

I'm afraid I can't be anymore helpful 😞

**Comment by amitghodke90** [comment]
@lorthirk  it's ok.
thats useful for me thank you its worked for me in maven project but one more final question any hint for android? i.t how can i convert this to android sdk.

**Comment by lorthirk** [comment]
I would just try to use this code inside an Android Activity, but unfortunately I'm not proficient enough in Android development to give you better hints.

**Comment by amitghodke90** [comment]
@lorthirk ok thank you once again.

**Comment by ctron** [comment]
I will have a look at this tomorrow, I am currently traveling.

In general it looks like you are trying to reference a pom only project as a jar project. You should add the fuse provider and the kura profile. Nothing else should be required. Be careful with the imports as some imports are statics imports.

**Comment by ctron** [comment]
To me this looks like a duplicate to #719 in the end. Please let me know if there is any difference.

**Comment by noumanpowersoft19** [comment]
@amitghodke90  @ctron @lorthirk i have tried to use this same code inside an android project but its not working for me. Kindly guide me on how to use it inside android application.
