### ISSUE TITLE
swagger.json not being built?

### ISSUE THREAD

**Issue by kartben** [eclipse/kapua#74]
The getting started on the website indicates that the API docs is available at http://192.168.33.10:8080/api/doc

The generic swagger webapp is indeed accessible at this URL, but it tries to locate swagger.json at http://192.168.33.10:8080/kapua/api/v1/swagger.json ... and there seems to be no such file there, or anywhere else in the Kapua build.

**Comment by lorthirk** [comment]
Hi Benjamin,

Swagger is currently broken on develop; the related fix is in PR #73, waiting to be merged.

**Comment by kartben** [comment]
Right, but even #73 does not seem to produce a swagger.json, or does it?

**Comment by lorthirk** [comment]
The swagger.json is served virtually at runtime by the Swagger servlet, it's not a static file residing on the disk. Could you point to http://localhost:8080/api/v1/swagger.json and check if you get any output?

**Comment by Coduz** [comment]
Hi @kartben and @lorthirk ,

this has been answered or it needs more details?

Thanks,

_Alberto_
