### ISSUE TITLE
API Client packages Error (POST /{scopeId}/devices/{deviceId}/packages/_download)

### ISSUE THREAD

**Issue by rougeo** [eclipse/kapua#740]
Hello
I am trying to make a Rest Client connecting to the API using angular2. I am using the SWAGGER to see how the requests works and theses ones areOK 

- Authentication
- get devices
- get packages
- Uninstall package

Yet i have some troubles with the download package even with the swagger.

The package URL is " http://dell/temp.dp" and it's accessible from the Kura device ( i have tested it using the kapua webUI and the deployment is working using it)
![screen shot 07-12-17 at 02 09 pm](https://user-images.githubusercontent.com/12080962/28117402-9138a222-670d-11e7-8dc4-73cf0198b6c0.PNG)

Now if I use the swagger: here is my data to POST: 
![screen shot 07-12-17 at 02 23 pm](https://user-images.githubusercontent.com/12080962/28117438-baf0d6de-670d-11e7-98eb-fe2b818f7b1a.PNG)

I have this error: 

![screen shot 07-12-17 at 02 23 pm 001](https://user-images.githubusercontent.com/12080962/28117455-cb5cfc8c-670d-11e7-8ec3-eb4027a02937.PNG)

I think that I used the right params, now I don't know if it's from the API server or what. I just want first to make it work with the swagger UI.

Thanks

Some ideas

**Comment by lorthirk** [comment]
Hi @rougeo,

Can you try to make uppercase the URI property in the body?

**Comment by rougeo** [comment]
Thank you  @lorthirk  !! it's working now with that !!

**Comment by lorthirk** [comment]
Ok. Now we just have to decide whether it's better to conform the doc to the API, or the other way around, since lowercase field are usually used in REST APIs.

Glad it works :)

**Comment by rougeo** [comment]
So keep us posted through this issue please before closing it !! 

Thanks again !!

**Comment by lorthirk** [comment]
I can confirm that the 0.2.0 release will contain commit f652983 (which is a cherrypick of f43410f), so the `uri` field will be only accepted in lowercase.
