### ISSUE TITLE
Scaling Kapua with Kubernetes

### ISSUE THREAD

**Issue by Mack13Podwin** [eclipse/kapua#744]
Hi! How can I scale Kapua with Kubernetes?

**Comment by stefanomorson** [comment]
Actually we don't provide a plain Kubernetes deployment, however the team maintains a reference deployment for OpenShift Origin [1] which is (citing the GitHub web site):
> a distribution of Kubernetes optimized for continuous application development and multi-tenant deployment

You can find the documentation for running Kapua on a OpenShift instance [here](https://github.com/eclipse/kapua/blob/develop/docs/developer-guide/en/running.md#openshift) in the project documentation.
 
[1] [OpenShift Origin](https://github.com/openshift/origin)

**Comment by stefanomorson** [comment]
Close the issue for inactivity.
If new feedbacks and questions will come feel free to open it up again.

**Comment by fedemonte89** [comment]
Hi! I'm curious about a possible scaling functionality in kapua. Are all its components developed to support multiple instances (ex. multiple instance of "console", multiple instances of "broker" and so on...)?

Thank you for your support :-) !
