### ISSUE TITLE
A problem about sso

### ISSUE THREAD

**Issue by StevenWash** [eclipse/kapua#749]
Hi,I am sorry to bother you !These days I find a new problem in sso when I use it.The code in  the SsoCallbackServlet can not get the accessToken correctly:
![image](https://user-images.githubusercontent.com/18731292/28257194-7a5b2e3e-6afb-11e7-9ba3-a4846d07beb1.png)  
And the jsonObject was null.And then I fund that 'getAccessToken()' was located in 
![image](https://user-images.githubusercontent.com/18731292/28257231-c100c38a-6afb-11e7-8e68-e462caf467ca.png)
But I think the method maybe located in AbstractSingleSignOnService.So can you give me some advice about it if it is a bug ?Or tell me how to use it !
Thank yo very much!

**Comment by ctron** [comment]
If the call goes got the `DisabledLocator` then SSO is disabled and the access token will always be `null`. The SSO system will be disabled if the configuration key `sso.provider` is unset. You can set it to `generic` or `keycloak` but you will need to provide additional configuration.

I think we will need to update the documentation to properly cover this.

**Comment by ctron** [comment]
I added a bit on the developer guide about that right now: http://download.eclipse.org/kapua/docs/develop/developer-guide/en/sso.html#enabling-single-sign-on

**Comment by StevenWash** [comment]
@ctron Thank you very much!I have known how to use sso with the help of you !And I also think you had better update the documentation to  properly cover this.
Thank you again!

**Comment by StevenWash** [comment]
@ctron 
Hi,
Excuse me ,I have a question to ask you that wether the sso implemet  operations that store the external user into the database ?And it include the table of usr_user ,athz_access_info and athz_access_token?
Thank you very much!

**Comment by ctron** [comment]
It uses the external user id in the user table.

**Comment by StevenWash** [comment]
Yes,I know it uses the external user id int the user table .But I mean that whether it will add a new user to the user table when a external user login successfully?For exapmle , in the SsoCallbackServlet,it will get accessToken and return to the homeUri,and then it will redirect to sso login page ,but an error will occured because that the 
![image](https://user-images.githubusercontent.com/18731292/28304082-c08bf550-6bc8-11e7-98d4-c334c7094a34.png) in the
![image](https://user-images.githubusercontent.com/18731292/28304106-d755773e-6bc8-11e7-9983-8df1e5cec425.png) of the AuthenticationServiceShiroImpl will throw a ShiroException.
I guess the problem maybe that there is not exist a external user in the user table.
So,I declear my problem again,wether it have stored the external user infomations into the user table ?
I don`t know wether I have declear my problem clearly.
Thank you very much!

**Comment by ctron** [comment]
Well this is a current limitation of the implementation. There is no real way to connect up an existing user to the SSO solution.

You can do this manually though, by assigning the external ID, assigned by your SSO solution, to the field in the user table.

An alternative is to use auto-account creation, which is however also undocumented, as this is currently only targeting the public sandbox server scenario, where we will auto-create a single user, with a single account. But plan to reset the server every now and then.

Sorry, I know this is probably not the answer you where looking for. But in any case I will close this issue and maybe you can open a new one, describing your SSO scenario. If you don't want to I can do this as well. But I guess it would be more correct if it comes from you.
