### ISSUE TITLE
Document how to connect Kura to Kapua

### ISSUE THREAD

**Issue by ctron** [eclipse/kapua#751]
There should be some guide we can point people towards when they want to configure Kura to connect to Kapua.

**Comment by ctron** [comment]
Also see: https://dentrassi.de/2017/02/14/testing-kapua-with-simulated-kura-gateways/#comment-19043

**Comment by LeoNerdoG** [comment]
@ctron I can make such documentation -  I can describe how to start Kapua (although already described) and connect it to Raspberry Pi. Where do I upload this document (or whom do I send it)? 
BR,
Leonardo

**Comment by LeoNerdoG** [comment]
Hi @ctron,
I have created PR PR#780 which contains steps for Kura -Kapua connection. 
This is the first version, it will be updated.

Regards,
Leonardo

**Comment by riccardomodanese** [comment]
closed via #780
