### ISSUE TITLE
help

### ISSUE THREAD

**Issue by zhouyue123** [eclipse/kapua#752]
I build a new entity ，Entity attributes correspond to database tables one by one。When I implemented the add function。Account password login, access to tookenId, return status 415,There are also some error messages：

 - with linked exception:
[Exception [EclipseLink-0] (Eclipse Persistence Services - 2.6.3.v20160428-59c81c5): org.eclipse.persistence.exceptions.IntegrityException
Descriptor Exceptions:
---------------------------------------------------------

Exception [EclipseLink-169] (Eclipse Persistence Services - 2.6.3.v20160428-59c81c5): org.eclipse.persistence.exceptions.DescriptorException
Exception Description: Problem in creating new instance of factory using the default constructor.  The default constructor triggered an exception.
Internal Exception: java.lang.reflect.InvocationTargetException
Target Invocation Exception: org.eclipse.kapua.KapuaRuntimeException: Error: interface org.eclipse.kapua.service.appversion.AppVersionFactory
Descriptor: XMLDescriptor(org.eclipse.kapua.service.appversion.AppVersionListResult --> [DatabaseTable(appVersionListResult), DatabaseTable(result)])

Exception [EclipseLink-169] (Eclipse Persistence Services - 2.6.3.v20160428-59c81c5): org.eclipse.persistence.exceptions.DescriptorException
Exception Description: Problem in creating new instance of factory using the default constructor.  The default constructor triggered an exception.
Internal Exception: java.lang.reflect.InvocationTargetException
Target Invocation Exception: org.eclipse.kapua.KapuaRuntimeException: Error: interface org.eclipse.kapua.service.appversion.AppVersionFactory
Descriptor: XMLDescriptor(org.eclipse.kapua.service.appversion.AppVersionCreator --> [DatabaseTable(appVersionCreator)])

Exception [EclipseLink-169] (Eclipse Persistence Services - 2.6.3.v20160428-59c81c5): org.eclipse.persistence.exceptions.DescriptorException
Exception Description: Problem in creating new instance of factory using the default constructor.  The default constructor triggered an exception.
Internal Exception: java.lang.reflect.InvocationTargetException
Target Invocation Exception: org.eclipse.kapua.KapuaRuntimeException: Error: interface org.eclipse.kapua.service.appversion.AppVersionFactory
Descriptor: XMLDescriptor(org.eclipse.kapua.service.appversion.AppVersion --> [DatabaseTable(appVersion)])

Exception [EclipseLink-169] (Eclipse Persistence Services - 2.6.3.v20160428-59c81c5): org.eclipse.persistence.exceptions.DescriptorException
Exception Description: Problem in creating new instance of factory using the default constructor.  The default constructor triggered an exception.
Internal Exception: java.lang.reflect.InvocationTargetException
Target Invocation Exception: org.eclipse.kapua.KapuaRuntimeException: Error: interface org.eclipse.kapua.service.appversion.AppVersionFactory
Descriptor: XMLDescriptor(org.eclipse.kapua.service.appversion.AppVersionQuery --> [DatabaseTable(query)])

Runtime Exceptions:
---------------------------------------------------------
]
        at org.eclipse.kapua.app.api.JaxbContextResolver.<init>(JaxbContextResolver.java:376)

![image](https://user-images.githubusercontent.com/28722594/28358919-38298688-6ca3-11e7-9ce3-829dedd3fd24.png)

Can you help  me?  thanks a lot

**Comment by Coduz** [comment]
Hi @zhouyue123 ,

Do you still have this problem? 

Regards, 

_Alberto_
