### ISSUE TITLE
Why cann`t use GwtUserService or UserService in SsoCallbackServlet in the console?

### ISSUE THREAD

**Issue by StevenWash** [eclipse/kapua#754]
Hi,
      I have a problem in how to create a new user in the servlet named SsoCallbackServlet in the console.I want to use the accessToken in the method named doGet in the SsoCallbackServlet to create a new user ,and then use the UserService to store the new user into the user table.But ,it occurred errors like that:
![image](https://user-images.githubusercontent.com/18731292/28397158-6475f3c2-6d32-11e7-8b74-106b3595364a.png)
      And then ,I tried to use GwtUserService to do the same things above, and ,it occurred errors llike above.So,I want to ask how to create a new user using the infomations from the accessToken after the SsoCallbackServlet was called.
     Thank you very mush!

**Comment by ctron** [comment]
Please have a look at the modules kapua-security-registration. They do exactly that.
