### ISSUE TITLE
How to Publish and Listen Message of Kapua In ActiveMQ ?

### ISSUE THREAD

**Issue by VivekPowar** [eclipse/kapua#756]
is there any console for ActiveMQ and on which host and port its running in kapua ?

**Comment by VivekPowar** [comment]
@ctron @lorthirk @Coduz need help

**Comment by ctron** [comment]
I don't know, did you check the ActiveMQ configuration? Did you check for any open ports which could indicate a running web console?

**Comment by VivekPowar** [comment]
@ctron yes i already added port while creating images of docker which is port 61614 but web console is not showing

**Comment by ctron** [comment]
So you did add a port in the Dockerfile? What about the rest?

**Comment by VivekPowar** [comment]
@ctron  
yes, but how can i see messages in ActiveMQ which is send by the device ? my device is publishing message with one topic name so is there any way to see in console ?

**Comment by ctron** [comment]
You can always subscribe with tool like MQTTfx

**Comment by VivekPowar** [comment]
@ctron Actually i want console like ActiveMQ server where i can see Queue, Topics , Messages Enqueued  Messages Dequeued of Kapua ?

**Comment by ctron** [comment]
Why not use the jolokia jmx integration in combination with OpenShift?

**Comment by VivekPowar** [comment]
@ctron how to subscribe topic in kapua ?

**Comment by ctron** [comment]
By using MQTT? Using the ActiveMQ broker?

**Comment by VivekPowar** [comment]
by using both

**Comment by ctron** [comment]
What do you mean by "both"? There is only one broker?!

**Comment by VivekPowar** [comment]
yes i connected device with MQTT and i want to subscribe topic

**Comment by ctron** [comment]
Feel free to re-open this issue if more information is needed.
