### ISSUE TITLE
Kapua and Oracle  DB

### ISSUE THREAD

**Issue by VMRaghu** [eclipse/kapua#759]
In the Kapua documnetation I have seen it supports marai and H2 database.  As per the project requirement we need to use Oracle DB. 

Please explain the steps to be followed to change from default  Kapua supported (H2/Maria) DB to Oracle

Thanks,
Raghu

**Comment by Coduz** [comment]
To allow Oracle DB integration you need to provide the correct parameters to build the correct JDBC connection string.

Parameters are:

- `commons.db.name`
- `commons.db.connection.scheme`
- `commons.db.connection.host`
- `commons.db.connection.port`
- `commons.db.schema (optional)`

All these parameters can be passed to the application via system properties.
These parameters will be handled by the `DefaultConfigurableJdbcConnectionUrlResolver` to build the correct JDBC connection string which is requested by the `JdbcConnectionUrlResolvers.resolveJdbcUrl()`.

It is also require to provide to the component the `.jar` with the correct JDBC driver. 

Regards, 

_Alberto_

**Comment by Coduz** [comment]
Closing the issue. Feel free to reopen the issue if you need more help.
