### ISSUE TITLE
How to get User wise Topics from swagger Api ?

### ISSUE THREAD

**Issue by VivekPowar** [eclipse/kapua#768]
@Coduz @ctron @lorthirk  is there any way to get all topic list of user ?

**Comment by Coduz** [comment]
Hi @VivekPowar , 

Filtering on datastore is not available by user.

BTW I think that we can see the issues even without direct tagging, thanks.

**Comment by VivekPowar** [comment]
Thanks @Coduz sorry for tagging

**Comment by Coduz** [comment]
No problem :)
