### ISSUE TITLE
Simulator-kura build failed

### ISSUE THREAD

**Issue by ishuverma** [eclipse/kapua#775]
When building the kura-simulator, I get the following error:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (checkstyle-check) on project kapua-simulator-kura: Execution checkstyle-check of goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check failed: Plugin org.apache.maven.plugins:maven-checkstyle-plugin:2.17 or one of its dependencies could not be resolved: Could not find artifact org.eclipse.kapua.build:kapua-build-tools:jar:0.2.0-SNAPSHOT in apache.snapshots (http://repository.apache.org/snapshots)

**Comment by ctron** [comment]
You will need to build the project `kapua-build-tools` by executing `mvn install` manually before building the kura-simulator.

Alternatively you can do a full kapua build from the root of the repository by executing `mvn install -Pdev -DskipTests`.

**Comment by ishuverma** [comment]
Thanks. I did the full build as suggested and it worked.
