### ISSUE TITLE
streams api body  in payload 

### ISSUE THREAD

**Issue by zhouyue123** [eclipse/kapua#794]
When publishing a message, how does the body parameter pass in  payload?

    {
        "type": "kapuaDataMessage",
        "position": {
        "type": "kapuaPosition",
          "latitude":5.0,
          "longitude":5.0
        },
        "clientId": "AA:BB:CC:DD:EE:FF",
        "channel": {
          "type": "kapuaDataChannel",
          "semanticParts": ["one", "two", "three"]
        },
        "payload": {
          "type": "kapuaDataPayload",
           "metrics": {
            "metric": [
              {
                "valueType": "string",
                "value": "aaa",
                "name": "metric-1"
              },
              {
                "valueType": "string",
               "value": "bbb",
                "name": "metric-2"
              }
            ]
          },
          "body":["1", "2", "3"]
        }
      }
![image](https://user-images.githubusercontent.com/28722594/30153302-ba05aaa8-93e8-11e7-98e4-bdc921bbd891.png)

**Comment by Coduz** [comment]
Hi,

`body` in `payload` MUST be encoded in base64.

Regards, 

_Alberto_

**Comment by zhouyue123** [comment]
could you please a template about body

**Comment by zhouyue123** [comment]
could you  please give me a  template about body

**Comment by Coduz** [comment]
I can give you an example of how it should be like:
```
"body": "Ym9keQ0K"
```

The `Ym9keQ0K` string is a base64 encoding of the characters `body`, which I used to give you and example.

**Comment by zhouyue123** [comment]
Is that so?
![image](https://user-images.githubusercontent.com/28722594/30206966-73385476-94c0-11e7-9c60-4daed794a5c1.png)
There are some mistakes here
![image](https://user-images.githubusercontent.com/28722594/30207235-6327a6a8-94c1-11e7-8579-804d43d9bd34.png)
![image](https://user-images.githubusercontent.com/28722594/30207243-6ba756fc-94c1-11e7-8998-8259312c4ce0.png)

**Comment by lorthirk** [comment]
Hi @zhouyue123, I just tried your payload and it worked. Are you testing this against the latest `develop` branch? Did you change any code?

**Comment by zhouyue123** [comment]
hi , No code change，Can you send me a full template with body?

**Comment by lorthirk** [comment]
Sure, here it is:

```
{
  "type": "kapuaDataMessage",
  "position": {
    "type": "kapuaPosition",
    "latitude": 5.0,
    "longitude": 5.0
  },
  "clientId": "AA:BB:CC:DD:EE:FF",
  "channel": {
    "type": "kapuaDataChannel",
    "semanticParts": [
      "one",
      "two",
      "three"
    ]
  },
  "payload": {
    "type": "kapuaDataPayload",
    "body": [
      "VGVzdCBCb2R5IERhdGE="
    ],
    "metrics": {
      "metric": [
        {
          "valueType": "string",
          "value": "aaa",
          "name": "metric-1"
        },
        {
          "valueType": "string",
          "value": "bbb",
          "name": "metric-2"
        }
      ]
    }
  }
}
```
Anyway, you could think about inspecting the REST API logs (`docker logs kapua-api`) to get a detailed error message.
