### ISSUE TITLE
Data - Results Table sort in console clears the data

### ISSUE THREAD

**Issue by muros-ct** [eclipse/kapua#809]
In console app sorting on Timestamp and Device column clears the result data and no results are returned.

**Steps to reproduce**
_Data must be available on topic_

1. Select **Data** in main menu on the left
2. Select **By Topic** tab
3. Select **topic** and **metric** in that topic
4. Select **Query** button
5. Data is displayed in **Results Table**

![beforesort](https://user-images.githubusercontent.com/23033235/30329930-1473f014-97d4-11e7-8722-5ae0260cfd7b.png)

6. Click on **Timestamp** column to reorder data in oposite order of current. Data disappears. Same for Device column. It works for other columns.

![aftersort](https://user-images.githubusercontent.com/23033235/30330042-3fdfc804-97d4-11e7-9214-ff7564e3f977.png)

**Comment by lorthirk** [comment]
Yes, I can confirm this happens to me as well. Unfortunately, due to #553, I still can't debug the view trying to understand what happens. I'll see if I manage to fix #553 first, otherwise I'll try to figure this out without debugging.
