### ISSUE TITLE
Build - Cucumber reports are no more recheable from Kapua Hudson build page 

### ISSUE THREAD

**Issue by stefanomorson** [eclipse/kapua#818]
The cucumber report have been moved to:

dev-tools/cucumber-reports/target/kapua-cucumber-report/

1-Change configurations in Hudson Build  for develop and for releases if need
2-Cherry pick the PR #817 into the release-0.3.x branch.

**Comment by stefanomorson** [comment]
Action: Tentatively changed the configuration for develop Kapua Build in Hudson account.

To be done: report the change to release builds if needed.

**Comment by Coduz** [comment]
#817 has been cherry-picked into the release branch `release-0.3.x`
