### ISSUE TITLE
accounts_query

### ISSUE THREAD

**Issue by zhouyue123** [eclipse/kapua#832]
about accouts  , POST    /{scopeId}/accounts/_query ,could you please  give me a  template  .

**Comment by Coduz** [comment]
Examples are available trough the Swagger UI integration that we have bundled with the REST API application. 
Currently filtering with that REST API resource is limited.

**Comment by zhouyue123** [comment]
like  ‘Gets the Account list in the scope’?   Can I write other functions?

**Comment by lorthirk** [comment]
For such a query you would just use `GET /accounts` specifying the desired scopeId in the URL instead of the wildcard `_`

**Comment by zhouyue123** [comment]
"sortCriteria": {},
  "fetchAttributes": [
    "string"
  ],
  "predicate": {},                              how to input  parameter

**Comment by Coduz** [comment]
Hi @zhouyue123 ,

I'll close this issue since it is quite old. 
Feel free to reopen if you need more help on this.

Regards, 

_Alberto_
