### ISSUE TITLE
Liquibase sql script file--Will the format be unified?

### ISSUE THREAD

**Issue by miricy** [eclipse/kapua#833]
The new files is sql, what's the plan.
We will converted SQL file to XML Liquibase files on new version 0.3.x?

./service/liquibase/src/test/resources/liquibase/liquibase.sql
./service/liquibase/target/test-classes/liquibase/liquibase.sql
./service/device/packages/job/src/main/resources/liquibase/0.3.0/package_uninstall_job_step_definition.sql
./service/device/packages/job/src/main/resources/liquibase/0.3.0/package_download_job_step_definition.sql
./service/device/packages/job/target/classes/liquibase/0.3.0/package_uninstall_job_step_definition.sql
./service/device/packages/job/target/classes/liquibase/0.3.0/package_download_job_step_definition.sql
./service/device/configuration/job/src/main/resources/liquibase/0.3.0/configuration_put_job_step_definition.sql
./service/device/configuration/job/target/classes/liquibase/0.3.0/configuration_put_job_step_definition.sql
./service/device/asset/job/src/main/resources/liquibase/0.3.0/asset_write_job_step_definition.sql
./service/device/asset/job/target/classes/liquibase/0.3.0/asset_write_job_step_definition.sql
./service/device/bundle/job/src/main/resources/liquibase/0.3.0/bundle_start_job_step_definition.sql
./service/device/bundle/job/src/main/resources/liquibase/0.3.0/bundle_stop_job_step_definition.sql
./service/device/bundle/job/target/classes/liquibase/0.3.0/bundle_start_job_step_definition.sql
./service/device/bundle/job/target/classes/liquibase/0.3.0/bundle_stop_job_step_definition.sql
./service/device/command/job/src/main/resources/liquibase/0.3.0/command_job_step_definition.sql
./service/device/command/job/target/classes/liquibase/0.3.0/command_job_step_definition.sql

**Comment by lorthirk** [comment]
Yes, they will be ported to Liquibase XML in the near future.

**Comment by Coduz** [comment]
Here is a table with info for each file

| File Name | Action |
|-----------|--------|
| ./service/liquibase/src/test/resources/liquibase/liquibase.sql | Test file taht will be not converted. |
| ./service/liquibase/target/test-classes/liquibase/liquibase.sql | Build generated file. No action.|
| ./service/device/packages/job/src/main/resources/liquibase/0.3.0/package_uninstall_job_step_definition.sql | It will be converted |
| ./service/device/packages/job/src/main/resources/liquibase/0.3.0/package_download_job_step_definition.sql | It will be converted |
| ./service/device/packages/job/target/classes/liquibase/0.3.0/package_uninstall_job_step_definition.sql | It will be converted |
| ./service/device/packages/job/target/classes/liquibase/0.3.0/package_download_job_step_definition.sql | It will be converted |
| ./service/device/configuration/job/src/main/resources/liquibase/0.3.0/configuration_put_job_step_definition.sql | It will be converted |
| ./service/device/configuration/job/target/classes/liquibase/0.3.0/configuration_put_job_step_definition.sql | It will be converted |
| ./service/device/asset/job/src/main/resources/liquibase/0.3.0/asset_write_job_step_definition.sql | It will be converted |
| ./service/device/asset/job/target/classes/liquibase/0.3.0/asset_write_job_step_definition.sql | It will be converted |
| ./service/device/bundle/job/src/main/resources/liquibase/0.3.0/bundle_start_job_step_definition.sql | It will be converted |
| ./service/device/bundle/job/src/main/resources/liquibase/0.3.0/bundle_stop_job_step_definition.sql | It will be converted |
| ./service/device/bundle/job/target/classes/liquibase/0.3.0/bundle_start_job_step_definition.sql | It will be converted |
| ./service/device/bundle/job/target/classes/liquibase/0.3.0/bundle_stop_job_step_definition.sql | It will be converted |
| ./service/device/command/job/src/main/resources/liquibase/0.3.0/command_job_step_definition.sql | It will be converted |
| ./service/device/command/job/target/classes/liquibase/0.3.0/command_job_step_definition.sql | It will be converted |
