### ISSUE TITLE
Mysql JobPersistenceException----Failed to obtain DB connection from data source 'quartzDataSource'

### ISSUE THREAD

**Issue by miricy** [eclipse/kapua#838]
### When run a admin.war, the log has a error.

The admin console can login, can get mysql connection. 
Version is the last release0.3.x

src/main/java/org/eclipse/kapua/service/scheduler/trigger/quartz/persistence/KapuaQuartzConnectionProvider.java

8:04:29.670 [QuartzScheduler_KapuaQuartzScheduler-ubuntu1506591809648_MisfireHandler] DEBUG org.quartz.impl.jdbcjobstore.JobStoreTX - MisfireHandler: scanning for misfires...
18:04:42.543 [QuartzScheduler_KapuaQuartzScheduler-ubuntu1506589962518_MisfireHandler] DEBUG org.quartz.impl.jdbcjobstore.JobStoreTX - MisfireHandler: scanning for misfires...
18:04:42.544 [QuartzScheduler_KapuaQuartzScheduler-ubuntu1506589962518_MisfireHandler] ERROR org.quartz.impl.jdbcjobstore.JobStoreTX - MisfireHandler: Error handling misfires: Failed to obtain DB connection from data source 'quartzDataSource': java.sql.SQLException: No suitable driver found for jdbc:mysql://localhost:3306/kapuadb?useTimezone=true&useLegacyDatetimeCode=false&serverTimezone=UTC&characterEncoding=UTF-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
org.quartz.JobPersistenceException: Failed to obtain DB connection from data source 'quartzDataSource': java.sql.SQLException: No suitable driver found for jdbc:mysql://localhost:3306/kapuadb?useTimezone=true&useLegacyDatetimeCode=false&serverTimezone=UTC&characterEncoding=UTF-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.getConnection(JobStoreSupport.java:778)
	at org.quartz.impl.jdbcjobstore.JobStoreTX.getNonManagedTXConnection(JobStoreTX.java:71)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3185)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.manage(JobStoreSupport.java:3951)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.run(JobStoreSupport.java:3972)

**Comment by lorthirk** [comment]
Looking at the log:

`java.sql.SQLException: No suitable driver found for jdbc:mysql://localhost:3306/kapuadb?useTimezone=true&useLegacyDatetimeCode=false&serverTimezone=UTC&characterEncoding=UTF-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull`

It looks like the MySQL connector is not in the classpath of the Admin Console.

**Comment by Coduz** [comment]
It sounds strange to me because it should use the `JdbcConnectionUrlResolvers.resolveJdbcUrl();` to retrieve correct info and it is the same class that is used by the other services. 

I'm assuming that there is a problem on the _.war_ configuration...
How old is your `release-0.3.x` branch in your fork? 
Can you please try to pull latest changes and rebuild the whole Kapua? Remember to use `-Pconsole` because otherwise the console resources do not get built.

**Comment by miricy** [comment]
### I merge the release-0.3.x time: Thu Sep 28 16:17:52 2017 +0800
### This is my git log:
dev@ubuntu:/work/dev/kapua/kapua$ git log
commit e58b31cd088de2fe320004fa188b43ca721c6e71
Merge: e22dcbdcc eb5b8bd0b
Author: miricy <miricy@gmail.com>
Date:   Thu Sep 28 16:17:52 2017 +0800

    delete all liquibase sql,change to xml script

commit eb5b8bd0b0e702b747cdb2ab80a66d67cceaedaa
Merge: 96ebfb176 8a34d505d
Author: miricy <miricy@gmail.com>
Date:   Thu Sep 28 16:14:36 2017 +0800

    Merge branch 'release-0.3.x' of https://github.com/eclipse/kapua into release-0.3.x

commit e22dcbdcc13d87ff939a696daf3dde71d90bfd16
Merge: 6ec2c3c36 96ebfb176
Author: miricy <miricy@gmail.com>
Date:   Thu Sep 28 16:14:12 2017 +0800

    merge to release-0.3.x

commit 8a34d505d886513a43aa8f0e617fd6b608923e6d
Author: Claudio Mezzasalma <claudio.mezzasalma@eurotech.com>
Date:   Wed Sep 27 10:58:08 2017 +0200

    Child Accounts filter heading fixed
    
    Signed-off-by: Claudio Mezzasalma <claudio.mezzasalma@eurotech.com>

commit 73ef6589aa34e2b729fe8b110ee43ae6b851ce28
Author: Claudio Mezzasalma <claudio.mezzasalma@eurotech.com>
Date:   Wed Sep 27 10:39:30 2017 +0200

    Child accounts tabs fixed
    
    Signed-off-by: Claudio Mezzasalma <claudio.mezzasalma@eurotech.com>

commit bb2c5faaeaca089fb1d494a205605dd75f78235d
Author: Claudio Mezzasalma <claudio.mezzasalma@eurotech.com>
Date:   Tue Sep 26 12:36:27 2017 +0200

    Job SQL scripts migrated to Liquibase XML
    
    Signed-off-by: Claudio Mezzasalma <claudio.mezzasalma@eurotech.com>

**Comment by miricy** [comment]
Seems to need to add code(add jdbc driver) ：Class.forName("com.mysql.jdbc.Driver"); 
on this file:
src/main/java/org/eclipse/kapua/service/scheduler/trigger/quartz/persistence/KapuaQuartzConnectionProvider.java

Where is the jdbc driver loader, I can't find it.

**Comment by miricy** [comment]
Thank you very much.

 I use -Pconsole to compile the console, It's ok.
But there's another mistake ，Please help see。

'kapuadb1.SCHDL_QRTZ_LOCKS' doesn't exist
org.quartz.impl.jdbcjobstore.LockException: Failure obtaining db row lock: Table 'kapuadb1.SCHDL_QRTZ_LOCKS' doesn't exist
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:157)
	at org.quartz.impl.jdbcjobstore.DBSemaphore.obtainLock(DBSemaphore.java:113)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doCheckin(JobStoreSupport.java:3274)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.manage(JobStoreSupport.java:3874)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.run(JobStoreSupport.java:3911)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'kapuadb1.SCHDL_QRTZ_LOCKS' doesn't exist
	at sun.reflect.GeneratedConstructorAccessor59.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2490)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1966)
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:96)
	... 4 common frames omitted
12:34:51.144 [QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager] DEBUG org.quartz.impl.jdbcjobstore.StdRowLockSemaphore - Lock 'STATE_ACCESS' is desired by: QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager
12:34:51.144 [QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager] DEBUG org.quartz.impl.jdbcjobstore.StdRowLockSemaphore - Lock 'STATE_ACCESS' is being obtained: QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager
12:34:51.174 [QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager] DEBUG org.quartz.impl.jdbcjobstore.StdRowLockSemaphore - Lock 'STATE_ACCESS' was not obtained by: QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager - will try again.
12:34:52.174 [QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager] DEBUG org.quartz.impl.jdbcjobstore.StdRowLockSemaphore - Lock 'STATE_ACCESS' is being obtained: QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager
12:34:52.204 [QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager] DEBUG org.quartz.impl.jdbcjobstore.StdRowLockSemaphore - Lock 'STATE_ACCESS' was not obtained by: QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager - will try again.
12:34:53.204 [QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager] DEBUG org.quartz.impl.jdbcjobstore.StdRowLockSemaphore - Lock 'STATE_ACCESS' is being obtained: QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager
12:34:53.235 [QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager] DEBUG org.quartz.impl.jdbcjobstore.StdRowLockSemaphore - Lock 'STATE_ACCESS' was not obtained by: QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager
12:35:08.555 [QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager] DEBUG org.quartz.impl.jdbcjobstore.StdRowLockSemaphore - Lock 'STATE_ACCESS' is desired by: QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager
12:35:08.555 [QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager] DEBUG org.quartz.impl.jdbcjobstore.StdRowLockSemaphore - Lock 'STATE_ACCESS' is being obtained: QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager
12:35:08.587 [QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager] DEBUG org.quartz.impl.jdbcjobstore.StdRowLockSemaphore - Lock 'STATE_ACCESS' was not obtained by: QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager - will try again.
12:35:09.587 [QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager] DEBUG org.quartz.impl.jdbcjobstore.StdRowLockSemaphore - Lock 'STATE_ACCESS' is being obtained: QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager
12:35:09.620 [QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager] DEBUG org.quartz.impl.jdbcjobstore.StdRowLockSemaphore - Lock 'STATE_ACCESS' was not obtained by: QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager - will try again.
12:35:10.620 [QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager] DEBUG org.quartz.impl.jdbcjobstore.StdRowLockSemaphore - Lock 'STATE_ACCESS' is being obtained: QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager
12:35:10.653 [QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager] DEBUG org.quartz.impl.jdbcjobstore.StdRowLockSemaphore - Lock 'STATE_ACCESS' was not obtained by: QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager
12:35:13.547 [QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_MisfireHandler] DEBUG org.quartz.impl.jdbcjobstore.JobStoreTX - MisfireHandler: scanning for misfires...
12:35:25.956 [QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager] DEBUG org.quartz.impl.jdbcjobstore.StdRowLockSemaphore - Lock 'STATE_ACCESS' is desired by: QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager
12:35:25.956 [QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager] DEBUG org.quartz.impl.jdbcjobstore.StdRowLockSemaphore - Lock 'STATE_ACCESS' is being obtained: QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager
12:35:25.986 [QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager] DEBUG org.quartz.impl.jdbcjobstore.StdRowLockSemaphore - Lock 'STATE_ACCESS' was not obtained by: QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager - will try again.
12:35:26.987 [QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager] DEBUG org.quartz.impl.jdbcjobstore.StdRowLockSemaphore - Lock 'STATE_ACCESS' is being obtained: QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager
12:35:27.017 [QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager] DEBUG org.quartz.impl.jdbcjobstore.StdRowLockSemaphore - Lock 'STATE_ACCESS' was not obtained by: QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager - will try again.
12:35:28.017 [QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager] DEBUG org.quartz.impl.jdbcjobstore.StdRowLockSemaphore - Lock 'STATE_ACCESS' is being obtained: QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager
12:35:28.047 [QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager] DEBUG org.quartz.impl.jdbcjobstore.StdRowLockSemaphore - Lock 'STATE_ACCESS' was not obtained by: QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager
12:35:43.340 [QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager] DEBUG org.quartz.impl.jdbcjobstore.StdRowLockSemaphore - Lock 'STATE_ACCESS' is desired by: QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager
12:35:43.340 [QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager] DEBUG org.quartz.impl.jdbcjobstore.StdRowLockSemaphore - Lock 'STATE_ACCESS' is being obtained: QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager
12:35:43.370 [QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager] DEBUG org.quartz.impl.jdbcjobstore.StdRowLockSemaphore - Lock 'STATE_ACCESS' was not obtained by: QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager - will try again.
12:35:44.370 [QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager] DEBUG org.quartz.impl.jdbcjobstore.StdRowLockSemaphore - Lock 'STATE_ACCESS' is being obtained: QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager
12:35:44.399 [QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager] DEBUG org.quartz.impl.jdbcjobstore.StdRowLockSemaphore - Lock 'STATE_ACCESS' was not obtained by: QuartzScheduler_KapuaQuartzScheduler-ubuntu1506648373515_ClusterManager - will try again.
