### ISSUE TITLE
kapua-client-gateway-features module pom configuration error

### ISSUE THREAD

**Issue by Coduz** [eclipse/kapua#839]
Hi @ctron ,

I was working with the `release-0.3.x` release procedure and I've encountered a problem.

When running `mvn release:prepare` there is an error in `kapua-client-gateway-features` module not being able to fetch some dependencies.

> [INFO] [INFO] ------------------------------------------------------------------------
> [INFO] [INFO] BUILD FAILURE
> [INFO] [INFO] ------------------------------------------------------------------------
> [INFO] [INFO] Total time: 01:11 min
> [INFO] [INFO] Finished at: 2017-10-02T12:44:22+02:00
> [INFO] [INFO] Final Memory: 166M/915M
> [INFO] [INFO] ------------------------------------------------------------------------
> [INFO] [ERROR] Failed to execute goal org.apache.karaf.tooling:karaf-maven-plugin:4.1.1:verify (verify) on project kapua-client-gateway-feature-karaf: Verification failures -> [Help 1]
> [INFO] [ERROR] 
> [INFO] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [INFO] [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [INFO] [ERROR] 
> [INFO] [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [INFO] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
> [INFO] [ERROR] 
> [INFO] [ERROR] After correcting the problems, you can resume the build with the command
> [INFO] [ERROR]   mvn <goals> -rf :kapua-client-gateway-feature-karaf

With error message:

> [INFO] [WARNING] Error resolving artifact org.eclipse.kapua:kapua-client-gateway-provider-paho:jar:0.3.0: [Could not find artifact org.eclipse.kapua:kapua-client-gateway-provider-paho:jar:0.3.0 in central (https://repo.maven.apache.org/maven2/)]
> [INFO] java.io.IOException: Error resolving artifact org.eclipse.kapua:kapua-client-gateway-provider-paho:jar:0.3.0: [Could not find artifact org.eclipse.kapua:kapua-client-gateway-provider-paho:jar:0.3.0 in central (https://repo.maven.apache.org/maven2/)]

This is reproducible by running: `mvn release:clean release:prepare -Darguments="-DskipTests" --batch-mode` in `release-0.3.x` or `develop` branches.

Looking at the configuration of the `kapua-client-gateway-features` pom file there is the `karaf-maven-plugin` configured referring two other kapua modules in verify phase.
This is a problem because at `verify` phase the other two modules are not installed and therefore causing an error while running `mvn release:prepare`. 

Since I'm not familiar with these modules on Kapua, can you please look at this error? Or give me some information/hint on which would be the best solution to solve the error? 

Thanks,

_Alberto_

**Comment by ctron** [comment]
I think the solution for that was to add "install" to the preparation goal, like this: https://github.com/ctron/kapua-gateway-client/blob/master/pom.xml#L286

**Comment by Coduz** [comment]
No longer an issue
