### ISSUE TITLE
Cannot change "tagService" fields in Child Account Settings

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#840]
Running Kapua locally with docker (release-0.3.x), as described in Kapua Quick Start Guide. 
When trying to change fields "InfiniteChildTags" and "maxNumberChildTags" under Child Accounts -> Account Name -> Settings UI shows that it is "Applying Configuration" but nothing happens. Neither field can be changed, UI does not report any error.

**Comment by lorthirk** [comment]
Uhm, it seems it's working for me. Could you please investigate a bit further?

**Comment by LeoNerdoG** [comment]
Hi @lorthirk ,
testFlow is as follows and bellow is also a screenshot of the problem: 

1) Log in as kapua-sys
2) Go to Child Accounts and create new child account (e.g. kapua-test123)
3) Select newly created account (kapua-test123) and go to its Settings tab
4) Click on TagService and try to : 
     - set infiniteChildTags to true
     - set maxNumberChildTags to value > 0 .

**In both cases I get response as shown bellow.**

<img width="1440" alt="screen shot 2017-10-18 at 07 48 29" src="https://user-images.githubusercontent.com/15121999/31702939-5cf9064a-b3da-11e7-8292-165c2dee7cbc.png">

Kapua does not "freeze", when you click something else and then go back, settings are not changed.
