### ISSUE TITLE
Unable to add Permissions to new User

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#841]
Following the procedure below I get an **Error retrieving domains: Subject does not have permission [domain:read:-1:*]**
1) Log into Kapua-sys
2) Create new child account (e.g. child-accunt1)
3) Add user to child-account1 (e.g. user1)
4) Logout from kapua-sys and login as user1
4) Go to "Users" tab and add new user (e.g. user2), set it as admin
5) Try to add permissions (here the error pops up)

<img width="1440" alt="screen shot 2017-10-04 at 14 50 26" src="https://user-images.githubusercontent.com/15121999/31176423-1197dec8-a913-11e7-9782-cfd2be59b275.png">

**Comment by lorthirk** [comment]
There was a bug preventing new permissions to be granted to a user, that should be fixed in 93de4d7c41e42df50912ed9b208035757165c2d1. Could you pull `develop` again and see if it still occurs?

**Comment by LeoNerdoG** [comment]
Hi @lorthirk ,
the error still persists, there are no changes.

**Comment by lorthirk** [comment]
Hey @LeoNerdoG,

is this fixed? I see that the error still persists, and then it's closed. Which one of the two? :smile:
