### ISSUE TITLE
Access denied to: https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/kapua/build/kapua-build-tools/0.3.0-SNAPSHOT/kapua-build-tools-0.3.0-20171005.121434-1.jar, ReasonPhrase: Forbidden.

### ISSUE THREAD

**Issue by RaghAkella** [eclipse/kapua#844]
Hi,

I have followed the steps given in below link "https://github.com/eclipse/kapua/blob/develop/assembly/README.md" and kapua build was successful but when I try to run **"mvn -Pdocker deploy"** Its giving an error **unauthorized** then I have created a seetings.xml file and run the command **"mvn -Pdocker deploy --settings path of the file"** and got below error. I verified <id>ossrh</id> in settings.xml and pom.xml inside <distributionManagement> id is also same.  Earlier when i try to do build and deploy it was working fine for me and it was not asking authentication to sonatype.org

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project kapua-build-tools: Failed to deploy artifacts: Could not transfer artifact org.eclipse.kapua.build:kapua-build-tools:jar:0.3.0-20171005.121434-1 from/to ossrh (https://oss.sonatype.org/content/repositories/snapshots): Access denied to: https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/kapua/build/kapua-build-tools/0.3.0-SNAPSHOT/kapua-build-tools-0.3.0-20171005.121434-1.jar, ReasonPhrase: Forbidden. ->

**settings.xml**
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                      https://maven.apache.org/xsd/settings-1.0.0.xsd">
<servers>
   <server>
      
 </server>
</servers>
</settings>

1. Do the user need any extra permissions If so how could I get those permissions. 

Please help me.

Thanks,
Raghav

**Comment by RaghAkella** [comment]
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                      https://maven.apache.org/xsd/settings-1.0.0.xsd">
<servers>
   <server>
      

   </server>
</servers>
</settings>

**Comment by RaghAkella** [comment]
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                      https://maven.apache.org/xsd/settings-1.0.0.xsd">
<servers>
   <server>
      <!--id>ossrh</id>
      <username>validuser</username>
      

> 

> `<password>pwd</password-->`

	
   </server>
</servers>
</settings>

**Comment by RaghAkella** [comment]
A new user has been created in sonatype.org and given the same credentials in settings.xml file

**Comment by Coduz** [comment]
You cannot push docker to our docker repository. 

You can create them (see https://github.com/eclipse/kapua/blob/develop/assembly/README.md#build) and run them see (https://github.com/eclipse/kapua/blob/develop/assembly/README.md#run).

If you want to publish them somewhere else, you can follow the instructions in [here](https://github.com/eclipse/kapua/blob/develop/assembly/README.md#pushing). It is also explained what to do to choose another repository to push to.

Regards, 

_Alberto_
