### ISSUE TITLE
Cannot Create More Than 3 "vertical" Child Accounts

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#852]
When creating "vertical" child accounts I cannot get to 4th level or "deeper". The accounts are created as stated bellow: 
1) In kapua-sys (infinite child accounts) I create kapua-child1 account (with 4 possible Child Accounts)
2) In kapua-child1 I create kapua-child2 account (with 3 possible Child Accounts)
3) In kapua-child2 I create kapua-child3 account (with 2 possible Child Accounts).
4) When I try to create kapua-child4 in kapua-child3 account I get an error: 

**Error: And internal error occured: Error durring Persistance Operation.** 

**Also if all of the child accounts have InfiniteChildAccounts set to True and MaxNumberChildAccounts is e.g. 10, the problem is the same.** 

Browsers used (although this is not a browser issue):

- Google Chrome (Version 61.0.3163.100 (Official Build) (64-bit))
- Safari (Version 11.0 (12604.1.38.1.7))
- Mozilla Firefox (56.0.1 (64-bit))
- Opera (Version 48.0.2685.39)

**Comment by muros-ct** [comment]
This issue has to do with database field being too smal to hold full path of account ids.
Account ids are pretty long and it will be hard to solve be extending length of database field. Other solution is needed.
