### ISSUE TITLE
An internal error occurred: org.apache.shiro.ShiroException: Error while find user!.

### ISSUE THREAD

**Issue by jpbourke** [eclipse/kapua#853]
Hi,

I am running the docker "get started" containers.

CONTAINER ID IMAGE COMMAND CREATED STATUS 
67dd2637119f kapua/kapua-api "/home/kapua/run-j..." 14 hours ago Up 37 minutes
d8192a881164 kapua/kapua-console "/home/kapua/run-c..." 14 hours ago Up 37 minutes
6bea837dc986 kapua/kapua-broker "/maven/bin/active..." 14 hours ago Up 37 minutes
73c4cb71de34 elasticsearch:5.4.0 "/docker-entrypoin..." 14 hours ago Up 37 minutes
255a0df57c5b kapua/kapua-sql "/home/kapua/run-h2" 15 hours ago Up 38 minutes

When I try to login

http://127.0.0.1:8080/ 
Username: kapua-sys 
Password: kapua-password 

I get a login error

Login Failed. 
An internal error occurred: org.apache.shiro.ShiroException: Error while find user!.

Can anyone help ?

Thanks

john

**Comment by Roopa-Siddaveerappa** [comment]
hi 
Even i am getting same issue...
could anyone help ..?
thanks

**Comment by lorthirk** [comment]
Could you please post the detailed stack trace?

**Comment by jpbourke** [comment]
Hi,

I am not a software developer, I am an end user, sorry  don’t know what a stack trace is.

John Bourke on Mobile


On 13 Oct 2017, at 08:00, Claudio Mezzasalma <notifications@github.com<mailto:notifications@github.com>> wrote:


Could you please post the detailed stack trace?

**Comment by lorthirk** [comment]
Just out of curiosity, could you point me to the instructions you followed?

**Comment by jpbourke** [comment]
Hi,

I followed this.

https://www.eclipse.org/kapua/getting-started.php

I had to increase the memory on docker to stop the eclipse container crashing, but now all containers are running ok.

I can access the swagger API definition.

Thanks


John Bourke on Mobile


On 13 Oct 2017, at 08:27, Claudio Mezzasalma <notifications@github.com<mailto:notifications@github.com>> wrote:


Just out of curiosity, could you point me to the instructions you followed?

**Comment by lorthirk** [comment]
Yes, as I suspected that commands were a bit outdated. We just fixed it; please look for `--env commons.db.schema.update=true` in the last three `docker run` commands to check you're viewing the last version, then remove the containers you already created and run all the five commands again.

**Comment by jpbourke** [comment]
Hello,

So I add --env commons.db.schema.update=true

docker run -td --name kapua-broker --link kapua-sql:db --link kapua-elasticsearch:es -p 1883:1883 -p 61614:61614 kapua/kapua-broker --env commons.db.schema.update=true
docker run -td --name kapua-console --link kapua-sql:db --link kapua-broker:broker --link kapua-elasticsearch:es -p 8080:8080 kapua/kapua-console --env commons.db.schema.update=true
docker run -td --name kapua-api --link kapua-sql:db --link kapua-broker:broker --link kapua-elasticsearch:es -p 8081:8080 kapua/kapua-api --env commons.db.schema.update=true

Thanks

John

**Comment by lorthirk** [comment]
Exactly. Please tell us if this fixes your issue :)

**Comment by jpbourke** [comment]
Hi,

Small issue with broker, it will not start.

INFO: Unrecognized option: --env

John


docker run -td --name kapua-sql -p 8181:8181 -p 3306:3306 kapua/kapua-sql
Unable to find image 'kapua/kapua-sql:latest' locally
latest: Pulling from kapua/kapua-sql
d9aaf4d82f24: Pull complete
fe92d9ed8a65: Pull complete
07d5d00523f2: Pull complete
417190f5bd67: Pull complete
Digest: sha256:986d18aecf7c760526afa47fd78ba1d1b4005cf2a9d3c9026b8ea8c4ac31ec0c
Status: Downloaded newer image for kapua/kapua-sql:latest
193b81b38520775b5175b1e085e2d80c7f2de0f2559dc077e4379bb5700797a0

docker run -td --name kapua-elasticsearch -p 9200:9200 -p 9300:9300 elasticsearch:5.4.0 -Ecluster.name=kapua-datastore -Ediscovery.type=single-node -Etransport.host=_site_ -Etransport.ping_schedule=-1 -Etransport.tcp.connect_timeout=30s
Unable to find image 'elasticsearch:5.4.0' locally
5.4.0: Pulling from library/elasticsearch
10a267c67f42: Pull complete
fb5937da9414: Pull complete
f131c9b3ecc4: Pull complete
f59cc3b26f35: Pull complete
63df868a0518: Pull complete
83282147e192: Pull complete
b9595cab9382: Pull complete
df2d57cc0364: Pull complete
eb968d8ad5ed: Pull complete
17d104994ea4: Pull complete
3fe4649beeb6: Pull complete
a8ce1c2b87a5: Pull complete
425d32b8d20b: Pull complete
89fa7bafc1e2: Pull complete
66bf462fa606: Pull complete
Digest: sha256:b8697c807aa65316714a5074ef039c42e6c4b400a6986c18b9a88ef37636acbc
Status: Downloaded newer image for elasticsearch:5.4.0
f4501f58a463521d1577ff3a075b85996a2acba3b96875fdaadac311bf1ca8ce

docker run -td --name kapua-broker --link kapua-sql:db --link kapua-elasticsearch:es -p 1883:1883 -p 61614:61614 kapua/kapua-broker --env commons.db.schema.update=true
Unable to find image 'kapua/kapua-broker:latest' locally
latest: Pulling from kapua/kapua-broker
d9aaf4d82f24: Already exists
fe92d9ed8a65: Already exists
01f8fb3841f2: Pull complete
0efa49fe185d: Pull complete
Digest: sha256:109b9f8d88416fa268c6cf349f980b85dd15077c3854239c71401ee795570ea0
Status: Downloaded newer image for kapua/kapua-broker:latest
8e5ccd31eadfc24006bfa976a2dce88181ca6c5546cebd685212218794b48715

docker run -td --name kapua-console --link kapua-sql:db --link kapua-broker:broker --link kapua-elasticsearch:es -p 8080:8080 kapua/kapua-console --env commons.db.schema.update=true
Unable to find image 'kapua/kapua-console:latest' locally
latest: Pulling from kapua/kapua-console
d9aaf4d82f24: Already exists
fe92d9ed8a65: Already exists
a34de7578a6a: Pull complete
6d02f08f72cc: Pull complete
64f3f3764d70: Pull complete
625e3222850d: Pull complete
Digest: sha256:ec3af04e29f3f7b6f7b89071fb2dac785ad952660c8626a8924fe3b15311f1f6
Status: Downloaded newer image for kapua/kapua-console:latest
047cdce51c21b56e10334162ab052dbf991f3a2ef22a6680a0e0beff5e9f83f9
docker: Error response from daemon: Cannot link to a non running container: /kapua-broker AS /kapua-console/broker.

docker run -td --name kapua-api --link kapua-sql:db --link kapua-broker:broker --link kapua-elasticsearch:es -p 8081:8080 kapua/kapua-api --env commons.db.schema.update=true
Unable to find image 'kapua/kapua-api:latest' locally
latest: Pulling from kapua/kapua-api
d9aaf4d82f24: Already exists
fe92d9ed8a65: Already exists
a34de7578a6a: Already exists
6d02f08f72cc: Already exists
64f3f3764d70: Already exists
48ed867e1cfb: Pull complete
Digest: sha256:54836a931590cc3e89c6f571f7442b3d30f1e77248b9a61727b54fd0d387081f
Status: Downloaded newer image for kapua/kapua-api:latest
dc723691435a7c3140c16ff66a14d12a0eb65ef0714aa8530b9be9bd26d1b653
docker: Error response from daemon: Cannot link to a non running container: /kapua-broker AS /kapua-api/broker.

docker ps
CONTAINER ID        IMAGE                 COMMAND                  CREATED             STATUS              PORTS                                                      NAMES
f4501f58a463        elasticsearch:5.4.0   "/docker-entrypoin..."   2 minutes ago       Up 2 minutes        0.0.0.0:9200->9200/tcp, 0.0.0.0:9300->9300/tcp             kapua-elasticsearch
193b81b38520        kapua/kapua-sql       "/home/kapua/run-h2"     4 minutes ago       Up 4 minutes        0.0.0.0:3306->3306/tcp, 0.0.0.0:8181->8181/tcp, 8778/tcp   kapua-sql


Broker logs

INFO: Loading '/maven//bin/env'
INFO: Using java '/usr/lib/jvm/jre-openjdk/bin/java'
INFO: Starting in foreground, this is just for debugging purposes (stop process by pressing CTRL+C)
INFO: Creating pidfile /maven//data/activemq.pid
Java Runtime: Oracle Corporation 1.8.0_144 /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.144-0.b01.el7_4.x86_64/jre
  Heap sizes: current=96256k  free=91728k  max=1409024k
    JVM args: -Dcommons.db.connection.host=${DB_PORT_3306_TCP_ADDR} -Dcommons.db.connection.port=${DB_PORT_3306_TCP_PORT} -Ddatastore.elasticsearch.nodes=${ES_PORT_9200_TCP_ADDR} -Ddatastore.elasticsearch.port=${ES_PORT_9200_TCP_PORT} -Ddatastore.client.class=org.eclipse.kapua.service.datastore.client.rest.RestDatastoreClient -Dcom.sun.management.jmxremote -Djava.awt.headless=true -Djava.io.tmpdir=/maven//tmp -Dactivemq.classpath=/maven//conf:/maven//../lib/: -Dactivemq.home=/maven/ -Dactivemq.base=/maven/ -Dactivemq.conf=/maven//conf -Dactivemq.data=/maven//data
Extensions classpath:
  [/maven/lib,/maven/lib/camel,/maven/lib/optional,/maven/lib/web,/maven/lib/extra]
ACTIVEMQ_HOME: /maven
ACTIVEMQ_BASE: /maven
ACTIVEMQ_CONF: /maven/conf
ACTIVEMQ_DATA: /maven/data
INFO: Unrecognized option: --env
Task Usage: Main start [start-options] [uri]
Description: Creates and starts a broker using a configuration file, or a broker URI.
Start Options:
    -D<name>=<value>      Define a system property.
    --version             Display the version information.
    -h,-?,--help          Display the start broker help information.
URI:
    XBean based broker configuration:
        Example: Main xbean:file:activemq.xml
            Loads the xbean configuration file from the current working directory
        Example: Main xbean:activemq.xml
            Loads the xbean configuration file from the classpath
    URI Parameter based broker configuration:
        Example: Main broker:(tcp://localhost:61616, tcp://localhost:5000)?useJmx=true
            Configures the broker with 2 transport connectors and jmx enabled
        Example: Main broker:(tcp://localhost:61616, network:tcp://localhost:5000)?persistent=false
            Configures the broker with 1 transport connector, and 1 network connector and persistence disabled

**Comment by lorthirk** [comment]
`--env commons.db.schema.update=true` must be put before the container name, otherwise it will be passed to the entry point as a parameter, while it is a Docker run parameter instead. Sorry I didn't catch it before in your example.

**Comment by jpbourke** [comment]
Hi,

Works now …..

docker run -td --env commons.db.schema.update=true --name kapua-broker --link kapua-sql:db --link kapua-elasticsearch:es -p 1883:1883 -p 61614:61614 kapua/kapua-broker
docker run -td --env commons.db.schema.update=true --name kapua-console --link kapua-sql:db --link kapua-broker:broker --link kapua-elasticsearch:es -p 8080:8080 kapua/kapua-console
docker run -td --env commons.db.schema.update=true --name kapua-api --link kapua-sql:db --link kapua-broker:broker --link kapua-elasticsearch:es -p 8081:8080 kapua/kapua-api

john

**Comment by lorthirk** [comment]
Great to hear 🙂
Closing.

**Comment by ruin1990** [comment]
It is very useful, thanks a lot! 👍
