### ISSUE TITLE
console resource re-defined the same string

### ISSUE THREAD

**Issue by ruin1990** [eclipse/kapua#859]
console/module/api/src/main/resources/org/eclipse/kapua/app/console/module/api/client/messages/ValidationMessages.properties
line 119: emailRuleActionDescriptionKey=Rule Action to send an Email message.
line 136: emailRuleActionDescriptionKey=Rule Action to send an Email message to IFTTT service.

I think line 136 maybe IFTTT email service.

**Comment by lorthirk** [comment]
Hi @ruin1990,

Good catch! A lot of those strings are not needed anymore; that file surely needs some cleanup, and possibly by spread across the console modules. I'll keep this issue open as a reminder.

**Comment by ruin1990** [comment]
Hi @lorthirk , i'm very appreciate that you reply my issue.
I also found that some *.properties files have so much unuse string resource, but maybe the re-defined string is unique with "emailRuleActionDescriptionKey". 
Because I'm tried to translate those string to Chinese, so i did a GUI tool to find those string, then I only find "emailRuleActionDescriptionKey" .

**Comment by lorthirk** [comment]
Closed by 74a53988e
