### ISSUE TITLE
MessageStore.expirationDate Can be Set to Any Value

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#860]
When setting child account's MessagStore.expirationDate, any character, number or special symbol can be entered without any error (
I suppose that Data storage expiration date should be in so kind of date format (DD.MM.YYYY, DD-MM-YYYY, DD/MM/YYYY, MM-DD-YYYY, ...) and not a random set of characters.

TestFlow: 
1) Log in as kapua-sys
2) Create new child account (e.g. kapua-child1) 
3) go to child account's Settings -> MessageStoreService 
4) Set messageStore.expirationDate

Browsers used:
- Google Chrome (Version 61.0.3163.100 (Official Build) (64-bit))
- Safari (Version 11.0 (12604.1.38.1.7))
- Mozilla Firefox (56.0.1 (64-bit))
- Opera (Version 48.0.2685.39)

**Comment by stefanomorson** [comment]
MessageStore.expirationDate has to be removed and replaced by another parameter:

* MessageStore.dataTimeToLive

which is a non negative integer number that defines the number of days the data is available  to the user before being deleted.

**Comment by LeoNerdoG** [comment]
I have verified that MessageStore.expirationDate has been removed and successfully replaced by MessageStore.dataTimeToLive.
