### ISSUE TITLE
No Version or Build Number in Kapua GUI

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#861]
When testing Kapua GUI (creating or performing test procedures, reporting issues, etc.) it would be good to have a version or build number (or both) somewhere (bottom right corner would be ebst I think), so it can be noted, which version is actually being tested/used. 

This will also be helpful for end users, who will ask questions, because not all will necessarily use the same version/build.

**Comment by ctron** [comment]
There is an about page, I think this could be a good place for it.

**Comment by lorthirk** [comment]
in `feature-version_number` branch I put the version number in the lower right corner of the console. I think it should be fine there.

**Comment by LeoNerdoG** [comment]
@lorthirk I have verified that branch `feature-version_number` successfully resolved this issue. It can be merged when ready.

**Comment by lorthirk** [comment]
Merged in develop with a8f38e05f08a01fbb4b9e0d87fef93353aa16158 and 9c61af102ea7487caeaec5a3c66c71ee9184e217

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
