### ISSUE TITLE
metricsIndexBy Can be Set to Any Value

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#864]
When setting child account's metricsIndexBy, any character, number or special symbol can be entered without any error, although the description says: Metric index by (timestamp, value or none).

TestFlow:
1) Log in as kapua-sys
2) Create new child account (e.g. kapua-child1)
3 )Go to child account's Settings -> MessageStoreService
4) Set metricsIndexBy to any desired value (e.g. randomVal123$%&)
**Kapua does not return any error.**

Only when we log in as user1 (created from kapua-child1 account), connect a device to it and start sending data, we get the following error (text in error box is not showed completely - see image bellow):
**_An internal error occurred: No enum constant org.eclipse.kapua.service.datastore.internal.model.MetricsIndexBy.randomVal123$%&_**

<img width="1440" alt="screen shot 2017-10-13 at 13 09 28" src="https://user-images.githubusercontent.com/15121999/31544054-5ddd7cc2-b019-11e7-9ebd-bcc4717954dd.png">

Browsers used:
- Google Chrome (Version 61.0.3163.100 (Official Build) (64-bit))
- Safari (Version 11.0 (12604.1.38.1.7))
- Mozilla Firefox (56.0.1 (64-bit))
- Opera (Version 48.0.2685.39)

**Comment by stefanomorson** [comment]
metricsIndexBy should be removed from settings

**Comment by LeoNerdoG** [comment]
I have verified that metricsIndexBy has been removed from settings so this issue is resolved.
