### ISSUE TITLE
Pages in Groups do not work

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#870]
When creating Groups, if total number exceeds one page, we cannot go to next page (next page, last page, previous page and first page buttons are not working). 

TestFlow: 
1) Log in as kapua-sys
2) Go to Groups, create 100+ groups
3) Try to switch to page 2, last page, back or first page. 
**When trying to change pages, GUI flashes, but Kapua does nothing.** 

![screen shot 2017-10-16 at 13 23 16](https://user-images.githubusercontent.com/15121999/31609613-331f7f5e-b275-11e7-933d-62d044eb28e2.png)

Browsers used:
- Google Chrome (Version 61.0.3163.100 (Official Build) (64-bit))
- Safari (Version 11.0 (12604.1.38.1.7))
- Mozilla Firefox (56.0.1 (64-bit))
- Opera (Version 48.0.2685.39)

**Comment by ct-goranpalibrk** [comment]
I started working on this.

**Comment by LeoNerdoG** [comment]
I am verifying that this issue is resolved via PR #956 .
