### ISSUE TITLE
Service events (docker) - ActiveMQ is unable to connect to Artemis service broker

### ISSUE THREAD

**Issue by riccardomodanese** [eclipse/kapua#874]
I created a pr for the service events ( #873 )

The ActiveMQ broker container seems to be unable to connect to the Artemis broker service instance (or at least to the failover broker url).
The log shows lines like this:
"[FailoverProvider: connect thread] INFO  o.a.q.j.p.failover.FailoverProvider - Connection attempt:[NN] to: amqp://events-broker:5672 failed"

**Comment by dejanb** [comment]
@riccardomodanese I just tried feature-serviceEventsRebased branch and when started Kapua in docker environment components connect properly to the events broker

```
11:57:48.483 [main] INFO  o.e.k.commons.core.KapuaApplication - Starting up...
11:57:48.483 [main] INFO  o.e.k.commons.core.KapuaApplication - Startup Kapua Eventbus...
11:57:53.200 [AmqpProvider :(1):[amqp://events-broker:5672]] INFO  o.a.q.jms.sasl.SaslMechanismFinder - Best match for SASL auth was: SASL-PLAIN
11:57:53.960 [FailoverProvider: serialization thread] INFO  org.apache.qpid.jms.JmsConnection - Connection ID:1ee3a4a4-f8db-46a3-97cd-0a66cce5115b:1 connected to remote Broker: amqp://events-broker:5672

```
I see problems with connecting to the database, so housekeeper job doesn't work and I can't login to the console, but that's another issue.

Can you send more details on what environment were you using?

**Comment by riccardomodanese** [comment]
Hi Dejan,

I just tried again after a new full build of the workspace and I still have the same issue.
I’m using plain docker. I double checked the containers and Artemis is running fine.
Maybe i'm using wrong docker commands

These are mine docker commands:
docker run -td --name kapua-sql -p 8181:8181 -p 3306:3306 kapua/kapua-sql
docker run -td --name kapua-elasticsearch -p 9200:9200 -p 9300:9300 elasticsearch:5.4.0 -Ecluster.name=kapua-datastore -Ediscovery.type=single-node -Etransport.host=_site_ -Etransport.ping_schedule=-1 -Etransport.tcp.connect_timeout=30s
docker run -td --name kapua-broker-service -p 5672:5672 enmasseproject/activemq-artemis:2.2.0-1
docker run -td --name kapua-broker --link kapua-sql:db --link kapua-elasticsearch:es --link kapua-broker-service:service -p 1883:1883 -p 61614:61614 kapua/kapua-broker
docker run -td --name kapua-console --link kapua-sql:db --link kapua-broker:broker --link kapua-elasticsearch:es --link kapua-broker-service:service -p 8080:8080 kapua/kapua-console
docker run -td --name kapua-api --link kapua-sql:db --link kapua-broker:broker --link kapua-elasticsearch:es --link kapua-broker-service:service -p 8081:8080 kapua/kapua-api


P.S. I wasn’t able to build Kapua in the service events branch since maven was complaining about the path of the projects. The assembly broker is under assembly directory but the parent project was Kapua. I switched parent project to kapua-assembly and it built Kapua.
I’m going to push this fix.

Il giorno 27 ott 2017, alle ore 14:10, Dejan Bosanac <notifications@github.com<mailto:notifications@github.com>> ha scritto:


@riccardomodanese<https://github.com/riccardomodanese> I just tried feature-serviceEventsRebased branch and when started Kapua in docker environment components connect properly to the events broker

11:57:48.483 [main] INFO  o.e.k.commons.core.KapuaApplication - Starting up...
11:57:48.483 [main] INFO  o.e.k.commons.core.KapuaApplication - Startup Kapua Eventbus...
11:57:53.200 [AmqpProvider :(1):[amqp://events-broker:5672]] INFO  o.a.q.jms.sasl.SaslMechanismFinder - Best match for SASL auth was: SASL-PLAIN
11:57:53.960 [FailoverProvider: serialization thread] INFO  org.apache.qpid.jms.JmsConnection - Connection ID:1ee3a4a4-f8db-46a3-97cd-0a66cce5115b:1 connected to remote Broker: amqp://events-broker:5672



I see problems with connecting to the database, so housekeeper job doesn't work and I can't login to the console, but that's another issue.

Can you send more details on what environment were you using?

**Comment by dejanb** [comment]
@riccardomodanese 

We now need to start docker containers using Docker compose, as we use default Artemis image and configure it using secrets.

Take a look at the new guide

https://github.com/eclipse/kapua/blob/feature-serviceEventsRebased/docs/developer-guide/en/running.md

You can also find more resources (configuration and scripts) here

https://github.com/eclipse/kapua/tree/feature-serviceEventsRebased/dev-tools/src/main/docker

Let me know if this works for you

**Comment by riccardomodanese** [comment]
I followed the instructions and, as you said, the console has some problem with the H2 database (failed to create quartz tables).

I don’t see ElasticSearch container and then the broker fails to connect to it.



Il giorno 30 ott 2017, alle ore 11:12, Dejan Bosanac <notifications@github.com<mailto:notifications@github.com>> ha scritto:

https://github.com/eclipse/kapua/blob/feature-serviceEventsRebased/docs/developer-guide/en/running.md

**Comment by riccardomodanese** [comment]
Hi Dejan, I added a commit to allow the JMSEventBus to reconnect to the service broker if the connection fails.

After that I rebased the branch so please delete your local copy before working on it.



Il giorno 30 ott 2017, alle ore 11:37, Modanese, Riccardo <Riccardo.Modanese@eurotech.com<mailto:Riccardo.Modanese@eurotech.com>> ha scritto:

I followed the instructions and, as you said, the console has some problem with the H2 database (failed to create quartz tables).

I don’t see ElasticSearch container and then the broker fails to connect to it.



Il giorno 30 ott 2017, alle ore 11:12, Dejan Bosanac <notifications@github.com<mailto:notifications@github.com>> ha scritto:

https://github.com/eclipse/kapua/blob/feature-serviceEventsRebased/docs/developer-guide/en/running.md

**Comment by dejanb** [comment]
Thanks Riccardo, I'll give it a test these days.

**Comment by riccardomodanese** [comment]
Thank you!

please delete your local branch since I rebased the branch few times!



Il giorno 21 nov 2017, alle ore 13:26, Dejan Bosanac <notifications@github.com<mailto:notifications@github.com>> ha scritto:


Thanks Riccardo, I'll give it a test these days.

**Comment by stefanomorson** [comment]
@dejanb: I was reviewing the work in the perspective of a first merge. I tried to run dockers following the link:

- https://github.com/eclipse/kapua/blob/feature-serviceEventsRebased/docs/developer-guide/en/running.md

but it doesn't work for me. For example, I get the errors [1]  from the broker and [2] from the console. It looks like the names configured in assembly POMs (e.g. SERVICE_PORT_5672_TCP_ADDR) don't match the names defined in docker-compose.yml. I guess the definitions of the links between containers are also missing. Is this part in progress ?

[1]
```
12:46:59.354 [main] ERROR o.e.k.c.event.ServiceEventBusManager - Error while initializing EventbusProvider
java.lang.IllegalArgumentException: Invalid remote URI: failover:(amqp://${SERVICE_PORT_5672_TCP_ADDR}:${SERVICE_PORT_5672_TCP_PORT})?jms.sendTimeout=1000 
```
[2]
```
Caused by: org.h2.jdbc.JdbcSQLException: General error: "java.lang.NumberFormatException: For input string: ""${DB_PORT_3306_TCP_PORT}""" [50000-192]
```

**Comment by dejanb** [comment]
@stefanomorson this commit 

https://github.com/stefanomorson/kapua/commit/d6704c32898f14491c1c1bf99d482ce42bdbf3dd

hasn't been properly merged. Take a look at the difference of the JAVA_OPTS values in this one pom.xml

https://github.com/eclipse/kapua/blob/0b60c4c3ef45659ada49382c52f7ba869ac5cfdc/assembly/api/pom.xml#L425

vs

https://github.com/stefanomorson/kapua/blob/feature-serviceEvents/assembly/api/pom.xml#L412

That need to be fixed in order for docker compose work properly.

We also need to take a add elasticsearch to the deployment

**Comment by dejanb** [comment]
This is now fixed on feature-serviceEventsRebased branch. I'll add elasticsearch container and do more cleanup next

**Comment by muros-ct** [comment]
One thing that is missing is **-Dcommons.db.schema.update=true**

because if it is not present, database schema doesn't get created.
I added it to broker and console start script and then everything runs.
Except ES but that is yet to be done.

**Comment by muros-ct** [comment]
This change https://github.com/eclipse/kapua/commit/ac146155f79121e89bcac53847c933680770e5ac fixes running of docker-compose based deploy.

I added **ElasticSearch:5.4.0** and changed dockers for **console** and **broker** that now do database creation.

Now docker-compose based deploy runs successfully.
@dejanb can you please check if this is correct way of adding ES.
Creating DB schema is somehow strange, but for basic development and demo deploy this is by my opinion the easiest option.

**Comment by muros-ct** [comment]
This change https://github.com/eclipse/kapua/commit/d20229d2677187c4c1487474ae6db1c3a1831557 based on issue and resolution provided by @alezzandro https://github.com/eclipse/kapua/issues/1207 solves running kapua on OpenShift.

I was able to run full deployment on Mac OS, but haven't tried it on Linux or Windows.

**Comment by dejanb** [comment]
@muros-ct on the first look, we don't have an IP log approved for es 5.4.0. Is it possible to use 5.3.0 in this way? I'll test both docker compose and openshift deployments now.

**Comment by dejanb** [comment]
@stefanomorson @muros-ct  I fixed OpenShift deployment with https://github.com/eclipse/kapua/commit/ce87e8dc07e6f14682302a0820ac8edc7ee9f155.

I fixed a template and split it into multiple templates, so that it will be easier to maintain it in the future. I also added more Minishift documentation

What I noticed though is that events are not triggered. This is not related to the deployment, but to the code. Can you give it a look?

**Comment by muros-ct** [comment]
Is this issue closed?
How is with es 5.4.0?
