### ISSUE TITLE
Custom Attributes in Devices Cannot be Used

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#875]
When setting Custom Attributes at device creation/editing, we can add up to 5 (five) different Custom Attributes. However, we can use only parameters 1 and 2 as filter or list parameters, while attributes 3,4 and 5 cannot be used as filtering criteria at all. The two uploaded images show what we can set when adding new device, and second one show what can we use as filtering/listing criteria. 

<img width="1151" alt="screen shot 2017-10-17 at 09 39 06" src="https://user-images.githubusercontent.com/15121999/31652597-f3fc6232-b31f-11e7-8203-6170449f6c0a.png">

<img width="1440" alt="screen shot 2017-10-17 at 09 38 33" src="https://user-images.githubusercontent.com/15121999/31652603-f6de60e0-b31f-11e7-8246-b8df6216cfa7.png">

Browsers used:
- Google Chrome (Version 61.0.3163.100 (Official Build) (64-bit))
- Safari (Version 11.0 (12604.1.38.1.7))
- Mozilla Firefox (56.0.1 (64-bit))
- Opera (Version 48.0.2685.39)

**Comment by lorthirk** [comment]
This was by design in EDC, and it's related to the indexing of the Custom Attributes field. We'll think about improving it.

**Comment by lorthirk** [comment]
See https://github.com/eclipse/kapua/issues/887#issuecomment-338122848

**Comment by lorthirk** [comment]
@Coduz what are your thoughts on this?

**Comment by Coduz** [comment]
Hi @LeoNerdoG ,

I think that we can leave like this. The other three attributes can be managed via REST API (which is the main point of integration). Until now we don't have ever seen intensive usage of those fields, so for now I think its fine to show only two. 

If requested we will add more.

Regards,

_Alberto_

**Comment by LeoNerdoG** [comment]
Ok, due to upper comments I am closing.
