### ISSUE TITLE
Groups Tabs Set to Default After we Leave Groups

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#876]
If we leave Groups settings, after we rearrange its tabs, everything goes to default when we click Groups again (see images bellow). 
First image shows how User wants the tabs to be arranged like shown on first screenshot (ID, Group Name, Created On). If User than clicks something else (or logs out / logs in again) and later comes back, the Group tabs are arranged in default order (Group Name, Created On, Created By).

Testflow: 
1) log in as kapua-sys
2) go to Groups settings, rearrange its tabs. 
3) click on some other settings (Roles, Devices, Info...) 
4) go back to Groups settings
**After this all the tabs are rearranged to default state.**

<img width="1436" alt="screen shot 2017-10-17 at 12 43 21" src="https://user-images.githubusercontent.com/15121999/31660863-24e25258-b339-11e7-85d6-306172d4c6fd.png">

<img width="1438" alt="screen shot 2017-10-17 at 12 44 50" src="https://user-images.githubusercontent.com/15121999/31660866-27be1b4c-b339-11e7-9799-8e32a9a1b2bf.png">

Browsers used:
- Google Chrome (Version 61.0.3163.100 (Official Build) (64-bit))
- Safari (Version 11.0 (12604.1.38.1.7))
- Mozilla Firefox (56.0.1 (64-bit))
- Opera (Version 48.0.2685.39)

**Comment by lorthirk** [comment]
See https://github.com/eclipse/kapua/issues/887#issuecomment-338122848

**Comment by stefanomorson** [comment]
@LeoNerdoG , @lorthirk : as explained in #887, I don't think this is a bug. Kapua currently does not support the persistence of the user settings of the UI elements (tables in this case).
However this is a good suggestion for future improvements of the UI.
