### ISSUE TITLE
Role Tabs Set to Default After we Leave Roles

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#877]
If we leave Role settings, after we rearrange its tabs, everything goes to default when we click Role settings again (see images bellow). 
First image shows how User wants the tabs to be arranged like shown on first screenshot (Name, Created By). If User than clicks something else (or logs out / logs in again) and later comes back, the Role tabs are arranged in default order.

Testflow: 
1) log in as kapua-sys
2) go to Role settings, rearrange its tabs. 
3) click on some other settings (Groups, Devices, Info...) 
4) go back to Role settings
**After this all the tabs are rearranged to default state.**

<img width="1440" alt="screen shot 2017-10-17 at 12 55 59" src="https://user-images.githubusercontent.com/15121999/31661312-844b89a2-b33a-11e7-9b03-3e87f5b48c40.png">

<img width="1440" alt="screen shot 2017-10-17 at 12 56 10" src="https://user-images.githubusercontent.com/15121999/31661314-874bfd1c-b33a-11e7-9e45-d664666590a0.png">

Browsers used:
- Google Chrome (Version 61.0.3163.100 (Official Build) (64-bit))
- Safari (Version 11.0 (12604.1.38.1.7))
- Mozilla Firefox (56.0.1 (64-bit))
- Opera (Version 48.0.2685.39)

**Comment by lorthirk** [comment]
See https://github.com/eclipse/kapua/issues/887#issuecomment-338122848

**Comment by stefanomorson** [comment]
@LeoNerdoG , @lorthirk : as explained in #887, I don't think this is a bug. Kapua currently does not support the persistence of the user settings of the UI elements (tables in this case).
However this is a good suggestion for future improvements of the UI.
