### ISSUE TITLE
Users Tabs Set to Default After we Leave Users

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#878]
If we leave Users settings, after we rearrange its tabs, everything goes to default when we click Users settings again (see images bellow). 
First image shows how user wants the tabs to be arranged like shown on first screenshot (Status ID, Name, Created On). If User than clicks something else (or logs out / logs in again) and later comes back, the Users tabs are arranged in default order.

Testflow: 
1) log in as kapua-sys
2) go to Users settings, rearrange its tabs. 
3) click on some other settings (Groups, Roles, Devices, Info...) 
4) go back to Users settings
**After this all the tabs are rearranged to default state.**

<img width="1439" alt="screen shot 2017-10-17 at 13 03 09" src="https://user-images.githubusercontent.com/15121999/31661579-8aaf9b98-b33b-11e7-9b4f-6708b01bafe2.png">

<img width="1436" alt="screen shot 2017-10-17 at 13 02 50" src="https://user-images.githubusercontent.com/15121999/31661586-8ead600e-b33b-11e7-90a8-a5cc49f2558d.png">

Browsers used:
- Google Chrome (Version 61.0.3163.100 (Official Build) (64-bit))
- Safari (Version 11.0 (12604.1.38.1.7))
- Mozilla Firefox (56.0.1 (64-bit))
- Opera (Version 48.0.2685.39)

**Comment by lorthirk** [comment]
See https://github.com/eclipse/kapua/issues/887#issuecomment-338122848

**Comment by stefanomorson** [comment]
@LeoNerdoG , @lorthirk : as explained in #887, I don't think this is a bug. Kapua currently does not support the persistence of the user settings of the UI elements (tables in this case).
However this is a good suggestion for future improvements of the UI.
