### ISSUE TITLE
Console insert and update of Access permissions

### ISSUE THREAD

**Issue by muros-ct** [eclipse/kapua#88]
Issue is based on current **develop** branch.

Scenario
----------
In console select Users  
Select Add on users toolbar  
Fill in all User Information data
Switch to Access tab  
Select user:read permission  
Submit changes  

User gets created.

Than select user and select Edit on users toolbar  
User information is displayed  

Issue
------
1 . When selecting Access tab, user:read permission is not selected. I checked database and user permission is there.  
2. When I select user:read again and do Submit error is displayed:

![persistence_error](https://cloud.githubusercontent.com/assets/23033235/20353841/62013430-ac1c-11e6-8ab0-5225e33838af.PNG)

I checked log and this is error message:
`
Caused by: org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "IDX_USER_PERMISSION_SCOPE_ID ON KAPUADB
.ATHZ_USER_PERMISSION(SCOPE_ID, USER_ID, DOMAIN, ACTION, TARGET_SCOPE_ID) VALUES (1, 1, 'user', 'read', 1, 1479310555697
)"; SQL statement:
INSERT INTO athz_user_permission (created_on, created_by, id, action, domain, target_scope_id, scope_id, user_id) VALUES
 (?, ?, ?, ?, ?, ?, ?, ?) [23505-192]
`
3. User permission is also not displayed in User grid undel column Permissions.

**Comment by Coduz** [comment]
Hi @muros-ct, 

as per discussion during the Kapua internal SCRUM, all issues related to the old console will be marked with "wontfix" label and closed.
We are already working on the new console implementation.

Regards, 

_Alberto_
