### ISSUE TITLE
Sorting in Connections Does Not Work

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#880]
If we have multiple connections in Kapua, we cannot simply sort them by clicking on Client ID, User ID, Protocol, Modified On (as we can in Devices?) but rather we have to "manually" select Sort Ascending, Sort Descending (look at screenshot bellow). 

Testflow: 
1) Log in as kapua-sys
2) Create new user (e.g. kapua-user1) and connect several devices to it
3) Go to Connections tab and try to sort devices by just clicking on: 
   - Client ID
   - User ID
   - Protocol 
   - Modified On

**As stated above, we can only change the list order by manually selecting Sort De/Ascending.**

<img width="1254" alt="screen shot 2017-10-18 at 08 56 01" src="https://user-images.githubusercontent.com/15121999/31704523-0f093c5e-b3e2-11e7-971c-130150352658.png">

Browsers used:
- Google Chrome (Version 61.0.3163.100 (Official Build) (64-bit))
- Safari (Version 11.0 (12604.1.38.1.7))
- Mozilla Firefox (56.0.1 (64-bit))
- Opera (Version 48.0.2685.39)

**Comment by stefanomorson** [comment]
@LeoNerdoG : Same comment as in #884 regarding the title of the issue
