### ISSUE TITLE
Deploy Kapua offical 0.3.0-Release docker image, but  login failed

### ISSUE THREAD

**Issue by ruin1990** [eclipse/kapua#882]
The control web site warning this messages:
```
Login Failed.
An internal error occurred: org.apache.shiro.ShiroException: Error while find user!.
```
This problem is happened when 0.3.0 released, 
I also type this command on a  clear ubuntu 14.04 server,
Like this:
```
sudo docker run -td --name kapua-sql -p 8181:8181 -p 3306:3306 kapua/kapua-sql
sudo docker run -td --name kapua-elasticsearch -p 9200:9200 -p 9300:9300 elasticsearch:5.4.0 -Ecluster.name=kapua-datastore -Ediscovery.type=single-node -Etransport.host=_site_ -Etransport.ping_schedule=-1 -Etransport.tcp.connect_timeout=30s
sudo docker run -td --name kapua-broker --link kapua-sql:db --link kapua-elasticsearch:es -p 1883:1883 -p 61614:61614 kapua/kapua-broker
sudo docker run -td --name kapua-console --link kapua-sql:db --link kapua-broker:broker --link kapua-elasticsearch:es -p 8080:8080 kapua/kapua-console
sudo docker run -td --name kapua-api --link kapua-sql:db --link kapua-broker:broker --link kapua-elasticsearch:es -p 8081:8080 kapua/kapua-api
```
But, I found that I cannot login, which i can login success with offical 0.2.0 release docker image when it's deployed.

I tried all my way to find the problem, but nothing can help me.
Anyone have a good solution, thanks a lot. : )

Best regards, 
Yours ruin1990

**Comment by lorthirk** [comment]
Hi @ruin1990,

You're following and outdated documentation; please see #853 to check the correct commands.

Also, may I ask you where did you get those commands? I thought we updated them everywhere, but probably something is still missing. It would be great if you could point me there.

**Comment by ruin1990** [comment]
oh, @lorthirk , thanks very much.
And i'm very sorry, that I didn't notice that the commands are changed.
I used the old commands by offline document with 0.2.0.
I was also found all the commands everywhere, it was updated.
This is my mistakes.
It works well~ 🙂

**Comment by lorthirk** [comment]
Great!

Closing  🙂
