### ISSUE TITLE
Sorting in Groups does not work

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#883]
If we have multiple Groups in Kapua, we cannot simply sort them by clicking on Access Group Name, ID, Created On, Created By, but rather we have to "manually" select Sort Ascending, Sort Descending (look at screenshot bellow).

Testflow:
1) Log in as kapua-sys
2) Go to Groups tab and create several new groups
3) Try to sort groups by just clicking on:
   - ID
   - Access Group Name
   - Created On
   - Created By

As stated above, we can only change the list order by manually selecting Sort De/Ascending.

<img width="1440" alt="screen shot 2017-10-18 at 15 49 21" src="https://user-images.githubusercontent.com/15121999/31722274-f5809022-b41b-11e7-8b49-67e0ed92a271.png">

Browsers used:
- Google Chrome (Version 61.0.3163.100 (Official Build) (64-bit))
- Safari (Version 11.0 (12604.1.38.1.7))
- Mozilla Firefox (56.0.1 (64-bit))
- Opera (Version 48.0.2685.39)

**Comment by stefanomorson** [comment]
@LeoNerdoG : Same comment as in #884 regarding the title of the issue
