### ISSUE TITLE
Sorting in Roles Does Not Work

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#884]
If we have multiple Roles in Kapua, we cannot simply sort them by clicking on Name, Created On, Created By, but rather we have to "manually" select Sort Ascending, Sort Descending (look at screenshot bellow).

Testflow:
1) Log in as kapua-sys
2) Go to Roles tab and create several new roles
3) Try to sort roles by just clicking on:
   - Name
   - Created On
   - Created By

As stated above, we can only change the list order by manually selecting Sort De/Ascending.

<img width="1440" alt="screen shot 2017-10-18 at 15 51 07" src="https://user-images.githubusercontent.com/15121999/31722382-36e77bf2-b41c-11e7-91eb-63a60f247b1b.png">

Browsers used:
- Google Chrome (Version 61.0.3163.100 (Official Build) (64-bit))
- Safari (Version 11.0 (12604.1.38.1.7))
- Mozilla Firefox (56.0.1 (64-bit))
- Opera (Version 48.0.2685.39)

**Comment by stefanomorson** [comment]
@LeoNerdoG : I think the title is a bit misleading. Can you change it to reflect the actual issue ? Maybe "Enable table sort by double click the ... "

**Comment by LeoNerdoG** [comment]
Hi @stefanomorson 
I will change this to "Double Click Sorting in Roles Does Not Work" if this is OK? If you agree, I will change all the other Issue names accordingly.
