### ISSUE TITLE
Tags Tabs Set to Default After we Leave Tags

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#887]
If we leave Tags settings, after we rearranged its tabs, everything goes to default when we click Tags settings again (see images bellow). 
First image shows how user wants the tabs to be arranged like shown on first screenshot (ID, Tagname). If user than clicks something else (or logs out / logs in again) and later comes back, the Tags tabs are arranged in default order.

Testflow: 
1) log in as kapua-sys
2) go to Tags settings, rearrange its tabs. 
3) click on some other settings (Groups, Roles, Devices, Info...) 
4) go back to Tags settings
**After this all the tabs are rearranged to default state.**

This is how user arranged tabs in Tags: 
<img width="1440" alt="screen shot 2017-10-19 at 13 45 47" src="https://user-images.githubusercontent.com/15121999/31769502-3a43dd00-b4d4-11e7-8c98-8744646a6159.png">

When user comes back, tabs are in default order: 
<img width="1440" alt="screen shot 2017-10-19 at 13 45 52" src="https://user-images.githubusercontent.com/15121999/31769505-3bd16d7c-b4d4-11e7-8872-2da3383e27ad.png">

Browsers used:
- Google Chrome (Version 61.0.3163.100 (Official Build) (64-bit))
- Safari (Version 11.0 (12604.1.38.1.7))
- Mozilla Firefox (56.0.1 (64-bit))
- Opera (Version 48.0.2685.39)

**Comment by lorthirk** [comment]
What do you mean exactly by "rearrange its tabs"?

**Comment by LeoNerdoG** [comment]
@lorthirk ,
when user goes to Tags, the default arrangement of its tabs/columns is as showed on second screenshot: 
 - Tag Name,
 - Created On
 - Created By

Let's say that user does not need Created On and Created By tabs/columns, but only ID of the created tag and tag name (look at screenshot 1). So, user rearranges everything, then clicks through Kapua GUI to do some things, and when he comes back to Tags, they are arranged in default order (as shown on second screenshot) and not as he arranged it. 
So user would have to rearrange columns every time he comes back.

**Comment by lorthirk** [comment]
Ok, so you're talking about columns.

There's no easy way to fix this, since the view gets instantiated again every time the user clicks on a menu item.

**Comment by stefanomorson** [comment]
@LeoNerdoG , @lorthirk : I don't think this is a bug. Kapua currently does not support the persistence of the user settings of the UI. 
However this is a good suggestion for future improvements of the UI.
