### ISSUE TITLE
Console empty fields on User list

### ISSUE THREAD

**Issue by muros-ct** [eclipse/kapua#89]
Issue is based on current **develop** branch.

Scenario
----------
Select Users  
User list is displayed  

Issue
------
1. List contains fields that are not present:
* Login Attempts  
* Attempts Reset On  
* Locked On  
* Unlock On  

I inspected user table in database and it also doesn't have those fields.  

2. I tried failed login and it didn't lock me out.

I checked user Metadata which has settings for default values for this fields. Ex. login attempts is set to 3 by default, but it doesn't check this, neither locks user out after 3 failed attempts.

Are those functionalities present in kapua?

![unused_columns](https://cloud.githubusercontent.com/assets/23033235/20354241/cde18564-ac1d-11e6-9f48-4eb07db814f8.PNG)

**Comment by Coduz** [comment]
Hi @muros-ct,

as per discussion during the Kapua internal SCRUM, all issues related to the old console will be marked with "wontfix" label and closed.
We are already working on the new console implementation.

Regards,

Alberto
