### ISSUE TITLE
No Client IP Field in Connections

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#891]
Connection filter contains Client ID, Connection Status and Client IP fields, which we can use to filter devices. 
When we look at the columns available in Connections, there is no Client IP field (this way it is much harder to filter devices by their IP). 

Testflow: 
1) Login as kapua-sys
2) Connect several devices to Kapua
3) Go to Connections - there is no Client IP column available. 

![screen shot 2017-10-19 at 14 17 23](https://user-images.githubusercontent.com/15121999/31772693-c4c300b2-b4e0-11e7-80c0-82dabf4fd892.png)

Browser used:
- Google Chrome (Version 61.0.3163.100 (Official Build) (64-bit))
- Safari (Version 11.0 (12604.1.38.1.7))
- Mozilla Firefox (56.0.1 (64-bit))
- Opera (Version 48.0.2685.39)

**Comment by bojanutkovic** [comment]
I started working on this
