### ISSUE TITLE
Cannot Add Credentials to Users

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#892]
When creating new user (as kapua-sys or in any other child account) we can add roles, permissions but no credentials. User can click on Credentials tab, but it looks like everything is frozen. Mouse pointer does change from mouse to hand-like pointer, but "add" button (and all others) is unclickable. 
(Also we cannot add Credentials to default users: kapua-broker and kapua-sys). 

Testflow: 
1) Login as kapua-sys
2) Go to Users and try to add Credentials to kapua-broker/kapua-sys or
3) Create new user and try to add Credentials to it. 
**It should not be possible due to bug in Kapua.**

<img width="1440" alt="screen shot 2017-10-19 at 15 22 59" src="https://user-images.githubusercontent.com/15121999/31773097-f0979d82-b4e1-11e7-8b73-628ac34ad204.png">

Browser used:
- Google Chrome (Version 61.0.3163.100 (Official Build) (64-bit))
- Safari (Version 11.0 (12604.1.38.1.7))
- Mozilla Firefox (56.0.1 (64-bit))
- Opera (Version 48.0.2685.39)

**Comment by ct-goranpalibrk** [comment]
I started working on this

**Comment by lorthirk** [comment]
Fixed by c47024a70b51ec15976fd5a0f2c3dfe0f67fa169
