### ISSUE TITLE
Refresh Button in Devices Freezes After Clicking on it

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#904]
When user clicks on refresh button in: Devices -> Bundles -> Refresh, list does not get refreshes and button freezes, becomes unclickable (look at the screenshot bellow). Other two buttons (start/stop) look frozen but are functional. 

Testflow: 
1) Login as kapua-sys
2) Connect a device to Kapua (e.g. Raspberry Pi)
3) Go to Devices -> Bundles
4) Try to refresh list of bundles
**After hitting refresh, nothing happens and button freezes. **

![screen shot 2017-10-26 at 15 07 26](https://user-images.githubusercontent.com/15121999/32054860-2c7990f2-ba60-11e7-83ec-de097d36d2b4.png)

Browsers used:
- Google Chrome (Version 61.0.3163.100 (Official Build) (64-bit))
- Safari (Version 11.0 (12604.1.38.1.7))
- Mozilla Firefox (56.0.1 (64-bit))
- Opera (Version 48.0.2685.39)

**Comment by lorthirk** [comment]
A fix is proposed in 4b74f8a

**Comment by LeoNerdoG** [comment]
I am verifying that this issue is resolved.
