### ISSUE TITLE
Cannot Add Cron Schedule in Jobs

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#905]
When trying to add cron schedule to certain job in Jobs, I get an error saying **Invalid Cron Expression** although the cron expression is OK (look at screenshot bellow). Several cron expressions have been used, but non of them was accepted by Kapua.  

Testflow: 
1) login as kapua-sys
2) Connect a device to Kapua (e.g. Raspberry Pi) 
3) Go to Jobs, create new job and add a target (Raspberry Pi)
4) Go to Schedules tab and try to add new schedule with cron schedule, Kapua shows an error: 
**Invalid Cron Expression.** 

<img width="1440" alt="screen shot 2017-10-26 at 15 48 14" src="https://user-images.githubusercontent.com/15121999/32056998-56f98408-ba66-11e7-938a-e802be47c011.png">

Browsers used:
- Google Chrome (Version 61.0.3163.100 (Official Build) (64-bit))
- Safari (Version 11.0 (12604.1.38.1.7))
- Mozilla Firefox (56.0.1 (64-bit))
- Opera (Version 48.0.2685.39)

**Comment by lorthirk** [comment]
The validation is provided by `org.quartz.CronExpression`. For the expression in the screenshot, the error message is:

> Support for specifying both a day-of-week AND a day-of-month parameter is not implemented.

**Comment by lorthirk** [comment]
Hi @LeoNerdoG, 

I've added the result of the cron validation as an info popup on the lower right. Do you think it's enough to make the user understand what's going on?

**Comment by LeoNerdoG** [comment]
@lorthirk I have checked this and I think it is OK, user should be aware of what is wrong. The error is a bit long for the message it contains (info box closes quickly), but user can click twice on _**Submit**_ and read again, so I see no problem there. 
From my point of view this can be merged into develop.

**Comment by lorthirk** [comment]
Merged in develop with e06d32cad

**Comment by LeoNerdoG** [comment]
@lorthirk I have verified that this issue is sucessfully resolved.
