### ISSUE TITLE
No Edit Button in Schedules Tab

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#908]
This is not a bug, but rather a proposal for enhancement. 
When creating a new job and configuring its schedules, it would be convenient to have an _edit_ button for changing parameters of a certain schedule (if a user makes a mistake entering schedule it is easier to change one parameter than creating whole new schedule).

![screen shot 2017-10-27 at 09 46 36](https://user-images.githubusercontent.com/15121999/32103169-7f7f90fc-bb1f-11e7-854f-05ce11f80caa.png)

**Comment by lorthirk** [comment]
This is by design. We don't allow editing of Schedules because it could be difficult to edit a Schedule with the current Job Scheduler implementation, so we prefer to delete a Schedule and create a new one instead of editing it.
