### ISSUE TITLE
Console expired session

### ISSUE THREAD

**Issue by muros-ct** [eclipse/kapua#91]
Issue is based on current **develop** branch.

Scenario
----------

Login into console  
Wait for 30 minutes for session to expire, do not use console  
Select Users  

Issue
-------

After expired session user is not redirected to login  
If Users option is selected you get Loading sign and error message  

![logout_error2](https://cloud.githubusercontent.com/assets/23033235/20380875/e9333222-aca4-11e6-8e88-c9fc3ebab33a.PNG)

![logout_error](https://cloud.githubusercontent.com/assets/23033235/20380887/f1116ec8-aca4-11e6-94a1-054b3e4cc020.PNG)

If Users option is already open, dialog opens, but it is empty
Error message with null KapuaSession is also displayed

**Comment by Coduz** [comment]
Hi @muros-ct,

as per discussion during the Kapua internal SCRUM, all issues related to the old console will be marked with "wontfix" label and closed.
We are already working on the new console implementation.

Regards,

Alberto
