### ISSUE TITLE
How to send sms or e-mail through kapua to Subscribers

### ISSUE THREAD

**Issue by dineshkumar4728** [eclipse/kapua#912]
Hi all,
     currently i am using eurotech sand box instead of kapua and coming to my problem is how send alerts (sms or e-mails) to subscribers (or) particular persons.please send any information related on this(for kapua also).

Thank you
-Dinesh

**Comment by lorthirk** [comment]
Hi,

Unfortunately there's no way to send SMS or emails through Kapua today.
