### ISSUE TITLE
A user with credential:update permissions should be able to unlock a credential

### ISSUE THREAD

**Issue by stefanomorson** [eclipse/kapua#915]
When a user credential gets locked due to enforcement of the defined lockout policy, another (non-locked) user with at least credential:write permission should be able to unlock the locked credential.

Proposed solution:

* In the admin console, user view, credential tab, add a button "Unlock credential". The button is enabled if the credential is actually locked. 
* In the rest api, /credential resource group: add an api to unlock the locked credential.

**Comment by lorthirk** [comment]
First point is resolved by 65304175630b276c5f77a703f2d363547142ba5a. Leaving this open to cover REST APIs as well.

**Comment by lorthirk** [comment]
Also, the button currently gets enabled regardless of the permission. An additional check has to be implemented to cover this.

**Comment by lorthirk** [comment]
This issue should be closed by the following commits:

6530417 - Credentials unlock button
94417b7 - Credential Unlock improvements
77d899b - Permission check for Credential tab and Unlock Credential button
d70960d - Credential Lockout visual indication after lockout expiration fixed
59ef163 - Credential unlock REST API
