### ISSUE TITLE
Kapua UI Freezes If Existing Role Renamed To Non-Unique Name

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#920]
If we create several roles (e.g. role1, role2, role3) and then try to rename for example role2 into role3, Kapua UI freezes (it is not responding) and whole webpage has to be refreshed. 

Testflow: 
1. Login as kapua-sys
2. Go to Roles, create several roles with unique names (e.g. role1, role2, role3)
3. Try to rename role2 into role3.
**Kapua UI freezes as shown in screenshot bellow.**

<img width="1440" alt="screen shot 2017-11-06 at 09 23 28" src="https://user-images.githubusercontent.com/15121999/32431801-1ebaddc2-c2d5-11e7-8c57-afeaf39f9352.png">

Browsers used: 
- Google Chrome (Version 62.0.3202.75 (Official Build) (64-bit))
- Safari (Version 11.0.1 (12604.3.5.1.1))
- Mozilla Firefox (56.0.2 (64-bit))
- Opera (Version 48.0.2685.52)

**Comment by lorthirk** [comment]
A fix is provided in 2e0b7528a

**Comment by LeoNerdoG** [comment]
I am verifying that this issue is resolved.
