### ISSUE TITLE
Backport relevant issues to branch 0.3.x

### ISSUE THREAD

**Issue by stefanomorson** [eclipse/kapua#926]
This issue is to track the back-port of the solution of relevant issues from  develop to branch 0.3.x after the creation of branch 0.3.x

**Comment by Coduz** [comment]
Backported commits/PRs/Issue

https://github.com/eclipse/kapua/pull/835 - Clean up of *.gwt.xml config file
https://github.com/eclipse/kapua/commit/16a86a257b7420a6b36b40a99c2fef5219a3ae35 - Allow a second logo in Console home page
https://github.com/eclipse/kapua/commit/ead4d0e0ea96443474a0b7caa71c2497ceeebd05 - Allow customization of default KapuaIcon color
https://github.com/eclipse/kapua/commit/2a7a3b33214494fccfb13227d0997fff27d53f08 - Configurable login dialog header
https://github.com/eclipse/kapua/commit/c47024a70b51ec15976fd5a0f2c3dfe0f67fa169 - Fix NPE on Credentials tab
https://github.com/eclipse/kapua/commit/c99ad187dfe3984f846a7cfdf7b4969d6e74a72a - Fixed device asset view tab when writing to asset
https://github.com/eclipse/kapua/pull/911 - Console UI bugs
https://github.com/eclipse/kapua/issues/855 https://github.com/eclipse/kapua/issues/856 https://github.com/eclipse/kapua/issues/857 - Credential Lockout Policy fix fixes 
https://github.com/eclipse/kapua/issues/841 - Unable to add Permissions to new User
https://github.com/eclipse/kapua/issues/928 - Console User Add Dialog does not set Target Scope Id

**Comment by Coduz** [comment]
https://github.com/eclipse/kapua/issues/910 - Device Command Management Execution in Jobs Does Not Work

**Comment by Coduz** [comment]
https://github.com/eclipse/kapua/commit/94417b7d4b8cb9ff2ed1a362e43ac3ce32681064 - Credential Unlock improvements
https://github.com/eclipse/kapua/commit/e25c33e3c2f4730b962a10bb47e1d486fe2b13c2 - Fixed add job target dialog grid result loading - fix issue #907

**Comment by lorthirk** [comment]
136e708a24a592eaaafb2b6c68569d69d837fdcb - Improved exception handling in service unit tests. (#898)
5c5de102b36c1d08cbe243b987fcb4bf6236c82a - A new batch of unit tests for the Job service (#901)
33466e13bc168c352fc05c7cfaaafaccedd3d553 - Prevent adding the same job target multiple times

**Comment by lorthirk** [comment]
1b77e8bf8 - Asset and Channel tables in Data view strings fixed Fixes #917

**Comment by lorthirk** [comment]
9579c881b - Datastore queries limit set to 10000 Fixes #916, Fixes #939

**Comment by Coduz** [comment]
https://github.com/eclipse/kapua/issues/942 - Fixed permissions required to have access to DeviceView

**Comment by lorthirk** [comment]
77d899bb918585021eb5b39d39809fdeb80eee86 - Permission check for Credential tab and Unlock Credential button
d70960dea7c2e5ed15ecbb99e1ac2e6b66f2f456 - Credential Lockout visual indication after lockout expiration fixed
59ef16300b129c3c3edeba4ff1970f884395f483 - Credential unlock REST API

**Comment by lorthirk** [comment]
2e0b7528a2c3d2286c4578e3532b892aae746f57 - Hide dialog after Role persistence fail Fix for #920

**Comment by lorthirk** [comment]
4b74f8ac9 - Bundles refresh button fixed Fix for #904

**Comment by lorthirk** [comment]
207af90d9 - Customizable product information for GWT console

**Comment by lorthirk** [comment]
0c19af3ff6946058ad376e477817188729137371 - fix permissions tab in roles view (#954)

**Comment by lorthirk** [comment]
d5d50cb79d5b40e70ebfa9b227d2d8a3e2d87b97 - Fix #894 (#953)

**Comment by lorthirk** [comment]
fb3951613 - Hide Roles and Permissions tab in Users view without proper permission

**Comment by lorthirk** [comment]
962f48e94 - Connections paging fixed Fix attempt for #929

**Comment by lorthirk** [comment]
c9fcc81a3 - Allow an user without permissions to access the console Fix for #958

**Comment by Coduz** [comment]
bd66399e1 - Fixed building documentation

**Comment by lorthirk** [comment]
fbc1c0adf - Device Description string fixed Fix for #919

**Comment by Coduz** [comment]
https://github.com/eclipse/kapua/issues/943 - Unable to associate a tag to a device

**Comment by lorthirk** [comment]
82638b3d4 - Check for existing Password credential when creating a new one Fix for #947

**Comment by lorthirk** [comment]
ed6266a827b29ad43ec7317c00b6fd105a3c7b9e - Merge pull request #971 from ct-goranpalibrk/fix-rxByteLimit Fix #862

**Comment by lorthirk** [comment]
a1ecd3df5 - message broker - fix broker name (#969)

**Comment by lorthirk** [comment]
74e6a3404 - DeviceConnectionService tight coupling setting implemented as a ComboBox Fix for #967

**Comment by lorthirk** [comment]
a61b72c4e - FIx #906, #944, #945, #946 (#973)

**Comment by lorthirk** [comment]
92c102605 - Proper error message shown when creating device if needed Fix for #970

**Comment by lorthirk** [comment]
500e0cd10 - add Expiration Date column (#980)

**Comment by lorthirk** [comment]
59b5e6e99 - add Expiration Date values for Password/API_Key (#986)

**Comment by lorthirk** [comment]
b202b1442 - Check for existing PASSWORD only if creating a new password Fix for #987

**Comment by Coduz** [comment]
b6af67ddd3f0a0fde55602aa763c8640bb7af429 - Fix edit dialog in Device View -  https://github.com/eclipse/kapua/issues/993

**Comment by lorthirk** [comment]
c2c80fc - Missing about.html files added Fixes #976

**Comment by lorthirk** [comment]
cc90b1bf5 - Start time and end time added in new Schedule dialog Fix for 992

**Comment by lorthirk** [comment]
bcf3de1f4 - Tag filter in Device view

**Comment by lorthirk** [comment]
255508810 - MessageStoreService configuration panel updated Fixes for #860, #863 and #864

**Comment by Coduz** [comment]
657dbe43a1e61a3436460339a0d0bb7ab3882f89 - Fixed tabs and dialogs permission view enablement in DeviceView #1000

**Comment by lorthirk** [comment]
c620e0378 - Hide tabs when missing required permissions

**Comment by lorthirk** [comment]
fccbb225b - Always call the callback when returning Users for a given Role Fix for #972

**Comment by lorthirk** [comment]
463cf7759 - Cross-domain authorization fixes Mostly to fix authorization exception when user:read permission is missing and an entity grid or entity description tab is shown. There could be other places to fix as well.

**Comment by lorthirk** [comment]
13f5d49d0 - Missing import fixed

**Comment by lorthirk** [comment]
81623675c - Scheduler domain seeding, adding schedule without end date/time fixed Fix for #1008

**Comment by lorthirk** [comment]
885d6f216 - Another round of cross domain fixes Fix fox #1020, #1021 and probably #1009

**Comment by lorthirk** [comment]
05a4447a1 - Added hidden BrokerURL system configuration Needed to support per-deploy broker url customization. The setting is under org.eclipse.kapua.service.account.AccountService

**Comment by lorthirk** [comment]
5185ece5a - Device export fixed Fix for #1037

**Comment by lorthirk** [comment]
7b217fc4c - Device management operations with no account:read permission fixed Fix for #1039, #1040, #1041, #1042 and #1043

**Comment by lorthirk** [comment]
305659490 - API Key confirmation dialog style fixed Fix for #1028

**Comment by lorthirk** [comment]
5e0a7d0 - Fixes #984, #983, #982, #981, #979, #978, #977 (#1038)

**Comment by Coduz** [comment]
3f78bc69f2ef19a866571cdf36032c96fb518a1e - Added running status column on JobExecution grid  - #1023

**Comment by lorthirk** [comment]
ee431a85f - Self account informations edit fixed Fix for #1054

**Comment by lorthirk** [comment]
98a571f22 - Account information editing permissions fixed Fix for #1053, also impacts #1054

**Comment by Coduz** [comment]
c6aca6d39922b4b558751d784a5030a26560da79 - In Users Phone Number Field Any Symbol Can Be Added (#988)

**Comment by Coduz** [comment]
ce67582b4 Fixed API_KEY credential generation and checking (#1033)
8a0eccc83 Fixed KapuaAuthenticationException handling on REST API
0873666bf Added KapuaAuthorizationException mapper to REST API
b41887198 Added model for returning a SubjectUnauthorized exception from REST API

**Comment by lorthirk** [comment]
a90e54016 - Asset list not autoselect Fix for #1052

**Comment by lorthirk** [comment]
a7efe8d0a - Gracefully manage permission error on description tab First part of fixes needed for #1053

**Comment by lorthirk** [comment]
b30e3dff0 - Avoid doulbe refresh on second level grids Fix for #972, #990, #1001, #1003, #1004, #1005

**Comment by Coduz** [comment]
be288830b - Fixed liquibase script boolean value set with dedicated property

**Comment by riccardomodanese** [comment]
fix #1063 
39297ffe - datatstore ttl - implementation 
f4eea1c - datatstore ttl - fix 
3f08405 - Log level cheìanged to debug

**Comment by Coduz** [comment]
819def826 display correct error mesage - fixes #1057 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 6391daf29 remove FailureHandler

51230a928 add meaningful title and a description  - fixes #989 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  bcf49c5ab fix error message in tag tab in Device View
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  7b3403701 fix changes for PR

**Comment by Coduz** [comment]
https://github.com/eclipse/kapua/pull/1087 - Fixed certificate loading on tests

**Comment by Coduz** [comment]
#1088 - Broker URI option in console

**Comment by Coduz** [comment]
#1090 - Added certificates paths to broker assembly docker plugin
