### ISSUE TITLE
Pages in Connections Do Not Work 

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#929]
When creating 100+ connections to Kapua, connections from 101 should be on page 2 (according to GUI) but all the connections are listed on page 1. 
When we switch to page 2, the list only gets refreshed (so we basically stay on page 1, although GUI says we are on page 2). 

Testflow: 
1. Login as kapua-sys
2. Create 100+ connections 
3. Go to page 2 of the connections list
**There should be only 100 connections listed on page 1 instead of all of them.**

![screen shot 2017-11-07 at 10 25 11](https://user-images.githubusercontent.com/15121999/32486461-fc038dce-c3a6-11e7-8623-172ac3897fa5.png)

Browsers used:
- Google Chrome (Version 62.0.3202.75 (Official Build) (64-bit))
- Safari (Version 11.0.1 (12604.3.5.1.1))
- Mozilla Firefox (56.0.2 (64-bit))
- Opera (Version 48.0.2685.52)

**Comment by LeoNerdoG** [comment]
I am verifying that this issue is solved with PR #956 .

**Comment by LeoNerdoG** [comment]
I am verifying that this issue is resolved via PR #956 .

**Comment by stefanomorson** [comment]
After testing around I found that the issue is not solved.

**Comment by LeoNerdoG** [comment]
I am confirming that this is fixed.
