### ISSUE TITLE
Kura not connecting to Kapua

### ISSUE THREAD

**Issue by dineshkumar4728** [eclipse/kapua#932]
Hi All,

I have experiencing issue while connecting to kapua , I have followed kura and kapua documentation but im getting errors while connecting to kapua which im sharing attachment, please take a look and let me know whether i have to make any changes

(Im trying to login with kapua-broker)
![capture](https://user-images.githubusercontent.com/32698518/32487537-f49741c4-c3cf-11e7-8a2f-4ad8cc15675e.PNG)

Thanks
Dinesh.

**Comment by riccardomodanese** [comment]
Hi Dinesh,
can you provide us some log to help us to understand your issue?
Both Kura and Kapua side will be better.

**Comment by dineshkumar4728** [comment]
Hi riccardomodanese,
  I didn't get any errors while running.

[INFO] Reactor Summary:
[INFO]
[INFO] kapua-build-tools .................................. SUCCESS [ 2.839 s]
[INFO] kapua .............................................. SUCCESS [ 32.379 s]
[INFO] kapua-service ...................................... SUCCESS [ 2.478 s]
[INFO] kapua-liquibase .................................... SUCCESS [ 2.213 s]
[INFO] kapua-service-api .................................. SUCCESS [ 0.734 s]
[INFO] kapua-user ......................................... SUCCESS [ 0.192 s]
[INFO] kapua-user-api ..................................... SUCCESS [ 0.246 s]
[INFO] kapua-security ..................................... SUCCESS [ 0.781 s]
[INFO] kapua-security-authorization ....................... SUCCESS [ 0.155 s]
[INFO] kapua-security-authorization-api ................... SUCCESS [ 0.440 s]
[INFO] kapua-security-authentication ...................... SUCCESS [ 0.121 s]
[INFO] kapua-security-authentication-api .................. SUCCESS [ 0.333 s]
[INFO] kapua-account ...................................... SUCCESS [ 0.186 s]
[INFO] kapua-account-api .................................. SUCCESS [ 0.188 s]
[INFO] kapua-commons ...................................... SUCCESS [ 2.058 s]
[INFO] kapua-locator ...................................... SUCCESS [ 0.106 s]
[INFO] kapua-guice ........................................ SUCCESS [ 0.261 s]
[INFO] kapua-message ...................................... SUCCESS [ 0.219 s]
[INFO] kapua-message-api .................................. SUCCESS [ 0.260 s]
[INFO] kapua-device ....................................... SUCCESS [ 0.733 s]
[INFO] kapua-device-api ................................... SUCCESS [ 0.166 s]
[INFO] kapua-device-registry .............................. SUCCESS [ 0.323 s]
[INFO] kapua-device-registry-api .......................... SUCCESS [ 0.369 s]
[INFO] kapua-datastore .................................... SUCCESS [ 0.616 s]
[INFO] kapua-datastore-client-api ......................... SUCCESS [ 0.239 s]
[INFO] kapua-test ......................................... SUCCESS [ 1.267 s]
[INFO] kapua-account-internal ............................. SUCCESS [ 0.355 s]
[INFO] kapua-datastore-api ................................ SUCCESS [ 0.312 s]
[INFO] kapua-user-internal ................................ SUCCESS [ 0.361 s]
[INFO] kapua-sso .......................................... SUCCESS [ 0.098 s]
[INFO] kapua-sso-jwt ...................................... SUCCESS [ 0.213 s]
[INFO] kapua-security-registration ........................ SUCCESS [ 0.156 s]
[INFO] kapua-security-registration-api .................... SUCCESS [ 0.193 s]
[INFO] kapua-security-shiro ............................... SUCCESS [ 1.808 s]
[INFO] kapua-message-internal ............................. SUCCESS [ 0.371 s]
[INFO] kapua-datastore-client-embedded .................... SUCCESS [ 0.256 s]
[INFO] kapua-datastore-client-transport ................... SUCCESS [ 0.347 s]
[INFO] kapua-datastore-client-rest ........................ SUCCESS [ 0.374 s]
[INFO] kapua-transport .................................... SUCCESS [ 0.132 s]
[INFO] kapua-transport-api ................................ SUCCESS [ 0.143 s]
[INFO] kapua-device-call .................................. SUCCESS [ 0.242 s]
[INFO] kapua-device-call-api .............................. SUCCESS [ 0.190 s]
[INFO] kapua-tag .......................................... SUCCESS [ 0.132 s]
[INFO] kapua-tag-api ...................................... SUCCESS [ 0.207 s]
[INFO] kapua-device-registry-internal ..................... SUCCESS [ 0.682 s]
[INFO] kapua-datastore-internal ........................... SUCCESS [ 1.113 s]
[INFO] kapua-device-asset ................................. SUCCESS [ 0.123 s]
[INFO] kapua-device-asset-api ............................. SUCCESS [ 0.142 s]
[INFO] kapua-translator ................................... SUCCESS [ 0.229 s]
[INFO] kapua-translator-api ............................... SUCCESS [ 0.192 s]
[INFO] kapua-device-call-kura ............................. SUCCESS [ 1.215 s]
[INFO] kapua-device-commons ............................... SUCCESS [ 0.296 s]
[INFO] kapua-device-asset-internal ........................ SUCCESS [ 0.236 s]
[INFO] kapua-job .......................................... SUCCESS [ 0.213 s]
[INFO] kapua-job-api ...................................... SUCCESS [ 0.225 s]
[INFO] kapua-job-engine ................................... SUCCESS [ 0.127 s]
[INFO] kapua-job-commons .................................. SUCCESS [ 0.201 s]
[INFO] kapua-device-asset-job ............................. SUCCESS [ 0.187 s]
[INFO] kapua-transport-mqtt ............................... SUCCESS [ 0.226 s]
[INFO] kapua-translator-kura .............................. SUCCESS [ 0.140 s]
[INFO] kapua-translator-kura-mqtt ......................... SUCCESS [ 0.176 s]
[INFO] kapua-device-call-test ............................. SUCCESS [ 0.091 s]
[INFO] kapua-device-configuration ......................... SUCCESS [ 0.116 s]
[INFO] kapua-device-configuration-api ..................... SUCCESS [ 0.113 s]
[INFO] kapua-device-configuration-internal ................ SUCCESS [ 0.281 s]
[INFO] kapua-device-configuration-job ..................... SUCCESS [ 0.120 s]
[INFO] kapua-device-packages .............................. SUCCESS [ 0.121 s]
[INFO] kapua-device-packages-api .......................... SUCCESS [ 0.158 s]
[INFO] kapua-device-packages-internal ..................... SUCCESS [ 0.289 s]
[INFO] kapua-device-packages-job .......................... SUCCESS [ 0.161 s]
[INFO] kapua-device-bundle ................................ SUCCESS [ 0.072 s]
[INFO] kapua-device-bundle-api ............................ SUCCESS [ 0.102 s]
[INFO] kapua-device-bundle-internal ....................... SUCCESS [ 0.199 s]
[INFO] kapua-device-bundle-job ............................ SUCCESS [ 0.636 s]
[INFO] kapua-device-command ............................... SUCCESS [ 0.132 s]
[INFO] kapua-device-command-api ........................... SUCCESS [ 0.213 s]
[INFO] kapua-device-command-internal ...................... SUCCESS [ 0.312 s]
[INFO] kapua-device-command-test .......................... SUCCESS [ 0.115 s]
[INFO] kapua-device-command-job ........................... SUCCESS [ 0.163 s]
[INFO] kapua-device-request ............................... SUCCESS [ 0.076 s]
[INFO] kapua-device-request-api ........................... SUCCESS [ 0.132 s]
[INFO] kapua-device-request-internal ...................... SUCCESS [ 0.418 s]
[INFO] kapua-job-internal ................................. SUCCESS [ 0.531 s]
[INFO] kapua-scheduler .................................... SUCCESS [ 0.118 s]
[INFO] kapua-scheduler-api ................................ SUCCESS [ 0.187 s]
[INFO] kapua-job-engine-api ............................... SUCCESS [ 0.087 s]
[INFO] kapua-scheduler-quartz ............................. SUCCESS [ 0.253 s]
[INFO] kapua-translator-kapua ............................. SUCCESS [ 0.166 s]
[INFO] kapua-translator-kapua-kura ........................ SUCCESS [ 0.501 s]
[INFO] kapua-transport-jms ................................ SUCCESS [ 0.307 s]
[INFO] kapua-translator-kura-jms .......................... SUCCESS [ 1.035 s]
[INFO] kapua-broker-core .................................. SUCCESS [ 1.745 s]
[INFO] kapua-security-registration-simple ................. SUCCESS [ 0.247 s]
[INFO] kapua-stream ....................................... SUCCESS [ 0.063 s]
[INFO] kapua-stream-api ................................... SUCCESS [ 0.331 s]
[INFO] kapua-stream-internal .............................. SUCCESS [ 0.231 s]
[INFO] kapua-tag-internal ................................. SUCCESS [ 0.306 s]
[INFO] kapua-transport-test ............................... SUCCESS [ 0.119 s]
[INFO] kapua-simulator-kura ............................... SUCCESS [ 2.877 s]
[INFO] kapua-qa ........................................... SUCCESS [ 1.107 s]
[INFO] kapua-qa-openshift ................................. SUCCESS [ 0.086 s]
[INFO] kapua-sso-api ...................................... SUCCESS [ 0.123 s]
[INFO] kapua-sso-provider ................................. SUCCESS [ 0.172 s]
[INFO] kapua-sso-provider-generic ......................... SUCCESS [ 0.193 s]
[INFO] kapua-sso-provider-keycloak ........................ SUCCESS [ 0.213 s]
[INFO] kapua-extras ....................................... SUCCESS [ 0.077 s]
[INFO] kapua-foreignkeys .................................. SUCCESS [ 0.099 s]
[INFO] kapua-rest-api ..................................... SUCCESS [ 0.276 s]
[INFO] kapua-rest-api-core ................................ SUCCESS [ 0.340 s]
[INFO] kapua-rest-api-resources ........................... SUCCESS [ 0.525 s]
[INFO] kapua-rest-api-web ................................. SUCCESS [ 4.320 s]
[INFO] kapua-job-engine-jbatch ............................ SUCCESS [ 2.727 s]
[INFO] kapua-client ....................................... SUCCESS [ 0.252 s]
[INFO] kapua-client-gateway ............................... SUCCESS [ 2.435 s]
[INFO] Eclipse Kapua :: Gateway Client :: API ............. SUCCESS [ 1.763 s]
[INFO] Eclipse Kapua :: Gateway Client :: SPI ............. SUCCESS [ 0.843 s]
[INFO] Eclipse Kapua :: Gateway Client :: Provider ........ SUCCESS [ 0.311 s]
[INFO] Eclipse Kapua :: Gateway Client :: Provider :: Core MQTT SUCCESS [ 0.416 s]
[INFO] Eclipse Kapua :: Gateway Client :: Provider :: FUSE MQTT SUCCESS [ 0.573 s]
[INFO] Eclipse Kapua :: Gateway Client :: Provider :: Eclipse Paho SUCCESS [ 0.482 s]
[INFO] Eclipse Kapua :: Gateway Client :: Profile :: Eclipse Kura SUCCESS [ 0.721 s]
[INFO] Eclipse Kapua :: Gateway Client :: Features ........ SUCCESS [ 0.066 s]
[INFO] Eclipse Kapua :: Gateway Client :: Features :: Karaf SUCCESS [ 3.031 s]
[INFO] kapua-assembly ..................................... SUCCESS [ 0.159 s]
[INFO] kapua-assembly-java-base ........................... SUCCESS [ 0.077 s]
[INFO] kapua-assembly-jetty-base .......................... SUCCESS [ 0.164 s]
[INFO] kapua-assembly-sql ................................. SUCCESS [ 0.112 s]
[INFO] kapua-assembly-broker .............................. SUCCESS [ 22.267 s]
[INFO] kapua-assembly-api ................................. SUCCESS [ 5.636 s]
[INFO] kapua-dev-tools .................................... SUCCESS [ 0.494 s]
[INFO] kapua-cucumber-reports ............................. SUCCESS [ 0.385 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:17 min
[INFO] Finished at: 2017-11-07T16:45:07+05:30
[INFO] Final Memory: 197M/1140M
[INFO] ------------------------------------------------------------------------

im running kura on raspberry pi

**Comment by LeoNerdoG** [comment]
Hi @dineshkumar4728 ,
did you try to follow complete [guide for basic Kura-Kapua connection](https://github.com/eclipse/kapua/blob/develop/docs/kuraKapuaDocs.md)?

My experience is that password is often wrong - maybe you can check that?

**Comment by dineshkumar4728** [comment]
Hi @LeoNerdoG ,

I have followed the document you shared, I have experiencing same issue .

Thanks 
Dinesh.

**Comment by dineshkumar4728** [comment]
Is it possible to change broker url @LeoNerdoG @riccardomodanese , Me along my colleague sharing the same broker url  is their any chance kura is not connecting to kapua because of this issue?

**Comment by riccardomodanese** [comment]
I'm assuming you would like to change the broker url in the device configuration, right? (so not binding the broker to a different network interface). You can follow the section "MqttDataTransport" of this guide:
https://eclipse.github.io/kura/cloud/kura-cloud.html
To understand the connection failure reason you should read the Kura/Kapua log (broker side) so I mean the files:
/var/log/kura.log
/var/log/kura-console.log
and
 /usr/local/activemq/apache-activemq-5.14.5/data/activemq.log (if you are using the vagrant machine)
docker logs -f container_id (if you are using docker)

**Comment by dineshkumar4728** [comment]
Hi @riccardomodanese ,
   These are my log files of kapua



[elasticsearch.log](https://github.com/eclipse/kapua/files/1452743/elasticsearch.log)
[kapua-api.log](https://github.com/eclipse/kapua/files/1452744/kapua-api.log)
[kapua-broker.log](https://github.com/eclipse/kapua/files/1452745/kapua-broker.log)
[kapua-console.log](https://github.com/eclipse/kapua/files/1452746/kapua-console.log)

**Comment by riccardomodanese** [comment]
Hi, looking at your logs I don't see any login attempts to the broker.
Are you using the right broker url in the device side?
Can you take a look to the device log?

You can find an extract of the logs showing the connection attempt (broker side) with right and wrong credentials.
[connection_log.txt](https://github.com/eclipse/kapua/files/1454271/connection_log.txt)

**Comment by dineshkumar4728** [comment]
Hi @riccardomodanese 
     These are the log files for kura
[kura.log](https://github.com/eclipse/kapua/files/1461035/kura.log)
[kura-console.log](https://github.com/eclipse/kapua/files/1461036/kura-console.log)
     Where can i find device log and connection log text files?

**Comment by riccardomodanese** [comment]
Hi Dinesh, it's a network issue:
MqttException (0) - java.net.NoRouteToHostException: No route to host

Your device is not able to solve the broker name or the address is not valid or not reachable by your device.
Please check the device MqttDataTransport section correctness and verify if your device is also able to solve the address you set.
You can use:
nc -z broker-ip_or-name port (expected output: Connection to broker-ip_or-name port port [tcp/*] succeeded!)

**Comment by dineshkumar4728** [comment]
Thanks @riccardomodanese it's working now :+1:
