### ISSUE TITLE
The Credentials tab should be hidden for a user with no permissions on credential service

### ISSUE THREAD

**Issue by stefanomorson** [eclipse/kapua#936]
A user with permission to connect to the console (es account:view and user:view) but with no permissions on the credential service can view the credentials tab in the user view even though he cannot do any action on it.

Testflow:

* Connect to kapua-sys as kapua-sys
* Create a new user kapua-user with the following permisssions
  * account:read:all:all
  * user:read:all:all
* Logout and login as kapua-user
* Open the user view
* Click on the Credentials tab

The an error pop-up appears explaining that the user  does't have enough permisssions (which is correct)

Expected:

* The permission tab is hidden.

![screen shot 2017-11-08 at 14 00 38](https://user-images.githubusercontent.com/11518067/32550473-95c0eaba-c48d-11e7-8f78-0c5a982dd86f.png)

**Comment by lorthirk** [comment]
This issue should by closed by the following commit:

77d899b - Permission check for Credential tab and Unlock Credential button
