### ISSUE TITLE
A user has device permission on a group but the device view is unavailable

### ISSUE THREAD

**Issue by stefanomorson** [eclipse/kapua#942]
Two users are created, one has device permissions on all resource groups instead the other has device permissions only on a specific resource group. When the first connects to the console the device view is available, when the second connects to the console the device view is not available.

Testflow:

* Create a new account test
* Create a user test-user with permissions:
  * account all
  * user all
  * device all
  * device connection all
  * device events all
  * device lifecycle all
  * device managment all
* Create a group ita
* Create a user test-user-ita with permissions:
  * account all on group ita
  * user all on group ita
  * device all on group ita
  * device connection all on group ita
  * device events all on group ita
  * device lifecycle all on group ita
  * device managment all on group ita
* Logout
* Connect as test-user: the device view is visible
* Connect ad test-user-ita: the device view is not visible
* The "group" column in the permission table under the user view is valued with the id of the group
 
Expected:

* When connecting through test-user-ita the device view should be visible
* The "group" column in the permission table under the user view is valued with the name of the group
 
![screen shot 2017-11-08 at 19 20 35](https://user-images.githubusercontent.com/11518067/32567469-ac58d106-c4bb-11e7-8725-2856d7d27c5f.png)

![screen shot 2017-11-08 at 19 34 55](https://user-images.githubusercontent.com/11518067/32567601-06c9b484-c4bc-11e7-97a4-e43fd4c828cc.png)

![screen shot 2017-11-08 at 19 21 29](https://user-images.githubusercontent.com/11518067/32567499-bd21a922-c4bb-11e7-88d6-f4afb0e7e094.png)

**Comment by stefanomorson** [comment]
@Coduz : I tested the flow and now the device view does appear. However, i got a different error while switching from one view to the device view. The error pops up on the lower right corner and states "Error while fetching groups".

**Comment by Coduz** [comment]
@stefanomorson 

I should have addressed problems on tabs and edit/add dialog. 
Can you please check that it works as expected? 

Still the buttons on the tabs have problems but I'll address it at later time, since it require more console template implementation.  I'll add another issue to dedicated to this.

Regards, 

_Alberto_

**Comment by stefanomorson** [comment]
The issue is solved
