### ISSUE TITLE
The Role tab should be hidden for a user with no permissions on role service

### ISSUE THREAD

**Issue by stefanomorson** [eclipse/kapua#959]
A user with permission to connect to the console (es account:view and user:view) but with no permissions on the role service can view the role tab in the user view even though he cannot do any action on it.

Testflow:

* Connect to kapua-sys as kapua-sys
* Create a new user kapua-user with the following permisssions
  * account:read:all:all
  * user:read:all:all
* Logout and login as kapua-user
* Open the user view
* Click on the Role tab
* The an error pop-up appears explaining that the user does't have enough permisssions (which is correct)

Expected:

* The role tab is disabled and hidden.

**Comment by lorthirk** [comment]
I think it would be better to check for the AccessRole permission rather than the Role permission

**Comment by lorthirk** [comment]
This should be fixed in fb395161310cb63ac53f0050806d90e8986fd24e

**Comment by stefanomorson** [comment]
Test ok.
