### ISSUE TITLE
Build and test dependencies for Kapua

### ISSUE THREAD

**Issue by stefanomorson** [eclipse/kapua#964]
This issue to track build and test dependencies for Kapua 1.0.0:

This CQ has to be filed at least two weeks before submitting the IP log approval:

Name - Version - License
-----------------------------------------------------------------
com.github.jnr:jnr-unixsocket  - 0.14 - Apache 2.0
com.github.os72:protoc-jar-maven-plugin - 3.4.0.2 - Apache 2.0

io.fabric8:docker-maven-plugin - 0.24.0 - Apache 2.0

com.github.eirslett:frontend-maven-plugin - 1.3 - Apache 2.0

concurrently - 3.5.1 - MIT - https://github.com/kimmobrunfeldt/concurrently
typescript - 2.8.1 - Apache 2.0 - http://www.typescriptlang.org
@types/jasmine - 2.8.8 - MIT - https://github.com/DefinitelyTyped/DefinitelyTyped#readme
babel-preset-es2015 - 6.24.1 - MIT
expose-loader - 0.7.5 - MIT - https://github.com/webpack-contrib/expose-loader
glob - 7.1.2 - ISC License - https://github.com/isaacs/node-glob#readme
html-webpack-plugin - 2.30.1 - MIT- https://github.com/jantimon/html-webpack-plugin
jquery - 3.3.1 - MIT - https://jquery.com
json-loader - 0.5.7 - MIT - https://github.com/webpack-contrib/json-loader#readme
karma-coverage - 1.1.2 - MIT - https://github.com/karma-runner/karma-coverage#readme
karma-phantomjs-launcher - 1.0.4 - MIT - https://github.com/karma-runner/karma-phantomjs-launcher#readme
phantomjs-prebuilt - 2.1.16 - Apache 2.0 - https://github.com/Medium/phantomjs
typings - 2.1.1 - MIT - https://github.com/typings/typings
url-loader - 0.5.9 - MIT - https://github.com/webpack-contrib/url-loader
webpack - 1.15.0 - MIT - https://github.com/webpack/webpack
webpack-dev-server - 1.16.5 - MIT - https://github.com/webpack/webpack-dev-server
webpack-fail-plugin - 1.0.6 - MIT - https://github.com/TiddoLangerak/webpack-fail-plugin#readme
nodemon - 1.17.2 - MIT - https://www.npmjs.com/package/nodemon/v/1.17.2

**Comment by Coduz** [comment]
Updated list for new for new build and test dependencies added by #1824

**Comment by stefanomorson** [comment]
Updated list for new for new build and test dependencies
com.github.eirslett:frontend-maven-plugin - 1.3 - Apache 2.0

**Comment by stefanomorson** [comment]
Updated list of dependencies for Console V2
Console V2 common
concurrently@3.5.1 - MIT - https://github.com/kimmobrunfeldt/concurrently
typescript@2.8.1 - Apache 2.0 - http://www.typescriptlang.org

Console V2 ui
@types/jasmine@2.8.8 - MIT - https://github.com/DefinitelyTyped/DefinitelyTyped#readme
babel-preset-es2015@6.24.1 - MIT
expose-loader@0.7.5 - MIT - https://github.com/webpack-contrib/expose-loader
glob@7.1.2 - ISC License - https://github.com/isaacs/node-glob#readme
html-webpack-plugin@2.30.1 - MIT- https://github.com/jantimon/html-webpack-plugin
jquery@3.3.1 - MIT - https://jquery.com
json-loader@0.5.7 - MIT - https://github.com/webpack-contrib/json-loader#readme
karma-coverage@1.1.2 - MIT - https://github.com/karma-runner/karma-coverage#readme
karma-phantomjs-launcher@1.0.4 - MIT - https://github.com/karma-runner/karma-phantomjs-launcher#readme
phantomjs-prebuilt@2.1.16 - Apache 2.0 - https://github.com/Medium/phantomjs
typings@2.1.1 - MIT - https://github.com/typings/typings
url-loader@0.5.9 - MIT - https://github.com/webpack-contrib/url-loader
webpack@1.15.0 - MIT - https://github.com/webpack/webpack
webpack-dev-server@1.16.5 - MIT - https://github.com/webpack/webpack-dev-server
webpack-fail-plugin@1.0.6 - MIT - https://github.com/TiddoLangerak/webpack-fail-plugin#readme

Console V2 server
nodemon@1.17.2 - MIT - https://www.npmjs.com/package/nodemon/v/1.17.2

**Comment by Coduz** [comment]
Kapua 1.0.0 has been release on 9th October 2018. 
We can close this issue
