### ISSUE TITLE
about.html files missing in a number of modules

### ISSUE THREAD

**Issue by ctron** [eclipse/kapua#976]
I just saw that in the 0.3.0 release a bunch on modules are missing the required `about.html` file:

![image](https://user-images.githubusercontent.com/202474/32838940-f1fc7a6c-ca12-11e7-96a0-edf4c77282bf.png)

@stefanomorson  This needs to be fixed and also please check with EMO if a respin of the release is required.

**Comment by stefanomorson** [comment]
Sent an email to EMO asking about respin.

**Comment by stefanomorson** [comment]
The missing about files have been added.
No answer received regarding respinning the release.
I'm going to close this issue and open a new one just for the re-spin part.
