### ISSUE TITLE
No Error Message If maxNumberChildAccounts Exceeded

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#977]
Best way to describe this issue is through an example. 
Create a child account from kapua-sys (e.g. kapua-child1), set InfiniteChildAccounts to false and maxNumberChildAccounts to 2. After that switch to kapua-child1 and create 2 child accounts. When user tries to change InfiniteChildAccounts to True or change maxNumberChildAccounts to something greater than 0 in at least one of them,  error without message pops-up (look at the screenshot). 
Empty error message also appears if we (after 2 child accounts have been created in kapua-child1) switch to kapua-sys and try to lower maxNumberChildAccounts of kapua-child1 from 2 to 1 or 0. 

Testflow: 
1) Login as kapua-sys
2) Go to Child Accounts, create new child account (e.g. kapua-child1) 
3) Set InfiniteChildAccounts to False and maxNumberChildAccounts to 2
4) Create two child accounts (e.g. kapua-child2 and kapua-child3) 
5) In one of them try to set infiniteChildAccounts to True or maxNumberChildAccounts to >0
**Kapua returns an error message without content, but there should really be an explanation that maximum number of child accounts has been exceeded.**

<img width="1438" alt="screen shot 2017-11-16 at 10 11 20" src="https://user-images.githubusercontent.com/15121999/32883189-f510dafa-cab6-11e7-967a-2debd5195ef6.png">

Browsers used: 
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0 (64-bit))
- Opera (Version 49.0.2725.34)

**Comment by muros-ct** [comment]
@LeoNerdoG has not been able to verify this issue.
Re-opening.

**Comment by LeoNerdoG** [comment]
I have verified that this issue is resovled by PR #1327 .
