### ISSUE TITLE
No Error Message If maxNumberChildDevices Exceeded

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#981]
Best way to describe this issue is through an example.
Create a child account from kapua-sys (e.g. kapua-child1), set InfiniteChildDevices to false and maxNumberChildDevices to 2. After that switch to kapua-child1, create new child account (e.g. kapua-child2) and add two devices to kapua-child1. When user tries to change InfiniteChildDevices  to True or change maxNumberChildDevices to something greater than 0 in kapua-child2 account, error without message pops-up (look at the screenshot).
Empty error message also appears if we (after 2 devices have been added in kapua-child1) switch to kapua-sys and try to lower maxNumberChildGroups of kapua-child1 from 2 to 1 or 0.

Testflow:
1. Login as kapua-sys
2. Go to Child Accounts, create new child account (e.g. kapua-child1)
3. Set InfiniteChildAccounts to False and maxNumberChildAccounts to 1
4. Go to groups, set infiniteChildGroups to False and maxNumberChildGroups to 2
5. Switch to kapua-child1 account and create two access groups
6. Create one child account (e.g. kapua-child2)
7. In kapua-child2 try to set infiniteChildGroups to True or maxNumberChildAccounts to >0
**Kapua returns an error message without content, but there should really be an explanation that maximum number of devices has been exceeded.**

<img width="722" alt="screen shot 2017-11-16 at 10 20 42" src="https://user-images.githubusercontent.com/15121999/32883598-2413bcfe-cab8-11e7-8aea-0337965c0239.png">

Browsers used:
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0 (64-bit))
- Opera (Version 49.0.2725.34)

**Comment by muros-ct** [comment]
@LeoNerdoG has not been able to verify this issue.
Re-opening.

**Comment by LeoNerdoG** [comment]
I have verified that this issue is resovled by PR #1327 .
