### ISSUE TITLE
Missing time picker for the schedule of a job

### ISSUE THREAD

**Issue by stefanomorson** [eclipse/kapua#992]
Time schedules should allow to define a date as well as a time for the Starts-on and Ends-on fields.

Testflow:
* Connect to kapua-sys as kapua-sys
* Open the job view
* Create a job: my-job
* Add a schedule

Start-on/End-on fields only allow to pick up a date.

Expected:

The user should be able to pick date as well as a time.

**Comment by lorthirk** [comment]
Fixed in commit cc90b1bf5

**Comment by stefanomorson** [comment]
I would have preferred to have date and time on the same row. According to @lorthirk this is a bit tricky to implement. In my opinion this issue is solved and I will create a new one to improve this usability aspect.
