### ISSUE TITLE
Device edit not working

### ISSUE THREAD

**Issue by stefanomorson** [eclipse/kapua#993]
Testflow:

* Connect to kapua-sys as kapua-sys
* Open the device view
* Manually add a new device
* Submit
* Select the device
* Press the edit button

The edit form pops up for a moment then disappears, an error reports: "Error loading device: last unit does not have enough valid bits"

**Comment by LeoNerdoG** [comment]
Hi @stefanomorson ,
this bug is already added. It is issue #985 .

**Comment by lorthirk** [comment]
Duplicate of #985
