### ISSUE TITLE
User should be able to define job targets using tags

### ISSUE THREAD

**Issue by stefanomorson** [eclipse/kapua#995]
A user may want to use tags to easily define the set of devices processed by the job.
A user may also want to specify that the set of devices has to be defined at the time the job is started the first time.

**Comment by Coduz** [comment]
Hi all,

This issue has been fixed in the linked PR. 

The PR was linked after it has been merged and closed. 
This feature was introduced in 1.1.0 and backported in 1.0.4 (see PR for linked project)

Closing this.

Regards, 

_Alberto_
