### ISSUE TITLE
User Can Login Although It Has No Permissions

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#999]
When creating new user (e.g. kapua-user1 when logged in as kapua-sys), although no permissions, credentials and/or roles are added to the user, we can login with this username, but Kapua has only About and Welcome tabs (look at the screenshot bellow). 

Testflow: 
1. Login as kapua-sys
2. Go to Users, create new user (e.g. kapua-user1) without adding any permissions, credentials or roles. 
3. Logout as kapua-sys and login as kapua-user1. 
_**User should not be able to login. Instead of that, user gets logged in and only Welcome and About tabs are displayed.**_

<img width="1287" alt="screen shot 2017-11-17 at 09 39 23" src="https://user-images.githubusercontent.com/15121999/32938718-6b738514-cb7d-11e7-839c-ac91df2ed3f4.png">

Browsers used:
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0 (64-bit))
- Opera (Version 49.0.2725.34)

**Comment by LeoNerdoG** [comment]
Closed as it is not an issue.

**Comment by ctron** [comment]
Why do you think this is not an issue? If that can be replicated with Kapua 0.3.0 is think this should be reported to security@eclipse.org!

**Comment by ctron** [comment]
Just as a general note, please be aware of the Eclipse security policy when reporting security vulnerabilities: https://eclipse.org/security

**Comment by LeoNerdoG** [comment]
Hi @ctron ,
I have checked this again and I closed it because this is not an issue. User had Password credential entered, just no Permissions or Roles. So it is logical that end-user can login with the username and password provided and not see any of the tabs available (Devices, Tags, Jobs...) as created user has not been given any Permissions.

**Comment by ctron** [comment]
So there is no "login permission" required in order to log in?
